/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.portraits.jsonc --include-runtime=false` (hash: 88baa68a2458a34b13934d74b1937c54)
interface __BaseEnv_Env {
	PORTRAITS: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/portrait-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
