// Source-backed local name components; coverage and limits in docs/geographic-data.md.
export const africaReviewedNames = {
  AO: {
    female: [
      'Maria', 'Ana', 'Helena', 'Isabel', 'Amélia', 'Teresa', 'Carolina',
      'Elisa', 'Luísa', 'Paula', 'Rosa', 'Joana', 'Luisa', 'Margarida',
      'Marta', 'Sandra', 'Antonia', 'Arminda', 'Carla', 'Cristina', 'Laurinda',
      'Liliana', 'Luzia', 'Manuela', 'Regina', 'Ruth', 'Sara', 'Telma',
      'Albertina', 'Alexandra', 'Amália', 'Ana Paula', 'Anastacia', 'Angela', 'Angelina',
      'Catarina', 'Chelsea', 'Conceição', 'Domingas', 'Eliane', 'Elizabeth', 'Elsa',
      'Emília', 'Engràcia', 'Esperança', 'Filomena', 'Francisca', 'Helga', 'Ilda',
      'Indira',
    ],
    male: [
      'João', 'José', 'Manuel', 'Pedro', 'Carlos', 'António', 'Paulo',
      'Francisco', 'Antonio', 'Fernando', 'Luís', 'Mário', 'Alberto', 'Eduardo',
      'Jorge', 'Luis', 'David', 'Joaquim', 'Ricardo', 'André', 'Filipe',
      'Henrique', 'Miguel', 'Alexandre', 'Daniel', 'Osvaldo', 'Wilson', 'Adriano',
      'Afonso', 'Augusto', 'Bruno', 'Domingos', 'Emanuel', 'Marcos', 'Rui',
      'Simão', 'Victor', 'Walter', 'Abel', 'Armando', 'Edmilson', 'Elias',
      'Jose', 'Marco', 'Mario', 'Mateus', 'Raúl', 'Agostinho', 'Alfredo',
      'Bernardo',
    ],
    family: [
      'Neto', 'Silva', 'Fernandes', 'Costa', 'Antonio', 'Gonçalves', 'Francisco',
      'Santos', 'Carvalho', 'Ferreira', 'Manuel', 'Alves', 'Gomes', 'Martins',
      'Miguel', 'Paulo', 'Pereira', 'da Silva', 'Oliveira', 'Afonso', 'Barros',
      'da Costa', 'Joao', 'Lima', 'Machado', 'Mingas', 'Morais', 'Abreu',
      'Almeida', 'Cardoso', 'Cruz', 'Da Silva', 'Fernando', 'Fonseca', 'Henriques',
      'Lopes', 'Monteiro', 'Nascimento', 'Pascoal', 'Pedro', 'Soares', 'Sousa',
      'Aguiar', 'Amaral', 'André', 'Augusto', 'Bastos', 'Caetano', 'Conceição',
      'Correia',
    ],
  },
  BF: {
    female: [
      'Mariam', 'Aminata', 'Awa', 'Martine', 'Alimata', 'Delphine', 'Aïssata',
      'Chantal', 'Fatoumata', 'Françoise', 'Juliette', 'Korotimi', 'Laetitia', 'Laure',
      'Madina', 'Maïmouna', 'Nathalie', 'Pauline', 'Sita', 'Aïcha', 'Alice',
      'Alima', 'Annick', 'Assita', 'Béatrice', 'Bintou', 'Carine', 'Carole',
      'Charlotte', 'Christine', 'Clarisse', 'Diane', 'Fatimata', 'Félicité', 'Flora',
      'Florentine', 'Habibou', 'Henriette', 'Honorine', 'Hortense', 'Irène', 'Jacqueline',
      'Joséphine', 'Malika', 'Minata', 'Monique', 'Patricia', 'Peggy', 'Priscille',
      'Ruth',
    ],
    male: [
      'Moussa', 'Abdoul', 'Mohamed', 'Aboubacar', 'Adama', 'Issa', 'Mamadou',
      'Souleymane', 'Abdoulaye', 'Idrissa', 'Jean', 'Jean-Baptiste', 'Serge', 'Yacouba',
      'Amadou', 'Ibrahim', 'Maurice', 'Pierre', 'Alain', 'Ali', 'Hervé',
      'Joseph', 'Karim', 'Laurent', 'Paul', 'Boubacar', 'Brahima', 'Frédéric',
      'Roger', 'Augustin', 'Bakary', 'Boureima', 'Charles', 'Dominique', 'Emmanuel',
      'François', 'Harouna', 'Ibrahima', 'Justin', 'Mahamoudou', 'Maxime', 'Muhammad',
      'Oumar', 'Ousmane', 'Patrick', 'Philippe', 'Robert', 'Salam', 'Salif',
      'Seydou',
    ],
    family: [
      'Ouédraogo', 'Traoré', 'Sawadogo', 'Kaboré', 'Ouattara', 'Ilboudo', 'Ouedraogo',
      'Zongo', 'Coulibaly', 'Compaoré', 'Touré', 'Dao', 'Diallo', 'Koné',
      'Sankara', 'Tapsoba', 'Zoungrana', 'Kabore', 'Nikiéma', 'Tiendrébéogo', 'Barry',
      'Diarra', 'Kambou', 'Nikiema', 'Paré', 'Thiombiano', 'Bationo', 'Cissé',
      'Damiba', 'Guissou', 'Kabré', 'Kouyaté', 'Minoungou', 'Bambara', 'Bamogo',
      'Bancé', 'Barro', 'Dabiré', 'Diakité', 'Kafando', 'Kini', 'Konaté',
      'Maïga', 'Naré', 'Sana', 'Sanon', 'Somda', 'Bado', 'Bangré',
      'Banse',
    ],
  },
  BJ: {
    female: [
      'Christelle', 'Agnès', 'Christine', 'Edwige', 'Evelyne', 'Françoise', 'Gisèle',
      'Huguette', 'Nadine', 'Sophie', 'Anna', 'Brigitte', 'Carole', 'Grace',
      'Honorine', 'Inès', 'Marcelline', 'Nelly', 'Olga', 'Sèna', 'Sonia',
      'Véronique', 'Anne', 'Annick', 'Béatrice', 'Bernadette', 'Célestine', 'Chantal',
      'Clarisse', 'Claudine', 'Constance', 'Eliane', 'Elisabeth', 'Emmanuelle', 'Estelle',
      'Eugénie', 'Fatima', 'Fifamè', 'Flore', 'Geneviève', 'Gloria', 'Henriette',
      'Hortense', 'Innocentia', 'Jeanne', 'Jemima', 'Justine', 'Karamatou', 'Laure',
      'Léa',
    ],
    male: [
      'Pascal', 'Michel', 'Richard', 'Alain', 'Daniel', 'Jean', 'Joseph',
      'Louis', 'Antoine', 'Paul', 'Serge', 'Julien', 'Mohamed', 'Pierre',
      'Christian', 'Christophe', 'Eric', 'Guy', 'Jacques', 'Jérôme', 'Joël',
      'Justin', 'Marcel', 'Robert', 'Romuald', 'Yves', 'Alexis', 'Arnaud',
      'Aurélien', 'Charles', 'Claude', 'Comlan', 'Damien', 'Emmanuel', 'Francis',
      'François', 'Grégoire', 'Lionel', 'Luc', 'Mathieu', 'Patrice', 'Philippe',
      'Steve', 'Thomas', 'Valentin', 'Armand', 'Bertin', 'Charlemagne', 'David',
      'Didier',
    ],
    family: [
      'Amoussou', 'Gbaguidi', 'Mensah', 'Quenum', 'Boko', 'Dossou', 'Hountondji',
      'Adjovi', 'Dansou', 'Kérékou', 'Kidjo', 'Lokossou', 'Tosou', 'Adjaho',
      'Adjanohoun', 'Agbo', 'Ahossi', 'Behanzin', 'd\'Almeida', 'de Souza', 'Houngbédji',
      'Sagbo', 'Soglo', 'Sossou', 'Talon', 'Zinsou', 'Affo', 'Agboton',
      'Akplogan', 'Akpovi', 'Apithy', 'Badarou', 'Badou', 'Bello', 'Chabi',
      'da Silva', 'do Rêgo', 'Fagbohoun', 'Gbadamassi', 'Godonou', 'Guédègbé', 'Hounkpatin',
      'Loko', 'Padonou', 'Salami', 'Traoré', 'Yayi', 'Adam', 'Adande',
      'Adissoda',
    ],
  },
  BW: {
    female: ['Unity', 'Beauty', 'Talita', 'Phildah', 'Peggy', 'Annah'],
    male: ['Duma', 'Dithapelo', 'Dumelang', 'Wynter', 'Polson', 'Mokwaledi'],
    family: ['Dow', 'Manake', 'Monnakgotla', 'Keorapetse', 'Saleshando', 'Mmolotsi', 'Kedikilwe'],
  },
  CD: {
    female: [
      'Charlotte', 'Thérèse', 'Yvonne', 'Chantal', 'Solange', 'Grace', 'Jolie',
      'Mireille', 'Odette', 'Rebecca', 'Rose', 'Antoinette', 'Christelle', 'Christine',
      'Julie', 'Liliane', 'Nathalie', 'Pauline', 'Sophie', 'Suzanne', 'Adèle',
      'Annie', 'Astrid', 'Bernadette', 'Catherine', 'Françoise', 'Jeanne', 'Joséphine',
      'Lucie', 'Mamie', 'Marie-Thérèse', 'Naomi', 'Nicole', 'Patricia', 'Prisca',
      'Ruth', 'Wivine', 'Arlette', 'Clémentine', 'Diane', 'Esther', 'Eugénie',
      'Farida', 'Fifi', 'Gisèle', 'Gloria', 'Ida', 'Jacqueline', 'Jeannine',
      'Josée',
    ],
    male: [
      'Jean', 'Joseph', 'Patrick', 'Christian', 'André', 'Pierre', 'Albert',
      'Emmanuel', 'Jean-Marie', 'Serge', 'Daniel', 'Paul', 'Alain', 'Didier',
      'Jean-Pierre', 'Jonathan', 'Antoine', 'Charles', 'François', 'Guy', 'Jacques',
      'Marcel', 'Michel', 'Roger', 'Yves', 'Cédric', 'David', 'Jean-Claude',
      'John', 'Pascal', 'Augustin', 'Jules', 'Martin', 'Olivier', 'Richard',
      'Justin', 'Léonard', 'Willy', 'Aimé', 'Alphonse', 'Bernard', 'Dieudonné',
      'Franck', 'Jean-Paul', 'Léon', 'Robert', 'Samuel', 'Célestin', 'Eddy',
      'Faustin',
    ],
    family: [
      'Kazadi', 'Mutombo', 'Ilunga', 'Mboyo', 'Ntambwe', 'Kadima', 'Kayembe',
      'Mukoko', 'Mwenze', 'Ngoy', 'Lumumba', 'Makengo', 'Mbemba', 'Mbuyi',
      'Mwamba', 'Kalulu', 'Kamba', 'Kasongo', 'Mandanda', 'Ngalula', 'Nsimba',
      'Bonga', 'Kabasele', 'Kabongo', 'Kabuya', 'Kalenga', 'Kalonji', 'Kanjinga',
      'Kashama', 'Lusamba', 'Mafuta', 'Malu', 'Massamba', 'Matondo', 'Mulamba',
      'Muzinga', 'Ngoma', 'Tambwe', 'Tshisekedi', 'Bakenga', 'Balikwisha', 'Baloji',
      'Banza', 'Bishweka', 'Biyombo', 'Bongo', 'Bussa', 'Kalemba', 'Kamanda',
      'Kamanga',
    ],
  },
  CG: {
    female: ['Pascaline', 'Simone', 'Hortense', 'Charlotte', 'Jeanne'],
    male: ['Daniel', 'Théophile', 'Michel', 'Pascal', 'Guillaume'],
    family: ['Adoua', 'Mahinga', 'Okoula', 'Ngoto', 'Assassa', 'Banvidi'],
  },
  CI: {
    female: [
      'Mariam', 'Fatou', 'Jeanne', 'Aminata', 'Awa', 'Patricia', 'Chantal',
      'Grace', 'Ange', 'Christelle', 'Christine', 'Adjoua', 'Anne', 'Assita',
      'Edwige', 'Fatim', 'Françoise', 'Henriette', 'Isabelle', 'Mariame', 'Marthe',
      'Rose', 'Salimata', 'Sarah', 'Stéphanie', 'Valérie', 'Akissi', 'Albertine',
      'Alima', 'Amoin', 'Angèle', 'Aya', 'Brigitte', 'Caroline', 'Constance',
      'Cynthia', 'Delphine', 'Emma', 'Fatoumata', 'Florence', 'Hélène', 'Inès',
      'Jennifer', 'Josée', 'Julie', 'Laetitia', 'Louise', 'Maïmouna', 'Mireille',
      'Mylène',
    ],
    male: [
      'Jean', 'Serge', 'Ibrahim', 'Alain', 'Mamadou', 'Adama', 'Mohamed',
      'Abdoulaye', 'Charles', 'Didier', 'Franck', 'Paul', 'Souleymane', 'Emmanuel',
      'Georges', 'Michel', 'Amadou', 'Bernard', 'François', 'Koffi', 'Laurent',
      'Moussa', 'Olivier', 'Patrick', 'Philippe', 'Joseph', 'Christian', 'Jacques',
      'Pascal', 'Wilfried', 'Alphonse', 'Ange', 'Armand', 'Eugène', 'Marcel',
      'Roger', 'Yacouba', 'Antoine', 'Axel', 'Blaise', 'Daniel', 'David',
      'Hervé', 'Ismael', 'Jean-Jacques', 'Joël', 'Lassina', 'Marc', 'Stéphane',
      'Yves',
    ],
    family: [
      'Koné', 'Touré', 'Traoré', 'Coulibaly', 'Ouattara', 'Fofana', 'Kouassi',
      'Cissé', 'Bamba', 'Koffi', 'Konan', 'Kouamé', 'Diomandé', 'Bakayoko',
      'Kouadio', 'Camara', 'Kone', 'N\'Guessan', 'Konaté', 'Kouakou', 'Diallo',
      'Sylla', 'Beugré', 'Diaby', 'Diabaté', 'Keita', 'Meité', 'Sanogo',
      'Yao', 'Boni', 'Diomande', 'Dosso', 'Bah', 'Blé', 'Brou',
      'Diakité', 'Diarra', 'Gbane', 'Keïta', 'Kouame', 'Koutouan', 'Meite',
      'N\'Zi', 'Traore', 'Aka', 'Ballo', 'Diarrassouba', 'Doué', 'Guéï',
      'Kamara',
    ],
  },
  CM: {
    female: [
      'Madeleine', 'Florence', 'Françoise', 'Jeanne', 'Solange', 'Thérèse', 'Chantal',
      'Carine', 'Esther', 'Louise', 'Rose', 'Laure', 'Monique', 'Anne',
      'Jacqueline', 'Nathalie', 'Audrey', 'Christelle', 'Marthe', 'Catherine', 'Cécile',
      'Céline', 'Justine', 'Mireille', 'Pauline', 'Rachel', 'Yvonne', 'Carole',
      'Charlotte', 'Christine', 'Colette', 'Diane', 'Elisabeth', 'Gaëlle', 'Isabelle',
      'Nadine', 'Patricia', 'Ruth', 'Stella', 'Agnès', 'Alice', 'Annie',
      'Antoinette', 'Brigitte', 'Estelle', 'Henriette', 'Judith', 'Odette', 'Suzanne',
      'Yvette',
    ],
    male: [
      'Jean', 'Joseph', 'Emmanuel', 'Paul', 'Pierre', 'Samuel', 'Serge',
      'Charles', 'Patrick', 'Alain', 'Guy', 'Martin', 'Christian', 'Michel',
      'Franck', 'Simon', 'David', 'Jacques', 'Eric', 'François', 'André',
      'Dieudonné', 'Hervé', 'Ernest', 'Claude', 'Thomas', 'Georges', 'Olivier',
      'Armand', 'Daniel', 'Henri', 'Jules', 'Louis', 'René', 'Francis',
      'Gabriel', 'Thierry', 'William', 'Albert', 'Luc', 'Patrice', 'Roger',
      'Yves', 'Junior', 'Richard', 'Vincent', 'Bernard', 'Jean-Pierre', 'Victor',
      'Antoine',
    ],
    family: [
      'Owona', 'Bell', 'Atangana', 'Fotso', 'Ayissi', 'Mbarga', 'Mvondo',
      'Njoya', 'Simo', 'Ateba', 'Eyenga', 'Onana', 'Oyono', 'Biya',
      'Eloundou', 'Essomba', 'Fouda', 'Kamdem', 'Mbappé', 'Nana', 'Ndam',
      'Ngo', 'Njock', 'Zambo', 'Zogo', 'Abega', 'Bella', 'Bissa',
      'Etoga', 'Eyango', 'Kadji', 'Kameni', 'Manga', 'Matam', 'Mbah',
      'Mbida', 'Mengue', 'Minlend', 'Monkam', 'Mveng', 'Noah', 'Obama',
      'Amadou', 'Amougou', 'Balla', 'Belinga', 'Boya', 'Dika', 'Effa',
      'Essama',
    ],
  },
  GH: {
    female: [
      'Elizabeth', 'Grace', 'Mary', 'Ama', 'Nana', 'Cynthia', 'Anita',
      'Abena', 'Akosua', 'Lydia', 'Akua', 'Esther', 'Gifty', 'Victoria',
      'Cecilia', 'Diana', 'Mavis', 'Patience', 'Priscilla', 'Rita', 'Theresa',
      'Afia', 'Alice', 'Beatrice', 'Gladys', 'Linda', 'Margaret', 'Rose',
      'Abigail', 'Florence', 'Gloria', 'Juliana', 'Mercy', 'Sandra', 'Adwoa',
      'Afua', 'Agnes', 'Doris', 'Ernestina', 'Hannah', 'Janet', 'Joyce',
      'Patricia', 'Rebecca', 'Ruth', 'Sophia', 'Yaa', 'Barbara', 'Belinda',
      'Comfort',
    ],
    male: [
      'Emmanuel', 'Samuel', 'Joseph', 'John', 'Isaac', 'Daniel', 'George',
      'Francis', 'Charles', 'Kofi', 'Kwabena', 'James', 'David', 'Michael',
      'Eric', 'Muhammad', 'Richard', 'Edward', 'Kwame', 'Stephen', 'William',
      'Anthony', 'Frank', 'Benjamin', 'Kwaku', 'Nana', 'Peter', 'Robert',
      'Yaw', 'Ernest', 'Alfred', 'Patrick', 'Paul', 'Kwadwo', 'Alex',
      'Ibrahim', 'Bernard', 'Ebenezer', 'Henry', 'Kwesi', 'Thomas', 'Joe',
      'Albert', 'Seth', 'Joshua', 'Prince', 'Felix', 'Frederick', 'Kwasi',
      'Lawrence',
    ],
    family: [
      'Mensah', 'Boateng', 'Owusu', 'Appiah', 'Adjei', 'Osei', 'Opoku',
      'Yeboah', 'Addo', 'Boakye', 'Tetteh', 'Adams', 'Asare', 'Acheampong',
      'Asante', 'Asamoah', 'Acquah', 'Adu', 'Ofori', 'Amoah', 'Donkor',
      'Agyemang', 'Darko', 'Lamptey', 'Sarpong', 'Adam', 'Addy', 'Amoako',
      'Annan', 'Frimpong', 'Quaye', 'Gyamfi', 'Gyan', 'Hammond', 'Johnson',
      'Mohammed', 'Williams', 'Amankwah', 'Antwi', 'Ibrahim', 'Poku', 'Salifu',
      'Andoh', 'Ansah', 'Awuah', 'Bonsu', 'Danquah', 'Konadu', 'Manu',
      'Ofosu',
    ],
  },
  GN: {
    female: [
      'Fatoumata', 'Aminata', 'Mariama', 'Hawa', 'Kadiatou', 'Aissatou', 'Hadja',
      'Binta', 'Fanta', 'Mariam', 'Oumou', 'Saran', 'Aïssata', 'Mariame',
      'Halimatou', 'Maïmouna', 'Ramatoulaye', 'Adama', 'Bintou', 'Fatou', 'Maimouna',
      'Mama', 'Safiatou', 'Sira', 'Aicha', 'Aïcha', 'Aissata', 'Diaka',
      'Diariatou', 'Djené', 'Eva', 'Fatima', 'Houleymatou', 'Khady', 'Lamarana',
      'Makèmè', 'Mariana', 'Paulette', 'Rougui', 'Salimatou', 'Sona', 'Ada',
      'Aïssatou', 'Andrée', 'Angeline', 'Anne-Marie', 'Arabiya', 'Ary', 'Aya',
      'Batouly',
    ],
    male: [
      'Mamadou', 'Mohamed', 'Ibrahima', 'Aboubacar', 'Abdoulaye', 'Alpha', 'Ousmane',
      'Amadou', 'Sekou', 'Moussa', 'Souleymane', 'Oumar', 'Fodé', 'Thierno',
      'Lamine', 'Mamady', 'Boubacar', 'Abdoul', 'Jean', 'Amara', 'Mory',
      'Ahmed', 'Aly', 'Saliou', 'Moustapha', 'Cheick', 'Chérif', 'Daouda',
      'Ibrahim', 'Lansana', 'Muhammad', 'Abdourahmane', 'Alhassane', 'Balla', 'Idrissa',
      'Karim', 'Mamoudou', 'Naby', 'Sékouba', 'Aliou', 'Ansoumane', 'Charles',
      'François', 'Kabinet', 'Oury', 'Saïdou', 'Seydouba', 'Sidiki', 'Abou',
      'Baba',
    ],
    family: [
      'Diallo', 'Camara', 'Bah', 'Barry', 'Sylla', 'Kaba', 'Keita',
      'Touré', 'Condé', 'Bangoura', 'Traoré', 'Baldé', 'Cissé', 'Soumah',
      'Sow', 'Kourouma', 'Diakité', 'Doumbouya', 'Fofana', 'Konaté', 'Diaby',
      'Kouyaté', 'Kanté', 'Sidibé', 'Diawara', 'Conté', 'Béavogui', 'Keïta',
      'Mara', 'Oularé', 'Thiam', 'Tounkara', 'Diabaté', 'Doré', 'Toure',
      'Bamba', 'Guilavogui', 'Koné', 'Koulibaly', 'Loua', 'Yansané', 'Balde',
      'Conde', 'Diané', 'Nabé', 'Sangaré', 'Tolno', 'Zoumanigui', 'Coumbassa',
      'Daffé',
    ],
  },
  KE: {
    female: [
      'Mary', 'Catherine', 'Esther', 'Margaret', 'Jane', 'Elizabeth', 'Rose',
      'Ruth', 'Caroline', 'Grace', 'Mercy', 'Anne', 'Gladys', 'Joyce',
      'Beatrice', 'Janet', 'Nancy', 'Susan', 'Agnes', 'Alice', 'Emily',
      'Irene', 'Sarah', 'Faith', 'Josephine', 'Judith', 'Lydia', 'Naomi',
      'Christine', 'Diana', 'Eunice', 'Florence', 'Cynthia', 'Lucy', 'Sylvia',
      'Betty', 'Hellen', 'Joan', 'Judy', 'Martha', 'Rebecca', 'Veronica',
      'Vivian', 'Yvonne', 'Dorothy', 'Edith', 'Eva', 'Monica', 'Nelly',
      'Pauline', 'Lilian', 'Eve', 'Millie',
    ],
    male: [
      'John', 'David', 'Peter', 'Joseph', 'James', 'Paul', 'Daniel',
      'Charles', 'George', 'Patrick', 'William', 'Julius', 'Francis', 'Robert',
      'Stephen', 'Philip', 'Simon', 'Moses', 'Geoffrey', 'Michael', 'Richard',
      'Benjamin', 'Samuel', 'Henry', 'Thomas', 'Joshua', 'Vincent', 'Edwin',
      'Nicholas', 'Sammy', 'Wilson', 'Gideon', 'Mike', 'Anthony', 'Christopher',
      'Eric', 'Alfred', 'Bernard', 'Fred', 'Mark', 'Martin', 'Samson',
      'Abraham', 'Elijah', 'Isaac', 'Brian', 'Duncan', 'Emmanuel', 'Evans',
      'Gilbert', 'Tom', 'Elisha',
    ],
    family: [
      'Cheruiyot', 'Kirui', 'Kosgei', 'Odhiambo', 'Rotich', 'Koech', 'Korir',
      'Maina', 'Otieno', 'Wambui', 'Kariuki', 'Kibet', 'Kimani', 'Kiprop',
      'Tanui', 'Wanjiru', 'Rono', 'Chebet', 'Kiptoo', 'Nderitu', 'Onyango',
      'Owino', 'Chelimo', 'Chepng\'etich', 'Kemboi', 'Kipruto', 'Makokha', 'Mbugua',
      'Jepchirchir', 'Kiplagat', 'Kiptum', 'Njoroge', 'Okoth', 'Biwott', 'Chepchumba',
      'Cherono', 'Kamau', 'Kimutai', 'Kiprotich', 'Kipsang', 'Langat', 'Masai',
      'Mutai', 'Odinga', 'Okumu', 'Ouma', 'Patel', 'Ruto', 'Shah',
      'Wanjiku', 'Ochieng', 'Opondo', 'Oduor', 'Omondi',
    ],
  },
  LS: {
    female: ['Matumelo', 'Mamoipone', 'Likeleli', 'Mathato', 'Manthabiseng'],
    male: ['Tello', 'Thabo', 'Motlatsi', 'Moshoeshoe', 'Tseliso'],
    family: ['Sekatle', 'Senauoane', 'Monare', 'Phafoli', 'Phohleli', 'Kibane', 'Maqelepo', 'Fako'],
  },
  ML: {
    female: [
      'Fatoumata', 'Aminata', 'Mariam', 'Aïssata', 'Oumou', 'Awa', 'Fanta',
      'Hawa', 'Kadiatou', 'Ramata', 'Bintou', 'Maïmouna', 'Mama', 'Salimata',
      'Sira', 'Fatou', 'Aicha', 'Alima', 'Fatimata', 'Penda', 'Rokia',
      'Safiatou', 'Saran', 'Adama', 'Aïcha', 'Aïchata', 'Aïchatou', 'Aïda',
      'Alimata', 'Diana', 'Jacqueline', 'Madeleine', 'Nassira', 'Ramatoulaye', 'Rokiatou',
      'Sadio', 'Suzanne', 'Ada', 'Adja', 'Aïssa', 'Alida', 'Ami',
      'Amy', 'Assa', 'Aya', 'Aziza', 'Batouly', 'Bernadette', 'Binta',
      'Coumba',
    ],
    male: [
      'Mamadou', 'Moussa', 'Abdoulaye', 'Mohamed', 'Amadou', 'Boubacar', 'Souleymane',
      'Modibo', 'Oumar', 'Ibrahim', 'Adama', 'Sekou', 'Ibrahima', 'Ousmane',
      'Lamine', 'Mahamadou', 'Bakary', 'Cheick', 'Samba', 'Idrissa', 'Muhammad',
      'Abdoul', 'Ahmed', 'Lassana', 'Malick', 'Sadio', 'Seydou', 'Aboubacar',
      'Dramane', 'Issa', 'Karim', 'Makan', 'Alassane', 'Ali', 'Alioune',
      'Baba', 'Habib', 'Hamadoun', 'Harouna', 'Salif', 'Sidiki', 'Yaya',
      'Alpha', 'Djibril', 'Ismaël', 'Jean', 'Omar', 'Tiémoko', 'Zoumana',
      'Birama',
    ],
    family: [
      'Traoré', 'Coulibaly', 'Diarra', 'Touré', 'Diallo', 'Keita', 'Traore',
      'Dembélé', 'Keïta', 'Camara', 'Koné', 'Sissoko', 'Cissé', 'Diawara',
      'Sidibé', 'Maïga', 'Konaté', 'Diakité', 'Sangaré', 'Diabaté', 'Fofana',
      'Samake', 'Dembele', 'Kouyaté', 'Bagayoko', 'N\'Diaye', 'Sidibe', 'Doucouré',
      'Kone', 'Toure', 'Sylla', 'Maiga', 'Sanogo', 'Diakite', 'Haidara',
      'Kanté', 'Sy', 'Danioko', 'Drame', 'Samaké', 'Sangare', 'Sow',
      'Ba', 'Doucoure', 'Haïdara', 'Samassékou', 'Ballo', 'Baradji', 'Diabate',
      'Dicko',
    ],
  },
  NA: {
    female: ['Saara', 'Emma', 'Alexia', 'Lucia', 'Hilma', 'Selma'],
    male: ['Phillipus', 'Paulus', 'Immanuel', 'Veikko', 'Salomon', 'Willem'],
    family: ['Kuugongelwa-Amadhila', 'Kantema', 'Manombe-Ncube', 'Iipumbu', 'Iita', 'Nekundi', 'Katamelo'],
  },
  RW: {
    female: [
      'Alice', 'Christine', 'Chantal', 'Claudine', 'Solange', 'Diane', 'Grace',
      'Yvonne', 'Aline', 'Clementine', 'Gloria', 'Immaculée', 'Jacqueline', 'Jeanne d\'Arc',
      'Liliane', 'Sandrine', 'Agnes', 'Angelique', 'Judith', 'Rose', 'Beatrice',
      'Claire', 'Claudette', 'Esther', 'Françoise', 'Jeanne', 'Madeleine', 'Nadine',
      'Agnès', 'Alphonsine', 'Ange', 'Aurore', 'Beata', 'Brigitte', 'Charlotte',
      'Clarisse', 'Cynthia', 'Denyse', 'Donatilla', 'Eliane', 'Florence', 'Hope',
      'Jeanette', 'Jeannette', 'Joselyne', 'Josiane', 'Louise', 'Monique', 'Olive',
      'Rosine', 'Emma',
    ],
    male: [
      'Jean', 'Joseph', 'Emmanuel', 'Patrick', 'Eric', 'Charles', 'Augustin',
      'Jean-Claude', 'Olivier', 'Alphonse', 'James', 'Samuel', 'Dominique', 'Jean-Paul',
      'Richard', 'Vincent', 'André', 'Gilbert', 'Jean-de-Dieu', 'Paul', 'Robert',
      'Abdul', 'Alexis', 'Bernard', 'Célestin', 'Elias', 'Eugène', 'Pierre',
      'Prince', 'Yves', 'Alexandre', 'Celestin', 'Christian', 'Christophe', 'Claude',
      'Daniel', 'David', 'Didier', 'Emile', 'Ernest', 'Faustin', 'Félicien',
      'Fulgence', 'Gaspard', 'Innocent', 'Jacques', 'Jean-Marie', 'Jimmy', 'John',
      'Justin', 'Anastase', 'Théogène', 'Venuste', 'Jean Claude',
    ],
    family: [
      'Ingabire', 'Uwizeye', 'Hakizimana', 'Kayitesi', 'Uwamahoro', 'Kamanzi', 'Sibomana',
      'Umuhoza', 'Habyarimana', 'Kagame', 'Mutesi', 'Nsengiyumva', 'Umutoni', 'Uwera',
      'Uwineza', 'Kabera', 'Mukeshimana', 'Nsabimana', 'Uwamariya', 'Bayisenge', 'Butera',
      'Gasana', 'Iradukunda', 'Irakoze', 'Kabanda', 'Karekezi', 'Kayibanda', 'Kimenyi',
      'Mugabo', 'Murangwa', 'Murekatete', 'Ndagijimana', 'Niyonkuru', 'Nsanzimana', 'Rugamba',
      'Shema', 'Umurungi', 'Uwanyirigira', 'Uwimana', 'Bizimana', 'Bizimungu', 'Gakuba',
      'Imanishimwe', 'Ineza', 'Irankunda', 'Ishimwe', 'Iyamuremye', 'Kanimba', 'Karemera',
      'Mahoro', 'Uwase', 'Iganze', 'Mugisha', 'Hirwa', 'Igiraneza',
    ],
  },
  SC: {
    female: ['Audrey', 'Denise', 'Azarel', 'Sandra', 'Sylvanne', 'Valdana'],
    male: ['Egbert', 'Bernard', 'Alvin', 'Andy', 'Churchill', 'Trevor'],
    family: ['Vidot', 'Clarisse', 'Ernesta', 'Sultan', 'Lemiel', 'Georges', 'Labonte', 'Gill'],
  },
  SN: {
    female: [
      'Fatou', 'Ndeye', 'Aminata', 'Mariama', 'Awa', 'Mame', 'Khady',
      'Fatoumata', 'Bineta', 'Seynabou', 'Sokhna', 'Aissatou', 'Maïmouna', 'Coumba',
      'Anna', 'Anta', 'Astou', 'Fatimata', 'Penda', 'Fatima', 'Khadidiatou',
      'Khadija', 'Marième', 'Amy', 'Binta', 'Bintou', 'Nafissatou', 'Rokhaya',
      'Sophie', 'Aicha', 'Aïcha', 'Aida', 'Aïda', 'Fanta', 'Hawa',
      'Kine', 'Marieme', 'Maty', 'Oumou', 'Ramatoulaye', 'Rose', 'Yaye',
      'Adama', 'Aïssatou', 'Amina', 'Dieynaba', 'Fama', 'Fatma', 'Jacqueline',
      'Jeanne',
    ],
    male: [
      'Mamadou', 'Abdoulaye', 'Ibrahima', 'Amadou', 'Moussa', 'Babacar', 'Ousmane',
      'Pape', 'Alioune', 'Moustapha', 'Souleymane', 'Lamine', 'Cheikh', 'Oumar',
      'Omar', 'Abdou', 'Adama', 'Samba', 'Papa', 'Assane', 'Mohamed',
      'Boubacar', 'Mouhamadou', 'Mouhamed', 'Mansour', 'Doudou', 'Issa', 'Mame',
      'Pierre', 'Ababacar', 'Alassane', 'Daouda', 'Djibril', 'Joseph', 'Mbaye',
      'Thierno', 'Abdoul', 'Aliou', 'Elhadji', 'Louis', 'Ousseynou', 'Serigne',
      'Baye', 'Malick', 'Aziz', 'Baba', 'Chérif', 'Habib', 'Ibrahim',
      'Karim', 'Ahmadou',
    ],
    family: [
      'Diop', 'Ndiaye', 'Fall', 'Diouf', 'Gueye', 'Diallo', 'Sarr',
      'Faye', 'N\'Diaye', 'Seck', 'Thiam', 'Sow', 'Mendy', 'Niang',
      'Ba', 'Mbaye', 'Cissé', 'Diagne', 'Camara', 'Touré', 'Sy',
      'Sall', 'Dieng', 'Kane', 'Sagna', 'Sylla', 'Wade', 'Mbengue',
      'Ndoye', 'Diatta', 'Sène', 'Badji', 'Traoré', 'Dabo', 'Gomis',
      'Ngom', 'Gaye', 'Samb', 'Diedhiou', 'Sané', 'Baldé', 'Ndao',
      'Coly', 'Coulibaly', 'Keita', 'Pouye', 'Sonko', 'Badiane', 'Barry',
      'Diaw', 'Wane',
    ],
  },
  TG: {
    female: [
      'Nathalie', 'Adjovi', 'Edwige', 'Kafui', 'Marguerite', 'Rita', 'Abla',
      'Ablavi', 'Abra', 'Adjo', 'Adjoavi', 'Afiwavi', 'Chimène', 'Christelle',
      'Christiane', 'Claire', 'Dede', 'Elisabeth', 'Elise', 'Essenam', 'Florence',
      'Françoise', 'Georgette', 'Germaine', 'Henriette', 'Ingrid', 'Isabelle', 'Joséphine',
      'Julie', 'Laura', 'Manuella', 'Naomi', 'Patricia', 'Rachel', 'Rolande',
      'Rose', 'Sonia', 'Valentine', 'Victoire', 'Ablamba', 'Adèle', 'Adwoa',
      'Afi', 'Afia', 'Afua', 'Ahoefa', 'Aïda', 'Aïssah', 'Akofa',
      'Aku',
    ],
    male: [
      'Koffi', 'Kokou', 'Kossi', 'Kofi', 'Emmanuel', 'Claude', 'Georges',
      'Kodjo', 'Kwami', 'Charles', 'David', 'Jacques', 'Joseph', 'Paul',
      'Robert', 'Didier', 'Franck', 'François', 'Guy', 'Komi', 'Komla',
      'Michel', 'Pascal', 'Abdoul', 'Alex', 'Antoine', 'Benoît', 'Gilbert',
      'Jean', 'Jonathan', 'Komlan', 'Loïc', 'Mohamed', 'Richard', 'Roger',
      'Serge', 'Yao', 'Aimé', 'Anani', 'André', 'Edem', 'Félix',
      'Germain', 'Gerson', 'Guillaume', 'Julien', 'Kevin', 'Martin', 'Moïse',
      'Philippe',
    ],
    family: [
      'Akakpo', 'Lawson', 'Mensah', 'Olympio', 'Johnson', 'Touré', 'Agbo',
      'Agbobli', 'D\'Almeida', 'de Souza', 'Ekoue', 'Folly', 'Abi', 'Agbégnénou',
      'Aidam', 'Ajavon', 'Akoto', 'Alipui', 'Amedomé', 'Amétépé', 'Amoussou',
      'Ananou', 'Assih', 'Ayayi', 'Ayeva', 'Barcola', 'Bonfoh', 'Dossevi',
      'Fofana', 'Freitas', 'Grunitzky', 'Hundt', 'Kpotsra', 'Makouvia', 'Maman',
      'Panou', 'Salifou', 'Tosou', 'Worou', 'Yaya', 'Acolatse', 'Adams',
      'Adebayor', 'Adjaho', 'Adjima', 'Afetse', 'Agba', 'Agbegna', 'Agbeko',
      'Agblemagnon',
    ],
  },
  TZ: {
    female: [
      'Anna', 'Elizabeth', 'Mary', 'Esther', 'Khadija', 'Grace', 'Lucy',
      'Rose', 'Catherine', 'Ester', 'Irene', 'Joyce', 'Maria', 'Martha',
      'Salome', 'Sophia', 'Amina', 'Diana', 'Fatma', 'Fatuma', 'Magdalena',
      'Neema', 'Rehema', 'Ruth', 'Susan', 'Aisha', 'Anne', 'Asha',
      'Beatrice', 'Brenda', 'Halima', 'Hawa', 'Jacqueline', 'Janeth', 'Jennifer',
      'Josephine', 'Margaret', 'Mariam', 'Stella', 'Sylvia', 'Zainab', 'Angelina',
      'Blandina', 'Cecilia', 'Doreen', 'Faith', 'Flora', 'Gertrude', 'Happiness',
      'Janet', 'Ashatu', 'Tulia', 'Suma', 'Agnes', 'Ummy',
    ],
    male: [
      'John', 'Joseph', 'Juma', 'Ali', 'Mohamed', 'Charles', 'Peter',
      'William', 'Emmanuel', 'James', 'David', 'Muhammad', 'Abdallah', 'Edward',
      'George', 'Daniel', 'Godfrey', 'Stephen', 'Adam', 'Christopher', 'Hussein',
      'Julius', 'Martin', 'Michael', 'Paul', 'Richard', 'Simon', 'Ahmed',
      'Anthony', 'Henry', 'Vincent', 'Abdul', 'Ally', 'Amani', 'Andrew',
      'Augustine', 'Francis', 'Omar', 'Patrick', 'Rashid', 'Salim', 'Salum',
      'Suleiman', 'Albert', 'Benedict', 'Bernard', 'Felix', 'Frank', 'Hassan',
      'Joel', 'Omary', 'Mussa',
    ],
    family: [
      'Juma', 'Ali', 'Khamis', 'Laizer', 'Mollel', 'Abdallah', 'Tarimo',
      'Issa', 'Mapunda', 'Mussa', 'Ameir', 'Divecha', 'Hamad', 'Khatib',
      'Mohamed', 'Mrema', 'Nyerere', 'Salim', 'Shija', 'Cheyo', 'Dewji',
      'Emmanuel', 'Gama', 'Hussein', 'Joseph', 'Karume', 'Kawawa', 'Khalfan',
      'Kikwete', 'Komba', 'Lema', 'Mabula', 'Magufuli', 'Marwa', 'Mgimwa',
      'Mhina', 'Mkapa', 'Msuya', 'Mwanga', 'Mwinyi', 'Ramadhani', 'Rugambwa',
      'Salum', 'Shah', 'Abeid', 'Amani', 'Bakar', 'Bayo', 'Chami',
      'Chiplunkar', 'Kijaji', 'Gekul', 'Mwalimu', 'Ishengoma', 'Ackson', 'Mavunde',
      'Mkuchika', 'Kipanga',
    ],
  },
  UG: {
    female: [
      'Sarah', 'Esther', 'Grace', 'Christine', 'Catherine', 'Florence', 'Ruth',
      'Margaret', 'Rose', 'Mary', 'Agnes', 'Betty', 'Jane', 'Josephine',
      'Irene', 'Judith', 'Lillian', 'Annet', 'Joan', 'Patricia', 'Rebecca',
      'Stella', 'Sylvia', 'Beatrice', 'Elizabeth', 'Juliet', 'Diana', 'Doreen',
      'Evelyn', 'Harriet', 'Joyce', 'Olivia', 'Gloria', 'Susan', 'Alice',
      'Barbara', 'Flavia', 'Lydia', 'Peace', 'Sheila', 'Patience', 'Winnie',
      'Aisha', 'Brenda', 'Hellen', 'Hope', 'Joy', 'Sandra', 'Victoria',
      'Janet', 'Jesca', 'Dorcus',
    ],
    male: [
      'John', 'James', 'Charles', 'David', 'Joseph', 'Robert', 'Moses',
      'Patrick', 'Richard', 'Paul', 'Samuel', 'Peter', 'Emmanuel', 'Henry',
      'Godfrey', 'Michael', 'Francis', 'Andrew', 'Fred', 'Ronald', 'Stephen',
      'William', 'George', 'Martin', 'Isaac', 'Daniel', 'Edward', 'Brian',
      'Julius', 'Simon', 'Vincent', 'Arthur', 'Lawrence', 'Sam', 'Denis',
      'Christopher', 'Alex', 'Anthony', 'Geoffrey', 'Ivan', 'Joshua', 'Solomon',
      'Allan', 'Frank', 'Kenneth', 'Jimmy', 'Ibrahim', 'Nicholas', 'Abraham',
      'Hassan', 'Cuthbert',
    ],
    family: [
      'Okello', 'Birungi', 'Mukasa', 'Lubega', 'Kasule', 'Kayondo', 'Matovu',
      'Nsubuga', 'Kavuma', 'Kizito', 'Mbabazi', 'Odongo', 'Bukenya', 'Byarugaba',
      'Kaggwa', 'Makumbi', 'Murungi', 'Musoke', 'Aber', 'Amin', 'Asiimwe',
      'Babirye', 'Chebet', 'Kabagambe', 'Kabugho', 'Kasirye', 'Kato', 'Kigozi',
      'Kirya', 'Kiwanuka', 'Lule', 'Lwanga', 'Mukiibi', 'Muwonge', 'Namara',
      'Tendo', 'Zziwa', 'Akol', 'Ali', 'Anena', 'Arinaitwe', 'Awori',
      'Baguma', 'Jackson', 'Jemutai', 'Kabuye', 'Kakooza', 'Kalungi', 'Kansiime',
      'Kasumba', 'Ababiku', 'Abeja', 'Abigaba', 'Acen', 'Acon', 'Adome',
      'Aeku', 'Afidra',
    ],
  },
  ZA: {
    female: ['Onalerona', 'Zanokuhle', 'Melokuhle', 'Lisakhanya', 'Lethabo', 'Nkanyezi', 'Lesedi', 'Omphile', 'Olwemihla'],
    male: ['Lethabo', 'Lubanzi', 'Nkazimulo', 'Nkanyezi', 'Langelihle', 'Lesedi', 'Lethokuhle', 'Siphosethu', 'Leano'],
    family: ['Dlamini', 'Ndlovu', 'Nkosi', 'Khumalo', 'Sithole', 'Mkhize', 'Mokoena', 'Mthembu', 'Gumede', 'Ngcobo'],
  },
  ZM: {
    female: [
      'Esther', 'Mary', 'Natasha', 'Gladys', 'Margaret', 'Catherine', 'Judith',
      'Mirriam', 'Grace', 'Mutale', 'Susan', 'Agnes', 'Anna', 'Elizabeth',
      'Hellen', 'Memory', 'Naomi', 'Patricia', 'Racheal', 'Yvonne', 'Alice',
      'Angela', 'Carol', 'Christine', 'Diana', 'Doreen', 'Edith', 'Ellen',
      'Eunice', 'Evelyn', 'Florence', 'Jane', 'Jean', 'Joyce', 'Juliet',
      'Karen', 'Lily', 'Lucy', 'Lulu', 'Martha', 'Monica', 'Mulenga',
      'Mutinta', 'Nancy', 'Prisca', 'Ruth', 'Sara', 'Sylvia', 'Thandiwe',
      'Towela', 'Pauline', 'Olive', 'Clarissa', 'Stella', 'Melissa', 'Rosemary',
    ],
    male: [
      'Emmanuel', 'George', 'Charles', 'Patrick', 'Christopher', 'Joseph', 'Brian',
      'Moses', 'Peter', 'Andrew', 'Godfrey', 'Paul', 'Elijah', 'John',
      'Lawrence', 'Robert', 'Stephen', 'Bernard', 'David', 'Dennis', 'Felix',
      'Francis', 'Jacob', 'James', 'Michael', 'Simon', 'Daniel', 'Davies',
      'Gabriel', 'Henry', 'Keith', 'Kelvin', 'Richard', 'Ronald', 'Anthony',
      'Benjamin', 'Dickson', 'Edgar', 'Edward', 'Harry', 'Kennedy', 'Kenneth',
      'Maxwell', 'Samuel', 'Stanley', 'Thomas', 'Timothy', 'William', 'Alexander',
      'Allan', 'Clement', 'Martin', 'Raphael',
    ],
    family: [
      'Mulenga', 'Banda', 'Phiri', 'Tembo', 'Lungu', 'Zulu', 'Musonda',
      'Kaunda', 'Malama', 'Mwale', 'Mwanza', 'Chama', 'Kapwepwe', 'Moyo',
      'Mwansa', 'Chileshe', 'Daka', 'Kabwe', 'Kunda', 'Mwamba', 'Ngulube',
      'Nyambe', 'Smith', 'Chinkuli', 'Hichilema', 'Kabinga', 'Kapil', 'Kasonde',
      'Lota', 'Mambwe', 'Mutale', 'Ngoma', 'Ngonga', 'Ngosa', 'Nkonde',
      'Sakala', 'Scott', 'Siamupangila', 'Skinner', 'Soko', 'Zimba', 'Abraham',
      'Alibuzwi', 'Barry', 'Blom', 'Bots', 'Chabala', 'Chala', 'Chardy',
      'Charlton', 'Biyete', 'Bwalya', 'Chanda', 'Chiboola', 'Chibuye', 'Chirambo',
    ],
  },
  ZW: {
    female: [
      'Margaret', 'Elizabeth', 'Grace', 'Precious', 'Samantha', 'Sarah', 'Linda',
      'Mavis', 'Sandra', 'Sharon', 'Susan', 'Tracy', 'Virginia', 'Yvonne',
      'Agnes', 'Alice', 'Charity', 'Charmaine', 'Chido', 'Ellen', 'Faith',
      'Julia', 'Kudakwashe', 'Kudzai', 'Monica', 'Nicola', 'Olivia', 'Patience',
      'Alexandra', 'Amanda', 'Anne', 'Audrey', 'Barbara', 'Carol', 'Catherine',
      'Christine', 'Claire', 'Cynthia', 'Debbie', 'Emily', 'Emma', 'Georgina',
      'Gladys', 'Heather', 'Helen', 'Hope', 'Irene', 'Jane', 'Josephine',
      'Joyce', 'Sheillah', 'Yeukai', 'Tsitsi',
    ],
    male: [
      'David', 'Peter', 'John', 'Charles', 'Brian', 'Christopher', 'Paul',
      'Patrick', 'James', 'Robert', 'Daniel', 'Tinashe', 'Joseph', 'Kevin',
      'Mark', 'Michael', 'Mike', 'Simon', 'Godfrey', 'Richard', 'Trevor',
      'Andrew', 'Bernard', 'Bruce', 'Gary', 'George', 'Ian', 'Ronald',
      'Ryan', 'Stephen', 'William', 'Blessing', 'Donald', 'Douglas', 'Henry',
      'Luke', 'Sean', 'Takudzwa', 'Allan', 'Benjamin', 'Brendon', 'Cephas',
      'Edward', 'Gilbert', 'Guy', 'Herbert', 'Liam', 'Malcolm', 'Roy',
      'Samuel', 'Mthuli', 'Tongai', 'Joshua',
    ],
    family: [
      'Moyo', 'Ncube', 'Ndlovu', 'Williams', 'Dube', 'Smith', 'Phiri',
      'Campbell', 'Evans', 'Jones', 'Lewis', 'Matambanadzo', 'Mitchell', 'Mpofu',
      'Mugabe', 'Robinson', 'Sibanda', 'Banda', 'Conway', 'Cox', 'Davies',
      'Davis', 'Murphy', 'Ndiweni', 'Ngwenya', 'Price', 'Taylor', 'Waller',
      'Watson', 'Bennett', 'Brown', 'Cameron', 'Chiwara', 'Clark', 'Colahan',
      'Cole', 'Coventry', 'Crocker', 'Cross', 'Davidson', 'Edwards', 'Gibson',
      'Goodwin', 'Gray', 'Gumbo', 'Gurira', 'Harnden', 'Hewlett', 'Higgins',
      'Hill', 'Muchinguri-Kashiri', 'Mutsvangwa', 'Shava', 'Mnangagwa', 'Chikomo', 'Zhou',
    ],
  },
} as const

export function isAfricaReviewedCountry(code: string): code is keyof typeof africaReviewedNames {
  return Object.hasOwn(africaReviewedNames, code)
}
