// Source-backed local name components; coverage and limits in docs/geographic-data.md.
export const africaReviewedNames = {
  AO: {
    female: [
      'Maria', 'Ana', 'Helena', 'Isabel', 'Amélia', 'Teresa', 'Carolina',
      'Elisa', 'Luísa', 'Paula', 'Rosa', 'Joana', 'Luisa', 'Margarida',
      'Marta', 'Sandra', 'Antonia', 'Arminda', 'Carla', 'Cristina', 'Laurinda',
      'Liliana', 'Luzia', 'Manuela', 'Regina', 'Ruth', 'Sara', 'Telma',
      'Albertina', 'Alexandra', 'Amália', 'Ana Paula', 'Anastacia', 'Angela', 'Angelina',
      'Catarina', 'Chelsea', 'Conceição', 'Domingas', 'Eliane', 'Elizabeth', 'Elsa',
      'Emília', 'Engràcia', 'Esperança', 'Filomena', 'Francisca', 'Helga', 'Ilda',
      'Indira',
    ],
    male: [
      'João', 'José', 'Manuel', 'Pedro', 'Carlos', 'António', 'Paulo',
      'Francisco', 'Antonio', 'Fernando', 'Luís', 'Mário', 'Alberto', 'Eduardo',
      'Jorge', 'Luis', 'David', 'Joaquim', 'Ricardo', 'André', 'Filipe',
      'Henrique', 'Miguel', 'Alexandre', 'Daniel', 'Osvaldo', 'Wilson', 'Adriano',
      'Afonso', 'Augusto', 'Bruno', 'Domingos', 'Emanuel', 'Marcos', 'Rui',
      'Simão', 'Victor', 'Walter', 'Abel', 'Armando', 'Edmilson', 'Elias',
      'Jose', 'Marco', 'Mario', 'Mateus', 'Raúl', 'Agostinho', 'Alfredo',
      'Bernardo',
    ],
    family: [
      'Neto', 'Silva', 'Fernandes', 'Costa', 'Antonio', 'Gonçalves', 'Francisco',
      'Santos', 'Carvalho', 'Ferreira', 'Manuel', 'Alves', 'Gomes', 'Martins',
      'Miguel', 'Paulo', 'Pereira', 'da Silva', 'Oliveira', 'Afonso', 'Barros',
      'da Costa', 'Joao', 'Lima', 'Machado', 'Mingas', 'Morais', 'Abreu',
      'Almeida', 'Cardoso', 'Cruz', 'Da Silva', 'Fernando', 'Fonseca', 'Henriques',
      'Lopes', 'Monteiro', 'Nascimento', 'Pascoal', 'Pedro', 'Soares', 'Sousa',
      'Aguiar', 'Amaral', 'André', 'Augusto', 'Bastos', 'Caetano', 'Conceição',
      'Correia',
    ],
  },
  BF: {
    female: [
      'Mariam', 'Aminata', 'Awa', 'Martine', 'Alimata', 'Delphine', 'Aïssata',
      'Chantal', 'Fatoumata', 'Françoise', 'Juliette', 'Korotimi', 'Laetitia', 'Laure',
      'Madina', 'Maïmouna', 'Nathalie', 'Pauline', 'Sita', 'Aïcha', 'Alice',
      'Alima', 'Annick', 'Assita', 'Béatrice', 'Bintou', 'Carine', 'Carole',
      'Charlotte', 'Christine', 'Clarisse', 'Diane', 'Fatimata', 'Félicité', 'Flora',
      'Florentine', 'Habibou', 'Henriette', 'Honorine', 'Hortense', 'Irène', 'Jacqueline',
      'Joséphine', 'Malika', 'Minata', 'Monique', 'Patricia', 'Peggy', 'Priscille',
      'Ruth',
    ],
    male: [
      'Moussa', 'Abdoul', 'Mohamed', 'Aboubacar', 'Adama', 'Issa', 'Mamadou',
      'Souleymane', 'Abdoulaye', 'Idrissa', 'Jean', 'Jean-Baptiste', 'Serge', 'Yacouba',
      'Amadou', 'Ibrahim', 'Maurice', 'Pierre', 'Alain', 'Ali', 'Hervé',
      'Joseph', 'Karim', 'Laurent', 'Paul', 'Boubacar', 'Brahima', 'Frédéric',
      'Roger', 'Augustin', 'Bakary', 'Boureima', 'Charles', 'Dominique', 'Emmanuel',
      'François', 'Harouna', 'Ibrahima', 'Justin', 'Mahamoudou', 'Maxime', 'Muhammad',
      'Oumar', 'Ousmane', 'Patrick', 'Philippe', 'Robert', 'Salam', 'Salif',
      'Seydou',
    ],
    family: [
      'Ouédraogo', 'Traoré', 'Sawadogo', 'Kaboré', 'Ouattara', 'Ilboudo', 'Ouedraogo',
      'Zongo', 'Coulibaly', 'Compaoré', 'Touré', 'Dao', 'Diallo', 'Koné',
      'Sankara', 'Tapsoba', 'Zoungrana', 'Kabore', 'Nikiéma', 'Tiendrébéogo', 'Barry',
      'Diarra', 'Kambou', 'Nikiema', 'Paré', 'Thiombiano', 'Bationo', 'Cissé',
      'Damiba', 'Guissou', 'Kabré', 'Kouyaté', 'Minoungou', 'Bambara', 'Bamogo',
      'Bancé', 'Barro', 'Dabiré', 'Diakité', 'Kafando', 'Kini', 'Konaté',
      'Maïga', 'Naré', 'Sana', 'Sanon', 'Somda', 'Bado', 'Bangré',
      'Banse',
    ],
  },
  BI: {
    female: [
      "Esther", "Jeanine", "Lydia", "Antoinette", "Diane", "Dorine", "Erica",
      "Evelyne", "Florence", "Floriane", "Francine", "Françoise", "Justine", "Larissa",
      "Odette", "Rachelle", "Sandra", "Agnes", "Agnès", "Aimée", "Aisha",
      "Alice", "Aline", "Ange", "Angèle", "Angeline", "Angelique", "Aniella",
      "Anita", "Anne-Marie", "Arielle", "Asha", "Aziza", "Belinda", "Berthila",
      "Carine", "Carmen", "Carole", "Chanice", "Chantal", "Charlotte", "Christine",
      "Clarisse", "Clotilde", "Colette", "Cynthia", "Denise", "Divine", "Domitille",
      "Edith",
    ],
    male: [
      "Jean", "Pierre", "Emmanuel", "Pascal", "Alain", "Joseph", "Patrick",
      "Christian", "Albert", "Alexis", "Cédric", "Charles", "David", "Eric",
      "Gabriel", "Gervais", "Joachim", "Juma", "Martin", "Melchior", "Olivier",
      "Aimé", "Antoine", "Armel", "Bernard", "Blaise", "Dieudonné", "Domitien",
      "Emery", "Ernest", "Faustin", "Frédéric", "Gaspard", "Hussein", "Jonathan",
      "Justin", "Karim", "Léonce", "Michel", "Omar", "Parfait", "Samuel",
      "Willy", "Abdi", "Abdoul", "Akbar", "Alfred", "Alvin", "André",
      "Augustin",
    ],
    family: [
      "Irakoze", "Ndikumana", "Hakizimana", "Ndayishimiye", "Niyonkuru", "Nkurunziza", "Amissi",
      "Ndayizeye", "Uwimana", "Niyongabo", "Bizimana", "Bukuru", "Igiraneza", "Iradukunda",
      "Irankunda", "Kaneza", "Nahimana", "Ndihokubwayo", "Nininahazwe", "Nshimirimana", "Uwamahoro",
      "Bigirimana", "Bucumi", "Girukwishaka", "Iteka", "Kagayo", "Mvuyekure", "Ndadaye",
      "Ndayiragije", "Niragira", "Niteretse", "Nyamitwe", "Ramazani", "Rukundo", "Akimana",
      "Bagaza", "Bankumukunzi", "Barancira", "Barukinamwo", "Batumubwira", "Berahino", "Bishaza",
      "Buyoya", "Dushime", "Gahongore", "Gapiya-Niyonzima", "Ineza", "Ingabire", "Irishura",
      "Iteriteka",
    ],
  },
  BJ: {
    female: [
      'Christelle', 'Agnès', 'Christine', 'Edwige', 'Evelyne', 'Françoise', 'Gisèle',
      'Huguette', 'Nadine', 'Sophie', 'Anna', 'Brigitte', 'Carole', 'Grace',
      'Honorine', 'Inès', 'Marcelline', 'Nelly', 'Olga', 'Sèna', 'Sonia',
      'Véronique', 'Anne', 'Annick', 'Béatrice', 'Bernadette', 'Célestine', 'Chantal',
      'Clarisse', 'Claudine', 'Constance', 'Eliane', 'Elisabeth', 'Emmanuelle', 'Estelle',
      'Eugénie', 'Fatima', 'Fifamè', 'Flore', 'Geneviève', 'Gloria', 'Henriette',
      'Hortense', 'Innocentia', 'Jeanne', 'Jemima', 'Justine', 'Karamatou', 'Laure',
      'Léa',
    ],
    male: [
      'Pascal', 'Michel', 'Richard', 'Alain', 'Daniel', 'Jean', 'Joseph',
      'Louis', 'Antoine', 'Paul', 'Serge', 'Julien', 'Mohamed', 'Pierre',
      'Christian', 'Christophe', 'Eric', 'Guy', 'Jacques', 'Jérôme', 'Joël',
      'Justin', 'Marcel', 'Robert', 'Romuald', 'Yves', 'Alexis', 'Arnaud',
      'Aurélien', 'Charles', 'Claude', 'Comlan', 'Damien', 'Emmanuel', 'Francis',
      'François', 'Grégoire', 'Lionel', 'Luc', 'Mathieu', 'Patrice', 'Philippe',
      'Steve', 'Thomas', 'Valentin', 'Armand', 'Bertin', 'Charlemagne', 'David',
      'Didier',
    ],
    family: [
      'Amoussou', 'Gbaguidi', 'Mensah', 'Quenum', 'Boko', 'Dossou', 'Hountondji',
      'Adjovi', 'Dansou', 'Kérékou', 'Kidjo', 'Lokossou', 'Tosou', 'Adjaho',
      'Adjanohoun', 'Agbo', 'Ahossi', 'Behanzin', 'd\'Almeida', 'de Souza', 'Houngbédji',
      'Sagbo', 'Soglo', 'Sossou', 'Talon', 'Zinsou', 'Affo', 'Agboton',
      'Akplogan', 'Akpovi', 'Apithy', 'Badarou', 'Badou', 'Bello', 'Chabi',
      'da Silva', 'do Rêgo', 'Fagbohoun', 'Gbadamassi', 'Godonou', 'Guédègbé', 'Hounkpatin',
      'Loko', 'Padonou', 'Salami', 'Traoré', 'Yayi', 'Adam', 'Adande',
      'Adissoda',
    ],
  },
  BW: {
    female: ['Unity', 'Beauty', 'Talita', 'Phildah', 'Peggy', 'Annah'],
    male: ['Duma', 'Dithapelo', 'Dumelang', 'Wynter', 'Polson', 'Mokwaledi'],
    family: ['Dow', 'Manake', 'Monnakgotla', 'Keorapetse', 'Saleshando', 'Mmolotsi', 'Kedikilwe'],
  },
  CD: {
    female: [
      'Charlotte', 'Thérèse', 'Yvonne', 'Chantal', 'Solange', 'Grace', 'Jolie',
      'Mireille', 'Odette', 'Rebecca', 'Rose', 'Antoinette', 'Christelle', 'Christine',
      'Julie', 'Liliane', 'Nathalie', 'Pauline', 'Sophie', 'Suzanne', 'Adèle',
      'Annie', 'Astrid', 'Bernadette', 'Catherine', 'Françoise', 'Jeanne', 'Joséphine',
      'Lucie', 'Mamie', 'Marie-Thérèse', 'Naomi', 'Nicole', 'Patricia', 'Prisca',
      'Ruth', 'Wivine', 'Arlette', 'Clémentine', 'Diane', 'Esther', 'Eugénie',
      'Farida', 'Fifi', 'Gisèle', 'Gloria', 'Ida', 'Jacqueline', 'Jeannine',
      'Josée',
    ],
    male: [
      'Jean', 'Joseph', 'Patrick', 'Christian', 'André', 'Pierre', 'Albert',
      'Emmanuel', 'Jean-Marie', 'Serge', 'Daniel', 'Paul', 'Alain', 'Didier',
      'Jean-Pierre', 'Jonathan', 'Antoine', 'Charles', 'François', 'Guy', 'Jacques',
      'Marcel', 'Michel', 'Roger', 'Yves', 'Cédric', 'David', 'Jean-Claude',
      'John', 'Pascal', 'Augustin', 'Jules', 'Martin', 'Olivier', 'Richard',
      'Justin', 'Léonard', 'Willy', 'Aimé', 'Alphonse', 'Bernard', 'Dieudonné',
      'Franck', 'Jean-Paul', 'Léon', 'Robert', 'Samuel', 'Célestin', 'Eddy',
      'Faustin',
    ],
    family: [
      'Kazadi', 'Mutombo', 'Ilunga', 'Mboyo', 'Ntambwe', 'Kadima', 'Kayembe',
      'Mukoko', 'Mwenze', 'Ngoy', 'Lumumba', 'Makengo', 'Mbemba', 'Mbuyi',
      'Mwamba', 'Kalulu', 'Kamba', 'Kasongo', 'Mandanda', 'Ngalula', 'Nsimba',
      'Bonga', 'Kabasele', 'Kabongo', 'Kabuya', 'Kalenga', 'Kalonji', 'Kanjinga',
      'Kashama', 'Lusamba', 'Mafuta', 'Malu', 'Massamba', 'Matondo', 'Mulamba',
      'Muzinga', 'Ngoma', 'Tambwe', 'Tshisekedi', 'Bakenga', 'Balikwisha', 'Baloji',
      'Banza', 'Bishweka', 'Biyombo', 'Bongo', 'Bussa', 'Kalemba', 'Kamanda',
      'Kamanga',
    ],
  },
  CF: {
    female: [
      "Sylvie", "Yvonne", "Catherine", "Elisabeth", "Mireille", "Adrienne", "Anne-Marie",
      "Isabelle", "Léonie", "Lucienne", "Rosalie", "Alexandra", "Alphonsine", "Ambroisine",
      "Andrée", "Antoinette", "Bernadette", "Bertille", "Brigitte", "Carmen", "Chloé",
      "Christelle", "Corrine", "Danièle", "Denise", "Elizabeth", "Émilie", "Felicité",
      "Flavie", "Françoise", "Gabriella", "Georgette", "Gisèle", "Henriette", "Jeanne-Marie",
      "Jennifer", "Judith", "Laetitia", "Léa", "Leila", "Lisa", "Louise",
      "Lucile", "Lydie", "Madeleine", "Marguerite", "Maria", "Marie Solange", "Marie-Josèphe",
      "Marie-Noëlle",
    ],
    male: [
      "Jean", "Joseph", "Maurice", "Michel", "Antoine", "Hervé", "Thierry",
      "Wilfried", "André", "Charles", "Christian", "Cyriaque", "Gabriel", "Gaston",
      "Armel", "Bernard", "Chris", "David", "Dieudonné", "Dominique", "Emmanuel",
      "François", "Gilbert", "Guy", "Henri", "Isaac", "Jean-Baptiste", "Jean-Louis",
      "Jean-Pierre", "Junior", "Lionel", "Mohamed", "Nicaise", "Olivier", "Pierre",
      "Toussaint", "Abel", "Alexandre", "Ali", "Anicet", "Arnaud", "Arsène",
      "Benoît", "Bertrand", "Bruno", "Cédric", "Didier", "Édouard", "Élie",
      "Elvis",
    ],
    family: [
      "Bokassa", "Darlan", "Gonda", "Kongbo", "Adam", "Enza", "Kolingba",
      "Ngakoutou", "Patassé", "Samedi", "Solet", "Toumandji", "Yamissi", "Zouma",
      "Abazene", "Baïpo-Temon", "Balcilia", "Banga", "Beninga", "Beyina", "Biazin",
      "Bomawoko", "Dacko", "Damango", "Demba", "Denguiadé", "Ganda", "Gboulou",
      "Gombé-Ketté", "Gouandjika-Vasilache", "Habibou", "Haroune", "Kamoun", "Kondogbia", "Kosseyo",
      "Koyalipou", "Mano", "Mayounga", "Mboyo", "Mombollet", "Momi", "Muzinga",
      "N'Goyos", "Nimani", "Nongo-Aziagbia", "Nzapalainga", "Sayo", "Sende", "Somse",
      "Souleymane",
    ],
  },
  CG: {
    female: ['Pascaline', 'Simone', 'Hortense', 'Charlotte', 'Jeanne'],
    male: ['Daniel', 'Théophile', 'Michel', 'Pascal', 'Guillaume'],
    family: ['Adoua', 'Mahinga', 'Okoula', 'Ngoto', 'Assassa', 'Banvidi'],
  },
  CI: {
    female: [
      'Mariam', 'Fatou', 'Jeanne', 'Aminata', 'Awa', 'Patricia', 'Chantal',
      'Grace', 'Ange', 'Christelle', 'Christine', 'Adjoua', 'Anne', 'Assita',
      'Edwige', 'Fatim', 'Françoise', 'Henriette', 'Isabelle', 'Mariame', 'Marthe',
      'Rose', 'Salimata', 'Sarah', 'Stéphanie', 'Valérie', 'Akissi', 'Albertine',
      'Alima', 'Amoin', 'Angèle', 'Aya', 'Brigitte', 'Caroline', 'Constance',
      'Cynthia', 'Delphine', 'Emma', 'Fatoumata', 'Florence', 'Hélène', 'Inès',
      'Jennifer', 'Josée', 'Julie', 'Laetitia', 'Louise', 'Maïmouna', 'Mireille',
      'Mylène',
    ],
    male: [
      'Jean', 'Serge', 'Ibrahim', 'Alain', 'Mamadou', 'Adama', 'Mohamed',
      'Abdoulaye', 'Charles', 'Didier', 'Franck', 'Paul', 'Souleymane', 'Emmanuel',
      'Georges', 'Michel', 'Amadou', 'Bernard', 'François', 'Koffi', 'Laurent',
      'Moussa', 'Olivier', 'Patrick', 'Philippe', 'Joseph', 'Christian', 'Jacques',
      'Pascal', 'Wilfried', 'Alphonse', 'Ange', 'Armand', 'Eugène', 'Marcel',
      'Roger', 'Yacouba', 'Antoine', 'Axel', 'Blaise', 'Daniel', 'David',
      'Hervé', 'Ismael', 'Jean-Jacques', 'Joël', 'Lassina', 'Marc', 'Stéphane',
      'Yves',
    ],
    family: [
      'Koné', 'Touré', 'Traoré', 'Coulibaly', 'Ouattara', 'Fofana', 'Kouassi',
      'Cissé', 'Bamba', 'Koffi', 'Konan', 'Kouamé', 'Diomandé', 'Bakayoko',
      'Kouadio', 'Camara', 'Kone', 'N\'Guessan', 'Konaté', 'Kouakou', 'Diallo',
      'Sylla', 'Beugré', 'Diaby', 'Diabaté', 'Keita', 'Meité', 'Sanogo',
      'Yao', 'Boni', 'Diomande', 'Dosso', 'Bah', 'Blé', 'Brou',
      'Diakité', 'Diarra', 'Gbane', 'Keïta', 'Kouame', 'Koutouan', 'Meite',
      'N\'Zi', 'Traore', 'Aka', 'Ballo', 'Diarrassouba', 'Doué', 'Guéï',
      'Kamara',
    ],
  },
  CM: {
    female: [
      'Madeleine', 'Florence', 'Françoise', 'Jeanne', 'Solange', 'Thérèse', 'Chantal',
      'Carine', 'Esther', 'Louise', 'Rose', 'Laure', 'Monique', 'Anne',
      'Jacqueline', 'Nathalie', 'Audrey', 'Christelle', 'Marthe', 'Catherine', 'Cécile',
      'Céline', 'Justine', 'Mireille', 'Pauline', 'Rachel', 'Yvonne', 'Carole',
      'Charlotte', 'Christine', 'Colette', 'Diane', 'Elisabeth', 'Gaëlle', 'Isabelle',
      'Nadine', 'Patricia', 'Ruth', 'Stella', 'Agnès', 'Alice', 'Annie',
      'Antoinette', 'Brigitte', 'Estelle', 'Henriette', 'Judith', 'Odette', 'Suzanne',
      'Yvette',
    ],
    male: [
      'Jean', 'Joseph', 'Emmanuel', 'Paul', 'Pierre', 'Samuel', 'Serge',
      'Charles', 'Patrick', 'Alain', 'Guy', 'Martin', 'Christian', 'Michel',
      'Franck', 'Simon', 'David', 'Jacques', 'Eric', 'François', 'André',
      'Dieudonné', 'Hervé', 'Ernest', 'Claude', 'Thomas', 'Georges', 'Olivier',
      'Armand', 'Daniel', 'Henri', 'Jules', 'Louis', 'René', 'Francis',
      'Gabriel', 'Thierry', 'William', 'Albert', 'Luc', 'Patrice', 'Roger',
      'Yves', 'Junior', 'Richard', 'Vincent', 'Bernard', 'Jean-Pierre', 'Victor',
      'Antoine',
    ],
    family: [
      'Owona', 'Bell', 'Atangana', 'Fotso', 'Ayissi', 'Mbarga', 'Mvondo',
      'Njoya', 'Simo', 'Ateba', 'Eyenga', 'Onana', 'Oyono', 'Biya',
      'Eloundou', 'Essomba', 'Fouda', 'Kamdem', 'Mbappé', 'Nana', 'Ndam',
      'Ngo', 'Njock', 'Zambo', 'Zogo', 'Abega', 'Bella', 'Bissa',
      'Etoga', 'Eyango', 'Kadji', 'Kameni', 'Manga', 'Matam', 'Mbah',
      'Mbida', 'Mengue', 'Minlend', 'Monkam', 'Mveng', 'Noah', 'Obama',
      'Amadou', 'Amougou', 'Balla', 'Belinga', 'Boya', 'Dika', 'Effa',
      'Essama',
    ],
  },
  CV: {
    female: [
      "Maria", "Ana", "Carla", "Alice", "Artemisa", "Belinda", "Cristina",
      "Eva", "Fátima", "Nancy", "Adriana", "Adysângela", "Albertina", "Alecia",
      "Alexia", "Alzira", "Angela", "Angelina", "Antonina", "Arianne", "Ashley",
      "Augusta", "Aurea", "Bernardina", "Camilla", "Carina", "Carlina", "Celina",
      "Cesária", "Clara", "Crispina", "Débora", "Denise", "Djamila", "Doris",
      "Edmira", "Eileen", "Élida", "Élisabeth", "Epifânia", "Eunice", "Evy",
      "Filomena", "Francelina", "Georgina", "Graça", "Helena", "Hermínia", "Isabel",
      "Isaura",
    ],
    male: [
      "Carlos", "António", "José", "Manuel", "Jorge", "Luís", "Pedro",
      "Fernando", "Emanuel", "João", "José Luís", "Mário", "Patrick", "Antonio",
      "David", "Emerson", "Hugo", "Kelvin", "Kevin", "Paulo", "Roberto",
      "Abílio", "Adilson", "Aires", "Alexandre", "Alexis", "Aristides", "Arlindo",
      "Augusto", "Daniel", "Dylan", "Edi", "Elvis", "Flávio", "Francisco",
      "Fredson", "Gabriel", "Gil", "Gilson", "Ildo", "Ivan", "Jeffrey",
      "João Baptista", "Joaquim", "Jordan", "Josimar", "Júlio", "Lúcio", "Luis",
      "Marco",
    ],
    family: [
      "Lopes", "Tavares", "Almeida", "Lima", "Monteiro", "Mendes", "Andrade",
      "Gomes", "Silva", "Soares", "Fernandes", "Duarte", "Pereira", "Martins",
      "Rodrigues", "Semedo", "Correia", "Alves", "Costa", "Delgado", "Fonseca",
      "Fortes", "Ramos", "Borges", "Brito", "Cruz", "Furtado", "Gonçalves",
      "Moreira", "Rocha", "Pina", "Varela", "Barbosa", "Barros", "Cabral",
      "Cardoso", "Chantre", "da Graça", "de Brito", "Dias", "Évora", "Freitas",
      "Mascarenhas", "Morais", "Ribeiro", "Veiga", "Vieira", "Almada", "Antunes",
      "Carvalho",
    ],
  },
  DZ: {
    female: [
      "Nadia", "Amina", "Yasmine", "Meriem", "Fatima", "Leila", "Malika",
      "Sarah", "Fatiha", "Zohra", "Amel", "Djamila", "Amira", "Samia",
      "Fāṭima al-Zahra", "Karima", "Nassima", "Sabrina", "Souad", "Kenza", "Lydia",
      "Salima", "Aïcha", "Dalila", "Inès", "Khadija", "Lynda", "Samira",
      "Anissa", "Farida", "Houria", "Nesrine", "Sofia", "Suhaila", "Baya",
      "Fatma", "Imane", "Kahina", "Katia", "Leïla", "Lina", "Linda",
      "Nabila", "Sara", "Selma", "Tassadit", "Yasmina", "Amal", "Asma",
      "Chaima",
    ],
    male: [
      "Mohamed", "Muhammad", "Ahmed", "Ali", "Abdelkader", "Rachid", "Kamel",
      "Karim", "Mustapha", "Samir", "Abd al-Rahman", "Djamel", "Nabil", "Sofiane",
      "Noureddine", "Youcef", "Saïd", "Amar", "Omar", "Yacine", "Mourad",
      "Brahim", "Farid", "Boualem", "Abdelaziz", "Ahmad", "Amine", "Hamza",
      "Abdelkarim", "Faïçal", "Hocine", "Rabah", "Salah", "Salim", "Abdelmalek",
      "Adel", "Hamid", "Sid", "Abd al-Qadir", "Abderrahmane", "Tahar", "Azzedine",
      "Mohand", "Hakim", "Larbi", "Mouloud", "Slimane", "Abdelhamid", "Hichem",
      "Miloud",
    ],
    family: [
      "Boushaki", "Belkacem", "Boutiche", "Brahimi", "Kerbouche", "Amrani", "Benyahia",
      "Rahmoune", "Saadi", "Talamali", "Zerrouki", "Bencheikh", "Boumerdassi", "Haddad",
      "Hakkar", "Hocine", "Kacimi", "Mebarki", "Mohammedi", "Mokhtari", "Taleb",
      "Toubal", "Tounsi", "Ziani", "Zitouni", "Ahmed", "Amar", "Amara",
      "Amrouche", "Belhocine", "Benabid", "Benali", "Bensalah", "Bouras", "Bouzidi",
      "Daoud", "Derradji", "Hassani", "Kaci", "Kadi", "Khaldi", "Laribi",
      "Madani", "Matoub", "Merabet", "Moussa", "Ouali", "Rahal", "Saïd",
      "Saidi",
    ],
  },
  EG: {
    female: [
      "Mona", "Sara", "Heba", "Nadia", "Farida", "Amira", "Aya",
      "Amina", "Laila", "Maha", "Mariam", "Reem", "Sahar", "Salma",
      "Fatima", "Eman", "Ghada", "Magda", "Nada", "Hana", "Huda",
      "Jana", "Nour", "Rania", "Amal", "Yasmin", "Aida", "Dalia",
      "Hanan", "Malak", "Abeer", "Jihan", "Marwa", "Samia", "Samira",
      "Sarah", "Wafaa", "Yasmine", "Amale", "Doaa", "Elham", "Fatma",
      "Mai", "Nahed", "Awatef", "Donia", "Habiba", "Inji", "Manal",
      "Nabila",
    ],
    male: [
      "Muhammad", "Mohamed", "Ahmad", "Ahmed", "Mahmoud", "Ibrahim", "Ali",
      "Hassan", "Mustafa", "Omar", "Hussein", "Salah", "Samir", "Karim",
      "Tarek", "Kamal", "Adel", "Abdullah", "Amr", "Mostafa", "Youssef",
      "Sherif", "Osama", "Alaa", "Fouad", "Abd al-Rahman", "Khaled", "Nabil",
      "Ismail", "Saeed", "Ayman", "Magdi", "Abdul Monem", "Hisham", "Yusuf",
      "Abdelaziz", "Ashraf", "Hamdi", "Hosam", "Tamer", "Saad", "Abbas",
      "Amir", "Fathi", "Ihab", "Sameh", "Wael", "Hasan", "Mohsen",
      "Sid",
    ],
    family: [
      "Mohamed", "Ahmed", "Hussein", "Ibrahim", "Salem", "Hassan", "Mostafa",
      "Mahmoud", "Amin", "Fahmi", "Zaki", "Khalil", "Saleh", "Fouad",
      "Mansour", "Ismail", "Youssef", "Abdelaziz", "Hegazy", "Moussa", "Awad",
      "Farghali", "Helmy", "Suleiman", "Ali", "Amer", "Hafez", "Magdy",
      "Selim", "Issa", "Mustafa", "Nasr", "Sabry", "Zulfikar", "Atiyah",
      "Darwish", "Ezzat", "Hasan", "Maher", "Morsi", "Osman", "Said",
      "Abbas", "Abdullah", "El Gendy", "Farid", "Hamza", "Kandil", "Khaled",
      "Makkawi",
    ],
  },
  GA: {
    female: [
      "Angèle", "Cynthia", "Flore", "Gisèle", "Grace", "Honorine", "Prisca",
      "Solange", "Anaïs", "Anne-Marie", "Audrey", "Brigitte", "Carine", "Charlaine",
      "Christine", "Claudine", "Danièle", "Diane", "Emmanuella", "Félicité", "Françoise",
      "Huguette", "Ida", "Jeanne", "Justine", "Larissa", "Liliane", "Marielle",
      "Martine", "Myriam", "Nadège", "Odette", "Pascaline", "Paulette", "Raisa",
      "Rose", "Ruth", "Sandra", "Sylvie", "Yvette", "Aicha", "Aida",
      "Albertine", "Alexa", "Angélique", "Anicette", "Annick", "Annie", "Anouchka",
      "Armande",
    ],
    male: [
      "Jean", "Paul", "Pierre", "Alain", "Charles", "Guy", "André",
      "Stéphane", "Cédric", "Georges", "Michel", "Thierry", "Claude", "Dieudonné",
      "Emmanuel", "Germain", "Jacques", "Joseph", "Landry", "Luc", "Patrick",
      "Vincent", "Anthony", "Antoine", "Franck", "François", "Jean-Baptiste", "Jean-Pierre",
      "Junior", "Léon", "Paulin", "Régis", "Richard", "Roger", "Serge",
      "Alexandre", "Alexis", "Augustin", "Aurélien", "Benjamin", "Bertrand", "Boris",
      "Brice", "Bruno", "Christian", "Daniel", "David", "Eric", "Étienne",
      "Fidèle",
    ],
    family: [
      "Ndong", "Moussavou", "Obiang", "Aubameyang", "Bongo", "Issembe", "Nguema",
      "Ondo", "Minko", "Mombo", "Assoumou", "Bouanga", "Gondjout", "Kanga",
      "Lemboumba", "Lemina", "Makaya", "Makosso-Akendengué", "Mamboundou", "Mba", "Moundounga",
      "Mpali", "Ngakoutou", "Obame", "Ossey", "Oyono", "Abessolo", "Anghiley",
      "Assembe", "Atcho", "Aubame", "Bading", "Batonon", "Boupendza", "Copa",
      "Ecuele Manga", "Ekondo", "Ella", "Ename", "Eneme", "Essono", "Gassita",
      "Kassa", "Koko", "Lasme", "Lepandou", "Londo", "Louembe", "Massala",
      "Mba Abessole",
    ],
  },
  GH: {
    female: [
      'Elizabeth', 'Grace', 'Mary', 'Ama', 'Nana', 'Cynthia', 'Anita',
      'Abena', 'Akosua', 'Lydia', 'Akua', 'Esther', 'Gifty', 'Victoria',
      'Cecilia', 'Diana', 'Mavis', 'Patience', 'Priscilla', 'Rita', 'Theresa',
      'Afia', 'Alice', 'Beatrice', 'Gladys', 'Linda', 'Margaret', 'Rose',
      'Abigail', 'Florence', 'Gloria', 'Juliana', 'Mercy', 'Sandra', 'Adwoa',
      'Afua', 'Agnes', 'Doris', 'Ernestina', 'Hannah', 'Janet', 'Joyce',
      'Patricia', 'Rebecca', 'Ruth', 'Sophia', 'Yaa', 'Barbara', 'Belinda',
      'Comfort',
    ],
    male: [
      'Emmanuel', 'Samuel', 'Joseph', 'John', 'Isaac', 'Daniel', 'George',
      'Francis', 'Charles', 'Kofi', 'Kwabena', 'James', 'David', 'Michael',
      'Eric', 'Muhammad', 'Richard', 'Edward', 'Kwame', 'Stephen', 'William',
      'Anthony', 'Frank', 'Benjamin', 'Kwaku', 'Nana', 'Peter', 'Robert',
      'Yaw', 'Ernest', 'Alfred', 'Patrick', 'Paul', 'Kwadwo', 'Alex',
      'Ibrahim', 'Bernard', 'Ebenezer', 'Henry', 'Kwesi', 'Thomas', 'Joe',
      'Albert', 'Seth', 'Joshua', 'Prince', 'Felix', 'Frederick', 'Kwasi',
      'Lawrence',
    ],
    family: [
      'Mensah', 'Boateng', 'Owusu', 'Appiah', 'Adjei', 'Osei', 'Opoku',
      'Yeboah', 'Addo', 'Boakye', 'Tetteh', 'Adams', 'Asare', 'Acheampong',
      'Asante', 'Asamoah', 'Acquah', 'Adu', 'Ofori', 'Amoah', 'Donkor',
      'Agyemang', 'Darko', 'Lamptey', 'Sarpong', 'Adam', 'Addy', 'Amoako',
      'Annan', 'Frimpong', 'Quaye', 'Gyamfi', 'Gyan', 'Hammond', 'Johnson',
      'Mohammed', 'Williams', 'Amankwah', 'Antwi', 'Ibrahim', 'Poku', 'Salifu',
      'Andoh', 'Ansah', 'Awuah', 'Bonsu', 'Danquah', 'Konadu', 'Manu',
      'Ofosu',
    ],
  },
  GM: {
    female: [
      'Fatou', 'Fatoumata', 'Hannah', 'Mariama', 'Anna', 'Awa', 'Isatou',
      'Amie', 'Elizabeth', 'Mary', 'Agnes', 'Cecilia', 'Fanta', 'Fatima',
      'Jainaba', 'Janet', 'Khadija', 'Mama', 'Sally', 'Adama', 'Adelaide',
      'Adja', 'Aminata', 'Aminatta', 'Angela', 'Ann', 'Annie', 'Augusta',
      'Beatrice', 'Belinda', 'Binta', 'Bintou', 'Caroline', 'Catherine', 'Dolly',
      'Fanny', 'Fatim', 'Florence', 'Georgiana', 'Gina', 'Gwladys', 'Hadja',
      'Harriet', 'Hawa', 'Ida', 'Isha', 'Juka', 'Julia', 'Lilian',
      'Loubna',
    ],
    male: [
      'Lamin', 'Momodou', 'Omar', 'Alieu', 'Mustapha', 'Abdoulie', 'Bakary',
      'Dawda', 'Musa', 'Alagie', 'Ebrima', 'John', 'Amadou', 'Ousman',
      'Assan', 'Modou', 'Muhammad', 'Muhammed', 'Pierre', 'Samuel', 'Yankuba',
      'Adama', 'Francis', 'Gibril', 'Ismaila', 'Joseph', 'Paul', 'Abdou',
      'Ali', 'Baba', 'Hassan', 'Henry', 'James', 'Malick', 'Peter',
      'Samba', 'Yahya', 'Yaya', 'Bala', 'Demba', 'Ebou', 'Edward',
      'Emil', 'Essa', 'Gabriel', 'George', 'Horace', 'Ibrahima', 'Karamba',
      'Lamine',
    ],
    family: [
      'Ceesay', 'Jatta', 'Njie', 'Jallow', 'Colley', 'Mendy', 'Bah',
      'Jammeh', 'Bojang', 'Touray', 'Badjie', 'Drammeh', 'Sowe', 'Faal',
      'Gaye', 'Sey', 'Camara', 'Gomez', 'Manneh', 'Barrow', 'Jobe',
      'Johnson', 'Jones', 'Nyassi', 'Peters', 'Sanyang', 'Sonko', 'Fatty',
      'Gómez', 'Jawara', 'Sabally', 'Sillah', 'Barry', 'Bensouda', 'Forster',
      'Gassama', 'Janneh', 'Joof', 'Keita', 'Mahoney', 'Saho', 'Secka',
      'Sinyan', 'Allen', 'Baldeh', 'Carayol', 'Cole', 'Conteh', 'Danso',
      'Dibba',
    ],
  },
  GN: {
    female: [
      'Fatoumata', 'Aminata', 'Mariama', 'Hawa', 'Kadiatou', 'Aissatou', 'Hadja',
      'Binta', 'Fanta', 'Mariam', 'Oumou', 'Saran', 'Aïssata', 'Mariame',
      'Halimatou', 'Maïmouna', 'Ramatoulaye', 'Adama', 'Bintou', 'Fatou', 'Maimouna',
      'Mama', 'Safiatou', 'Sira', 'Aicha', 'Aïcha', 'Aissata', 'Diaka',
      'Diariatou', 'Djené', 'Eva', 'Fatima', 'Houleymatou', 'Khady', 'Lamarana',
      'Makèmè', 'Mariana', 'Paulette', 'Rougui', 'Salimatou', 'Sona', 'Ada',
      'Aïssatou', 'Andrée', 'Angeline', 'Anne-Marie', 'Arabiya', 'Ary', 'Aya',
      'Batouly',
    ],
    male: [
      'Mamadou', 'Mohamed', 'Ibrahima', 'Aboubacar', 'Abdoulaye', 'Alpha', 'Ousmane',
      'Amadou', 'Sekou', 'Moussa', 'Souleymane', 'Oumar', 'Fodé', 'Thierno',
      'Lamine', 'Mamady', 'Boubacar', 'Abdoul', 'Jean', 'Amara', 'Mory',
      'Ahmed', 'Aly', 'Saliou', 'Moustapha', 'Cheick', 'Chérif', 'Daouda',
      'Ibrahim', 'Lansana', 'Muhammad', 'Abdourahmane', 'Alhassane', 'Balla', 'Idrissa',
      'Karim', 'Mamoudou', 'Naby', 'Sékouba', 'Aliou', 'Ansoumane', 'Charles',
      'François', 'Kabinet', 'Oury', 'Saïdou', 'Seydouba', 'Sidiki', 'Abou',
      'Baba',
    ],
    family: [
      'Diallo', 'Camara', 'Bah', 'Barry', 'Sylla', 'Kaba', 'Keita',
      'Touré', 'Condé', 'Bangoura', 'Traoré', 'Baldé', 'Cissé', 'Soumah',
      'Sow', 'Kourouma', 'Diakité', 'Doumbouya', 'Fofana', 'Konaté', 'Diaby',
      'Kouyaté', 'Kanté', 'Sidibé', 'Diawara', 'Conté', 'Béavogui', 'Keïta',
      'Mara', 'Oularé', 'Thiam', 'Tounkara', 'Diabaté', 'Doré', 'Toure',
      'Bamba', 'Guilavogui', 'Koné', 'Koulibaly', 'Loua', 'Yansané', 'Balde',
      'Conde', 'Diané', 'Nabé', 'Sangaré', 'Tolno', 'Zoumanigui', 'Coumbassa',
      'Daffé',
    ],
  },
  GQ: {
    female: [
      "María", "Consuelo", "Mónica", "Ángela", "Catalina", "Cristina", "Dolores",
      "Emiliana", "Eulalia", "Juliana", "Lucrecia", "Margarita", "María del Pilar", "Monserrat",
      "Nuria", "Raquel", "Trinidad", "Adoración", "Adriana", "Anacleta", "Anastasia",
      "Ángeles", "Angelina", "Antonina", "Asunción", "Athenea", "Begoño", "Brígida",
      "Carina", "Carmela", "Cecilia", "Celeste", "Celestina", "Constancia", "Diana",
      "Dorine", "Elena", "Emilia", "Engracia", "Erundina", "Esperanza", "Estefanía",
      "Eugenia", "Eva", "Evangelina", "Francisca", "Genoveva", "Gertrudis", "Ghyslaine",
      "Goretti",
    ],
    male: [
      "Juan", "José", "Miguel", "Pedro", "Manuel", "Antonio", "Pablo",
      "Ángel", "Francisco", "Carlos", "Federico", "Salvador", "Daniel", "Enrique",
      "Felipe", "Iván", "Jesús", "Óscar", "Santiago", "Andrés", "David",
      "Javier", "Junior", "Luis", "Marcelino", "Marcos", "Rubén", "Alberto",
      "Alejandro", "Baltasar", "Basilio", "Bonifacio", "Celestino", "César", "Crispín",
      "Cristian", "Diosdado", "Domingo", "Emiliano", "Emilio", "Esteban", "Joaquín",
      "José Luis", "Justo", "Lucas", "Marcelo", "Martín", "Ramón", "Reginaldo",
      "Ruslan",
    ],
    family: [
      "Esono", "Nguema", "Ondo", "Asumu", "Nsue", "Obama", "Obiang",
      "Balboa", "Ela", "Mba", "Obono", "Eneme", "Malango", "Mbomio",
      "Ndong", "Oyono", "Bibang", "Boho", "Engonga", "Envo", "Ntutumu",
      "Okenve", "Abeso", "Akapo", "Ayingono", "Barila", "Bolekia", "Botey",
      "Buale", "Bueriberi", "Buyla", "Dacosta", "Elo", "Enguru", "Eyang",
      "García", "Hernández", "Lobede", "Machín", "Macías", "Makoli", "Manga",
      "Nculu", "Ngui", "Nsang", "Nze", "Owono", "Rondo", "Seriche",
      "Sipi",
    ],
  },
  KE: {
    female: [
      'Mary', 'Catherine', 'Esther', 'Margaret', 'Jane', 'Elizabeth', 'Rose',
      'Ruth', 'Caroline', 'Grace', 'Mercy', 'Anne', 'Gladys', 'Joyce',
      'Beatrice', 'Janet', 'Nancy', 'Susan', 'Agnes', 'Alice', 'Emily',
      'Irene', 'Sarah', 'Faith', 'Josephine', 'Judith', 'Lydia', 'Naomi',
      'Christine', 'Diana', 'Eunice', 'Florence', 'Cynthia', 'Lucy', 'Sylvia',
      'Betty', 'Hellen', 'Joan', 'Judy', 'Martha', 'Rebecca', 'Veronica',
      'Vivian', 'Yvonne', 'Dorothy', 'Edith', 'Eva', 'Monica', 'Nelly',
      'Pauline', 'Lilian', 'Eve', 'Millie',
    ],
    male: [
      'John', 'David', 'Peter', 'Joseph', 'James', 'Paul', 'Daniel',
      'Charles', 'George', 'Patrick', 'William', 'Julius', 'Francis', 'Robert',
      'Stephen', 'Philip', 'Simon', 'Moses', 'Geoffrey', 'Michael', 'Richard',
      'Benjamin', 'Samuel', 'Henry', 'Thomas', 'Joshua', 'Vincent', 'Edwin',
      'Nicholas', 'Sammy', 'Wilson', 'Gideon', 'Mike', 'Anthony', 'Christopher',
      'Eric', 'Alfred', 'Bernard', 'Fred', 'Mark', 'Martin', 'Samson',
      'Abraham', 'Elijah', 'Isaac', 'Brian', 'Duncan', 'Emmanuel', 'Evans',
      'Gilbert', 'Tom', 'Elisha',
    ],
    family: [
      'Cheruiyot', 'Kirui', 'Kosgei', 'Odhiambo', 'Rotich', 'Koech', 'Korir',
      'Maina', 'Otieno', 'Wambui', 'Kariuki', 'Kibet', 'Kimani', 'Kiprop',
      'Tanui', 'Wanjiru', 'Rono', 'Chebet', 'Kiptoo', 'Nderitu', 'Onyango',
      'Owino', 'Chelimo', 'Chepng\'etich', 'Kemboi', 'Kipruto', 'Makokha', 'Mbugua',
      'Jepchirchir', 'Kiplagat', 'Kiptum', 'Njoroge', 'Okoth', 'Biwott', 'Chepchumba',
      'Cherono', 'Kamau', 'Kimutai', 'Kiprotich', 'Kipsang', 'Langat', 'Masai',
      'Mutai', 'Odinga', 'Okumu', 'Ouma', 'Patel', 'Ruto', 'Shah',
      'Wanjiku', 'Ochieng', 'Opondo', 'Oduor', 'Omondi',
    ],
  },
  LR: {
    female: [
      'Ellen', 'Grace', 'Agnes', 'Antoinette', 'Emma', 'Izetta', 'Martha',
      'Mary', 'Ophelia', 'Thelma', 'Victoria', 'Abigail', 'Angela', 'Anna',
      'Charlyne', 'Cherie', 'Dawn', 'Dede', 'Destiny', 'Dorothy', 'Ebony',
      'Edith', 'Ethel', 'Eugenia', 'Faith', 'Fatima', 'Fatu', 'Finda',
      'Florence', 'Frances', 'Ginny', 'Gladys', 'Gloria', 'Hannah', 'Iho',
      'Inez', 'Iris', 'Jane', 'Jeannette', 'Jewel', 'Julia', 'Juliet',
      'Kia', 'Lina', 'Lois', 'Mae', 'Mai', 'Maia', 'Malinda',
      'Margaret',
    ],
    male: [
      'George', 'James', 'Joseph', 'Samuel', 'Thomas', 'Edward', 'John',
      'Anthony', 'Charles', 'David', 'William', 'Emmanuel', 'Alex', 'Alfred',
      'Daniel', 'Francis', 'Alexander', 'Amos', 'Ben', 'Christopher', 'Gabriel',
      'Michael', 'Nicholas', 'Patrick', 'Prince', 'Arthur', 'Augustus', 'Chris',
      'Clarence', 'Eric', 'Ernest', 'Eugene', 'Frank', 'Henry', 'Lewis',
      'Nathaniel', 'Robert', 'Stephen', 'Adam', 'Aloysius', 'Amara', 'Andrew',
      'Augustine', 'Benjamin', 'Darius', 'Dominic', 'Edwin', 'Hilary', 'Isaac',
      'Jeremiah',
    ],
    family: [
      'Johnson', 'Cooper', 'Dennis', 'Roberts', 'Williams', 'Gibson', 'Jones',
      'Morris', 'Smith', 'Carr', 'Doe', 'Harris', 'Tolbert', 'Brown',
      'Collins', 'Davis', 'Dixon', 'Harmon', 'King', 'Kromah', 'Massaquoi',
      'Taylor', 'Weah', 'Addy', 'Anderson', 'Barclay', 'Blay', 'Brooks',
      'Bryant', 'Clinton', 'Coleman', 'Davies', 'Diallo', 'Diggs', 'Duncan',
      'Forko', 'Freeman', 'Gbandi', 'Grimes', 'Holder', 'Jackson', 'Kennedy',
      'Kollie', 'Lewis', 'McClain', 'McIntosh', 'Minor', 'Morrison', 'Nagbe',
      'Nimely',
    ],
  },
  LS: {
    female: ['Matumelo', 'Mamoipone', 'Likeleli', 'Mathato', 'Manthabiseng'],
    male: ['Tello', 'Thabo', 'Motlatsi', 'Moshoeshoe', 'Tseliso'],
    family: ['Sekatle', 'Senauoane', 'Monare', 'Phafoli', 'Phohleli', 'Kibane', 'Maqelepo', 'Fako'],
  },
  LY: {
    female: [
      "Khadija", "Farida", "Fatima", "Amira", "Hana", "Hanan", "Huda",
      "Iman", "Mabrouka", "A'isha", "Aïcha", "Aisha", "Amna", "Anisa",
      "Asia", "Dania", "Duaa", "Faraḥ", "Fethiye", "Hager", "Hajer",
      "Hikmat", "Ibtissem", "Izza", "Kaouther", "Kariman", "Laila", "Lamia",
      "Latifa", "Lütfiye", "Maryam", "Nadia", "Najat", "Najla", "Najwa",
      "Nissa", "Rodaina", "Safia", "Samira", "Saniya", "Sema", "Vivienne",
      "Yasmina", "Zahra", "Zaima", "Amel", "Ghada", "Halla", "Mayada",
      "Selma",
    ],
    male: [
      "Muhammad", "Ali", "Ahmad", "Ahmed", "Mohamed", "Abdullah", "Omar",
      "Mustafa", "Fathi", "Ibrahim", "Osama", "Abd al-Salam", "Mahmoud", "Abd al-Qadir",
      "Abd al-Rahman", "Chalifa", "Hussein", "Mansour", "Samir", "Umar", "Abdel Fattah",
      "Faraj", "Fethi", "Hasan", "Hisham", "Kamal", "Mahmud", "Waleed",
      "Yousef", "Abdul Hafiz", "Abdul Razak", "Abu Bakr", "Anwar", "Aymen", "Bashir",
      "Faouzi", "Hamza", "Hassan", "Jamal", "Kamel", "Mahdi", "Miloud",
      "Moussa", "Muammar", "Nabil", "Nuri", "Saad", "Saeed", "Salih",
      "Suleiman",
    ],
    family: [
      "Al-Bar'asi", "Al-Musrati", "al-Saʻdāwī", "Hassan", "Labidi", "Salem", "Tarhouni",
      "Abdulgader", "Aboud", "Ahmed", "Al Abaidy", "Al Senussi", "Al-Haddad", "Al-Masri",
      "Al-Shuwayrif", "Al-Talhi", "Al-Werfalli", "Alfasi", "Allag", "Benali", "Daoud",
      "Deghayes", "Fawzi", "Filali", "Ghouma", "Hamada", "Hariri", "Ibrahim",
      "Jaber", "Jabr", "Jalli", "Jibril", "Kabar", "Koussa", "Labi",
      "Maatouk", "Makhlouf", "Mangoush", "Massoudi", "Matar", "Mayet", "Mejri",
      "Milad", "Najm", "Okasha", "Omran", "Osman", "Rajab", "Roumani",
      "Saqr",
    ],
  },
  MA: {
    female: [
      "Fatima", "Khadija", "Fāṭima al-Zahra", "Amina", "Latifa", "Nadia", "Malika",
      "Hanane", "Leila", "Souad", "Hind", "Najat", "Imane", "Nezha",
      "Samira", "Asma", "Bouchra", "Aicha", "Meryem", "Salma", "Zineb",
      "Ibtissam", "Laila", "Naima", "Sofia", "Kenza", "Mounia", "Sara",
      "Amal", "Fatiha", "Sanaa", "Sarah", "Siham", "Touria", "Yasmine",
      "Hafida", "Hayat", "Jamila", "Lamia", "Meriem", "Nadiyah", "Nora",
      "Salima", "Soukaïna", "Aziza", "Nawal", "Rania", "Farida", "Loubna",
      "Naïma",
    ],
    male: [
      "Mohamed", "Muhammad", "Ahmed", "Rachid", "Driss", "Hassan", "Ahmad",
      "Omar", "Youssef", "Ali", "Hicham", "Mustapha", "Abdelaziz", "Karim",
      "Amine", "Brahim", "Aziz", "Abdullah", "Yassine", "Abdelkader", "Said",
      "Adil", "ʿAbd al-Laṭīf", "Abderrahim", "Hamza", "Noureddine", "Zakaria", "Abd al-Rahman",
      "Nabil", "Abdelkarim", "Fouad", "Hamid", "Ibrahim", "Abd al-Salam", "Abdellatif",
      "Larbi", "Abdellah", "Mustafa", "Jamal", "Mounir", "Saïd", "Samir",
      "Soufiane", "Redouane", "Tarik", "Bilal", "Mourad", "Reda", "Saeed",
      "Younes",
    ],
    family: [
      "Alaoui", "Bennani", "Berrada", "Slaoui", "Chraïbi", "Jirari", "Tazi",
      "Zniber", "Al-Idrissi", "Alami", "Benjelloul", "Cherkaoui", "Sbaï", "Ziani",
      "Idrissi", "Aziz", "Bahja", "Benchekroun", "Boucetta", "Chami", "Chraibi",
      "Filali", "Haddad", "Hadji", "Hafidi", "Ibrahim", "Kadiri", "Tahiri",
      "Tounsi", "Touzani", "Akesbi", "Al-Fadili", "Al-Kattānī", "Alioui", "Allali",
      "Amrani", "Azoulay", "Baha", "Bakkali", "Benchemsi", "Benmoussa", "Bennis",
      "Bennouna", "Bensaïd", "Bensouda", "Buzaglo", "Cohen", "El Fassi", "El Hachimi",
      "Elbaz",
    ],
  },
  MG: {
    female: [
      "Aina", "Lalao", "Aurélie", "Elia", "Esther", "Mireille", "Nicole",
      "Thérèse", "Ange", "Anne", "Arlette", "Berthe", "Berthine", "Chantal",
      "Charlotte", "Christiane", "Clarisse", "Claudine", "Domoina", "Gisèle", "Hanitra",
      "Jocelyne", "Josiane", "Juliana", "Julie", "Juliette", "Landy", "Lydia",
      "Mamisoa", "Mamy", "Mialy", "Monique", "Nathalie", "Perline", "Rosa",
      "Sidonie", "Suzanne", "Viviane", "Albertine", "Alice", "Aloma", "Anastasie",
      "Andoniaina", "Anique", "Anja", "Annie", "Antonia", "Ariane", "Arisoa",
      "Asminah",
    ],
    male: [
      "Jean", "Charles", "Joseph", "Olivier", "Albert", "Henri", "Paul",
      "Raymond", "Guy", "Roger", "André", "Bruno", "Christian", "Désiré",
      "Michel", "René", "Richard", "Victor", "Armand", "Edmond", "Honoré",
      "Jacques", "Jean-Jacques", "Justin", "Louis", "Mamy", "Roland", "Alain",
      "Ernest", "Gabriel", "Georges", "Hubert", "Jean-Claude", "Jeannot", "Jimmy",
      "Jules", "Julien", "Marcel", "Patrick", "Philippe", "Pierre", "Alfred",
      "Andry", "Anicet", "Benjamin", "Bernard", "Christophe", "Edgard", "Elie",
      "Félix",
    ],
    family: [
      "Rakotomalala", "Rakotonirina", "Ratsimbazafy", "Ramaroson", "Randrianarisoa", "Rabaraona", "Rakotovao",
      "Ramanantsoa", "Randrianasolo", "Razafimahefa", "Andrianantenaina", "Bezara", "Rakotoniaina", "Ranaivo",
      "Ratsiraka", "Razafy", "Andriambololona", "Andriatsitohaina", "Rajaonarivelo", "Rajoelina", "Rakotobe",
      "Rakotondramanana", "Ratsimamanga", "Ravalomanana", "Ravelomanantsoa", "Tsiranana", "Andriamalala", "Andriamihaingo",
      "Andrianarivo", "Andriantiana", "Beriziky", "Rabemananjara", "Rabenoro", "Rabesahala", "Rabetafika",
      "Raharison", "Rajaonarimampianina", "Rajaonarison", "Rajaonary", "Rakotoarisoa", "Rakotoarivelo", "Rakotomaharo",
      "Rakotomanana", "Rakotondrazafy", "Rakotoson", "Rakotozafy", "Ramaherijaona", "Ramaholimasy", "Ramamonjisoa",
      "Ramarolahy",
    ],
  },
  ML: {
    female: [
      'Fatoumata', 'Aminata', 'Mariam', 'Aïssata', 'Oumou', 'Awa', 'Fanta',
      'Hawa', 'Kadiatou', 'Ramata', 'Bintou', 'Maïmouna', 'Mama', 'Salimata',
      'Sira', 'Fatou', 'Aicha', 'Alima', 'Fatimata', 'Penda', 'Rokia',
      'Safiatou', 'Saran', 'Adama', 'Aïcha', 'Aïchata', 'Aïchatou', 'Aïda',
      'Alimata', 'Diana', 'Jacqueline', 'Madeleine', 'Nassira', 'Ramatoulaye', 'Rokiatou',
      'Sadio', 'Suzanne', 'Ada', 'Adja', 'Aïssa', 'Alida', 'Ami',
      'Amy', 'Assa', 'Aya', 'Aziza', 'Batouly', 'Bernadette', 'Binta',
      'Coumba',
    ],
    male: [
      'Mamadou', 'Moussa', 'Abdoulaye', 'Mohamed', 'Amadou', 'Boubacar', 'Souleymane',
      'Modibo', 'Oumar', 'Ibrahim', 'Adama', 'Sekou', 'Ibrahima', 'Ousmane',
      'Lamine', 'Mahamadou', 'Bakary', 'Cheick', 'Samba', 'Idrissa', 'Muhammad',
      'Abdoul', 'Ahmed', 'Lassana', 'Malick', 'Sadio', 'Seydou', 'Aboubacar',
      'Dramane', 'Issa', 'Karim', 'Makan', 'Alassane', 'Ali', 'Alioune',
      'Baba', 'Habib', 'Hamadoun', 'Harouna', 'Salif', 'Sidiki', 'Yaya',
      'Alpha', 'Djibril', 'Ismaël', 'Jean', 'Omar', 'Tiémoko', 'Zoumana',
      'Birama',
    ],
    family: [
      'Traoré', 'Coulibaly', 'Diarra', 'Touré', 'Diallo', 'Keita', 'Traore',
      'Dembélé', 'Keïta', 'Camara', 'Koné', 'Sissoko', 'Cissé', 'Diawara',
      'Sidibé', 'Maïga', 'Konaté', 'Diakité', 'Sangaré', 'Diabaté', 'Fofana',
      'Samake', 'Dembele', 'Kouyaté', 'Bagayoko', 'N\'Diaye', 'Sidibe', 'Doucouré',
      'Kone', 'Toure', 'Sylla', 'Maiga', 'Sanogo', 'Diakite', 'Haidara',
      'Kanté', 'Sy', 'Danioko', 'Drame', 'Samaké', 'Sangare', 'Sow',
      'Ba', 'Doucoure', 'Haïdara', 'Samassékou', 'Ballo', 'Baradji', 'Diabate',
      'Dicko',
    ],
  },
  MU: {
    female: [
      "Aurélie", "Nathalie", "Caroline", "Priscilla", "Séphora", "Sheila", "Stephanie",
      "Annabelle", "Audrey", "Chloé", "Christine", "Karina", "Lydia", "Maryse",
      "Michèle", "Natacha", "Sandra", "Shania", "Tara", "Agnès", "Alexandrine",
      "Alicia", "Aline", "Alison", "Ameenah", "Amélie", "Amjum", "Amrita",
      "Anaïs", "Ananda", "Angelique", "Angélique", "Anjali", "Annabella", "Anne-Gaëlle",
      "Annick", "Anusha", "Asha", "Ashley", "Bernadette", "Bhavna", "Brenda",
      "Camille", "Cathy", "Célia", "Chiara", "Christianne", "Christina", "Corinne",
      "Danika",
    ],
    male: [
      "Jean", "Charles", "Christopher", "Jonathan", "Philippe", "Louis", "Maurice",
      "David", "Eddy", "Éric", "Paul", "Bruno", "Daniel", "Désiré",
      "Gaëtan", "Georges", "Henri", "Jacques", "James", "Jean-Claude", "Joseph",
      "Michael", "Robert", "Stéphane", "Alain", "Alexandre", "Alfred", "Amédée",
      "André", "Anil", "Ashley", "Ashok", "Benjamin", "Bertrand", "Christophe",
      "Dany", "Denis", "Édouard", "Edwin", "Eric", "Fabrice", "Gilles",
      "Giovanni", "Gregory", "Herbert", "Jean-Marie", "Jerry", "Johan", "John",
      "Kounal",
    ],
    family: [
      "Mayer", "Aboobakar", "de Chazal", "Foo", "Kune", "Colin", "Couacaud",
      "Dookhee", "Duval", "Lagesse", "Leung", "Masson", "Paul", "Vincent",
      "Wiehe", "Allet", "Appiah", "Augustin", "Babet", "Baboolall", "Bellepeau",
      "Bhurtun", "Boulle", "Boullé", "Chevreau", "Chiniah", "Constantin", "de Montlehu",
      "Desvaux", "Dussain", "Edoo", "Justin", "Koo", "Lagane", "Laval",
      "Lent", "Liénard", "Louis", "Louison", "Lubah", "Mamet", "Mathieu",
      "Mungrah", "Patel", "Pillay", "Pin Harry", "Rassoolkhan", "Ravina", "Richard",
      "Rochecouste",
    ],
  },
  MZ: {
    female: [
      "Maria", "Ana", "Isabel", "Helena", "Elisa", "Carla", "Esperança",
      "Alcinda", "Amelia", "Amélia", "Carolina", "Cecilia", "Celeste", "Selma",
      "Tânia", "Adina", "Alice", "Anabela", "Beatriz", "Carmen", "Denise",
      "Deolinda", "Domingas", "Ermelinda", "Frances", "Francisca", "Graça", "Ilda",
      "Karen", "Laurinda", "Lina", "Manuela", "Margarida", "Maria Inês", "Neima",
      "Paula", "Paulina", "Sandra", "Stella", "Teresa", "Vanessa", "Acacia",
      "Adelaide", "Admira", "Afra", "Albertine", "Alicia", "Amália", "Amarilis",
      "Ana Paula",
    ],
    male: [
      "João", "Alberto", "Carlos", "Francisco", "José", "António", "Manuel",
      "Fernando", "Pedro", "Luís", "Gabriel", "Joaquim", "Jorge", "Mário",
      "Paulo", "Abel", "Bruno", "Eduardo", "Júlio", "Ricardo", "Arnaldo",
      "Daniel", "David", "Diogo", "Edson", "Jaime", "Lucas", "Mario",
      "Raúl", "Rui", "Sérgio", "Albino", "André", "Ernesto", "Filipe",
      "Issufo", "Luis", "Nelson", "Nuno", "Orlando", "Sebastião", "Vicente",
      "Adriano", "Afonso", "Agostinho", "Alfredo", "Amândio", "Augusto", "Basilio",
      "Celso",
    ],
    family: [
      "Cossa", "Muchanga", "Alves", "Cardoso", "Lopes", "Martins", "Couto",
      "da Costa", "de Sousa", "Ferreira", "Leite", "Mussagy", "Noronha", "Pinto",
      "Silva", "Abranches", "Augusto", "Azevedo", "Baptista", "Bucuane", "Corsini",
      "Costa", "Da Silva", "de Vasconcelos", "Dias", "Domingos", "Fernandes", "Fernando",
      "Fonseca", "Gabriel", "Gonçalves", "Guebuza", "Joaquim", "Lemos", "Lobo",
      "Loforte", "Lucas", "Mandlate", "Manjate", "Manuel", "Matos", "Mendes",
      "Mesquita", "Monteiro", "Mussa", "Novela", "Pequenino", "Pinheiro", "Rebelo",
      "Rodrigues",
    ],
  },
  NG: {
    female: [
      'Grace', 'Esther', 'Aisha', 'Mary', 'Maryam', 'Zainab', 'Joy',
      'Fatima', 'Hauwa', 'Helen', 'Blessing', 'Ngozi', 'Victoria', 'Amina',
      'Stella', 'Chioma', 'Elizabeth', 'Mercy', 'Gloria', 'Sarah', 'Florence',
      'Hadiza', 'Patience', 'Ifeoma', 'Halima', 'Ijeoma', 'Lola', 'Margaret',
      'Patricia', 'Rita', 'Josephine', 'Rebecca', 'Damilola', 'Mariam', 'Angela',
      'Ruth', 'Adeola', 'Cecilia', 'Jane', 'Rosemary', 'Abimbola', 'Abiola',
      'Adenike', 'Binta', 'Chinwe', 'Funmi', 'Janet', 'Juliet', 'Modupe',
      'Deborah',
    ],
    male: [
      'Emmanuel', 'Muhammad', 'John', 'Samuel', 'Joseph', 'Ibrahim', 'David',
      'Michael', 'Peter', 'Abubakar', 'Victor', 'Anthony', 'Daniel', 'James',
      'Ahmed', 'Patrick', 'Charles', 'Isaac', 'Abdullahi', 'Stephen', 'Christopher',
      'Francis', 'Paul', 'Henry', 'Umar', 'Gabriel', 'Solomon', 'Usman',
      'Adamu', 'George', 'Joshua', 'Moses', 'Chris', 'Emeka', 'Yusuf',
      'Godwin', 'Sam', 'Sunday', 'Tony', 'Richard', 'Andrew', 'Babatunde',
      'Musa', 'Felix', 'Vincent', 'Christian', 'Kenneth', 'Samson', 'Benjamin',
      'Ifeanyi',
    ],
    family: [
      'Muhammad', 'Bello', 'Abubakar', 'Ibrahim', 'Adamu', 'Umar', 'Mohammed',
      'Usman', 'Lawal', 'Ajayi', 'Aliyu', 'Okafor', 'Okoye', 'Williams',
      'Johnson', 'Abdullahi', 'Yusuf', 'Okeke', 'Ojo', 'Adebayo', 'Ahmed',
      'Okonkwo', 'Eze', 'Musa', 'Sani', 'Yakubu', 'Nwosu', 'Shehu',
      'Afolabi', 'George', 'Sunday', 'John', 'Balogun', 'Bassey', 'Kalu',
      'Nwankwo', 'Ali', 'Igwe', 'Taiwo', 'Hassan', 'Obi', 'Ahmad',
      'Idowu', 'Nwachukwu', 'Ogbonna', 'Okoli', 'Abba', 'Abiodun', 'Adeleke',
      'Ezeh',
    ],
  },
  NA: {
    female: ['Saara', 'Emma', 'Alexia', 'Lucia', 'Hilma', 'Selma'],
    male: ['Phillipus', 'Paulus', 'Immanuel', 'Veikko', 'Salomon', 'Willem'],
    family: ['Kuugongelwa-Amadhila', 'Kantema', 'Manombe-Ncube', 'Iipumbu', 'Iita', 'Nekundi', 'Katamelo'],
  },
  RE: {
    female: [
      "Marie", "Léa", "Emma", "Jade", "Chloé", "Camille", "Manon",
      "Eva", "Océane", "Sarah", "Lucie", "Mathilde", "Anna", "Inès",
      "Louna", "Anaïs", "Noemie", "Inaya", "Emilie", "Alicia", "Léna",
      "Mia", "Gabrielle", "Lisa", "Maëlys", "Marion", "Zoé", "Kenza",
      "Amélie", "Julie", "Luna", "Lola", "Ambre", "Mya", "Maeva",
      "Louise", "Marine", "Rachel", "Emeline", "Célia", "Romane", "Léana",
      "Maya", "Pauline", "Clara", "Louane", "Maelle", "Elisa", "Lya",
      "Julia",
    ],
    male: [
      "Lucas", "Noah", "Raphaël", "Ethan", "Gabriel", "Théo", "Enzo",
      "Thomas", "Jean", "Mathéo", "Nathan", "Mathis", "Quentin", "Hugo",
      "Benjamin", "Nicolas", "Samuel", "Romain", "Nolan", "Anthony", "Alexandre",
      "Léo", "Liam", "Maël", "Maxime", "Lyam", "Evan", "Dylan",
      "Arthur", "Julien", "Kylian", "Aaron", "Mathys", "Erwan", "Adrien",
      "Louis", "Mathias", "Clément", "Damien", "Florian", "Emmanuel", "Loïc",
      "Mael", "Mathieu", "Rohan", "Warren", "Jules", "Tom", "Alexis",
      "Isaac",
    ],
    family: [
      "Payet", "Grondin", "Hoarau", "Fontaine", "Boyer", "Hoareau", "Robert",
      "Riviere", "Dijoux", "Maillot", "Techer", "Lebon", "Lauret", "Begue",
      "Clain", "Turpin", "Sautron", "Benard", "Gonthier", "Damour", "Etheve",
      "Cadet", "Mussard", "Morel", "Picard", "Nativel", "Dalleau", "Thomas",
      "Vitry", "Huet", "Lallemand", "Pothin", "Sery", "Lebreton", "Leperlier",
      "Folio", "Lepinay", "Pause", "Barret", "Legros", "Baret", "Vidot",
      "Ferrere", "Elisabeth", "Guichard", "Corre", "Naze", "Duchemann", "Vienne",
      "Noel", "Zitte", "Martin", "Lebeau", "Louise", "Malet", "Severin",
      "Leveneur", "Minatchy", "Latchimy", "Chamand", "Nourry", "Gigan", "Collet",
      "Gauvin", "Francoise", "Hubert", "Cazal", "Gastrin", "Carron", "Padre",
      "Gence", "Hamilcaro", "Blard", "Cerveaux", "Aure", "Pitou", "Poudroux",
      "Dennemont", "Richard", "Moutoussamy", "Dubard", "Grosset", "Marimoutou", "Smith",
      "Crescence", "Baillif", "Michel", "Zettor", "Ramsamy", "Cuvelier", "Plante",
      "Jean-Baptiste", "Baptiste", "Ramaye", "Nirlo", "Laravine", "Grimaud", "Boucher",
      "Morin", "Caro",
    ],
  },
  RW: {
    female: [
      'Alice', 'Christine', 'Chantal', 'Claudine', 'Solange', 'Diane', 'Grace',
      'Yvonne', 'Aline', 'Clementine', 'Gloria', 'Immaculée', 'Jacqueline', 'Jeanne d\'Arc',
      'Liliane', 'Sandrine', 'Agnes', 'Angelique', 'Judith', 'Rose', 'Beatrice',
      'Claire', 'Claudette', 'Esther', 'Françoise', 'Jeanne', 'Madeleine', 'Nadine',
      'Agnès', 'Alphonsine', 'Ange', 'Aurore', 'Beata', 'Brigitte', 'Charlotte',
      'Clarisse', 'Cynthia', 'Denyse', 'Donatilla', 'Eliane', 'Florence', 'Hope',
      'Jeanette', 'Jeannette', 'Joselyne', 'Josiane', 'Louise', 'Monique', 'Olive',
      'Rosine', 'Emma',
    ],
    male: [
      'Jean', 'Joseph', 'Emmanuel', 'Patrick', 'Eric', 'Charles', 'Augustin',
      'Jean-Claude', 'Olivier', 'Alphonse', 'James', 'Samuel', 'Dominique', 'Jean-Paul',
      'Richard', 'Vincent', 'André', 'Gilbert', 'Jean-de-Dieu', 'Paul', 'Robert',
      'Abdul', 'Alexis', 'Bernard', 'Célestin', 'Elias', 'Eugène', 'Pierre',
      'Prince', 'Yves', 'Alexandre', 'Celestin', 'Christian', 'Christophe', 'Claude',
      'Daniel', 'David', 'Didier', 'Emile', 'Ernest', 'Faustin', 'Félicien',
      'Fulgence', 'Gaspard', 'Innocent', 'Jacques', 'Jean-Marie', 'Jimmy', 'John',
      'Justin', 'Anastase', 'Théogène', 'Venuste', 'Jean Claude',
    ],
    family: [
      'Ingabire', 'Uwizeye', 'Hakizimana', 'Kayitesi', 'Uwamahoro', 'Kamanzi', 'Sibomana',
      'Umuhoza', 'Habyarimana', 'Kagame', 'Mutesi', 'Nsengiyumva', 'Umutoni', 'Uwera',
      'Uwineza', 'Kabera', 'Mukeshimana', 'Nsabimana', 'Uwamariya', 'Bayisenge', 'Butera',
      'Gasana', 'Iradukunda', 'Irakoze', 'Kabanda', 'Karekezi', 'Kayibanda', 'Kimenyi',
      'Mugabo', 'Murangwa', 'Murekatete', 'Ndagijimana', 'Niyonkuru', 'Nsanzimana', 'Rugamba',
      'Shema', 'Umurungi', 'Uwanyirigira', 'Uwimana', 'Bizimana', 'Bizimungu', 'Gakuba',
      'Imanishimwe', 'Ineza', 'Irankunda', 'Ishimwe', 'Iyamuremye', 'Kanimba', 'Karemera',
      'Mahoro', 'Uwase', 'Iganze', 'Mugisha', 'Hirwa', 'Igiraneza',
    ],
  },
  SC: {
    female: ['Audrey', 'Denise', 'Azarel', 'Sandra', 'Sylvanne', 'Valdana'],
    male: ['Egbert', 'Bernard', 'Alvin', 'Andy', 'Churchill', 'Trevor'],
    family: ['Vidot', 'Clarisse', 'Ernesta', 'Sultan', 'Lemiel', 'Georges', 'Labonte', 'Gill'],
  },
  SD: {
    female: [
      "Rania", "Sara", "Amal", "Amna", "Asma", "Fatima", "Farida",
      "Hanan", "Hawa", "Kamala", "Maha", "Mariam", "Nadia", "Nafisa",
      "Reem", "Sabrine", "Sarah", "Sawsan", "Siham", "Suad", "Zeinab",
      "A'isha", "Afaf", "Ahlam", "Alaa", "Amanie", "Amina", "Amira",
      "Ann", "Assia", "Athar", "Badriya", "Dalia", "Eiman", "Fadwa",
      "Fahima", "Faiza", "Hadja", "Halima", "Howayda", "Hyam", "ʻUzayyah",
      "Josephine", "Joséphine", "Khadija", "Layla", "Leila", "Lena", "Lubna",
      "Manal",
    ],
    male: [
      "Muhammad", "Mohamed", "Ahmed", "Ibrahim", "Ali", "Ahmad", "Hassan",
      "Abdullah", "Omer", "Osman", "Joseph", "Abdelaziz", "Amir", "Omar",
      "Peter", "Abd al-Rahim", "John", "Mustafa", "Salah", "Abd al-Karīm", "Daniel",
      "George", "Hashim", "Jamal", "Khaled", "Mahmoud", "Malik", "Salih",
      "Aamir", "Abd al-Aziz", "Abd al-Qadir", "Abd al-Rahman", "Abd al-Salam", "Abdallah", "Abdel Fattah",
      "Abdullahi", "Abel", "Adam", "Adil", "Amin", "Faisal", "Fazlollah",
      "Gabriel", "Haitham", "Hamid", "Ismail", "Issam", "Ja'far", "Jimmy",
      "Kamal",
    ],
    family: [
      "Ibrahim", "Adam", "Ahmed", "Mohamed", "Hussein", "Abdallah", "Badawi",
      "Mohammed", "Yousif", "Ismail", "Mahmoud", "Mukhtar", "Musa", "Mustafa",
      "Salih", "Shaddad", "Abdalla", "Abdullah", "Ahmad", "al-Hassan", "Alier",
      "Awadalla", "Badri", "Bakr", "Bashir", "Bol", "Chuot", "Eisa",
      "Elamin", "Eltayeb", "Gai", "Garang", "Hamad", "Hassan", "Khair",
      "Khalifa", "Kuku", "Nour", "Omar", "Osman", "Sadiq", "Saeed",
      "Siddiq", "Simon", "Taha", "Zakaria", "Abakar", "Abbas", "Abboud",
      "Abdel-Rahman",
    ],
  },
  SL: {
    female: [
      'Fatmata', 'Isata', 'Mabinty', 'Sarah', 'Elizabeth', 'Enid', 'Eugenia',
      'Hannah', 'Isha', 'Josephine', 'Alice', 'Amanda', 'Aminata', 'Asma',
      'Barbara', 'Bernadette', 'Bertha', 'Binta', 'Cecilia', 'Christiana', 'Constance',
      'Daisy', 'Desiree', 'Diana', 'Dora', 'Edna', 'Ella', 'Ellen',
      'Emma', 'Essie', 'Eunice', 'Fatima', 'Finda', 'Florence', 'Frances',
      'Georgiana', 'Hafsatu', 'Henrietta', 'Hillary', 'Irene', 'June', 'Kadi',
      'Kadiato', 'Kathleen', 'Khadija', 'Laura', 'Lucy', 'Maggie', 'Margaret',
      'Mary',
    ],
    male: [
      'Mohamed', 'Ibrahim', 'John', 'Abdul', 'Joseph', 'David', 'Albert',
      'Edward', 'Alpha', 'George', 'Henry', 'Christian', 'Lamin', 'Samuel',
      'Solomon', 'Ahmed', 'Alfred', 'Augustine', 'Ernest', 'Francis', 'James',
      'Julius', 'Moses', 'Mustapha', 'Patrick', 'Tom', 'William', 'Andrew',
      'Charles', 'Frank', 'Gibril', 'Michael', 'Muhammad', 'Nathaniel', 'Paul',
      'Abd al-Karīm', 'Alie', 'Arthur', 'Augustus', 'Benjamin', 'Cyril', 'Daniel',
      'Desmond', 'Harry', 'Hassan', 'Israel', 'Issa', 'Jimmy', 'Joe',
      'Mike',
    ],
    family: [
      'Kamara', 'Conteh', 'Sesay', 'Bangura', 'Koroma', 'Kanu', 'Cole',
      'Jones', 'Kargbo', 'Williams', 'Turay', 'Jalloh', 'Johnson', 'Margai',
      'Tucker', 'Bockarie', 'Bundu', 'James', 'Smith', 'Strasser', 'Thomas',
      'Bart-Williams', 'Demby', 'Dumbuya', 'Francis', 'Ganda', 'Garnett', 'Massaquoi',
      'Pratt', 'Samba', 'Sankoh', 'Sawyerr', 'Sillah', 'Stevens', 'Thompson',
      'Wright', 'Abayomi', 'Abraham', 'Africanus', 'Aruna', 'Awolo', 'Barber',
      'Barlay', 'Barnett', 'Barrie', 'Bellon', 'Benjamin', 'Bio', 'Blyden',
      'Boston',
    ],
  },
  SN: {
    female: [
      'Fatou', 'Ndeye', 'Aminata', 'Mariama', 'Awa', 'Mame', 'Khady',
      'Fatoumata', 'Bineta', 'Seynabou', 'Sokhna', 'Aissatou', 'Maïmouna', 'Coumba',
      'Anna', 'Anta', 'Astou', 'Fatimata', 'Penda', 'Fatima', 'Khadidiatou',
      'Khadija', 'Marième', 'Amy', 'Binta', 'Bintou', 'Nafissatou', 'Rokhaya',
      'Sophie', 'Aicha', 'Aïcha', 'Aida', 'Aïda', 'Fanta', 'Hawa',
      'Kine', 'Marieme', 'Maty', 'Oumou', 'Ramatoulaye', 'Rose', 'Yaye',
      'Adama', 'Aïssatou', 'Amina', 'Dieynaba', 'Fama', 'Fatma', 'Jacqueline',
      'Jeanne',
    ],
    male: [
      'Mamadou', 'Abdoulaye', 'Ibrahima', 'Amadou', 'Moussa', 'Babacar', 'Ousmane',
      'Pape', 'Alioune', 'Moustapha', 'Souleymane', 'Lamine', 'Cheikh', 'Oumar',
      'Omar', 'Abdou', 'Adama', 'Samba', 'Papa', 'Assane', 'Mohamed',
      'Boubacar', 'Mouhamadou', 'Mouhamed', 'Mansour', 'Doudou', 'Issa', 'Mame',
      'Pierre', 'Ababacar', 'Alassane', 'Daouda', 'Djibril', 'Joseph', 'Mbaye',
      'Thierno', 'Abdoul', 'Aliou', 'Elhadji', 'Louis', 'Ousseynou', 'Serigne',
      'Baye', 'Malick', 'Aziz', 'Baba', 'Chérif', 'Habib', 'Ibrahim',
      'Karim', 'Ahmadou',
    ],
    family: [
      'Diop', 'Ndiaye', 'Fall', 'Diouf', 'Gueye', 'Diallo', 'Sarr',
      'Faye', 'N\'Diaye', 'Seck', 'Thiam', 'Sow', 'Mendy', 'Niang',
      'Ba', 'Mbaye', 'Cissé', 'Diagne', 'Camara', 'Touré', 'Sy',
      'Sall', 'Dieng', 'Kane', 'Sagna', 'Sylla', 'Wade', 'Mbengue',
      'Ndoye', 'Diatta', 'Sène', 'Badji', 'Traoré', 'Dabo', 'Gomis',
      'Ngom', 'Gaye', 'Samb', 'Diedhiou', 'Sané', 'Baldé', 'Ndao',
      'Coly', 'Coulibaly', 'Keita', 'Pouye', 'Sonko', 'Badiane', 'Barry',
      'Diaw', 'Wane',
    ],
  },
  SO: {
    female: [
      "Hawa", "Amina", "Khadija", "Asha", "Fatima", "Halima", "Hodan",
      "Zahra", "Fadumo", "Sahra", "Saida", "Ubah", "Aini", "Amira",
      "Asli", "Ayan", "Faiza", "Faraḥ", "Fartuun", "Fathia", "Fāṭima al-Zahra",
      "Fauzia", "Fouzia", "Hanan", "Haniifa", "Hibaaq", "Hibo", "Idil",
      "Iman", "Jamila", "Khadra", "Ladan", "Leila", "Leyla", "Maryam",
      "Miriam", "Mona", "Muna", "Nasra", "Rahma", "Saba", "Safia",
      "Samia", "Samira", "Shadia", "Shamsa", "Soraya", "Sulekha", "Waris",
      "Yasmin",
    ],
    male: [
      "Mohamed", "Ahmed", "Ali", "Abdi", "Hassan", "Omar", "Muhammad",
      "Abdullahi", "Yusuf", "Hussein", "Osman", "Ibrahim", "Abd al-Qadir", "Abdirahman",
      "Ismail", "Abdullah", "Ahmad", "Aden", "Abdulkadir", "Mustafa", "Said",
      "Abd al-Rahman", "Daud", "Faraḥ", "Jama", "Bashir", "Faisal", "Liban",
      "Ömer", "Saeed", "Yasin", "Abdul Nasser", "Amin", "Hasan", "Jamal",
      "Khalif", "Mahmoud", "Mohammad", "Mokhtar", "Salah", "Abbas", "Abd al-Hakim",
      "Abdalla", "Abdel Fattah", "Abdel Nour", "Abdelaziz", "Abdisalaam", "Abdisalam", "Abdourahman",
      "Abdul",
    ],
    family: [
      "Mohamed", "Ahmed", "Abdi", "Ali", "Farah", "Hassan", "Ibrahim",
      "Osman", "Warsame", "Hussein", "Elmi", "Omar", "Shire", "Yusuf",
      "Abdullahi", "Adam", "Barre", "Dirie", "Diriye", "Hashi", "Ismail",
      "Jama", "Mohamud", "Mumin", "Mursal", "Said", "Abdalla", "Abdillahi",
      "Abdulla", "Abdurahman", "Abdurrahman", "Abubakar", "Adan", "Aden", "Ahamed",
      "Awale", "Bashir", "Bile", "Daar", "Dayib", "Degan", "Dini",
      "Dubbe", "Gaal", "Harawe", "Hasan", "Hussain", "Hussen", "Issa",
      "Jimale",
    ],
  },
  SS: {
    female: [
      "Mary", "Grace", "Sarah", "Alek", "Anna", "Elizabeth", "Josephine",
      "Naomi", "Perina", "Rebecca", "Rose", "Susan", "Agnes", "Alicia",
      "Aluel", "Amy", "Angelina", "Anisia", "Ann", "Apollonia", "Beatrice",
      "Betty", "Cecilia", "Christina", "Deborah", "Delicia", "Dorka", "Dorothy",
      "Esther", "Felicita", "Gloria", "Hellen", "Jacinta", "Jennifer", "Joia",
      "Juliet", "Karima", "Lily", "Loice", "Lucia", "Lucy", "Luice",
      "Margret", "Mari", "Maria", "Maura", "Mercy", "Mona", "Monica",
      "Nyibol",
    ],
    male: [
      "Emmanuel", "Peter", "James", "John", "Joseph", "David", "Paul",
      "Stephen", "Alex", "Daniel", "Gabriel", "Samuel", "Alfred", "Ali",
      "Deng", "Dominic", "Isaac", "Simon", "Abdullah", "Anthony", "Augustino",
      "Barnaba", "Francis", "Gordon", "Khamis", "Madut", "Marial", "Michael",
      "Moses", "Nelson", "Paulino", "Richard", "Steven", "Thomas", "Tito",
      "William", "Abel", "Abraham", "Adil", "Adnan", "Aggrey", "Aher",
      "Aloisio", "Augustine", "Barnabas", "Bernard", "Bernardino", "Cherlino", "Clement",
      "Dani",
    ],
    family: [
      "Deng", "Maker", "Gabriel", "Ajak", "Biel", "Emmanuel", "Garang",
      "Hassan", "Kuol", "Majak", "Majok", "Martin", "Riak", "Samson",
      "Taban", "Tac", "Aguer", "Akol", "Akot", "Akuot", "Albano",
      "Albert", "Alberto", "Alier", "Amadeo", "Amet", "Amotun", "Atari",
      "Atem", "Ayen", "Baime", "Baki", "Bar", "Batali", "Benjamin",
      "Bile", "Bimo", "Bol", "Boro", "Both", "Bowen", "Boyoi",
      "Bruno", "Bullen", "Chiang", "Chuol", "Dada", "Dara", "Dawa",
      "Dusman",
    ],
  },
  TG: {
    female: [
      'Nathalie', 'Adjovi', 'Edwige', 'Kafui', 'Marguerite', 'Rita', 'Abla',
      'Ablavi', 'Abra', 'Adjo', 'Adjoavi', 'Afiwavi', 'Chimène', 'Christelle',
      'Christiane', 'Claire', 'Dede', 'Elisabeth', 'Elise', 'Essenam', 'Florence',
      'Françoise', 'Georgette', 'Germaine', 'Henriette', 'Ingrid', 'Isabelle', 'Joséphine',
      'Julie', 'Laura', 'Manuella', 'Naomi', 'Patricia', 'Rachel', 'Rolande',
      'Rose', 'Sonia', 'Valentine', 'Victoire', 'Ablamba', 'Adèle', 'Adwoa',
      'Afi', 'Afia', 'Afua', 'Ahoefa', 'Aïda', 'Aïssah', 'Akofa',
      'Aku',
    ],
    male: [
      'Koffi', 'Kokou', 'Kossi', 'Kofi', 'Emmanuel', 'Claude', 'Georges',
      'Kodjo', 'Kwami', 'Charles', 'David', 'Jacques', 'Joseph', 'Paul',
      'Robert', 'Didier', 'Franck', 'François', 'Guy', 'Komi', 'Komla',
      'Michel', 'Pascal', 'Abdoul', 'Alex', 'Antoine', 'Benoît', 'Gilbert',
      'Jean', 'Jonathan', 'Komlan', 'Loïc', 'Mohamed', 'Richard', 'Roger',
      'Serge', 'Yao', 'Aimé', 'Anani', 'André', 'Edem', 'Félix',
      'Germain', 'Gerson', 'Guillaume', 'Julien', 'Kevin', 'Martin', 'Moïse',
      'Philippe',
    ],
    family: [
      'Akakpo', 'Lawson', 'Mensah', 'Olympio', 'Johnson', 'Touré', 'Agbo',
      'Agbobli', 'D\'Almeida', 'de Souza', 'Ekoue', 'Folly', 'Abi', 'Agbégnénou',
      'Aidam', 'Ajavon', 'Akoto', 'Alipui', 'Amedomé', 'Amétépé', 'Amoussou',
      'Ananou', 'Assih', 'Ayayi', 'Ayeva', 'Barcola', 'Bonfoh', 'Dossevi',
      'Fofana', 'Freitas', 'Grunitzky', 'Hundt', 'Kpotsra', 'Makouvia', 'Maman',
      'Panou', 'Salifou', 'Tosou', 'Worou', 'Yaya', 'Acolatse', 'Adams',
      'Adebayor', 'Adjaho', 'Adjima', 'Afetse', 'Agba', 'Agbegna', 'Agbeko',
      'Agblemagnon',
    ],
  },
  TN: {
    female: [
      "Fatma", "Sonia", "Iman", "Leila", "Rim", "Amel", "Wafaa",
      "Olfa", "Asma", "Meriem", "Nadia", "Nour", "Amira", "Marwa",
      "Sarra", "Mouna", "Samia", "Yasmine", "Amina", "Chaima", "Hela",
      "Mariem", "Maroua", "Nesrine", "Sihem", "Kaouther", "Khawla", "Lilia",
      "Monia", "Rahma", "Souad", "Faten", "Jamila", "Soumaya", "Hajer",
      "Khadija", "Munira", "Omaima", "Yosra", "Abir", "Amal", "Emna",
      "Lamia", "Najla", "Raja", "Salma", "Sarah", "Zeineb", "Ahlem",
      "Boutheina",
    ],
    male: [
      "Mohamed", "Ahmed", "Ali", "Habib", "Hédi", "Moncef", "Lotfi",
      "Bashir", "Ridha", "Sami", "Noureddine", "Tawfik", "Aymen", "Youssef",
      "Kamel", "Anis", "Salah", "Samir", "Hamza", "Waleed", "Mahmoud",
      "Mourad", "Slim", "Adel", "Sadok", "Yassine", "Hatem", "Osama",
      "Tahar", "Maher", "Bilel", "Mounir", "Tarek", "Mustapha", "Abdelaziz",
      "Moez", "Mongi", "Fethi", "Hichem", "Karim", "Houssem", "Nabil",
      "Brahim", "Aziz", "Chokri", "Faouzi", "Hamdi", "Khalil", "Mokhtar",
      "Riadh",
    ],
    family: [
      "Trabelsi", "Ayari", "Gharbi", "Chebbi", "Labidi", "Hamdi", "Hammami",
      "Ayadi", "Ben Ammar", "Sassi", "Ben Abdallah", "Karoui", "Masmoudi", "Meddeb",
      "Abid", "Ben Amor", "Mansour", "Amri", "Dridi", "Jebali", "Oueslati",
      "Saidi", "Ammar", "Attia", "Ayachi", "bin Ali", "Miled", "Arfaoui",
      "Baccouche", "Ben Youssef", "Hosni", "Marzouki", "Mejri", "Selmi", "Touati",
      "Triki", "Turki", "Ayed", "Bahri", "Belaïd", "Besbes", "Cohen",
      "Haddad", "Jaziri", "Jouini", "Mabrouk", "Missaoui", "Rekik", "Yahyaoui",
      "Bouzid",
    ],
  },
  TZ: {
    female: [
      'Anna', 'Elizabeth', 'Mary', 'Esther', 'Khadija', 'Grace', 'Lucy',
      'Rose', 'Catherine', 'Ester', 'Irene', 'Joyce', 'Maria', 'Martha',
      'Salome', 'Sophia', 'Amina', 'Diana', 'Fatma', 'Fatuma', 'Magdalena',
      'Neema', 'Rehema', 'Ruth', 'Susan', 'Aisha', 'Anne', 'Asha',
      'Beatrice', 'Brenda', 'Halima', 'Hawa', 'Jacqueline', 'Janeth', 'Jennifer',
      'Josephine', 'Margaret', 'Mariam', 'Stella', 'Sylvia', 'Zainab', 'Angelina',
      'Blandina', 'Cecilia', 'Doreen', 'Faith', 'Flora', 'Gertrude', 'Happiness',
      'Janet', 'Ashatu', 'Tulia', 'Suma', 'Agnes', 'Ummy',
    ],
    male: [
      'John', 'Joseph', 'Juma', 'Ali', 'Mohamed', 'Charles', 'Peter',
      'William', 'Emmanuel', 'James', 'David', 'Muhammad', 'Abdallah', 'Edward',
      'George', 'Daniel', 'Godfrey', 'Stephen', 'Adam', 'Christopher', 'Hussein',
      'Julius', 'Martin', 'Michael', 'Paul', 'Richard', 'Simon', 'Ahmed',
      'Anthony', 'Henry', 'Vincent', 'Abdul', 'Ally', 'Amani', 'Andrew',
      'Augustine', 'Francis', 'Omar', 'Patrick', 'Rashid', 'Salim', 'Salum',
      'Suleiman', 'Albert', 'Benedict', 'Bernard', 'Felix', 'Frank', 'Hassan',
      'Joel', 'Omary', 'Mussa',
    ],
    family: [
      'Juma', 'Ali', 'Khamis', 'Laizer', 'Mollel', 'Abdallah', 'Tarimo',
      'Issa', 'Mapunda', 'Mussa', 'Ameir', 'Divecha', 'Hamad', 'Khatib',
      'Mohamed', 'Mrema', 'Nyerere', 'Salim', 'Shija', 'Cheyo', 'Dewji',
      'Emmanuel', 'Gama', 'Hussein', 'Joseph', 'Karume', 'Kawawa', 'Khalfan',
      'Kikwete', 'Komba', 'Lema', 'Mabula', 'Magufuli', 'Marwa', 'Mgimwa',
      'Mhina', 'Mkapa', 'Msuya', 'Mwanga', 'Mwinyi', 'Ramadhani', 'Rugambwa',
      'Salum', 'Shah', 'Abeid', 'Amani', 'Bakar', 'Bayo', 'Chami',
      'Chiplunkar', 'Kijaji', 'Gekul', 'Mwalimu', 'Ishengoma', 'Ackson', 'Mavunde',
      'Mkuchika', 'Kipanga',
    ],
  },
  UG: {
    female: [
      'Sarah', 'Esther', 'Grace', 'Christine', 'Catherine', 'Florence', 'Ruth',
      'Margaret', 'Rose', 'Mary', 'Agnes', 'Betty', 'Jane', 'Josephine',
      'Irene', 'Judith', 'Lillian', 'Annet', 'Joan', 'Patricia', 'Rebecca',
      'Stella', 'Sylvia', 'Beatrice', 'Elizabeth', 'Juliet', 'Diana', 'Doreen',
      'Evelyn', 'Harriet', 'Joyce', 'Olivia', 'Gloria', 'Susan', 'Alice',
      'Barbara', 'Flavia', 'Lydia', 'Peace', 'Sheila', 'Patience', 'Winnie',
      'Aisha', 'Brenda', 'Hellen', 'Hope', 'Joy', 'Sandra', 'Victoria',
      'Janet', 'Jesca', 'Dorcus',
    ],
    male: [
      'John', 'James', 'Charles', 'David', 'Joseph', 'Robert', 'Moses',
      'Patrick', 'Richard', 'Paul', 'Samuel', 'Peter', 'Emmanuel', 'Henry',
      'Godfrey', 'Michael', 'Francis', 'Andrew', 'Fred', 'Ronald', 'Stephen',
      'William', 'George', 'Martin', 'Isaac', 'Daniel', 'Edward', 'Brian',
      'Julius', 'Simon', 'Vincent', 'Arthur', 'Lawrence', 'Sam', 'Denis',
      'Christopher', 'Alex', 'Anthony', 'Geoffrey', 'Ivan', 'Joshua', 'Solomon',
      'Allan', 'Frank', 'Kenneth', 'Jimmy', 'Ibrahim', 'Nicholas', 'Abraham',
      'Hassan', 'Cuthbert',
    ],
    family: [
      'Okello', 'Birungi', 'Mukasa', 'Lubega', 'Kasule', 'Kayondo', 'Matovu',
      'Nsubuga', 'Kavuma', 'Kizito', 'Mbabazi', 'Odongo', 'Bukenya', 'Byarugaba',
      'Kaggwa', 'Makumbi', 'Murungi', 'Musoke', 'Aber', 'Amin', 'Asiimwe',
      'Babirye', 'Chebet', 'Kabagambe', 'Kabugho', 'Kasirye', 'Kato', 'Kigozi',
      'Kirya', 'Kiwanuka', 'Lule', 'Lwanga', 'Mukiibi', 'Muwonge', 'Namara',
      'Tendo', 'Zziwa', 'Akol', 'Ali', 'Anena', 'Arinaitwe', 'Awori',
      'Baguma', 'Jackson', 'Jemutai', 'Kabuye', 'Kakooza', 'Kalungi', 'Kansiime',
      'Kasumba', 'Ababiku', 'Abeja', 'Abigaba', 'Acen', 'Acon', 'Adome',
      'Aeku', 'Afidra',
    ],
  },
  YT: {
    female: [
      "Fatima", "Naïma", "Assia", "Nasra", "Aïcha", "Roukaya", "Yousra",
      "Loubna", "Soumaya", "Youmna", "Asma", "Naïra", "Inaya", "Amina",
      "Nasma", "Kamila", "Malika", "Raïna", "Faïna", "Mariama", "Yasmine",
      "Anaïs", "Lina", "Maïna", "Hadidja", "Naïla", "Kayla", "Rania",
      "Alicia", "Asna", "Nazra", "Rayana", "Bahati", "Maïra", "Mayra",
      "Rachida", "Samira", "Samra", "Yasmina", "Chaïma", "Mariame", "Yamina",
      "Anissa", "Elina", "Faïza", "Nadjima", "Raïssa", "Rayna", "Yasna",
      "Yasra",
    ],
    male: [
      "Rayane", "Ben", "Ibrahim", "Ismaël", "Ayane", "Yanis", "Naël",
      "Karim", "Amine", "Aymane", "Rayan", "Samir", "Daniel", "Ismael",
      "Youssouf", "Imrane", "Ikram", "Samuel", "Yassine", "Nassim", "Nasri",
      "Nasser", "Hamza", "Fayel", "Nayel", "Yasser", "Mohamed", "Izak",
      "Rahim", "Naïm", "Younes", "Irham", "Kaïs", "Nael", "Youssef",
      "Kassim", "Roihim", "Hakim", "Raphaël", "Akram", "Djamil", "Kayel",
      "Liam", "Malik", "Rachid", "Amir", "Dayane", "Ilane", "Noah",
      "Abdou",
    ],
    family: [
      "Said", "Sarment", "Mdere", "Vitta", "Ahamadi", "Velou", "Moussa Ahamadi",
      "Omar", "Issa", "Saindou-Malide", "Hassani", "M'Dallah", "Abdallah-Boina", "Manroufou",
      "Pollozec", "Sidi", "Kamardine", "Mouayad Ben", "Attoumani", "Chanfi", "El Hadad",
      "Zaidani", "Ibrahim", "Ousseni", "Saindou", "Ahamada", "Moussa", "Saïd",
      "Soilihi", "Ali", "Attoumani Douchina", "Audoin", "Bacar", "Baco", "Balick",
      "Bamana", "Belliard", "Boura", "Chabas", "Chappuis", "Daou", "Djailani",
      "Ducrest", "Giraud", "Henry", "Lafont", "Madi", "Mansour", "Maoulida",
      "Martial",
    ],
  },
  ZA: {
    female: ['Onalerona', 'Zanokuhle', 'Melokuhle', 'Lisakhanya', 'Lethabo', 'Nkanyezi', 'Lesedi', 'Omphile', 'Olwemihla'],
    male: ['Lethabo', 'Lubanzi', 'Nkazimulo', 'Nkanyezi', 'Langelihle', 'Lesedi', 'Lethokuhle', 'Siphosethu', 'Leano'],
    family: ['Dlamini', 'Ndlovu', 'Nkosi', 'Khumalo', 'Sithole', 'Mkhize', 'Mokoena', 'Mthembu', 'Gumede', 'Ngcobo'],
  },
  ZM: {
    female: [
      'Esther', 'Mary', 'Natasha', 'Gladys', 'Margaret', 'Catherine', 'Judith',
      'Mirriam', 'Grace', 'Mutale', 'Susan', 'Agnes', 'Anna', 'Elizabeth',
      'Hellen', 'Memory', 'Naomi', 'Patricia', 'Racheal', 'Yvonne', 'Alice',
      'Angela', 'Carol', 'Christine', 'Diana', 'Doreen', 'Edith', 'Ellen',
      'Eunice', 'Evelyn', 'Florence', 'Jane', 'Jean', 'Joyce', 'Juliet',
      'Karen', 'Lily', 'Lucy', 'Lulu', 'Martha', 'Monica', 'Mulenga',
      'Mutinta', 'Nancy', 'Prisca', 'Ruth', 'Sara', 'Sylvia', 'Thandiwe',
      'Towela', 'Pauline', 'Olive', 'Clarissa', 'Stella', 'Melissa', 'Rosemary',
    ],
    male: [
      'Emmanuel', 'George', 'Charles', 'Patrick', 'Christopher', 'Joseph', 'Brian',
      'Moses', 'Peter', 'Andrew', 'Godfrey', 'Paul', 'Elijah', 'John',
      'Lawrence', 'Robert', 'Stephen', 'Bernard', 'David', 'Dennis', 'Felix',
      'Francis', 'Jacob', 'James', 'Michael', 'Simon', 'Daniel', 'Davies',
      'Gabriel', 'Henry', 'Keith', 'Kelvin', 'Richard', 'Ronald', 'Anthony',
      'Benjamin', 'Dickson', 'Edgar', 'Edward', 'Harry', 'Kennedy', 'Kenneth',
      'Maxwell', 'Samuel', 'Stanley', 'Thomas', 'Timothy', 'William', 'Alexander',
      'Allan', 'Clement', 'Martin', 'Raphael',
    ],
    family: [
      'Mulenga', 'Banda', 'Phiri', 'Tembo', 'Lungu', 'Zulu', 'Musonda',
      'Kaunda', 'Malama', 'Mwale', 'Mwanza', 'Chama', 'Kapwepwe', 'Moyo',
      'Mwansa', 'Chileshe', 'Daka', 'Kabwe', 'Kunda', 'Mwamba', 'Ngulube',
      'Nyambe', 'Smith', 'Chinkuli', 'Hichilema', 'Kabinga', 'Kapil', 'Kasonde',
      'Lota', 'Mambwe', 'Mutale', 'Ngoma', 'Ngonga', 'Ngosa', 'Nkonde',
      'Sakala', 'Scott', 'Siamupangila', 'Skinner', 'Soko', 'Zimba', 'Abraham',
      'Alibuzwi', 'Barry', 'Blom', 'Bots', 'Chabala', 'Chala', 'Chardy',
      'Charlton', 'Biyete', 'Bwalya', 'Chanda', 'Chiboola', 'Chibuye', 'Chirambo',
    ],
  },
  ZW: {
    female: [
      'Margaret', 'Elizabeth', 'Grace', 'Precious', 'Samantha', 'Sarah', 'Linda',
      'Mavis', 'Sandra', 'Sharon', 'Susan', 'Tracy', 'Virginia', 'Yvonne',
      'Agnes', 'Alice', 'Charity', 'Charmaine', 'Chido', 'Ellen', 'Faith',
      'Julia', 'Kudakwashe', 'Kudzai', 'Monica', 'Nicola', 'Olivia', 'Patience',
      'Alexandra', 'Amanda', 'Anne', 'Audrey', 'Barbara', 'Carol', 'Catherine',
      'Christine', 'Claire', 'Cynthia', 'Debbie', 'Emily', 'Emma', 'Georgina',
      'Gladys', 'Heather', 'Helen', 'Hope', 'Irene', 'Jane', 'Josephine',
      'Joyce', 'Sheillah', 'Yeukai', 'Tsitsi',
    ],
    male: [
      'David', 'Peter', 'John', 'Charles', 'Brian', 'Christopher', 'Paul',
      'Patrick', 'James', 'Robert', 'Daniel', 'Tinashe', 'Joseph', 'Kevin',
      'Mark', 'Michael', 'Mike', 'Simon', 'Godfrey', 'Richard', 'Trevor',
      'Andrew', 'Bernard', 'Bruce', 'Gary', 'George', 'Ian', 'Ronald',
      'Ryan', 'Stephen', 'William', 'Blessing', 'Donald', 'Douglas', 'Henry',
      'Luke', 'Sean', 'Takudzwa', 'Allan', 'Benjamin', 'Brendon', 'Cephas',
      'Edward', 'Gilbert', 'Guy', 'Herbert', 'Liam', 'Malcolm', 'Roy',
      'Samuel', 'Mthuli', 'Tongai', 'Joshua',
    ],
    family: [
      'Moyo', 'Ncube', 'Ndlovu', 'Williams', 'Dube', 'Smith', 'Phiri',
      'Campbell', 'Evans', 'Jones', 'Lewis', 'Matambanadzo', 'Mitchell', 'Mpofu',
      'Mugabe', 'Robinson', 'Sibanda', 'Banda', 'Conway', 'Cox', 'Davies',
      'Davis', 'Murphy', 'Ndiweni', 'Ngwenya', 'Price', 'Taylor', 'Waller',
      'Watson', 'Bennett', 'Brown', 'Cameron', 'Chiwara', 'Clark', 'Colahan',
      'Cole', 'Coventry', 'Crocker', 'Cross', 'Davidson', 'Edwards', 'Gibson',
      'Goodwin', 'Gray', 'Gumbo', 'Gurira', 'Harnden', 'Hewlett', 'Higgins',
      'Hill', 'Muchinguri-Kashiri', 'Mutsvangwa', 'Shava', 'Mnangagwa', 'Chikomo', 'Zhou',
    ],
  },
} as const

export function isAfricaReviewedCountry(code: string): code is keyof typeof africaReviewedNames {
  return Object.hasOwn(africaReviewedNames, code)
}
