// Reviewed country-linked Wikidata candidate components; see docs/geographic-data.md.
export const asiaEastNames = {
  CN: {
    female: [
      "Li", "Wei", "Ping", "Jìng", "Yan", "Ying",
      "Lu", "Juan", "Dan", "Tíng", "Qing", "Yu",
      "Mei", "Fei", "Shuang", "Xiaoyan", "Min", "Lei",
      "Yue", "Chen", "Hui", "Lin", "Rui", "Yang",
      "Hóng", "Jing", "Jun", "Shuzhen", "Yīng", "Qin",
      "Xin", "Yì", "Lìlì", "Ling", "Nan", "Qí",
      "Tíngtíng", "Xiao", "Yíng", "Jiaxin",
    ],
    male: [
      "Wei", "Jun", "Lei", "Hao", "Yang", "Guóqiáng",
      "Qiang", "Yu", "Píng", "Xin", "Peng", "Jianguo",
      "Gang", "Long", "Guang", "Xiao", "Yì", "Feng",
      "Yong", "Yuan", "Bin", "Fei", "Jiànpíng", "Liang",
      "Ming", "Zhēng", "Bo", "Chen", "Jin", "Zhen",
      "Zhiqiang", "Hui", "Lì", "Rui", "Haoran", "Jiahao",
      "Jùnjié", "Wenbin", "Wēi", "Xiangdong",
    ],
    family: [
      "Wang", "Li", "Zhang", "Chen", "Liu", "Yang",
      "Wu", "Huang", "Xu", "Zhou", "Zhao", "Sun",
      "Ma", "He", "Lin", "Zhu", "Hu", "Jiang",
      "Yu", "Guo", "Gao", "Zheng", "Lu", "Liang",
      "Luo", "Shen", "Feng", "Xie", "Tang", "Shi",
      "Cheng", "Yan", "Cao", "Cai", "Deng", "Yuan",
      "Pan", "Han", "Dong", "Su", "Lü", "Ding",
      "Fan", "Fu", "Fang", "Song", "Ye", "Wei",
      "Jin", "Du", "Yao", "Zeng", "Tian", "Peng",
      "Bai", "Dai", "Qian", "Gu", "Tan", "Qiu",
    ],
  },
  HK: {
    female: [
      "Jessica", "Jenny", "Annie", "Carmen", "Jennifer", "Joey",
      "Kitty", "Stephanie", "Xiaotong", "Yan", "Agnes", "Alice",
      "Anna", "Bonnie", "Brenda", "Elaine", "Emily", "Grace",
      "Jasmine", "Karen", "Lisa", "Maggie", "Michelle", "Natalie",
      "Peggy", "Qíng", "Rachel", "Stella", "Tracy", "Vicky",
      "Yoyo", "Amanda", "Amber", "Angela", "Betty", "Carol",
      "Celine", "Cherry", "Chloe", "Christine",
    ],
    male: [
      "Alan", "Matthew", "Alex", "Andrew", "Henry", "James",
      "Ryan", "Simon", "Vincent", "Adrian", "Albert", "Andy",
      "Anthony", "Ben", "Daniel", "Danny", "Edmond", "Jack",
      "Jason", "Joseph", "Kelvin", "Ken", "Kenny", "Kevin",
      "Leo", "Peter", "Roy", "Sam", "Tommy", "Alexander",
      "Angus", "Byron", "Charles", "Clement", "David", "Eddie",
      "Edward", "Eric", "Eugene", "Hubert",
    ],
    family: [
      "Chen", "Li", "Huang", "Zhang", "Lin", "Wu",
      "Liang", "Liu", "He", "Luo", "Yang", "Zhou",
      "Wang", "Zheng", "Feng", "Deng", "Lu", "Wong",
      "Ma", "Zhong", "Zhu", "Xu", "Hu", "Pan",
      "Yu", "Mai", "Cai", "Fang", "Guan", "Su",
      "Yuan", "Zeng", "Cheng", "Guo", "Jiang", "Xie",
      "Zhao", "Gao", "Tang", "Kwong", "Leung", "Ou",
      "Tan", "Ye", "Jian", "Lam", "Lee", "Liao",
      "Peng", "Shi", "Wen", "Cheung", "Dai", "Lai",
      "Lo", "Ren", "Yao", "Zhuo", "Cui", "Du",
    ],
  },
  JP: {
    female: [
      "Yōko", "Aya", "Keiko", "Yūko", "Akiko", "Kaori",
      "Noriko", "Tomoko", "Mika", "Miki", "Hiroko", "Megumi",
      "Kyōko", "Junko", "Hitomi", "Mari", "Mai", "Miho",
      "Ai", "Yui", "Maki", "Michiko", "Rika", "Mariko",
      "Rie", "Naoko", "Reiko", "Mayumi", "Yoshiko", "Yukiko",
      "Hiromi", "Ayako", "Sayaka", "Ayaka", "Rina", "Haruka",
      "Naomi", "Ayumi", "Yumi", "Masako", "Yumiko", "Yuri",
      "Sachiko", "Mio", "Saki", "Mizuki", "Yuka", "Aki",
      "Miyuki", "Yuki",
    ],
    male: [
      "Hiroshi", "Akira", "Takashi", "Hiroyuki", "Takeshi", "Kenji",
      "Makoto", "Kōji", "Jun", "Kazuo", "Ryō", "Tadashi",
      "Kōichi", "Hideo", "Tōru", "Toshio", "Daisuke", "Masahiro",
      "Yoshio", "Atsushi", "Satoshi", "Ken", "Masao", "Kiyoshi",
      "Yutaka", "Osamu", "Yūji", "Ken'ichi", "Shigeru", "Eiji",
      "Shinji", "Yūsuke", "Naoki", "Shin'ichi", "Masayuki", "Takahiro",
      "Tetsuya", "Kōsuke", "Takeo", "Hiroki", "Hitoshi", "Takayuki",
      "Ichirō", "Hajime", "Masato", "Tsutomu", "Hiroaki", "Takuya",
      "Yasuo", "Minoru",
    ],
    family: [
      "Tanaka", "Satō", "Takahashi", "Suzuki", "Nakamura", "Itō",
      "Kobayashi", "Katō", "Yamamoto", "Watanabe", "Yoshida", "Saitō",
      "Inoue", "Yamada", "Sasaki", "Matsumoto", "Kimura", "Mori",
      "Hayashi", "Abe", "Shimizu", "Yamaguchi", "Okada", "Murakami",
      "Fujii", "Endō", "Ishikawa", "Ikeda", "Maeda", "Hasegawa",
      "Honda", "Miura", "Nakajima", "Gotō", "Fujita", "Nakano",
      "Ono", "Ogawa", "Okamoto", "Hashimoto", "Sakai", "Ishii",
      "Nakayama", "Aoki", "Morita", "Nakagawa", "Yamashita", "Mizuno",
      "Kondō", "Sakamoto", "Takeuchi", "Ōta", "Ueda", "Maruyama",
      "Yamazaki", "Yokoyama", "Hoshino", "Murata", "Kaneko", "Kikuchi",
      "Takeda", "Sugiyama", "Arai", "Nishimura", "Uchida", "Matsuda",
      "Ishida", "Ōno", "Andō", "Yoshikawa", "Sakurai", "Fukuda",
      "Tachibana", "Harada", "Wada",
    ],
  },
  KP: {
    female: [
      "Yeong-suk", "Jeong-suk", "Chun-hwa", "Gyeong-hui", "Hye-yeong", "Jeong-hwa",
      "Myeong-sun", "Sun-hui", "Yun-mi", "Bun-hui", "Chun-hui", "Eun-jeong",
      "Gyeong-suk", "Hye-seong", "Hyeon-gyeong", "Hyeon-hui", "Hyo-sim", "Jeong-ae",
      "Jeong-hui", "Myeong-hui", "Myeong-hwa", "Pil-hwa", "Seon-hui", "Su-jeong",
      "Sung-hee", "Yeong-ae", "Yeong-mi", "Yeong-ok", "Ae-ran", "Bok-sun",
      "Chang-ok", "Chun-hi", "Eun-byeol", "Eun-gyeong", "Eun-ha", "Eun-sil",
      "Eun-sun", "Geum-hwa",
    ],
    male: [
      "Yeong-ho", "Geum-cheol", "Cheol-min", "Seong-cheol", "Yeong-cheol", "Chol-man",
      "In-guk", "Jeong-cheol", "Jeong-nam", "Jeong-sik", "Myeong-cheol", "Seong-nam",
      "Su-il", "Yeong-nam", "Young-il", "Byeong-ho", "Guk-cheol", "Gwang-cheol",
      "Gwang-ho", "Gwang-hyeok", "Hyok-chol", "Jeong-su", "Jin-hyeok", "Ju-seong",
      "Seok-hyeong", "Seong-guk", "Yeong-gil", "Yeong-seop", "Yeong-sik", "Yong-ho",
      "Chang-sik", "Cheol-ho", "Cheol-su", "Cheol-ung", "Dong-chun", "Dong-geun",
      "Dong-hyuk", "Gi-ryong", "Gwang-min", "Gyeong-il",
    ],
    family: [
      "Kim", "Park", "Choi", "Lee", "Ri", "Kang",
      "Cho", "Ahn", "Jung", "Jang", "Jeon", "Oh",
      "Hong", "Han", "Im", "Baek", "Shin", "Heo",
      "Hwang", "Jin", "Ko", "Noh", "Ju", "Moon",
      "Song", "Yang", "Yoon", "Bang", "Cha", "Ryu",
      "Seo", "Gye", "Hyeon", "Yoo", "Ji", "Kwon",
      "Eom", "Gil", "Son", "Tae",
    ],
  },
  KR: {
    female: [
      "Su-jin", "Ji-yeon", "Ji-yeong", "Ji-hyeon", "So-yeong", "Ji-eun",
      "Min-ji", "Yu-jin", "Ji-won", "So-yeon", "Hyeon-jeong", "Ji-hye",
      "Eun-yeong", "Hye-jin", "Min-jeong", "Su-yeon", "Seon-yeong", "Mi-gyeong",
      "Eun-jeong", "Hye-gyeong", "Hyeon-ju", "Su-jeong", "Eun-ji", "Jeong-eun",
      "Jeong-hui", "Ji-su", "Yu-jeong", "Eun-ju", "Min-gyeong", "Ye-ji",
      "Hye-jeong", "Seo-yeon", "Yeong-hui", "Eun-hye", "Gyeong-hui", "Ji-min",
      "Ju-hui", "Na-yeong", "Yun-jeong", "Yun-hui", "Bo-ra", "Eun-gyeong",
      "Su-gyeong", "Su-hyeon", "Yeong-mi", "Hye-won", "Ju-yeon", "Su-min",
      "Eun-hui", "Ji-yun",
    ],
    male: [
      "Ji-hoon", "Dong-hyeon", "Jun-ho", "Sung-min", "Sang-hun", "Seong-ho",
      "Jeong-hun", "Yeong-jun", "Seong-hun", "Jin-woo", "Min-su", "Jae-won",
      "Min-gyu", "Hyeon-u", "Jae-hyeon", "Min-ho", "Jun-yeong", "Jung-hyun",
      "Yeong-su", "Hyeon-jun", "Jae-hun", "Seung-hyeon", "Jeong-ho", "Jae-ho",
      "Min-seok", "Yeong-hun", "Jeong-u", "Jin-ho", "Sang-ho", "Tae-yeong",
      "Dong-uk", "Seong-u", "Jeong-min", "Seung-u", "Yeong-cheol", "Jeong-hwan",
      "Sang-hyeon", "Seong-jun", "Dong-jin", "Jin-yeong", "Seung-min", "Seung-hun",
      "Dong-won", "Jeong-su", "Yeong-min", "Dong-hun", "Yeong-ho", "Yeong-jin",
      "Jong-hyeon", "Jun-seok",
    ],
    family: [
      "Kim", "Lee", "Park", "Jung", "Choi", "Cho",
      "Kang", "Yoon", "Jang", "Shin", "Han", "Yoo",
      "Im", "Seo", "Oh", "Ahn", "Song", "Jeon",
      "Hwang", "Hong", "Kwon", "Ko", "Yang", "Moon",
      "Baek", "Son", "Bae", "Noh", "Heo", "Ryu",
      "Shim", "Ha", "Nam", "Cha", "Ju", "Gu",
      "Na", "Kwak", "Jin", "Min", "Seong", "Byeon",
      "Ji", "Bang", "Woo", "Eom", "Won", "Chae",
      "Cheon", "Hyeon", "Gong", "Ham", "Chu", "Do",
      "Yeom", "Yeo", "Seol", "Yeon", "Gil", "Seok",
    ],
  },
  TW: {
    female: [
      "Huiling", "Shúfēn", "Alice", "Meiling", "Jennifer", "Lihua",
      "Lìlì", "Annie", "Cindy", "Jenny", "Shuhua", "Shuzhen",
      "Ya Ting", "Amanda", "Joanne", "Kelly", "Michelle", "Peggy",
      "Teresa", "Tíng", "Elaine", "Joyce", "Lìlíng", "Nancy",
      "Qíng", "Shujuan", "Sophia", "Vicky", "Xinyi", "Yvonne",
      "Amber", "Angela", "Ann", "Betty", "Cynthia", "Hui",
      "Jane", "Jean", "Jessica", "Jessie",
    ],
    male: [
      "James", "John", "David", "Jason", "Michael", "Paul",
      "Joseph", "Peter", "Andrew", "George", "Kevin", "Wei",
      "Eric", "Jiahao", "William", "Zhiming", "Hao", "Jinlong",
      "Charles", "Daniel", "Thomas", "Vincent", "Edward", "Guohua",
      "Henry", "Jimmy", "Jùnjié", "Mark", "Richard", "Sean",
      "Simon", "Wenbin", "Wenxiong", "Yu", "Matthew", "Mingzhe",
      "Tony", "Zhiwei", "Alex", "Andy",
    ],
    family: [
      "Chen", "Lin", "Li", "Zhang", "Wang", "Huang",
      "Wu", "Xu", "Liu", "Yang", "Cai", "Zheng",
      "Zhou", "Guo", "Xie", "Jiang", "Qiu", "Zeng",
      "Hong", "Liao", "Gao", "Su", "Ye", "Zhu",
      "He", "Yu", "Lai", "Shi", "Luo", "Lü",
      "Hu", "Sun", "Lu", "Zhao", "Yan", "Peng",
      "Xiao", "Shen", "You", "Zhuang", "Jian", "Pan",
      "Liang", "Tang", "Ma", "Fang", "Zhong", "Du",
      "Wei", "Zhan", "Fu", "Song", "Dai", "Cheng",
      "Weng", "Fan", "Ke", "Cao", "Deng", "Ding",
    ],
  },
  VN: {
    female: [
      "Phương", "Ngọc", "Anh", "Thanh", "Hương", "Nga",
      "Thảo", "Huyền", "Lan", "Tuyết", "Linh", "Quỳnh",
      "Kim", "Thủy", "Trang", "Thùy", "Vân", "Hà",
      "Hồng", "Thu", "Mai", "Minh", "Như", "Bích",
      "Dung", "My", "Thúy", "Ánh", "Hoàng", "Huệ",
      "Mỹ", "Phượng", "Xuân", "Giang", "Ngân", "Chi",
      "Hoa", "Nhi", "Tâm", "Trinh",
    ],
    male: [
      "Minh", "Anh", "Hoàng", "Sơn", "Dũng", "Miên",
      "Quang", "Đức", "Tuấn", "Hùng", "Quân", "Thanh",
      "Thành", "Việt", "Hải", "Bảo", "Huy", "Long",
      "Ngọc", "Nguyên", "Thịnh", "Tùng", "Vinh", "Duy",
      "Hồng", "Khôi", "Tông", "Trường", "Cường", "Dương",
      "Hiếu", "Khánh", "Nam", "Thái", "Châu", "Phong",
      "Quốc", "Xuân", "Khoa", "Kim",
    ],
    family: [
      "Nguyễn", "Trần", "Lê", "Phạm", "Vũ", "Hoàng",
      "Bùi", "Ngô", "Đặng", "Phan", "Nguyen", "Trịnh",
      "Huỳnh", "Trương", "Đỗ", "Dương", "Võ", "Hà",
      "Hồ", "Lý", "Cao", "Lưu", "Đinh", "Đoàn",
      "Lương", "Mai", "Phùng", "Đào", "Quách", "Lâm",
      "Pham", "Vương", "Mạc", "Tạ", "Bui", "Châu",
      "Tran", "Le", "Thái", "Tôn Thất",
    ],
  },
} as const

export function isAsiaEastCountry(code: string): code is keyof typeof asiaEastNames {
  return Object.hasOwn(asiaEastNames, code)
}
