// Reviewed citizenship-linked Wikidata candidate components; see docs/geographic-data.md.
export const asiaAdditionalNames = {
  ID: {
    female: [
      "Farida", "Retno", "Eva", "Maria", "Anna", "Irma",
      "Annisa", "Anita", "Putri", "Lina", "Henny", "Diana",
      "Elly", "Ida", "Jessica", "Olivia", "Sarah", "Linda",
      "Siti", "Amanda", "Theresia", "Nadia", "Rina", "Ana",
      "Maya", "Natalia", "Rita", "Vera", "Grace", "Regina",
      "Sylvia", "Amelia", "Cindy", "Natasha", "Ria", "Hilda",
      "Michelle", "Rachel", "Tina", "Dewi",
    ],
    male: [
      "Muhammad", "Eddy", "Amir", "Ahmad", "Herman", "Abdul",
      "John", "Ali", "Mohammad", "Robert", "Erwin", "Frans",
      "Denny", "Agus", "Johan", "Samuel", "Henry", "Dani",
      "Thomas", "Albert", "David", "Abdullah", "Paulus", "Kevin",
      "Victor", "Andi", "Edward", "James", "Joseph", "Benny",
      "Bobby", "Daniel", "Hendra", "Johannes", "Tommy", "Alexander",
      "Michael", "Rudy", "Bambang", "Christian", "Indra", "Joko",
      "Ricky", "Rizky", "Adam",
    ],
    family: [
      "Wijaya", "Santoso", "Sondakh", "Ginting", "Tan", "Arifin",
      "Hartono", "Hidayat", "Wanggai", "Nasution", "Nugroho", "Widjaja",
      "Jauhari", "Papilaya", "Chandra", "Hadju", "Sitorus", "Waworuntu",
      "Lubis", "Mainaky", "Rachman", "Kairupan", "Laoh", "Lapian",
      "Pasaribu", "Senduk", "Sinaga", "Sutrisna", "Halim",
    ],
  },
  SG: {
    female: [
      "Michelle", "Mary", "Elizabeth", "Nancy", "Amy", "Ann",
      "Cheryl", "Helen", "Jean", "Margaret", "Rachel", "Theresa",
      "Vanessa", "Victoria", "Anita", "Belinda", "Charmaine", "Chloe",
      "Christina", "Daphne", "Denise", "Grace", "Janice", "Jessica",
      "Joanne", "Lily", "Mariam", "Melissa", "Stella", "Wendy",
      "Alice", "Alyssa", "Amanda", "Angela", "Anna", "Caroline",
      "Cindy", "Claire", "Clara", "Colleen", "Constance", "Cynthia",
      "Dawn", "Eileen", "Eleanor", "Emily", "Eunice", "Evelyn",
      "Fatimah", "Fiona",
    ],
    male: [
      "David", "Desmond", "Robert", "Joseph", "John", "Kelvin",
      "Peter", "Benjamin", "Charles", "Eric", "Muhammad", "Aaron",
      "Andrew", "Paul", "Richard", "Anthony", "Arthur", "Bernard",
      "Christopher", "Daniel", "Edwin", "James", "Jason", "Leon",
      "Mark", "Omar", "Adam", "Adrian", "Ahmad", "Alex",
      "Aloysius", "Andy", "George", "Harry", "Jimmy", "Jonathan",
      "Joshua", "Kenneth", "Leslie", "Mohamed", "Simon", "Steven",
      "Vincent", "William", "Colin", "Henry", "Ismail", "Jack",
      "Jeffrey", "Joel",
    ],
    family: [
      "Chen", "Tan", "Li", "Lim", "Lin", "Huang",
      "Wong", "Lee", "Yang", "Ong", "Wang", "Wu",
      "Koh", "Zheng", "Liang", "Liu", "Zhang", "Low",
      "Wee", "Xu", "Cai", "He", "Yeo", "Goh",
      "Zhu", "Chew", "Chia", "Fu", "Guo", "Neo",
      "Teo", "Loh", "Qiu", "Seah", "Tay", "Xie",
      "Zhou", "Cheng", "Cheong", "Chin", "Guan", "Hong",
      "Jiang", "Khoo", "Kwek", "Lam", "Lau", "Pan",
      "Shen", "Sun", "Tang", "Woo", "Ang", "Hu",
      "Lai", "Luo", "Soh", "Tán", "Yan", "Yap",
    ],
  },
  TH: {
    female: [
      "Sunisa", "Nicha", "Porntip", "Alisa", "Benyapa", "Chayanit",
      "Peeraya", "Yanisa", "Ajjima", "Anisa", "Chananchida", "Chanida",
      "Chinda", "Janyaporn", "Jenjira", "Jutatip", "Kamala", "Kanyanat",
      "Kanyawee", "Ladawan", "Lalita", "Natcha", "Nichakarn", "Pimchanok",
      "Puttita", "Saranporn", "Sasithorn", "Suchanya", "Sukanya", "Sumol",
      "Supatra", "Sutatta", "Wanna", "Warattaya", "Yanin",
    ],
    male: [
      "Anucha", "Chavalit", "Pakorn", "Tanongsak", "Adisak", "Santi",
      "Chaiwat", "Tanawat", "Winai", "Nawat", "Niti", "Seksan",
      "Somsak", "Suwat", "Adisorn", "Anand", "Anat", "Anon",
      "Apichasit", "Danai", "Kittisak", "Krit", "Mongkol", "Nakarin",
      "Napat", "Narong", "Nattawat", "Nattawut", "Natthanan", "Natthapat",
      "Nopadol", "Pichai", "Pinit", "Pongsakorn", "Poompat",
    ],
    family: [
      "Shinawatra", "Bhirombhakdi", "Pattabongse", "Pinthong", "Teeraratsakul", "Bunnag",
      "Bū̀athǭ́ng", "Chatborirak", "Chidchob", "Kamsing", "Promsarin", "Vejjajiva",
      "Aiamvareesrisakul", "Aimsaard", "Amatayakul", "Ampansuwan", "Ampunsuwan", "Apisuk",
      "Chaiman", "Chaimanee", "Chamnaktan", "Chatupornkarnchana", "Chitcharoen", "Chochuwong",
      "Dansoonthornwong", "Deearom", "Dumrongthamavoot", "Iamratanamaetheekul", "Jatupanaporn", "Jindapol",
      "Jutanugarn", "Kanchanaraphi", "Kaosamaang", "Kleebyeesoon",
    ],
  },
  MV: {
    female: [
      "Aishath", "Fathimath", "Aminath", "Mariya", "Mariyam", "Afnaan",
      "Amaani", "Aneesa", "Azima", "Dunya", "Eesha", "Faiza",
      "Farzana", "Fatima", "Fazna", "Ilham", "Jameela", "Laiba",
      "Laila", "Maisa", "Maryam", "Murushida", "Nabaaha", "Nabeeha",
      "Naseemah", "Rashida", "Zeenath",
    ],
    male: [
      "Mohamed", "Ahmed", "Ibrahim", "Ali", "Ismail", "Hassan",
      "Abdulla", "Muhammad", "Abdul", "Abdullah", "Hussain", "Adam",
      "İmran", "Naseer", "Abbas", "Abdul-Hameed", "Abdur Rashid", "Ahmad",
      "Ajfan", "Anwar", "Aslam", "Faisal", "Fathullah", "Haitham",
      "Hamdhoon", "Hannan", "Hussein", "Ilyas", "Mamdhoon", "Mohammad",
      "Moosa", "Mustafa", "Nasheeu", "Nashfan", "Omar", "Rishwan",
      "Sharif", "Zayan",
    ],
    family: [
      "Rasheed", "Mohamed", "Ahmed", "Ali", "Abdulla", "Shareef",
      "Adam", "Riyaz", "Hassan", "Hussain", "Ibrahim", "Khaleel",
      "Naseem", "Shaheed", "Shaheem", "Abbas", "Adeeb", "Afeef",
      "Ashfaq", "Ashraf", "Asim", "Aslam", "Bari", "Falah",
      "Haitham", "Haleem", "Imran", "Ismail", "Jameel", "Junaid",
      "Latheef", "Mahloof", "Mannan", "Naeem", "Najeeb", "Nashid",
      "Nashwath", "Nasir", "Nibal", "Razzaq",
    ],
  },
  QA: {
    female: [
      "Mariam", "Noura", "Alya", "Amal", "Āmina", "Amira",
      "Asma", "Assrar", "Aya", "Danah", "Ebtesam", "Fatima",
      "Hamda", "Hind", "Huda", "Kamilah", "Kenza", "Khadija",
      "Kholoud", "Laila", "Leena", "Lina", "Maram", "Nada",
      "Nadeen", "Nadia", "Najla", "Nawal", "Rabea", "Sara",
      "Shayma", "Tala",
    ],
    male: [
      "Muhammad", "Ahmed", "Ali", "Abdullah", "Mohamed", "Ahmad",
      "Ibrahim", "Abd al-Aziz", "Abd al-Rahman", "Abdurahman", "Abdelaziz", "Adel",
      "Hassan", "Khaled", "Nasser", "Fahad", "Abdulla", "Hamad",
      "Jamal", "Jassem", "Rashid", "Yassin", "Yusuf", "Adam",
      "Bilal", "Hamed", "Issa", "Mahmoud", "Mohamad", "Mustafa",
      "Saad", "Salah", "Salman", "Waleed", "Aymen", "Chalifa",
      "Hashim", "Khamis", "Mohammad", "Saeed", "Saud", "Abdelilah",
    ],
    family: [
      "Hassan", "Al-Marri", "Mohammed", "Adam", "Ahmed", "Al-Hamad",
      "Al-Jassim", "Al-Mullah", "Hamad", "Khayyat", "Madadi", "Mohamed",
      "Omar", "Abbas", "Abdurisag", "Afif", "Aiesh", "Akram",
      "Al Khayat", "Al-Hajri", "Al-Maadeed", "Al-Malki", "Al-Qaradawi", "Al-Saadi",
      "Al-Siyabi", "Al-subaey", "Alaaeldin", "Alawi", "Arfa", "Arkaji",
      "Atari", "Attiyah", "Bader", "Barshim",
    ],
  },
} as const

export function isAsiaAdditionalCountry(code: string): code is keyof typeof asiaAdditionalNames {
  return Object.hasOwn(asiaAdditionalNames, code)
}
