// Reviewed citizenship-linked Wikidata candidates; see docs/geographic-data.md.
export const asiaCentralNames = {
  AZ: {
    female: [
      "Nərgiz", "Sabina", "Leyla", "Fəridə", "Anna", "Nigar",
      "Tamara", "Yelena", "Sevil", "Rəhilə", "Aida", "Marina",
      "Rafiqa", "Sevda", "Alina", "Amina", "Anastasiya", "Arzu",
      "Asya", "Aynur", "Elmira", "Günay", "Khadija", "Lala",
      "Ləman", "Mehriban", "Oksana", "Sara", "Sona", "Ulviyya",
      "Yuliya", "Alla", "Almaz", "Ayan", "Aybaniz", "Aygün",
      "Aysel", "Diana", "Dilara", "Dinara", "Elena", "Elina",
      "Elnara", "Fatima", "Fatma", "Fidan", "Hokuma", "Khanim",
      "Lyudmila", "Mariya",
    ],
    male: [
      "Ali", "Nazim", "Samir", "Elchin", "Vüqar", "Fuad",
      "Arif", "Eldar", "Emin", "Ruslan", "Aydın", "Farid",
      "Zaur", "Murad", "Aleksandr", "Elmar", "Elvin", "Kamil",
      "Azer", "Mammad", "Anar", "Ibrahim", "Rashad", "Chingiz",
      "Malik", "Rasim", "Vasif", "Asif", "Ceyhun", "Elnur",
      "Hikmat", "Ilgar", "Ilham", "Kamran", "Mikayıl", "Ramiz",
      "Rustam", "Tofig", "Tural", "Abbas", "Emil", "Faiq",
      "İlkin", "Nadir", "Parviz", "Sardar", "Səbuhi", "Tahir",
      "Vagif", "Adil",
    ],
    familyFemale: [
      "Əliyeva", "Hüseynova", "Mammadova", "Aliyeva", "Gurbanova", "Mustafayeva",
      "Ismayilova", "Valiyeva", "Abbasova", "Abdullayeva", "Azizova", "Safarova",
      "Abıyeva", "Akhundova", "Babayeva", "Bagirova", "Musayeva", "Qasımova",
      "Bayramova", "Fataliyeva", "Gadirova", "Guliyeva", "Kerimova", "Mehdiyeva",
      "Qadimova", "Ramazanova", "Səmədova", "Tagiyeva",
    ],
    familyMale: [
      "Mamedov", "Aliev", "Abdullayev", "Əliyev", "Hüseynov", "Hajiyev",
      "Mammadov", "Abbasov", "Guliyev", "Kərimov", "Quliyev", "Ibraguimov",
      "Ağayev", "Hasanov", "Jafarov", "Bağırov", "Akhmedov", "Kerimov",
      "Babayev", "Aslanov", "Bayramov", "Sultanov", "Ismayılov", "Kazimov",
      "Khalilov", "Mehdiyev", "Məhərrəmov", "Afandiyev", "Ahmadov", "Asgarov",
      "Axundov", "İsayev", "Musayev", "Nabiyev", "Vəliyev", "Mustafayev",
      "Safarov", "Alakbarov", "Hashimov", "Dadashov", "Əzizov", "Garayev",
      "Şükürov", "Suleymanov", "Vakilov", "Valiyev", "Aliyev", "Atakişiyev",
      "Mukhtarov", "Novruzov",
    ],
  },
  KG: {
    female: [
      "Dinara", "Olga", "Elena", "Elvira", "Anna", "Baktygul",
      "Irina", "Nazgul", "Zamira", "Aisuluu", "Alina", "Arina",
      "Gulnar", "Jana", "Klara", "Lyudmila", "Maria", "Svetlana",
      "Aida", "Aidana", "Aleksandra", "Alexandra", "Aliya", "Anastasia",
      "Angelina", "Angélique", "Ayana", "Aygül", "Begimay", "Damira",
      "Dariia", "Darya", "Diana", "Elmira", "Evgenia", "Farida",
      "Galina", "Gulmira", "Gulnaz", "Inga", "Iskra", "Kamila",
      "Karina", "Katharina", "Larisa", "Leila", "Marina", "Mariya",
      "Meerim", "Milan",
    ],
    male: [
      "Vladimir", "Aleksandr", "Sergey", "Ruslan", "Valery", "Dmitry",
      "Marat", "Aleksey", "Andrey", "Yevgeny", "Oleg", "Aibek",
      "Anton", "Emil", "Leonid", "Nikolay", "Pavel", "Roman",
      "Timur", "Vladislav", "Gennady", "Igor", "Sergej", "Alexander",
      "Arsen", "Artyom", "Askar", "Aziz", "Bekbolot", "Boris",
      "Chingiz", "Dastan", "Guljigit", "Ivan", "Konstantin", "Maksim",
      "Mikhail", "Nurlan", "Temirlan", "Viktor", "Arkady", "Azamat",
      "Denis", "Ernest", "Jengishbek", "Kirill", "Kubanychbek", "Mambet",
      "Murat", "Myktybek",
    ],
    familyFemale: [
      "Maslova", "Aknazarova", "Andreeva", "Artamonova", "Asanova", "Bogachyova",
      "Borisova", "Gorbacheva", "Ismailova", "Kalykova", "Karybekova", "Kolesnikova",
      "Tagaeva",
    ],
    familyMale: [
      "Zhorobekov", "Akayev", "Akmataliyev", "Isakov", "Ismailov", "Ivanov",
      "Samakov", "Abakirov", "Aliev", "Askarov", "Beyshenaliyev", "Jeenbekov",
      "Kenjebaev", "Sultanbekov", "Temirov", "Umetaliev", "Akhmetov", "Alimov",
      "Amirov", "Artykov", "Aytmatov", "Azizov", "Borisov", "Ibraev",
      "Kadyrbekov", "Kadyrov", "Karimov", "Kozubayev", "Kuznetsov", "Lazarev",
      "Musayev", "Omuraliev", "Sultanov", "Tagaev", "Tashiev", "Temirbaev",
      "Tsarnayev", "Yusupov", "Zhamankulov", "Abdraimov", "Abdrakhmanov", "Agapov",
      "Akhunov", "Akimaliev", "Alexeyev", "Alykulov", "Asanbaev", "Asanov",
      "Babanov", "Baisalov",
    ],
  },
  KZ: {
    female: [
      "Olga", "Yelena", "Irina", "Marina", "Nataliya", "Anna",
      "Lyudmila", "Svetlana", "Galina", "Anastasia", "Darya", "Yuliya",
      "Alina", "Aleksandra", "Mariya", "Kristina", "Alexandra", "Ekaterina",
      "Elena", "Nadezhda", "Dinara", "Viktoriya", "Arina", "Lidiya",
      "Veronika", "Aigerim", "Diana", "Karina", "Margarita", "Natalia",
      "Raisa", "Tamara", "Inna", "Maya", "Zoya", "Lyubov",
      "Madina", "Nina", "Oksana", "Valentina", "Antonina", "Aqmaral",
      "Catherine", "Maria", "Moldir", "Natalja", "Oxana", "Polina",
      "Rosa", "Sabina",
    ],
    male: [
      "Sergey", "Aleksandr", "Vladimir", "Andrey", "Dmitry", "Aleksey",
      "Yevgeny", "Igor", "Alexander", "Viktor", "Anatoly", "Nikolay",
      "Oleg", "Roman", "Mikhail", "Yury", "Marat", "Maksim",
      "Pavel", "Konstantin", "Vladislav", "Yevgeni", "Denis", "Bolat",
      "Ruslan", "Anton", "Vitaly", "Ivan", "Nurlan", "Timur",
      "Valery", "Murat", "Stanislav", "Vadim", "Ilya", "Leonid",
      "Boris", "Nikita", "Vyacheslav", "Alexandr", "Däuren", "Kairat",
      "Kirill", "Artur", "Askar", "Vasily", "Alexey", "Artyom",
      "Azamat", "Arman",
    ],
    familyFemale: [
      "Nazarbayeva", "Bogdanova", "Düisenova", "Gavrilova", "Ivanova", "Lebedeva",
      "Qojahmetova", "Smagulova", "Smirnova", "Smolyakova", "Syzdykova", "Temirkhanova",
      "Abdrakhmanova",
    ],
    familyMale: [
      "Kuznetsov", "Abdrakhmanov", "Akhmetov", "Ivanov", "Yegorov", "Aliev",
      "Äliev", "Ibraev", "Ibraguimov", "Medvedev", "Pavlov", "Ergaliev",
      "Popov", "Tarasov", "Yakovlev", "Abdraimov", "Alexandrov", "Belyayev",
      "Kenjebaev", "Korolyov", "Nazarov", "Orazbayev", "Ospanov", "Smirnov",
      "Sokolov", "Asanov", "Cherkasov", "Gavrilov", "Ismailov", "Jūmağūlov",
      "Karimov", "Kazantsev", "Khusainov", "Kozlov", "Makarov", "Novikov",
      "Petrov", "Rypakov", "Semyonov", "Shayakhmetov", "Strelnikov", "Sultanov",
      "Umarov", "Valiyev", "Vasilyev", "Yevseyev", "Abdullayev", "Abenov",
      "Abramov", "Ahmetjanov",
    ],
  },
  UZ: {
    female: [
      "Svetlana", "Irina", "Elena", "Umida", "Anna", "Olga",
      "Anastasia", "Anastasiya", "Lola", "Dilorom", "Ekaterina", "Nataliya",
      "Aziza", "Dinara", "Kamola", "Marina", "Sabina", "Tamara",
      "Yelena", "Alina", "Arina", "Halima", "Karina", "Luisa",
      "Luiza", "Madina", "Malika", "Mariya", "Nafisa", "Nilufar",
      "Oksana", "Sofia", "Vera", "Yuliya", "Aida", "Albina",
      "Aleksandra", "Alexandra", "Angelina", "Azadeh", "Darya", "Dildora",
      "Galina", "Gülistan", "Gulnara", "Kamara", "Kamilla", "Kristina",
      "Leila", "Lyudmila",
    ],
    male: [
      "Sergey", "Oleg", "Vladimir", "Aleksandr", "Ruslan", "Rustam",
      "Aziz", "Alisher", "Andrey", "Timur", "Aleksey", "Muhammad",
      "Nikolay", "Akbar", "Igor", "Sergej", "Vadim", "Viktor",
      "Yevgeny", "Ivan", "Pavel", "Vyacheslav", "Akmal", "Azamat",
      "Boris", "Georgy", "Nikita", "Shavkat", "Alexander", "Artyom",
      "Asad", "Denis", "Gennady", "Ibrahim", "Islam", "Konstantin",
      "Mikhail", "Pyotr", "Roman", "Vladislav", "Artur", "Behrouz",
      "Dilshod", "Dmitry", "Eldor", "Marat", "Muzaffar", "Nodirbek",
      "Sardor", "Sherzod",
    ],
    familyFemale: [
      "Yusupova", "Abdullayeva", "Akhmedova", "Ibragimova", "Mirziyoyeva", "Nazarova",
      "Rakhimova", "Rashidova", "Rustamova", "Toshmuhamedova", "Abbasova", "Abdurakhmanova",
      "Ahmadjonova", "Ahmedova", "Alimova", "Amanova", "Aminova", "Azizova",
      "Bakirova", "Dayibekova", "Ergasheva",
    ],
    familyMale: [
      "Karimov", "Abdullayev", "Yusupov", "Shomurodov", "Alijonov", "Gafurov",
      "Ibraguimov", "Rakhimov", "Ahmedov", "Aripov", "Haydarov", "Saidov",
      "Usmanov", "Akhmedov", "Ganiev", "Kadyrov", "Kurbanov", "Sultanov",
      "Zakirov", "Abramov", "Andreyev", "Jalilov", "Nazarov", "Nurmanov",
      "Qodirov", "Sabirov", "Sindarov", "Umarov", "Vohidov", "Akbarov",
      "Aliev", "Alimov", "Amirov", "Azimov", "Azizov", "Burkhanov",
      "Ergashev", "Fayzullaev", "Isakov", "Ismailov", "Kamilov", "Masharipov",
      "Odilov", "Qurbonov", "Rustamov", "Temirov", "Yuldashev", "Yunusov",
      "Abdulkhalikov", "Abdullaev",
    ],
  },
} as const

export function isAsiaCentralCountry(code: string): code is keyof typeof asiaCentralNames {
  return Object.hasOwn(asiaCentralNames, code)
}
