// Reviewed country-linked Wikidata candidate components; see docs/geographic-data.md.
export const asiaReviewedNames = {
  AM: {
    female: [
      "Anna", "Karine", "Anahit", "Mariam", "Emma", "Vardouhi",
      "Nelly", "Susanna", "Gohar", "Armine", "Diana", "Margarita",
      "Alla", "Irina", "Kristine", "Laura", "Liana", "Hasmik",
      "Mary", "Nune", "Tamara", "Alina", "Ani", "Anush",
      "Gayane", "Nina", "Aida", "Eva", "Larisa", "Lena",
      "Lilit", "Margarit", "Marine", "Naira", "Seda", "Sona",
      "Elena", "Elina", "Greta", "Maria", "Natalia", "Silva",
      "Sofia", "Tatevik", "Valentina", "Angela", "Arevik", "Karina",
      "Lusine", "Lyudmila",
    ],
    male: [
      "Karen", "Armen", "David", "Ashot", "Aram", "Artur",
      "Ruben", "Albert", "Robert", "Arthur", "Eduard", "Hrant",
      "Hayk", "Ara", "Arman", "Henrik", "Vladimir", "Alexander",
      "Suren", "Vardan", "Stepan", "Andranik", "Sergey", "Yury",
      "Edward", "Arsen", "Martin", "Georgy", "Levon", "Harutyun",
      "Rafik", "Boris", "Sargis", "Vahe", "Norayr", "Edgar",
      "Hovhannes", "Mher", "Rafayel", "Arshak", "Felix", "Gregory",
      "Simon", "Petros", "Roman", "Aramayis", "Gevorg", "Karapet",
      "Michael", "Rafael",
    ],
    family: [
      "Grigorian", "Hovhannisyan", "Sargsyan", "Harutyunyan", "Margaryan", "Hakobyan",
      "Petrossian", "Arutyunyan", "Mkrtchyan", "Ghazaryan", "Karapetyan", "Abrahamyan",
      "Martirosyan", "Manukyan", "Akopyan", "Avetisyan", "Poghossian", "Davtyan",
      "Khachatryan", "Tovmasyan", "Vardanyan", "Gevorgyan", "Mnatsakanyan", "Minassjan",
      "Barseghyan", "Hayrapetyan", "Nazarian", "Sahakian", "Vartanian", "Ambartsumian",
      "Arakelyan", "Grigoryan", "Howhannisjan", "Kocharyan", "Melkonyan", "Shahinyan",
      "Voskanyan", "Arzumanyan", "Galstyan", "Mkhitaryan", "Movsisyan", "Muradyan",
      "Safaryan", "Babayan", "Badalyan", "Darbinyan", "Ghukasyan", "Manasyan",
      "Melikyan", "Nalbandian", "Zakaryan", "Baghdasaryan", "Nersessian", "Ohanian",
      "Petrosyan", "Poghosyan", "Sahakyan", "Simonian", "Sukiasyan", "Yeritsyan",
      "Aslanyan", "Mirzoyan", "Tumanyan", "Aleksanyan", "Azatyan", "Gabrielyan",
      "Galstian", "Gasparian", "Gasparyan", "Papikyan", "Simonyan", "Stepanyan",
      "Tadevosyan", "Tsaturyan", "Vartapetian",
    ],
  },
  BD: {
    female: [
      "Farida", "Selina", "Laila", "Rokeya", "Yasmin", "Dilara",
      "Nadia", "Sabrina", "Sonia", "Sultana", "Sabina", "Sadia",
      "Salma", "Shirin", "Anika", "Anwara", "Dolly", "Farzana",
      "Ferdousy", "Khadija", "Nusrat", "Rozina", "Sabita", "Sahara",
      "Sara", "Sufia", "Alina", "Anjana", "Doli", "Faraḥ",
      "Farhana", "Jahanara", "Jasmin", "Khatun", "Lata", "Latifa",
      "Lucy", "Mahfuza", "Maya", "Monica", "Monira", "Mumtaz",
      "Nasima", "Nina", "Nova", "Parvin", "Rina", "Rita",
      "Samina", "Sanjida",
    ],
    male: [
      "Mohammad", "Muhammad", "Ahmed", "Mohamed", "Abdullah", "Ali",
      "Enamul", "Asif", "Fazlur", "Hasan", "Iqbal", "Mustafa",
      "Anwar", "Kamal", "Ziaur", "Aziz", "İmran", "Jewel",
      "Lutfor", "Mostafa", "Nazmul", "Rahman", "Rashid", "Farid",
      "Hossain", "Mizanur", "Quazi", "Sohel", "Abdul Mannan", "Asaduzzaman",
      "Ayub", "Ferdous", "Habib", "Jamal", "Mahbub", "Masud",
      "Oli", "Sadik", "Salman", "Abd al-Karīm", "Abd al-Salam", "Abdul Jabbar",
      "Abed", "Ahmad", "Akhtar", "Ali Akbar", "Amir", "Anisul",
      "Azad", "Barua",
    ],
    family: [
      "Chowdhury", "Rahman", "Ahmed", "Hossain", "Islam", "Khan",
      "Hasan", "Haque", "Alam", "Akhter", "Ali", "Choudhury",
      "Khatun", "Begum", "Ghosh", "Ahmad", "Akter", "Zaman",
      "Hoque", "Kabir", "Karim", "Sarkar", "Roy", "Saha",
      "Sarker", "Uddin", "Das", "Dutta", "Hussein", "Imam",
      "Mahmud", "Rashid", "Talukder", "Anwar", "Barua", "Biswas",
      "Hussain", "Jahan", "Khondakar", "Parvin", "Rozario", "Siddique",
      "Sultana", "Haider", "Hamid", "Haq", "Hayat", "Huq",
      "Kaiser", "Abedin", "Alauddin", "Azam", "Bhuiyan", "Chakrabarti",
      "Chakraborty", "Chaudhury", "Costa", "Gomes", "Kamal", "Kazi",
      "Khaled", "Khanam", "Khandker", "Lohani", "Nahar", "Parvez",
      "Pathan", "Russell", "Samad", "Selim", "Shah", "Singh",
      "Abdullah", "Abed", "Adhikari",
    ],
  },
  GE: {
    female: [
      "Nino", "Mariam", "Nana", "Ana", "Ketevan", "Maia",
      "Rusudan", "Manana", "Anna", "Tinatin", "Marina", "Irine",
      "Eteri", "Hélène", "Tamara", "Irma", "Natela", "Tea",
      "Eka", "Maya", "Mzia", "Irina", "Salomé", "Gvantsa",
      "Lela", "Natalia", "Sofia", "Inga", "Khatuna", "Leila",
      "Lia", "Medea", "Natia", "Salome", "Ekaterine", "Khatia",
      "Lali", "Liana", "Maka", "Miriam", "Nato", "Nona",
      "Tamar", "Anastasia", "Elene", "Tamuna", "Tsira", "Vera",
      "Ekaterina", "Ia",
    ],
    male: [
      "Giorgi", "Davit", "Levan", "Irakli", "Zurab", "David",
      "Georgy", "Vakhtang", "Aleksandre", "Guram", "Nikoloz", "Otar",
      "Givi", "Revaz", "Tamaz", "Alexander", "Lasha", "Mikheil",
      "Nodar", "Zaza", "Shota", "Avtandil", "Teimuraz", "Tengiz",
      "Gia", "Merab", "Tornike", "Aleksandr", "Archil", "Mikhail",
      "Vladimer", "Akaki", "Ilia", "Shalva", "Mamuka", "Nika",
      "Paata", "Beka", "Malkhaz", "Grigol", "Nugzar", "George",
      "Konstantin", "Vazha", "Gela", "Gocha", "Roman", "Temur",
      "Boris", "Jemal",
    ],
    family: [
      "Bagrationi", "Abashidze", "Japaridze", "Asatiani", "Beridze", "Shengelia",
      "Machavariani", "Maisuradze", "Chkheidze", "Giorgadze", "Lortkipanidze", "Abuladze",
      "Bolkvadze", "Kapanadze", "Nadiradze", "Gelashvili", "Gotsiridze", "Ioseliani",
      "Kalandadze", "Khutsishvili", "Lezhava", "Akhvlediani", "Bakradze", "Davitashvili",
      "Janelidze", "Kvaratskhelia", "Kandelaki", "Kipiani", "Metreveli", "Tabatadze",
      "Tsintsadze", "Arveladze", "Chelidze", "Dadiani", "Gabunia", "Kakabadze",
      "Kutateladze", "Makharadze", "Nozadze", "Rekhviashvili", "Tevzadze", "Aleksidze",
      "Chikovani", "Javakhishvili", "Kavtaradze", "Kobakhidze", "Rukhadze", "Tsereteli",
      "Zhvania", "Dvalishvili", "Gachechiladze", "Gogoladze", "Iashvili", "Kiknadze",
      "Mgaloblishvili", "Mgeladze", "Natsvlishvili", "Petriashvili", "Razmadze", "Sikharulidze",
      "Antadze", "Bakhtadze", "Batonishvili", "Burjanadze", "Chavchavadze", "Cheishvili",
      "Dolidze", "Eristavi", "Ghonghadze", "Gogichaishvili", "Janashia", "Jikia",
      "Mikeladze", "Oniani", "Pavliashvili",
    ],
  },
  IL: {
    female: [
      "Yael", "Michal", "Rachel", "Ruth", "Tamar", "Miriam",
      "Maya", "Anat", "Esther", "Dana", "Sharon", "Adi",
      "Naomi", "Noa", "Sarah", "Efrat", "Rivka", "Anna",
      "Dalia", "Leah", "Sara", "Nurit", "Shoshana", "Hanna",
      "Ilana", "Orly", "Ronit", "Orit", "Rina", "Dafna",
      "Iris", "Ayelet", "Hana", "Hila", "Irit", "Judith",
      "Tali", "Dorit", "Keren", "Roni", "Tal", "Edna",
      "Einat", "Moran", "Hadas", "Aliza", "Ella", "Orna",
      "Yehudit", "Aviva",
    ],
    male: [
      "Moshe", "David", "Michael", "Avraham", "Zvi", "Shlomo",
      "Daniel", "Yitzhak", "Israel", "Chaim", "Shmuel", "Yosef",
      "Avi", "Mordecai", "Uri", "Yehuda", "Yossi", "Dan",
      "Yaakov", "Guy", "Jacob", "Abraham", "Shimon", "Amir",
      "Eli", "Aharon", "Arie", "Haim", "Menachem", "Yuval",
      "Joseph", "Dov", "Baruch", "Eliezer", "Gideon", "Yaacov",
      "Itzhak", "Alon", "Amos", "Ron", "Noam", "Yair",
      "Yoav", "Dávid", "Eyal", "Alexander", "Jonathan", "Danny",
      "Doron", "Ilan",
    ],
    family: [
      "Cohen", "Levy", "Katz", "Levi", "Friedman", "Shapira",
      "Goldberg", "Segal", "Klein", "Schwartz", "Weiss", "Levin",
      "Golan", "Rosen", "Goldstein", "Kaplan", "Landau", "Tal",
      "Adler", "Stern", "Bar", "Peretz", "Gross", "Berger",
      "Epstein", "Feldman", "Peled", "Shamir", "Zohar", "Dayan",
      "Gal", "Sharon", "Gordon", "Peleg", "Arad", "Lev",
      "Mizrahi", "Tamir", "Miller", "Alon", "Amir", "Harel",
      "Rubinstein", "Shavit", "Berman", "Meir", "Rosenberg", "Almog",
      "Navon", "Rabinovich", "David", "Goldman", "Raz", "Roth",
      "Sela", "Aharoni", "Dagan", "Goren", "Israeli", "Lavi",
      "Amit", "Ben-David", "Bergman", "Koren", "Ronen", "Rubin",
      "Sagi", "Segev", "Shalev", "Aloni", "Ben-Zvi", "Biton",
      "Halperin", "Harari", "Horowitz",
    ],
  },
  IN: {
    female: [
      "Anita", "Priya", "Rita", "Aditi", "Geeta", "Seema",
      "Asha", "Priyanka", "Uma", "Anjali", "Archana", "Indira",
      "Kiran", "Tara", "Amrita", "Divya", "Sonia", "Kavita",
      "Aishwarya", "Mary", "Pooja", "Krishna", "Chitra", "Rani",
      "Maya", "Vandana", "Varsha", "Aparna", "Kamala", "Nandita",
      "Rekha", "Lakshmi", "Sheila", "Deepa", "Leena", "Manisha",
      "Monica", "Monika", "Radha", "Radhika", "Sandhya", "Sujata",
      "Anna", "Meenakshi", "Mona", "Natasha", "Prachi", "Shobha",
      "Ananya", "Gayatri",
    ],
    male: [
      "Ram", "Anil", "Vijay", "Ashok", "Muhammad", "Arun",
      "Sunil", "Rahul", "Rajesh", "Deepak", "Joseph", "Ajay",
      "John", "Ramesh", "Suresh", "Krishna", "Mohammad", "Prakash",
      "Ravi", "Thomas", "Amit", "Anand", "Kumar", "Arjun",
      "Rakesh", "Sanjay", "Sanjeev", "George", "Satish", "Vinod",
      "Arvind", "Narayan", "Prem", "Sandeep", "Abhishek", "Pankaj",
      "Samir", "Gopal", "Manish", "Narendra", "Karan", "Shankar",
      "Mahesh", "Raj", "Rajiv", "Ali", "Chandra", "Mahendra",
      "Paul", "Vikram",
    ],
    family: [
      "Singh", "Sharma", "Mishra", "Roy", "Ghosh", "Joshi",
      "Jena", "Kumar", "Khan", "Mohanty", "Das", "Gupta",
      "Kaur", "Patel", "Dutta", "Gandhi", "Banerjee", "Rath",
      "Chatterjee", "Pattnaik", "Basu", "Shukla", "Agarwal", "D'Souza",
      "Malhotra", "Shah", "Mehta", "Mukherjee", "Kulkarni", "Fernandes",
      "Sengupta", "Jain", "Dasgupta", "George", "Paul", "Rao",
      "Chakrabarti", "Dubey", "Sen", "Reddy", "Devi", "Thomas",
      "Dey", "Trivedi", "Verma", "Bhattacharya", "Chakraborty", "Desai",
      "Chaturvedi", "Mehra", "Barik", "Chowdhury", "Pandey", "Yadav",
      "Anand", "Sinha", "Deshmukh", "Bose", "Prasad", "Ganguly",
      "Hansda", "Menon", "Bhatt", "Jacob", "Sarkar", "Arora",
      "Dwivedi", "Murmu", "Nair", "Patil", "Biswas", "Chauhan",
      "Modi", "Chopra", "John",
    ],
  },
  IR: {
    female: [
      "Maryam", "Zohreh", "Fatemeh", "Samaneh", "Zahra", "Fahimeh",
      "Afsaneh", "Bahareh", "Sara", "Leila", "Ruqayyah", "Farzaneh",
      "Mahsa", "Nafiseh", "Sepideh", "Mina", "Sahar", "Soudabeh",
      "Fereshteh", "Maliheh", "Massumeh", "Negar", "Parvin", "Shirin",
      "Elham", "Katayoun", "Mahdieh", "Raheleh", "Azadeh", "Khadija",
      "Marjan", "Marzieh", "Farideh", "Homa", "Fariba", "Nazanín",
      "Nazila", "Nilufar", "Samira", "Atefeh", "Elaheh", "Neda",
      "Roya", "Shahla", "Somayyeh", "Zhila", "Farnaz", "Maedeh",
      "Mona", "Mozhgan",
    ],
    male: [
      "Mohammad", "Ali", "Reza", "Ahmad", "Hossein", "Amir",
      "Mohammad-Ali", "Hassan", "Ali Reza", "Mohsen", "Hamid", "Abbas",
      "Mahmoud", "Muhammad", "Murtuza", "Mohammad-Reza", "Hussein", "Saeed",
      "Behnam", "Mostafa", "Saeid", "Ebrahim", "Parviz", "Majid",
      "Hadi", "Masoud", "Nasser", "Farhad", "Ali Akbar", "Ruhollah",
      "Akbar", "Gholamreza", "Javad", "Ali-Asghar", "Hamed", "Omid",
      "Mojtaba", "Eḥsan", "Iraj", "Milad", "Siavash", "Abdullah",
      "Abolfazl", "Babak", "Bahman", "Mahdi", "Mehrdad", "Behrouz",
      "Manouchehr", "Mansour",
    ],
    family: [
      "Ebrahimi", "Heidari", "Ghorbani", "Tehrani", "Mohammadi", "Hosseini",
      "Ahmadi", "Karimi", "Sadeghi", "Mousavi", "Afshar", "Kazemi",
      "Hashemi", "Bagheri", "Asadi", "Jafari", "Abbasi", "Rezaee",
      "Soltani", "Moradi", "Alizadeh", "Amini", "Amiri", "Ansari",
      "Nouri", "Gholami", "Soleimani", "Akbarzadeh", "Azizi", "Raḥimi",
      "Tabatabaei", "Yazdi", "Jafarian", "Najafi", "Rahmani", "Bahrami",
      "Hatami", "Zamani", "Asgari", "Emami", "Farahani", "Khosravi",
      "Moghaddam", "Nazari", "Norouzi", "Shariati", "Abdi", "Abdollahi",
      "Akbari", "Bayat", "Ghaffari", "Ghasemi", "Latifi", "Moradian",
      "Shahbazi", "Shirazi", "Esmaeili", "Habibi", "Kalhor", "Kiani",
      "Rajabi", "Rouhani", "Salehi", "Salimi", "Sharifi", "Taheri",
      "Aghaei", "Aslani", "Eslami", "Fallah", "Hejazi", "Kashani",
      "Mahmoudi", "Mirzaei", "Pahlavi",
    ],
  },
  LK: {
    female: [
      "Chandrika", "Doreen", "Nanda", "Samantha", "Thilini", "Anne",
      "Chitra", "Damitha", "Inoka", "Kumari", "Maureen", "Michelle",
      "Nadeesha", "Rita", "Rosemary", "Samanthi", "Tamara", "Vivienne",
      "Achini", "Adele", "Agnes", "Amali", "Amara", "Amitha",
      "Anarkali", "Angeline", "Anoma", "Anthea", "Antoinette", "Anula",
      "Aruni", "Aseka", "Asha", "Barbara", "Benuri", "Caroline",
      "Chandi", "Chandra", "Christine", "Deepika", "Dilhani", "Dilmi",
      "Dona", "Dorothy", "Dulanya", "Edna", "Ellis", "Eva",
      "Fathima", "Ferial",
    ],
    male: [
      "Mohamed", "James", "Rohan", "Ananda", "Anton", "Charles",
      "Cyril", "John", "Lakshman", "Sunil", "Don", "Henry",
      "Joseph", "Romesh", "Stanley", "Thomas", "Victor", "Basil",
      "Chandra", "Kamal", "Muhammad", "Sam", "Shantha", "Ajith",
      "Amal", "Arthur", "Bernard", "Douglas", "Edward", "Eric",
      "George", "Harold", "Lal", "Lionel", "Mahesh", "Neville",
      "Ravindra", "Rex", "Richard", "Suresh", "Upali", "William",
      "Albert", "Alfred", "Angelo", "Asela", "Hector", "Justin",
      "Kingsley", "Leslie",
    ],
    family: [
      "Silva", "Fernando", "Perera", "Dias", "de Silva", "Dissanayake",
      "Peiris", "Gunasekera", "Corea", "Gamage", "Gunathilake", "Karunaratne",
      "Wijesekera", "Amarasuriya", "Amerasinghe", "Cooray", "Dahanayaka", "Dahanayake",
      "Jayasinghe", "Liyanage", "Ratnayake", "Weerasinghe", "Abeykoon", "Bandaranaike",
      "Bawa", "David", "Jayawardena", "Kannangara", "Kumarasinghe", "Mendis",
      "Nagasinghe", "Ranasinghe", "White", "Wickremasinghe", "Abeysinghe", "Abeywickrama",
      "Adikaram", "Alexander", "Amarasinghe", "Anthony", "Aponsu", "Ariyadasa",
      "Arulpragasam", "Bandara", "Basnayake", "Chandrasena", "da Silva", "Dassanayake",
      "de Kretser", "Dharmadasa", "Ediriweera", "Francis", "Geeganage", "Gunasekara",
      "Gunawardana", "Hettiarachchi", "Iddamalgoda", "Jansz", "John", "Kuruppu",
      "Lanka", "Maheswaran", "Majeed", "Mallawarachchi", "Muralitharan", "Nadarajah",
      "Paul", "Premadasa", "Raheem", "Rajapaksa", "Ranaweera", "Samaraweera",
      "Sansoni", "Selvadurai", "Sirisena",
    ],
  },
  NP: {
    female: [
      "Sita", "Asha", "Lila", "Sarita", "Anita", "Nisha",
      "Rita", "Shanti", "Devi", "Gita", "Indira", "Lakshmi",
      "Radha", "Rekha", "Sunita", "Amita", "Amrita", "Anju",
      "Anu", "Chandra", "Gauri", "Manita", "Maya", "Mina",
      "Mira", "Namrata", "Neri", "Nirmala", "Pooja", "Punam",
      "Reema", "Rupa", "Sabina", "Sabita", "Sahana", "Sujata",
      "Sushama", "Tara", "Uma", "Aanchal", "Aditi", "Aishwarya",
      "Alina", "Alisha", "Annapurna", "Anuradha", "Anushka", "Arunima",
      "Arzu", "Bandana",
    ],
    male: [
      "Ram", "Krishna", "Chandra", "Prakash", "Narayan", "Prem",
      "Deepak", "Hari", "Shyam", "Anil", "Lal", "Narendra",
      "Raju", "Gopal", "Shiva", "Sunil", "Amar", "Indra",
      "Ramesh", "Uday", "Bishal", "Kamal", "Kedar", "Mahendra",
      "Mahesh", "Prasad", "Raj", "Sanjeev", "Shankar", "Sitaram",
      "Arjun", "Arun", "Bijay", "Binod", "Govinda", "Karna",
      "Keshav", "Kishor", "Nanda", "Pradip", "Pushpa", "Rajesh",
      "Suresh", "Upendra", "Abhishek", "Ashok", "Baburam", "Balram",
      "Basanta", "Bharat",
    ],
    family: [
      "Shrestha", "Gurung", "Thapa", "Sharma", "Rai", "Koirala",
      "Rana", "Shah", "Ghimire", "Kunwar", "Malla", "Singh",
      "Acharya", "Joshi", "Karki", "Pradhan", "Adhikari", "Bajracharya",
      "Basnet", "Maharjan", "Sherpa", "Yadav", "Bogati", "Giri",
      "Mishra", "Regmi", "Rijal", "Shahi", "Subba", "Tamang",
      "Teli", "Amatya", "Basnyat", "Bhandari", "Budhathoki", "Chaudhary",
      "Kandel", "Khatri Chhetri", "Lamsal", "Magar", "Pant", "Pokhrel",
      "Sapkota", "Subedi", "Baksi", "Bista", "Chaudhari", "Chhetri",
      "Dangol", "Das", "Devkota", "Dhakal", "Gautam", "Gharti",
      "Gyawali", "Kafle", "Khadka", "Kharel", "Kumar", "Lama",
      "Limbu", "Mahato", "Neupane", "Paudel", "Pun", "Rayamajhi",
      "Thapaliya", "Tiwari", "Uprety", "Aalam", "Agrahari", "Anand",
      "Aryal", "Aufschnaiter", "Babu",
    ],
  },
  PH: {
    female: [
      "Maria", "Mary", "María", "Anna", "Ana", "Carmen",
      "Lourdes", "Cecilia", "Cristina", "Karen", "Nicole", "Patricia",
      "Bernadette", "Imelda", "Mae", "Michelle", "Rosa", "Teresita",
      "Alice", "Ann", "Bianca", "Camille", "Irene", "Jennifer",
      "Josephine", "Victoria", "Andrea", "Angela", "Aurora", "Elizabeth",
      "Eva", "Isabel", "Jane", "Luisa", "Margarita", "Nina",
      "Rachel", "Agnes", "Alicia", "Anne", "Bea", "Carla",
      "Christine", "Cynthia", "Elena", "Ella", "Grace", "Janet",
      "Kristine", "Louise",
    ],
    male: [
      "Jose", "José", "Antonio", "Francisco", "Manuel", "John",
      "Mark", "Juan", "Michael", "Vicente", "Pedro", "Carlos",
      "Ramon", "Luis", "Miguel", "Joseph", "Eduardo", "James",
      "Francis", "Roberto", "Mariano", "Jaime", "Paul", "Rodolfo",
      "Victor", "Alfredo", "Paolo", "Daniel", "Rafael", "Carlo",
      "Gabriel", "Ricardo", "Christian", "Emilio", "Eric", "Mario",
      "Ronald", "Benjamin", "Christopher", "Oscar", "Angelo", "Enrique",
      "Ernesto", "Fernando", "Robert", "Arturo", "David", "Edgardo",
      "Gregorio", "Jason",
    ],
    family: [
      "Reyes", "Santos", "Cruz", "García", "Bautista", "Ramos",
      "Perez", "Lopez", "Padilla", "Villanueva", "Mendoza", "Aquino",
      "Castro", "Fernandez", "Rodriguez", "Diaz", "Gonzales", "del Rosario",
      "Lim", "Flores", "Tan", "Morales", "Navarro", "Santiago",
      "Romuáldez", "Bernardo", "Hernandez", "Soriano", "Sotto", "Delgado",
      "Francisco", "Guerrero", "Medina", "Moreno", "Rosales", "Torres",
      "Aguilar", "de Leon", "Dizon", "Garcia", "Laurel", "Ledesma",
      "Miranda", "Pangilinan", "Piccio", "Pineda", "Salvador", "David",
      "Luna", "Manalo", "Marcos", "Marquez", "Revilla", "Uy",
      "Velasco", "Vergara", "Wilson", "Yap", "Zamora", "Arellano",
      "López", "Molina", "Romero", "Roxas", "Sanchez", "Valdez",
      "Abad", "Alejandro", "Araneta", "Atienza", "Domingo", "Duterte",
      "Elizalde", "Espinosa", "Estrada",
    ],
  },
  PK: {
    female: [
      "Samina", "Fatima", "Nadia", "Rubina", "Sara", "Sadia",
      "Laila", "Mariam", "Farida", "Maryam", "Sarah", "Asma",
      "Bushra", "Faraḥ", "Fauzia", "Kiran", "Sonia", "Zara",
      "Azra", "Khadija", "Saba", "Tahira", "Abida", "Anita",
      "Ayesha", "Farzana", "Ghazala", "Maria", "Naila", "Palwasha",
      "Parvin", "Rabia", "Saira", "Shahla", "Sidra", "Tehmina",
      "Yasmin", "Anwara", "Nasim", "Natasha", "Rehana", "Sabiha",
      "Saima", "Sanam", "Selina", "Shamim", "Shazia", "Tasneem",
      "Zahida", "Zainab",
    ],
    male: [
      "Muhammad", "Mohammad", "Ali", "Ahmed", "İmran", "Tariq",
      "Anwar", "Shahid", "Asif", "Abdullah", "Ahmad", "Iqbal",
      "Rashid", "Saeed", "Amir", "Akhtar", "Faisal", "Amjad",
      "Hasan", "Hassan", "Aziz", "Adnan", "Hamid", "Mustafa",
      "Bilal", "Arsalan", "Rizwan", "Irfan", "Kamran", "Shaukat",
      "Aamir", "Imtiaz", "Tahir", "Abid", "Adil", "Arif",
      "Ijaz", "Jamal", "Sajid", "Abdur Rashid", "Asim", "Eḥsan",
      "Fawad", "Ghulam", "Hameed", "Hamza", "Kamal", "Shabbir",
      "Abbas", "Abd al-Aziz",
    ],
    family: [
      "Khan", "Ali", "Ahmad", "Ahmed", "Chowdhury", "Hussain",
      "Rahman", "Butt", "Saeed", "Iqbal", "Shah", "Malik",
      "Aziz", "Hassan", "Siddiqui", "Akhtar", "Baig", "Haq",
      "Hossain", "Qureshi", "Raza", "Abbas", "Alam", "Chaudhry",
      "Mahmood", "Muhammad", "Sarwar", "Abbasi", "Anwar", "Baloch",
      "Bashir", "Haider", "Hayat", "Islam", "Nadeem", "Sadiq",
      "Saleem", "Tahir", "Waqas", "Afridi", "Choudhury", "Hasan",
      "Hashmi", "Sharif", "Usmani", "Akram", "Aslam", "Bhutto",
      "Bukhari", "Farooq", "Hamid", "Husain", "Hussein", "Karim",
      "Masood", "Mohammad", "Syed", "Abidi", "Azam", "Gilani",
      "Ilyas", "Kaiser", "Kamal", "Mir", "Mirza", "Naeem",
      "Qadir", "Rashid", "Rehman", "Riaz", "Roy", "Zaidi",
      "Ansari", "Arshad", "Asghar",
    ],
  },
  TR: {
    female: [
      "Zeynep", "Ayşe", "Özlem", "Esra", "Elif", "Emine",
      "Fatma", "Pınar", "Merve", "Burcu", "Hatice", "Ebru",
      "Deniz", "Özge", "Yasemin", "Ayşegül", "Meltem", "Tuğba",
      "Çiğdem", "Sibel", "Asli", "Dilek", "Ceren", "Derya",
      "Gizem", "Yeşim", "Duygu", "Hülya", "Ezgi", "Filiz",
      "Seda", "Büşra", "Gözde", "Zehra", "Arzu", "Leyla",
      "Betül", "Canan", "Nur", "Sema", "Emel", "Cansu",
      "Aylin", "Başak", "Eda", "Demet", "Ece", "Didem",
      "Gamze", "Tuğçe",
    ],
    male: [
      "Mehmet", "Ahmet", "Mustafa", "Ali", "Hüseyin", "Murat",
      "Hasan", "Ömer", "Emre", "İbrahim", "Osman", "Fatih",
      "İsmail", "Burak", "Orhan", "Hakan", "Yusuf", "Kemal",
      "Bülent", "Can", "Cem", "Metin", "Gökhan", "Onur",
      "Serdar", "Uğur", "Abdullah", "Halil", "Mahmut", "Süleyman",
      "Sinan", "Erol", "Özgür", "Alper", "Serkan", "Ümit",
      "Barış", "Deniz", "Mert", "Umut", "Erkan", "Ibrahim",
      "Muhammed", "Recep", "Cemal", "Erhan", "Levent", "İhsan",
      "Muhammet", "Zeki",
    ],
    family: [
      "Yılmaz", "Öztürk", "Şahin", "Kaya", "Yıldırım", "Yıldız",
      "Aydın", "Özdemir", "Çelik", "Arslan", "Kılıç", "Demir",
      "Doğan", "Özcan", "Çetin", "Aksoy", "Erdoğan", "Özkan",
      "Can", "Yüksel", "Turan", "Yalcin", "Şimşek", "Aslan",
      "Şen", "Güler", "Bozkurt", "Köse", "Erdem", "Aktaş",
      "Bulut", "Ünal", "Yücel", "Koç", "Özer", "Acar",
      "Çakır", "Güneş", "Sönmez", "Korkmaz", "Yavuz", "Güven",
      "Mutlu", "Demirci", "Polat", "Işık", "Coşkun", "Yiğit",
      "Akın", "Eren", "Ceylan", "Tekin", "Keskin", "Albayrak",
      "Kara", "Güngör", "Ateş", "Gündüz", "Deniz", "Kurt",
      "Yazıcı", "Avcı", "Uzun", "Uysal", "Gül", "Koçak",
      "Genç", "Kahraman", "Turgut", "Güner", "Kaplan", "Çınar",
      "Başaran", "Gümüş", "Uğur",
    ],
  },
} as const

export function isAsiaReviewedCountry(code: string): code is keyof typeof asiaReviewedNames {
  return Object.hasOwn(asiaReviewedNames, code)
}
