// Reviewed country-linked Wikidata candidate components; see docs/geographic-data.md.
export const asiaWestNames = {
  AE: {
    female: [
      "Fatima", "Maryam", "A'isha", "Miriam", "Mona", "Reem",
      "Aisha", "Hind", "Mariam", "Najla", "Noura", "Afra",
      "Amal", "Amna", "Fatma", "Habiba", "Hamda", "Jamila",
      "Latifa", "Mahra", "Manal", "Najat", "Nora", "Sara",
      "Sarah", "Shamma", "Ahlam", "Aleena", "Alexandra", "Aliza",
      "Amani", "Amina", "Amira", "Anne-Cécile", "Aysha", "Diana",
      "Ebtisam", "Eliana", "Eman", "Haifa", "Hasseh", "Haya",
      "Hoor", "Hooria", "Houria", "Huda", "Ibtisam", "Jalila",
      "Khadija", "Lamya",
    ],
    male: [
      "Muhammad", "Ahmed", "Abdullah", "Ali", "Ahmad", "Mohamed",
      "Khaled", "Saeed", "Ibrahim", "Mohammad", "Abdulla", "Nasser",
      "Adel", "Omar", "Sultan", "Abd al-Rahman", "Hassan", "Juma",
      "Rashid", "Abd al-Aziz", "Faisal", "Abdelaziz", "Fahad", "Ismail",
      "Issa", "Jamal", "Salem", "Salih", "Waleed", "Abdurahman",
      "Adnan", "Chalifa", "Essa", "Khamis", "Mahmoud", "Habib",
      "Hamdan", "Hamza", "Hasan", "Hussein", "Mansour", "Marwan",
      "Mohammad-Ali", "Salim", "Sami", "Suhail", "Yousef", "Abbas",
      "Abd al-Qadir", "Abd al-Rahim",
    ],
    family: [
      "Al Dhaheri", "Al Qasimi", "Salem", "Al Maktoum", "Ali", "bin Sulayem",
      "Maktoum", "Qubaisi", "Abbas", "Abdulrahman", "Abulhoul", "Ahmed",
      "Al-Hamadi", "Al-Qubaisi", "Almheiri", "Ayyappan", "Hashimi", "Hassan",
      "Khamis", "Khan", "Rahmani", "Saeed", "Sajwani", "Shamsi",
      "Abdel-Shafi", "Abdelaziz", "Abdoleh", "Abdulhadi", "Abdulla", "Adel",
      "Al Ghurair", "Al Habtoor", "Al Mazroui", "Al Shamsi", "Al-Balushi", "Al-Baqqali",
      "Al-Futtaim", "Al-Khatri", "Al-Mubarak", "Al-Qubaysi", "al-Zarouni", "Alama",
      "Alameri", "Alkaabi", "Alqahtani", "Alsafar", "Ameri", "Amiri",
      "Anfar", "Ashraf", "Atiq", "Ayaz", "Badr", "Bagheri",
      "Bernardini", "Bishir", "Boubakri", "Boushaki", "Bujsaim", "Canedo",
    ],
  },
  AF: {
    female: [
      "Farida", "Fatima", "Kobra", "Zahra", "Khadija", "Nadia",
      "Soraya", "Suraya", "Zakia", "A'isha", "Adela", "Amina",
      "Aziza", "Bibi", "Diana", "Fahimeh", "Fariba", "Farzana",
      "Fereshta", "Fereshteh", "Humaira", "Jamila", "Layla", "Manizha",
      "Mary", "Maryam", "Nadiyah", "Naheed", "Nila", "Nilufar",
      "Parwin", "Rangina", "Roya", "Safia", "Sahar", "Samira",
      "Seema", "Shahla", "Sima", "Tahmina", "Zohra", "Alie",
      "Aliya", "Alka", "Amena", "Anahita", "Anarkali", "Anoush",
      "Asifa", "Asila",
    ],
    male: [
      "Mohammad", "Muhammad", "Ahmad", "Ali", "Abdullah", "Ahmed",
      "Amir", "Ibrahim", "Abd al-Rahman", "Mustafa", "Abd al-Qadir", "Anwar",
      "Daud", "Najibullah", "Abd al-Rahim", "Abdul Ghafoor", "Abdul Qayyum", "Jan",
      "Said", "Abd al-Hakim", "Abd al-Haqq", "Abd al-Salam", "Abdul Hadi", "Asadullah",
      "Azizullah", "Faiz", "Farid", "Hamid", "Ismail", "Karim",
      "Mohamed", "Sayed", "Abbas", "Abdul Ghani", "Abdul Jabbar", "Ajmal",
      "Assadullah", "Aziz", "David", "Ezatullah", "Habib", "Hakim",
      "Homayoun", "Rahim", "Safdar", "Ubaidullah", "Abdoul", "Abdul Baqi",
      "Abdul Bari", "Abdul Hai",
    ],
    family: [
      "Karzai", "Haqqani", "Khan", "Mohammad", "Sadat", "Wardak",
      "Zaland", "Ahmad", "Ahmadi", "Amin", "Mohammadi", "Nazari",
      "Omar", "Akhundzada", "Amini", "Amiri", "Ayubi", "Ebrahimi",
      "Habibi", "Hashimi", "Ludin", "Mujahid", "Noorzai", "Raḥimi",
      "Rahman", "Shah", "Wali", "Zadran", "Abdullah", "Afghani",
      "Ahmadzai", "Akbari", "Ali", "Aman", "Azimi", "Aziz",
      "Balkhi", "Barakzai", "Barmak", "Bayat", "Durrani", "Farid",
      "Gholami", "Haq", "Hassan", "Hassani", "Hosseini", "Ibrahimi",
      "Jafari", "Jahani", "Jalal", "Joya", "Karimi", "Khalid",
      "Khalili", "Najem", "Nikzad", "Noor", "Qaderi", "Rabbani",
    ],
  },
  BH: {
    female: [
      "Mariam", "Fatima", "Munira", "Amal", "Fawzia", "Lulwa",
      "Maha", "Maryam", "Nada", "Rehana", "Amna", "Assala",
      "Azza", "Dalal", "Dalila", "Ebtisam", "Esra", "Ghada",
      "Hajar", "Hamda", "Haya", "Huda", "Ibtisam", "Iman",
      "Jamila", "Jihad", "Kadeeja", "Kaltham", "Lamees", "Latifa",
      "Layla", "Mai", "Manal", "Masoomah", "May", "Mona",
      "Nadiyah", "Nahed", "Najla", "Noora",
    ],
    male: [
      "Muhammad", "Ali", "Ahmad", "Abdullah", "Ahmed", "Mohamed",
      "Ibrahim", "Salman", "Abd al-Rahman", "Hassan", "Adel", "Adnan",
      "Chalifa", "Faisal", "Rashid", "Ebrahim", "Isa", "Yusuf",
      "Hamad", "Omar", "Abbas", "Al-Sayed", "Hussein", "Issa",
      "Jamal", "Khaled", "Nasser", "Salih", "Sami", "Abraham",
      "Abu Bakr", "Badr", "Hamed", "Hasan", "Hisham", "Mahdi",
      "Mahmoud", "Mansour", "Mirza", "Saad", "Saeed", "Salah",
      "Abd al-Aziz", "Abd al-Hussein", "Abd al-Karīm", "Abd-an-Nabí", "Abdul Qayyum", "Abdul Razak",
      "Abdulhakim", "Abduljalil",
    ],
    family: [
      "Khalifa", "Ebrahim", "Jafar", "Fadhel", "Khamis", "Khawaja",
      "Madan", "Mandi", "Naser", "Nasir", "Salman", "Abbas",
      "Abbasi", "Abdulla", "Ahmed", "Ahmedi", "Al-Ansari", "Al-Bahrani",
      "Al-Dossari", "Al-Flaij", "al-Omari", "Al-Turk", "Alkhawaja", "Alomari",
      "Arafat", "Awaed", "Bader", "Behzad", "Borashid", "Burshid",
      "Haddad", "Hasan", "Hubail", "Husain", "Husseini",
    ],
  },
  IQ: {
    female: [
      "Huda", "Nadia", "Asma", "Lamia", "Sahar", "Samira",
      "Ahlam", "Amal", "Eman", "Esra", "Hanan", "Hayat",
      "Hind", "Maysoon", "Mona", "Alaa", "Amale", "Aseel",
      "Laila", "Mayada", "Shatha", "Abeer", "Adiba", "Aida",
      "Aliya", "Aliyah", "Āmina", "Areej", "Awatef", "Boutheina",
      "Dikra", "Faiza", "Farida", "Fatima", "Hana", "Heba",
      "Iman", "Josephine", "Khadija", "Leila", "Maha", "Manar",
      "Maryam", "Miriam", "Naziha", "Rabab", "Ragaa", "Rana",
      "Safia", "Salama",
    ],
    male: [
      "Muhammad", "Ali", "Ahmad", "Hussein", "Ibrahim", "Ahmed",
      "Hassan", "Saad", "Abbas", "Mahmoud", "Abdullah", "Adnan",
      "Mustafa", "Hamid", "Abd al-Karīm", "Haidar", "Ismail", "Mohamed",
      "Alaa", "Hashim", "Salih", "Taha", "Abd al-Rahman", "Ja'far",
      "Salah", "Waleed", "Hadi", "Jamal", "Mohammad", "Samir",
      "Jawad", "Karim", "Omar", "Amer", "Ayad", "Hikmat",
      "Kamal", "Mohannad", "Saeed", "Adil", "Jassem", "Kamil",
      "Mahdi", "Shakir", "Abdul Razak", "Amir", "Ammar", "Basil",
      "Fadhel", "Jamil",
    ],
    family: [
      "Al-Jabburi", "Al-Zubaidi", "al-Tai", "Hashimi", "Tamimi", "Hussein",
      "Al-Ani", "Al-Jannabi", "al-Rāwī", "Ibrahim", "Al-Bu Nasir", "Mohammed",
      "Al-Badri", "Al-Dulaymi", "Barzani", "Labidi", "Ahmad", "Al-Budeiri",
      "Al-Khafājī", "Barzanji", "Debbagh", "Hadithi", "Hassan", "Omar al-Ali",
      "Sadr", "Sūdānī", "Abbas", "Ahmed", "Al-Assadi", "Al-Hakeem",
      "Al-Kinani", "al-Maliki", "al-Qaysi", "Karim", "Mousavi", "Qasim",
      "Talabani", "Yousif", "Abboud", "Al dawod", "Al-Bahrani", "Al-Douri",
      "Al-Mamuri", "Al-Mash'hadani", "Ali", "Allawi", "Baban", "Chalabi",
      "Habib", "Hanna", "Hosseini", "Mahmoud", "Naciri", "Qazwini",
      "Saleh", "Salem", "Salih", "Shaker", "Zubaydi", "Abdel-Karim",
    ],
  },
  JO: {
    female: [
      "Lara", "Dana", "Iman", "Lina", "Rania", "Samira",
      "Abeer", "Amal", "Emily", "Faraḥ", "Maha", "Nada",
      "Nadia", "Samar", "Sarah", "Aida", "Aisha", "Diana",
      "Fadia", "Haifa", "Hanaa", "Hanan", "Haya", "Jumana",
      "Marah", "Nadiyah", "Natasha", "Nour", "Rana", "Reem",
      "Rima", "Sahar", "Salma", "Samah", "Sanae", "Shadia",
      "Sumaya", "Zain", "Zaynab", "Zina", "Ahlam", "Ala",
      "Alaa", "Aliya", "Amale", "Amani", "Areeb", "Areej",
      "Aseel", "Asia",
    ],
    male: [
      "Muhammad", "Ahmad", "Mohammad", "Ali", "Ibrahim", "Abdullah",
      "Mahmoud", "Omar", "Mohamed", "Ahmed", "Adnan", "Mustafa",
      "Jamal", "Samir", "Khaled", "Abd al-Rahman", "Amjad", "Nabil",
      "Yusuf", "Abd al-Karīm", "Anas", "Faisal", "Hussein", "Jamil",
      "Salih", "Zaid", "Abd al-Rahim", "Amin", "Marwan", "Mohannad",
      "Raed", "Rami", "Saeed", "Ayman", "Hassan", "Hisham",
      "Issam", "Kamel", "Nasser", "Nizār", "Saleh", "Tawfik",
      "Ziad", "Zouheir", "Abdallah", "Alaa", "Fahad", "Fayez",
      "Haitham", "Hamza",
    ],
    family: [
      "Barghouti", "Hamdan", "Malkawi", "Al-Masri", "Husseini", "Abu Ghazaleh",
      "Badran", "Haddad", "Kanan", "Majali", "Al-Kilani", "Bisisu",
      "Farah", "Hanoun", "Hassan", "Jazy", "Khatib", "Khouri",
      "Khoury", "Mahmoud", "Mansour", "Mashini", "Sayyid", "Talhouni",
      "Tamimi", "Zeid", "Abdul Hadi", "Aboubacar", "Abu Hijleh", "Abū Mayzar",
      "Abuarrah", "Al-Abadi", "Al-Khatib", "Al-Khuffash", "al-Omari", "al-Qaysi",
      "Al-Zoubi", "Ali", "Alshannik", "Aqel", "Atiyah", "Awad",
      "Awaed", "Barakat", "Bushnak", "Dajani", "Elias", "Erekat",
      "Habash", "Hadi", "Hadid", "Haikal", "Halabi", "Hashem",
      "Helal", "Ibrahim", "Jaber", "Jaradat", "Jarrah", "Jarrar",
    ],
  },
  KW: {
    female: [
      "Souad", "Basma", "Eman", "Hayat", "Najla", "Noura",
      "Reem", "Sara", "Sarah", "Shahd", "Abeer", "Abla",
      "Amal", "Amani", "Areej", "Aseel", "Asma", "Badriya",
      "Colette", "Dana", "Danah", "Elham", "Ema", "Fadwa",
      "Faiza", "Faraḥ", "Fatemah", "Fatima", "Fatma", "Feriel",
      "Ghaida", "Ghanima", "Halima", "Hanan", "Haya", "Heba",
      "Huda", "Ibtihal", "Iman", "Jamila", "Janna", "Laila",
      "Lara", "Laura", "Leila", "Malak", "Manal", "Maram",
      "Marguerite", "Maryam",
    ],
    male: [
      "Muhammad", "Ahmad", "Abdullah", "Ali", "Abdelaziz", "Badr",
      "Abd al-Aziz", "Abd al-Rahman", "Faisal", "Ahmed", "Nasser", "Mohammad",
      "Fahad", "Ibrahim", "Khaled", "Saad", "Mohamed", "Hussein",
      "Abd al-Muhsin", "Jassem", "Mishary", "Mubarak", "Waleed", "Abdul Razak",
      "Adel", "Salih", "Suleiman", "Yakub", "Ebrahim", "Jamal",
      "Saleh", "Salman", "Tarek", "Hamad", "Hassan", "Mahmoud",
      "Sami", "Yusuf", "Zaid", "Abd al-Karīm", "Adam", "Ammar",
      "Ayman", "Essa", "Gaber", "Habib", "Nabil", "Nawaf",
      "Omar", "Osama",
    ],
    family: [
      "Abdullah", "Al-Ateeqi", "Hussein", "Suleiman", "Al Mosawi", "Al Yaseen",
      "Al-Aazmi", "Al-Amiri", "Al-Awadi", "Al-Balushi", "Al-Baqsami", "Al-Haddad",
      "Al-Jarrah", "Al-Jassim", "Al-Kharafi", "Al-Khatib", "Al-Mutairi", "Al-Nafisi",
      "Al-Rumi", "Al-Sharekh", "Ali", "Marzouq", "Shammari", "Abbas",
      "Abdulla", "Abdulrahman", "Achour", "ad-Din", "Ahmed", "Ajab",
      "Akbar", "Al Hajji", "Al Hashem", "Al-Ahmad", "Al-Ajeery", "Al-Ansari",
      "Al-Awazem", "Al-Babtain", "Al-Baghli", "Al-Dulaymi", "Al-Ghabra", "Al-Ghais",
      "Al-Harbi", "al-Ḥashshāsh", "Al-Kadhimi", "Al-Mullah", "Al-Munis", "Al-Mutawaa",
      "Al-Muzayyin", "Al-Najjar", "Al-Nibari", "Al-Otaibi", "Al-Qabendi", "Al-Rowaished",
      "Al-Sabbah", "Al-Sabiay", "Al-Sanousi", "Al-Sharah", "Al-Shehri", "al-Tawil",
    ],
  },
  LB: {
    female: [
      "Maya", "Mona", "Nadine", "May", "Nadia", "Rania",
      "Leila", "Nada", "Amal", "Randa", "Rita", "Sara",
      "Aida", "Ghada", "Huda", "Karen", "Lina", "Maria",
      "Rima", "Rola", "Carla", "Carole", "Caroline", "Cynthia",
      "Diana", "Jana", "Lamia", "Layla", "Nour", "Sahar",
      "Aline", "Antoinette", "Carmen", "Lana", "Lara", "Maha",
      "Mai", "Mariam", "Mireille", "Nadiyah", "Nancy", "Pamela",
      "Sandra", "Yara", "Yasmine", "Yumna", "Zeina", "Aya",
      "Céline", "Dominique",
    ],
    male: [
      "Ali", "Muhammad", "Joseph", "Ahmad", "Michel", "Antoine",
      "Hassan", "Ibrahim", "Fouad", "Georges", "Samir", "Elias",
      "Hussein", "George", "Jean", "Abdullah", "Pierre", "Elie",
      "Salim", "Mohammad", "Ghassān", "Youssef", "Mohamad", "Waleed",
      "Ziad", "Farid", "Khalil", "Mahmoud", "Nabil", "Abbas",
      "Adnan", "Nicolas", "Omar", "Raymond", "Paul", "Philippe",
      "Fadi", "Issam", "Mohamed", "Ahmed", "Camille", "Marwan",
      "Robert", "Yusuf", "Amin", "Nadim", "Tony", "Charbel",
      "Charles", "Henri",
    ],
    family: [
      "Khoury", "Aoun", "Maalouf", "Gemayel", "Haddad", "Hayek",
      "Ghosn", "Khalil", "Chamoun", "Dagher", "Eddé", "Matar",
      "Daher", "Hamada", "Hammoud", "Ibrahim", "Lahoud", "Abū Shaqrā",
      "Barakat", "Jumblatt", "Mansour", "Saab", "Salamé", "Saleh",
      "Tabet", "Abboud", "Beydoun", "Boutros", "Farah", "Fares",
      "Harb", "Issa", "Majdalani", "Nasrallah", "Nassar", "Saadé",
      "Abdallah", "Al-Solh", "Arslan", "Assaf", "Awada", "Azar",
      "El-Khoury", "Farhat", "Feghali", "Ghandour", "Hakim", "Hamdan",
      "Hariri", "Jaber", "Karam", "Keyrouz", "Murr", "Najjar",
      "Rizk", "Safieddine", "Sarkis", "Sleiman", "Zein", "Akl",
    ],
  },
  PS: {
    female: [
      "Amal", "Fatima", "Laila", "Hanan", "Heba", "Lina",
      "Reem", "Wafaa", "Abeer", "Hind", "Jumana", "Malak",
      "Maysoon", "Mona", "Nada", "Nadine", "Rola", "Sahar",
      "Āmina", "Hana'a", "Marwa", "Maryam", "Rania", "Safa",
      "Salam", "Samah", "Samar", "Samira", "Sanaa", "Shatha",
      "Shereen", "Siham", "Widad", "A'isha", "Abir", "Ahlam",
      "Amina", "Basma", "Bayan", "Bushra", "Dalal", "Dania",
      "Dima", "Eman", "Esra", "Fadwa", "Faraḥ", "Feriel",
      "Haneen", "Huda",
    ],
    male: [
      "Muhammad", "Ahmad", "Ibrahim", "Mahmoud", "Mohamed", "Ali",
      "Yusuf", "Ahmed", "Waleed", "Abdullah", "Marwan", "Omar",
      "Hassan", "Jamal", "Saeed", "Samir", "Mustafa", "Abd al-Rahman",
      "Adnan", "Hussein", "Imad", "Nabil", "Nasser", "Ziad",
      "Ismail", "Jihad", "Hosam", "Issam", "Ashraf", "Ayad",
      "Ayman", "Mohammad", "Raed", "Yahya", "Yasser", "Magdi",
      "Salah", "Salih", "Salim", "Abd al-Rahim", "Alaa", "Anwar",
      "Fathi", "Khaled", "Khalil", "Naim", "Nizār", "Osama",
      "Rami", "Taysir",
    ],
    family: [
      "Barghouti", "Al-Masri", "Khatib", "Odeh", "Awad", "Arafat",
      "Mansour", "Salameh", "Abbas", "De'meh", "Husseini", "Jarrar",
      "Saleh", "Abu Daqqa", "Abu Hijleh", "Adwan", "Al-Najjar", "Bisisu",
      "Hamdan", "Jaradat", "Khoury", "Shawa", "Abu Ghazaleh", "Barakat",
      "Darwish", "Erekat", "Haniyeh", "Kaddoumi", "Matar", "Najjar",
      "Shtayyeh", "Tamimi", "Zaqout", "Abdelhamid", "Al-Budeiri", "Al-Kahlut",
      "Ali", "Assaf", "Awaed", "Badran", "Ghannam", "Ghunaym",
      "Habash", "Hussein", "Jaber", "Khalidi", "Khalil", "Mehanna",
      "Muheisen", "Nassar", "Rabah", "Shaath", "Shehadeh", "Siyam",
      "Tarazi", "Abdel-Shafi", "Aboubacar", "Abu Sittah", "Abughaush", "Al Balawi",
    ],
  },
  SA: {
    female: [
      "Sara", "Sarah", "Fatima", "Laila", "Mona", "Reem",
      "Haifa", "Huda", "Maha", "Noura", "Rania", "Samar",
      "A'isha", "Nadiyah", "Reema", "Amina", "Aseel", "Aziza",
      "Dalal", "Elham", "Ghada", "Halima", "Hana", "Hind",
      "Khairiah", "Latifa", "Lubna", "Mai", "Manal", "Mariam",
      "Maryam", "Norah", "Ruqayyah", "Samia", "Samira", "Thuraya",
      "Yara", "Abeer", "Adila", "Ahlam", "Aida", "Alaa",
      "Amale", "Amira", "Amy", "Asya", "Bayan", "Dalia",
      "Dalma", "Dania",
    ],
    male: [
      "Muhammad", "Abdullah", "Ahmad", "Ali", "Abd al-Aziz", "Abd al-Rahman",
      "Ahmed", "Ibrahim", "Abdelaziz", "Fahad", "Faisal", "Salih",
      "Khaled", "Badr", "Saeed", "Hassan", "Nasser", "Saad",
      "Waleed", "Hussein", "Turki", "Salman", "Mansour", "Mohamed",
      "Mohammad", "Abd al-Karīm", "Omar", "Sultan", "Yahya", "Abd al-Muhsin",
      "Saud", "Suleiman", "Sami", "Adel", "Adnan", "Bandar",
      "Mohannad", "Hamad", "Hamza", "Hisham", "Mahmoud", "Majed",
      "Mustafa", "Saleh", "Talal", "Abd al-Qadir", "Jamal", "Osama",
      "Rashid", "Abbas",
    ],
    family: [
      "Al-Harbi", "Shehri", "Alqahtani", "Al-Shehri", "Alghamdi", "Al-Qarni",
      "Al ash-Sheikh", "Al-Otaibi", "Mohammed", "Al-Shamani", "Abdulrahman", "Al dawod",
      "Al-Bishi", "Al-Dossari", "Al-Muwallad", "Al-Saif", "Attar", "Hamad",
      "Jamjoum", "Juffali", "Khan", "Khashoggi", "Ojjeh", "Salem",
      "Abdulaziz", "Abu Sulayman", "Al Gosaibi", "Al-Abbasi", "Al-Assiry", "Al-Barakah",
      "Al-Ghannam", "Al-Jassim", "Al-Johani", "Al-Saud", "Al-Shaibi", "Al-Sudhan",
      "Al-Tayyar", "Al-Tuwaijri", "Al-Wahaibi", "Amin", "Dawasir", "Elrashidy",
      "Ghareeb", "Hariri", "Hashimi", "Hawsawi", "Hazazi", "Jassem",
      "Kadi", "Mansour", "Mohamed", "Omran", "Saleem", "Shahwan",
      "Tamimi", "Turki", "Zaid", "Zakzouk", "Abbas", "Abboud",
    ],
  },
  SY: {
    female: [
      "Zeynep", "Fatima", "A'isha", "Sara", "Khadija", "Leila",
      "Lina", "Maha", "Asma", "Huda", "Nadia", "Rima",
      "Āmina", "Heba", "Hind", "Malak", "Maram", "Mary",
      "Mayada", "Rana", "Rania", "Reem", "Ruqayyah", "Wafaa",
      "Amal", "Amani", "Amira", "Ayşe", "Bushra", "Dana",
      "Diana", "Dima", "Fadwa", "Ghada", "Habiba", "Ilham",
      "Jenny", "Jumana", "Khatun", "Khouloud", "Latifa", "Layla",
      "Maria", "Miriam", "Mona", "Nadine", "Nahed", "Najah",
      "Nancy", "Nour",
    ],
    male: [
      "Muhammad", "Ahmad", "Ali", "Abdullah", "Omar", "Adnan",
      "Ibrahim", "Mahmoud", "Mohammad", "Mustafa", "Joseph", "Abd al-Rahman",
      "Hassan", "Mohamed", "Abd al-Qadir", "Mohamad", "George", "Ghassān",
      "Marwan", "Hussein", "Elias", "Saeed", "Abd al-Karīm", "Georges",
      "Khaled", "Nabil", "Yusuf", "Haitham", "Issam", "Riad",
      "Ahmed", "Anas", "Anwar", "Ayman", "Ḥassān", "Jamal",
      "Jamil", "Michel", "Nasser", "Nizār", "Osama", "Waleed",
      "Bassam", "Hisham", "Ignatius", "Kamal", "Sami", "Ignace",
      "Imad", "Mohamed Khair",
    ],
    family: [
      "Khatib", "Al-Maqdisi", "Al-Atassi", "Haddad", "Khoury", "Al Asad",
      "Ali", "Assad", "Issa", "Khalil", "Youssef", "Al-Masri",
      "Barakat", "Khayat", "Malluhi", "Nasser", "Abboud", "Ahmad",
      "Al Hassani", "Al-Atrash", "Al-Khatib", "Bayṭār", "Ghazi", "Hussein",
      "Kabbani", "Khani", "Martini", "Murad", "Omar al-Ali", "Salem",
      "Abdelaziz", "Abdullah", "Abedin", "Abu Ghudda", "Akkad", "Al-Baba",
      "al-Hassan", "Al-Qudsi", "Al-Rayyis", "al-Sabbagh", "Al-Sawaf", "al-Sibai",
      "Antaki", "Arnaoot", "Attar", "Bader", "Baker", "Daoud",
      "Elias", "Farfūr", "Hamada", "Harb", "Hariri", "Hassan",
      "Ibrahim", "Ismail", "Jarrah", "Kayyali", "Khalifa", "Mahmoud",
    ],
  },
  YE: {
    female: [
      "Fatima", "Amal", "Amat", "Bushra", "Hoda", "Huda",
      "Khadija", "Nadiyah", "Alaa", "Āmina", "Ashwaq", "Asmahan",
      "Azizah", "Bouchra", "Bracha", "Elham", "Emy", "Eqbal",
      "Farida", "Ghada", "Ghaleb", "Hana", "Hind", "Hooria",
      "Ibtisam", "Iman", "Insaf", "Intisar", "Isra", "Jamila",
      "Jamilah", "Laila", "Madiha", "Maha", "Maysoon", "Mimouna",
      "Mona", "Nabila", "Rana", "Reem", "Reema", "Sabah",
      "Safa", "Safiye", "Sali", "Samira", "Sara", "Sarah",
      "Shatha", "Su'ad",
    ],
    male: [
      "Muhammad", "Ali", "Ahmad", "Abdullah", "Abd al-Rahman", "Yahya",
      "Abd al-Karīm", "Ahmed", "Ibrahim", "Abd al-Aziz", "Abdelaziz", "Saeed",
      "Mohamed", "Nasser", "Faisal", "Saleh", "Abdul Malik", "Fuad",
      "Khaled", "Abu Bakr", "Hamoud", "Hassan", "Jamal", "Mohammad",
      "Abd al-Qadir", "Abd al-Salam", "Hussein", "Mahmoud", "Nabil", "Omar",
      "Abd Rabbo", "Abdul Ghani", "Abdul Razak", "Adel", "Hameed", "Hasan",
      "Hashim", "Marwan", "Samir", "Waleed", "Yosef", "Yousef",
      "Abdul Bari", "Adil", "Adnan", "Amr", "Anwar", "Badr",
      "Basheer", "Fathi",
    ],
    family: [
      "al-Ahmar", "Al-Eryani", "al-Mutawakkil", "Damaj", "Al-Awlaki", "Ahmed",
      "Al-Ahdal", "Alawi", "Bakr", "Din", "Fathi", "Gamal",
      "Karman", "Khalil", "Omar", "Sarum", "Abdo", "Abdulhak",
      "Afif", "Aklan", "Al-Aini", "Al-Alfi", "Al-Alwani", "Al-Ansi",
      "Al-Awadi", "Al-Badawi", "Al-bahri", "Al-Dailami", "al-Daylami", "Al-Ghaili",
      "Al-Ghimary", "al-Hammadi", "Al-Harthi", "Al-Himyari", "Al-hubaishi", "Al-Jabri",
      "Al-Khatib", "Al-Kokabany", "Al-Lawzi", "al-Marouni", "al-Muhatwari", "Al-murtadha",
      "al-Mutahhar", "al-Omari", "Al-Qarni", "al-Qirbi", "Al-Qrize", "al-Saadi",
      "Al-Shamiri", "al-Sharafi", "Al-Wazir", "Al-yafaee", "Al-Zubaidi", "Alimi",
      "Alwan", "Amer", "Amran", "Bakker", "Basha", "Bassera",
    ],
  },
} as const

export function isAsiaWestCountry(code: string): code is keyof typeof asiaWestNames {
  return Object.hasOwn(asiaWestNames, code)
}
