// Source snapshot: iso-3166@4.4.0 and libphonenumber-js@1.13.14; see docs/geographic-data.md.
export const registryEdition = '2026-09-24'
export const countryData = [
  {"code":"AD","alpha3":"AND","numeric":"020","name":"Andorra","callingCode":"+376","generation":"eligible"},
  {"code":"AE","alpha3":"ARE","numeric":"784","name":"United Arab Emirates","callingCode":"+971","generation":"eligible"},
  {"code":"AF","alpha3":"AFG","numeric":"004","name":"Afghanistan","callingCode":"+93","generation":"eligible"},
  {"code":"AG","alpha3":"ATG","numeric":"028","name":"Antigua and Barbuda","callingCode":"+1","generation":"eligible"},
  {"code":"AI","alpha3":"AIA","numeric":"660","name":"Anguilla","callingCode":"+1","generation":"eligible"},
  {"code":"AL","alpha3":"ALB","numeric":"008","name":"Albania","callingCode":"+355","generation":"eligible"},
  {"code":"AM","alpha3":"ARM","numeric":"051","name":"Armenia","callingCode":"+374","generation":"eligible"},
  {"code":"AO","alpha3":"AGO","numeric":"024","name":"Angola","callingCode":"+244","generation":"eligible"},
  {"code":"AQ","alpha3":"ATA","numeric":"010","name":"Antarctica","callingCode":null,"generation":"unavailable"},
  {"code":"AR","alpha3":"ARG","numeric":"032","name":"Argentina","callingCode":"+54","generation":"eligible"},
  {"code":"AS","alpha3":"ASM","numeric":"016","name":"American Samoa","callingCode":"+1","generation":"eligible"},
  {"code":"AT","alpha3":"AUT","numeric":"040","name":"Austria","callingCode":"+43","generation":"eligible"},
  {"code":"AU","alpha3":"AUS","numeric":"036","name":"Australia","callingCode":"+61","generation":"eligible"},
  {"code":"AW","alpha3":"ABW","numeric":"533","name":"Aruba","callingCode":"+297","generation":"eligible"},
  {"code":"AX","alpha3":"ALA","numeric":"248","name":"Åland Islands","callingCode":"+358","generation":"eligible"},
  {"code":"AZ","alpha3":"AZE","numeric":"031","name":"Azerbaijan","callingCode":"+994","generation":"eligible"},
  {"code":"BA","alpha3":"BIH","numeric":"070","name":"Bosnia and Herzegovina","callingCode":"+387","generation":"eligible"},
  {"code":"BB","alpha3":"BRB","numeric":"052","name":"Barbados","callingCode":"+1","generation":"eligible"},
  {"code":"BD","alpha3":"BGD","numeric":"050","name":"Bangladesh","callingCode":"+880","generation":"eligible"},
  {"code":"BE","alpha3":"BEL","numeric":"056","name":"Belgium","callingCode":"+32","generation":"eligible"},
  {"code":"BF","alpha3":"BFA","numeric":"854","name":"Burkina Faso","callingCode":"+226","generation":"eligible"},
  {"code":"BG","alpha3":"BGR","numeric":"100","name":"Bulgaria","callingCode":"+359","generation":"eligible"},
  {"code":"BH","alpha3":"BHR","numeric":"048","name":"Bahrain","callingCode":"+973","generation":"eligible"},
  {"code":"BI","alpha3":"BDI","numeric":"108","name":"Burundi","callingCode":"+257","generation":"eligible"},
  {"code":"BJ","alpha3":"BEN","numeric":"204","name":"Benin","callingCode":"+229","generation":"eligible"},
  {"code":"BL","alpha3":"BLM","numeric":"652","name":"Saint Barthélemy","callingCode":"+590","generation":"eligible"},
  {"code":"BM","alpha3":"BMU","numeric":"060","name":"Bermuda","callingCode":"+1","generation":"eligible"},
  {"code":"BN","alpha3":"BRN","numeric":"096","name":"Brunei Darussalam","callingCode":"+673","generation":"eligible"},
  {"code":"BO","alpha3":"BOL","numeric":"068","name":"Bolivia, Plurinational State of","callingCode":"+591","generation":"eligible"},
  {"code":"BQ","alpha3":"BES","numeric":"535","name":"Bonaire, Sint Eustatius and Saba","callingCode":"+599","generation":"eligible"},
  {"code":"BR","alpha3":"BRA","numeric":"076","name":"Brazil","callingCode":"+55","generation":"eligible"},
  {"code":"BS","alpha3":"BHS","numeric":"044","name":"Bahamas","callingCode":"+1","generation":"eligible"},
  {"code":"BT","alpha3":"BTN","numeric":"064","name":"Bhutan","callingCode":"+975","generation":"eligible"},
  {"code":"BV","alpha3":"BVT","numeric":"074","name":"Bouvet Island","callingCode":null,"generation":"unavailable"},
  {"code":"BW","alpha3":"BWA","numeric":"072","name":"Botswana","callingCode":"+267","generation":"eligible"},
  {"code":"BY","alpha3":"BLR","numeric":"112","name":"Belarus","callingCode":"+375","generation":"eligible"},
  {"code":"BZ","alpha3":"BLZ","numeric":"084","name":"Belize","callingCode":"+501","generation":"eligible"},
  {"code":"CA","alpha3":"CAN","numeric":"124","name":"Canada","callingCode":"+1","generation":"eligible"},
  {"code":"CC","alpha3":"CCK","numeric":"166","name":"Cocos (Keeling) Islands","callingCode":"+61","generation":"eligible"},
  {"code":"CD","alpha3":"COD","numeric":"180","name":"Congo, Democratic Republic of the","callingCode":"+243","generation":"eligible"},
  {"code":"CF","alpha3":"CAF","numeric":"140","name":"Central African Republic","callingCode":"+236","generation":"eligible"},
  {"code":"CG","alpha3":"COG","numeric":"178","name":"Congo","callingCode":"+242","generation":"eligible"},
  {"code":"CH","alpha3":"CHE","numeric":"756","name":"Switzerland","callingCode":"+41","generation":"eligible"},
  {"code":"CI","alpha3":"CIV","numeric":"384","name":"Côte d'Ivoire","callingCode":"+225","generation":"eligible"},
  {"code":"CK","alpha3":"COK","numeric":"184","name":"Cook Islands","callingCode":"+682","generation":"eligible"},
  {"code":"CL","alpha3":"CHL","numeric":"152","name":"Chile","callingCode":"+56","generation":"eligible"},
  {"code":"CM","alpha3":"CMR","numeric":"120","name":"Cameroon","callingCode":"+237","generation":"eligible"},
  {"code":"CN","alpha3":"CHN","numeric":"156","name":"China","callingCode":"+86","generation":"eligible"},
  {"code":"CO","alpha3":"COL","numeric":"170","name":"Colombia","callingCode":"+57","generation":"eligible"},
  {"code":"CR","alpha3":"CRI","numeric":"188","name":"Costa Rica","callingCode":"+506","generation":"eligible"},
  {"code":"CU","alpha3":"CUB","numeric":"192","name":"Cuba","callingCode":"+53","generation":"eligible"},
  {"code":"CV","alpha3":"CPV","numeric":"132","name":"Cabo Verde","callingCode":"+238","generation":"eligible"},
  {"code":"CW","alpha3":"CUW","numeric":"531","name":"Curaçao","callingCode":"+599","generation":"eligible"},
  {"code":"CX","alpha3":"CXR","numeric":"162","name":"Christmas Island","callingCode":"+61","generation":"eligible"},
  {"code":"CY","alpha3":"CYP","numeric":"196","name":"Cyprus","callingCode":"+357","generation":"eligible"},
  {"code":"CZ","alpha3":"CZE","numeric":"203","name":"Czechia","callingCode":"+420","generation":"eligible"},
  {"code":"DE","alpha3":"DEU","numeric":"276","name":"Germany","callingCode":"+49","generation":"eligible"},
  {"code":"DJ","alpha3":"DJI","numeric":"262","name":"Djibouti","callingCode":"+253","generation":"eligible"},
  {"code":"DK","alpha3":"DNK","numeric":"208","name":"Denmark","callingCode":"+45","generation":"eligible"},
  {"code":"DM","alpha3":"DMA","numeric":"212","name":"Dominica","callingCode":"+1","generation":"eligible"},
  {"code":"DO","alpha3":"DOM","numeric":"214","name":"Dominican Republic","callingCode":"+1","generation":"eligible"},
  {"code":"DZ","alpha3":"DZA","numeric":"012","name":"Algeria","callingCode":"+213","generation":"eligible"},
  {"code":"EC","alpha3":"ECU","numeric":"218","name":"Ecuador","callingCode":"+593","generation":"eligible"},
  {"code":"EE","alpha3":"EST","numeric":"233","name":"Estonia","callingCode":"+372","generation":"eligible"},
  {"code":"EG","alpha3":"EGY","numeric":"818","name":"Egypt","callingCode":"+20","generation":"eligible"},
  {"code":"EH","alpha3":"ESH","numeric":"732","name":"Western Sahara","callingCode":"+212","generation":"eligible"},
  {"code":"ER","alpha3":"ERI","numeric":"232","name":"Eritrea","callingCode":"+291","generation":"eligible"},
  {"code":"ES","alpha3":"ESP","numeric":"724","name":"Spain","callingCode":"+34","generation":"eligible"},
  {"code":"ET","alpha3":"ETH","numeric":"231","name":"Ethiopia","callingCode":"+251","generation":"eligible"},
  {"code":"FI","alpha3":"FIN","numeric":"246","name":"Finland","callingCode":"+358","generation":"eligible"},
  {"code":"FJ","alpha3":"FJI","numeric":"242","name":"Fiji","callingCode":"+679","generation":"eligible"},
  {"code":"FK","alpha3":"FLK","numeric":"238","name":"Falkland Islands (Malvinas)","callingCode":"+500","generation":"eligible"},
  {"code":"FM","alpha3":"FSM","numeric":"583","name":"Micronesia, Federated States of","callingCode":"+691","generation":"eligible"},
  {"code":"FO","alpha3":"FRO","numeric":"234","name":"Faroe Islands","callingCode":"+298","generation":"eligible"},
  {"code":"FR","alpha3":"FRA","numeric":"250","name":"France","callingCode":"+33","generation":"eligible"},
  {"code":"GA","alpha3":"GAB","numeric":"266","name":"Gabon","callingCode":"+241","generation":"eligible"},
  {"code":"GB","alpha3":"GBR","numeric":"826","name":"United Kingdom of Great Britain and Northern Ireland","callingCode":"+44","generation":"eligible"},
  {"code":"GD","alpha3":"GRD","numeric":"308","name":"Grenada","callingCode":"+1","generation":"eligible"},
  {"code":"GE","alpha3":"GEO","numeric":"268","name":"Georgia","callingCode":"+995","generation":"eligible"},
  {"code":"GF","alpha3":"GUF","numeric":"254","name":"French Guiana","callingCode":"+594","generation":"eligible"},
  {"code":"GG","alpha3":"GGY","numeric":"831","name":"Guernsey","callingCode":"+44","generation":"eligible"},
  {"code":"GH","alpha3":"GHA","numeric":"288","name":"Ghana","callingCode":"+233","generation":"eligible"},
  {"code":"GI","alpha3":"GIB","numeric":"292","name":"Gibraltar","callingCode":"+350","generation":"eligible"},
  {"code":"GL","alpha3":"GRL","numeric":"304","name":"Greenland","callingCode":"+299","generation":"eligible"},
  {"code":"GM","alpha3":"GMB","numeric":"270","name":"Gambia","callingCode":"+220","generation":"eligible"},
  {"code":"GN","alpha3":"GIN","numeric":"324","name":"Guinea","callingCode":"+224","generation":"eligible"},
  {"code":"GP","alpha3":"GLP","numeric":"312","name":"Guadeloupe","callingCode":"+590","generation":"eligible"},
  {"code":"GQ","alpha3":"GNQ","numeric":"226","name":"Equatorial Guinea","callingCode":"+240","generation":"eligible"},
  {"code":"GR","alpha3":"GRC","numeric":"300","name":"Greece","callingCode":"+30","generation":"eligible"},
  {"code":"GS","alpha3":"SGS","numeric":"239","name":"South Georgia and the South Sandwich Islands","callingCode":null,"generation":"unavailable"},
  {"code":"GT","alpha3":"GTM","numeric":"320","name":"Guatemala","callingCode":"+502","generation":"eligible"},
  {"code":"GU","alpha3":"GUM","numeric":"316","name":"Guam","callingCode":"+1","generation":"eligible"},
  {"code":"GW","alpha3":"GNB","numeric":"624","name":"Guinea-Bissau","callingCode":"+245","generation":"eligible"},
  {"code":"GY","alpha3":"GUY","numeric":"328","name":"Guyana","callingCode":"+592","generation":"eligible"},
  {"code":"HK","alpha3":"HKG","numeric":"344","name":"Hong Kong","callingCode":"+852","generation":"eligible"},
  {"code":"HM","alpha3":"HMD","numeric":"334","name":"Heard Island and McDonald Islands","callingCode":null,"generation":"unavailable"},
  {"code":"HN","alpha3":"HND","numeric":"340","name":"Honduras","callingCode":"+504","generation":"eligible"},
  {"code":"HR","alpha3":"HRV","numeric":"191","name":"Croatia","callingCode":"+385","generation":"eligible"},
  {"code":"HT","alpha3":"HTI","numeric":"332","name":"Haiti","callingCode":"+509","generation":"eligible"},
  {"code":"HU","alpha3":"HUN","numeric":"348","name":"Hungary","callingCode":"+36","generation":"eligible"},
  {"code":"ID","alpha3":"IDN","numeric":"360","name":"Indonesia","callingCode":"+62","generation":"eligible"},
  {"code":"IE","alpha3":"IRL","numeric":"372","name":"Ireland","callingCode":"+353","generation":"eligible"},
  {"code":"IL","alpha3":"ISR","numeric":"376","name":"Israel","callingCode":"+972","generation":"eligible"},
  {"code":"IM","alpha3":"IMN","numeric":"833","name":"Isle of Man","callingCode":"+44","generation":"eligible"},
  {"code":"IN","alpha3":"IND","numeric":"356","name":"India","callingCode":"+91","generation":"eligible"},
  {"code":"IO","alpha3":"IOT","numeric":"086","name":"British Indian Ocean Territory","callingCode":"+246","generation":"unavailable"},
  {"code":"IQ","alpha3":"IRQ","numeric":"368","name":"Iraq","callingCode":"+964","generation":"eligible"},
  {"code":"IR","alpha3":"IRN","numeric":"364","name":"Iran, Islamic Republic of","callingCode":"+98","generation":"eligible"},
  {"code":"IS","alpha3":"ISL","numeric":"352","name":"Iceland","callingCode":"+354","generation":"eligible"},
  {"code":"IT","alpha3":"ITA","numeric":"380","name":"Italy","callingCode":"+39","generation":"eligible"},
  {"code":"JE","alpha3":"JEY","numeric":"832","name":"Jersey","callingCode":"+44","generation":"eligible"},
  {"code":"JM","alpha3":"JAM","numeric":"388","name":"Jamaica","callingCode":"+1","generation":"eligible"},
  {"code":"JO","alpha3":"JOR","numeric":"400","name":"Jordan","callingCode":"+962","generation":"eligible"},
  {"code":"JP","alpha3":"JPN","numeric":"392","name":"Japan","callingCode":"+81","generation":"eligible"},
  {"code":"KE","alpha3":"KEN","numeric":"404","name":"Kenya","callingCode":"+254","generation":"eligible"},
  {"code":"KG","alpha3":"KGZ","numeric":"417","name":"Kyrgyzstan","callingCode":"+996","generation":"eligible"},
  {"code":"KH","alpha3":"KHM","numeric":"116","name":"Cambodia","callingCode":"+855","generation":"eligible"},
  {"code":"KI","alpha3":"KIR","numeric":"296","name":"Kiribati","callingCode":"+686","generation":"eligible"},
  {"code":"KM","alpha3":"COM","numeric":"174","name":"Comoros","callingCode":"+269","generation":"eligible"},
  {"code":"KN","alpha3":"KNA","numeric":"659","name":"Saint Kitts and Nevis","callingCode":"+1","generation":"eligible"},
  {"code":"KP","alpha3":"PRK","numeric":"408","name":"Korea, Democratic People's Republic of","callingCode":"+850","generation":"eligible"},
  {"code":"KR","alpha3":"KOR","numeric":"410","name":"Korea, Republic of","callingCode":"+82","generation":"eligible"},
  {"code":"KW","alpha3":"KWT","numeric":"414","name":"Kuwait","callingCode":"+965","generation":"eligible"},
  {"code":"KY","alpha3":"CYM","numeric":"136","name":"Cayman Islands","callingCode":"+1","generation":"eligible"},
  {"code":"KZ","alpha3":"KAZ","numeric":"398","name":"Kazakhstan","callingCode":"+7","generation":"eligible"},
  {"code":"LA","alpha3":"LAO","numeric":"418","name":"Lao People's Democratic Republic","callingCode":"+856","generation":"eligible"},
  {"code":"LB","alpha3":"LBN","numeric":"422","name":"Lebanon","callingCode":"+961","generation":"eligible"},
  {"code":"LC","alpha3":"LCA","numeric":"662","name":"Saint Lucia","callingCode":"+1","generation":"eligible"},
  {"code":"LI","alpha3":"LIE","numeric":"438","name":"Liechtenstein","callingCode":"+423","generation":"eligible"},
  {"code":"LK","alpha3":"LKA","numeric":"144","name":"Sri Lanka","callingCode":"+94","generation":"eligible"},
  {"code":"LR","alpha3":"LBR","numeric":"430","name":"Liberia","callingCode":"+231","generation":"eligible"},
  {"code":"LS","alpha3":"LSO","numeric":"426","name":"Lesotho","callingCode":"+266","generation":"eligible"},
  {"code":"LT","alpha3":"LTU","numeric":"440","name":"Lithuania","callingCode":"+370","generation":"eligible"},
  {"code":"LU","alpha3":"LUX","numeric":"442","name":"Luxembourg","callingCode":"+352","generation":"eligible"},
  {"code":"LV","alpha3":"LVA","numeric":"428","name":"Latvia","callingCode":"+371","generation":"eligible"},
  {"code":"LY","alpha3":"LBY","numeric":"434","name":"Libya","callingCode":"+218","generation":"eligible"},
  {"code":"MA","alpha3":"MAR","numeric":"504","name":"Morocco","callingCode":"+212","generation":"eligible"},
  {"code":"MC","alpha3":"MCO","numeric":"492","name":"Monaco","callingCode":"+377","generation":"eligible"},
  {"code":"MD","alpha3":"MDA","numeric":"498","name":"Moldova, Republic of","callingCode":"+373","generation":"eligible"},
  {"code":"ME","alpha3":"MNE","numeric":"499","name":"Montenegro","callingCode":"+382","generation":"eligible"},
  {"code":"MF","alpha3":"MAF","numeric":"663","name":"Saint Martin (French part)","callingCode":"+590","generation":"eligible"},
  {"code":"MG","alpha3":"MDG","numeric":"450","name":"Madagascar","callingCode":"+261","generation":"eligible"},
  {"code":"MH","alpha3":"MHL","numeric":"584","name":"Marshall Islands","callingCode":"+692","generation":"eligible"},
  {"code":"MK","alpha3":"MKD","numeric":"807","name":"North Macedonia","callingCode":"+389","generation":"eligible"},
  {"code":"ML","alpha3":"MLI","numeric":"466","name":"Mali","callingCode":"+223","generation":"eligible"},
  {"code":"MM","alpha3":"MMR","numeric":"104","name":"Myanmar","callingCode":"+95","generation":"eligible"},
  {"code":"MN","alpha3":"MNG","numeric":"496","name":"Mongolia","callingCode":"+976","generation":"eligible"},
  {"code":"MO","alpha3":"MAC","numeric":"446","name":"Macao","callingCode":"+853","generation":"eligible"},
  {"code":"MP","alpha3":"MNP","numeric":"580","name":"Northern Mariana Islands","callingCode":"+1","generation":"eligible"},
  {"code":"MQ","alpha3":"MTQ","numeric":"474","name":"Martinique","callingCode":"+596","generation":"eligible"},
  {"code":"MR","alpha3":"MRT","numeric":"478","name":"Mauritania","callingCode":"+222","generation":"eligible"},
  {"code":"MS","alpha3":"MSR","numeric":"500","name":"Montserrat","callingCode":"+1","generation":"eligible"},
  {"code":"MT","alpha3":"MLT","numeric":"470","name":"Malta","callingCode":"+356","generation":"eligible"},
  {"code":"MU","alpha3":"MUS","numeric":"480","name":"Mauritius","callingCode":"+230","generation":"eligible"},
  {"code":"MV","alpha3":"MDV","numeric":"462","name":"Maldives","callingCode":"+960","generation":"eligible"},
  {"code":"MW","alpha3":"MWI","numeric":"454","name":"Malawi","callingCode":"+265","generation":"eligible"},
  {"code":"MX","alpha3":"MEX","numeric":"484","name":"Mexico","callingCode":"+52","generation":"eligible"},
  {"code":"MY","alpha3":"MYS","numeric":"458","name":"Malaysia","callingCode":"+60","generation":"eligible"},
  {"code":"MZ","alpha3":"MOZ","numeric":"508","name":"Mozambique","callingCode":"+258","generation":"eligible"},
  {"code":"NA","alpha3":"NAM","numeric":"516","name":"Namibia","callingCode":"+264","generation":"eligible"},
  {"code":"NC","alpha3":"NCL","numeric":"540","name":"New Caledonia","callingCode":"+687","generation":"eligible"},
  {"code":"NE","alpha3":"NER","numeric":"562","name":"Niger","callingCode":"+227","generation":"eligible"},
  {"code":"NF","alpha3":"NFK","numeric":"574","name":"Norfolk Island","callingCode":"+672","generation":"eligible"},
  {"code":"NG","alpha3":"NGA","numeric":"566","name":"Nigeria","callingCode":"+234","generation":"eligible"},
  {"code":"NI","alpha3":"NIC","numeric":"558","name":"Nicaragua","callingCode":"+505","generation":"eligible"},
  {"code":"NL","alpha3":"NLD","numeric":"528","name":"Netherlands, Kingdom of the","callingCode":"+31","generation":"eligible"},
  {"code":"NO","alpha3":"NOR","numeric":"578","name":"Norway","callingCode":"+47","generation":"eligible"},
  {"code":"NP","alpha3":"NPL","numeric":"524","name":"Nepal","callingCode":"+977","generation":"eligible"},
  {"code":"NR","alpha3":"NRU","numeric":"520","name":"Nauru","callingCode":"+674","generation":"eligible"},
  {"code":"NU","alpha3":"NIU","numeric":"570","name":"Niue","callingCode":"+683","generation":"eligible"},
  {"code":"NZ","alpha3":"NZL","numeric":"554","name":"New Zealand","callingCode":"+64","generation":"eligible"},
  {"code":"OM","alpha3":"OMN","numeric":"512","name":"Oman","callingCode":"+968","generation":"eligible"},
  {"code":"PA","alpha3":"PAN","numeric":"591","name":"Panama","callingCode":"+507","generation":"eligible"},
  {"code":"PE","alpha3":"PER","numeric":"604","name":"Peru","callingCode":"+51","generation":"eligible"},
  {"code":"PF","alpha3":"PYF","numeric":"258","name":"French Polynesia","callingCode":"+689","generation":"eligible"},
  {"code":"PG","alpha3":"PNG","numeric":"598","name":"Papua New Guinea","callingCode":"+675","generation":"eligible"},
  {"code":"PH","alpha3":"PHL","numeric":"608","name":"Philippines","callingCode":"+63","generation":"eligible"},
  {"code":"PK","alpha3":"PAK","numeric":"586","name":"Pakistan","callingCode":"+92","generation":"eligible"},
  {"code":"PL","alpha3":"POL","numeric":"616","name":"Poland","callingCode":"+48","generation":"eligible"},
  {"code":"PM","alpha3":"SPM","numeric":"666","name":"Saint Pierre and Miquelon","callingCode":"+508","generation":"eligible"},
  {"code":"PN","alpha3":"PCN","numeric":"612","name":"Pitcairn","callingCode":null,"generation":"eligible"},
  {"code":"PR","alpha3":"PRI","numeric":"630","name":"Puerto Rico","callingCode":"+1","generation":"eligible"},
  {"code":"PS","alpha3":"PSE","numeric":"275","name":"Palestine, State of","callingCode":"+970","generation":"eligible"},
  {"code":"PT","alpha3":"PRT","numeric":"620","name":"Portugal","callingCode":"+351","generation":"eligible"},
  {"code":"PW","alpha3":"PLW","numeric":"585","name":"Palau","callingCode":"+680","generation":"eligible"},
  {"code":"PY","alpha3":"PRY","numeric":"600","name":"Paraguay","callingCode":"+595","generation":"eligible"},
  {"code":"QA","alpha3":"QAT","numeric":"634","name":"Qatar","callingCode":"+974","generation":"eligible"},
  {"code":"RE","alpha3":"REU","numeric":"638","name":"Réunion","callingCode":"+262","generation":"eligible"},
  {"code":"RO","alpha3":"ROU","numeric":"642","name":"Romania","callingCode":"+40","generation":"eligible"},
  {"code":"RS","alpha3":"SRB","numeric":"688","name":"Serbia","callingCode":"+381","generation":"eligible"},
  {"code":"RU","alpha3":"RUS","numeric":"643","name":"Russian Federation","callingCode":"+7","generation":"eligible"},
  {"code":"RW","alpha3":"RWA","numeric":"646","name":"Rwanda","callingCode":"+250","generation":"eligible"},
  {"code":"SA","alpha3":"SAU","numeric":"682","name":"Saudi Arabia","callingCode":"+966","generation":"eligible"},
  {"code":"SB","alpha3":"SLB","numeric":"090","name":"Solomon Islands","callingCode":"+677","generation":"eligible"},
  {"code":"SC","alpha3":"SYC","numeric":"690","name":"Seychelles","callingCode":"+248","generation":"eligible"},
  {"code":"SD","alpha3":"SDN","numeric":"729","name":"Sudan","callingCode":"+249","generation":"eligible"},
  {"code":"SE","alpha3":"SWE","numeric":"752","name":"Sweden","callingCode":"+46","generation":"eligible"},
  {"code":"SG","alpha3":"SGP","numeric":"702","name":"Singapore","callingCode":"+65","generation":"eligible"},
  {"code":"SH","alpha3":"SHN","numeric":"654","name":"Saint Helena, Ascension and Tristan da Cunha","callingCode":"+290","generation":"eligible"},
  {"code":"SI","alpha3":"SVN","numeric":"705","name":"Slovenia","callingCode":"+386","generation":"eligible"},
  {"code":"SJ","alpha3":"SJM","numeric":"744","name":"Svalbard and Jan Mayen","callingCode":"+47","generation":"eligible"},
  {"code":"SK","alpha3":"SVK","numeric":"703","name":"Slovakia","callingCode":"+421","generation":"eligible"},
  {"code":"SL","alpha3":"SLE","numeric":"694","name":"Sierra Leone","callingCode":"+232","generation":"eligible"},
  {"code":"SM","alpha3":"SMR","numeric":"674","name":"San Marino","callingCode":"+378","generation":"eligible"},
  {"code":"SN","alpha3":"SEN","numeric":"686","name":"Senegal","callingCode":"+221","generation":"eligible"},
  {"code":"SO","alpha3":"SOM","numeric":"706","name":"Somalia","callingCode":"+252","generation":"eligible"},
  {"code":"SR","alpha3":"SUR","numeric":"740","name":"Suriname","callingCode":"+597","generation":"eligible"},
  {"code":"SS","alpha3":"SSD","numeric":"728","name":"South Sudan","callingCode":"+211","generation":"eligible"},
  {"code":"ST","alpha3":"STP","numeric":"678","name":"Sao Tome and Principe","callingCode":"+239","generation":"eligible"},
  {"code":"SV","alpha3":"SLV","numeric":"222","name":"El Salvador","callingCode":"+503","generation":"eligible"},
  {"code":"SX","alpha3":"SXM","numeric":"534","name":"Sint Maarten (Dutch part)","callingCode":"+1","generation":"eligible"},
  {"code":"SY","alpha3":"SYR","numeric":"760","name":"Syrian Arab Republic","callingCode":"+963","generation":"eligible"},
  {"code":"SZ","alpha3":"SWZ","numeric":"748","name":"Eswatini","callingCode":"+268","generation":"eligible"},
  {"code":"TC","alpha3":"TCA","numeric":"796","name":"Turks and Caicos Islands","callingCode":"+1","generation":"eligible"},
  {"code":"TD","alpha3":"TCD","numeric":"148","name":"Chad","callingCode":"+235","generation":"eligible"},
  {"code":"TF","alpha3":"ATF","numeric":"260","name":"French Southern Territories","callingCode":null,"generation":"unavailable"},
  {"code":"TG","alpha3":"TGO","numeric":"768","name":"Togo","callingCode":"+228","generation":"eligible"},
  {"code":"TH","alpha3":"THA","numeric":"764","name":"Thailand","callingCode":"+66","generation":"eligible"},
  {"code":"TJ","alpha3":"TJK","numeric":"762","name":"Tajikistan","callingCode":"+992","generation":"eligible"},
  {"code":"TK","alpha3":"TKL","numeric":"772","name":"Tokelau","callingCode":"+690","generation":"eligible"},
  {"code":"TL","alpha3":"TLS","numeric":"626","name":"Timor-Leste","callingCode":"+670","generation":"eligible"},
  {"code":"TM","alpha3":"TKM","numeric":"795","name":"Turkmenistan","callingCode":"+993","generation":"eligible"},
  {"code":"TN","alpha3":"TUN","numeric":"788","name":"Tunisia","callingCode":"+216","generation":"eligible"},
  {"code":"TO","alpha3":"TON","numeric":"776","name":"Tonga","callingCode":"+676","generation":"eligible"},
  {"code":"TR","alpha3":"TUR","numeric":"792","name":"Türkiye","callingCode":"+90","generation":"eligible"},
  {"code":"TT","alpha3":"TTO","numeric":"780","name":"Trinidad and Tobago","callingCode":"+1","generation":"eligible"},
  {"code":"TV","alpha3":"TUV","numeric":"798","name":"Tuvalu","callingCode":"+688","generation":"eligible"},
  {"code":"TW","alpha3":"TWN","numeric":"158","name":"Taiwan, Province of China","callingCode":"+886","generation":"eligible"},
  {"code":"TZ","alpha3":"TZA","numeric":"834","name":"Tanzania, United Republic of","callingCode":"+255","generation":"eligible"},
  {"code":"UA","alpha3":"UKR","numeric":"804","name":"Ukraine","callingCode":"+380","generation":"eligible"},
  {"code":"UG","alpha3":"UGA","numeric":"800","name":"Uganda","callingCode":"+256","generation":"eligible"},
  {"code":"UM","alpha3":"UMI","numeric":"581","name":"United States Minor Outlying Islands","callingCode":null,"generation":"unavailable"},
  {"code":"US","alpha3":"USA","numeric":"840","name":"United States of America","callingCode":"+1","generation":"eligible"},
  {"code":"UY","alpha3":"URY","numeric":"858","name":"Uruguay","callingCode":"+598","generation":"eligible"},
  {"code":"UZ","alpha3":"UZB","numeric":"860","name":"Uzbekistan","callingCode":"+998","generation":"eligible"},
  {"code":"VA","alpha3":"VAT","numeric":"336","name":"Holy See","callingCode":"+39","generation":"eligible"},
  {"code":"VC","alpha3":"VCT","numeric":"670","name":"Saint Vincent and the Grenadines","callingCode":"+1","generation":"eligible"},
  {"code":"VE","alpha3":"VEN","numeric":"862","name":"Venezuela, Bolivarian Republic of","callingCode":"+58","generation":"eligible"},
  {"code":"VG","alpha3":"VGB","numeric":"092","name":"Virgin Islands (British)","callingCode":"+1","generation":"eligible"},
  {"code":"VI","alpha3":"VIR","numeric":"850","name":"Virgin Islands (U.S.)","callingCode":"+1","generation":"eligible"},
  {"code":"VN","alpha3":"VNM","numeric":"704","name":"Viet Nam","callingCode":"+84","generation":"eligible"},
  {"code":"VU","alpha3":"VUT","numeric":"548","name":"Vanuatu","callingCode":"+678","generation":"eligible"},
  {"code":"WF","alpha3":"WLF","numeric":"876","name":"Wallis and Futuna","callingCode":"+681","generation":"eligible"},
  {"code":"WS","alpha3":"WSM","numeric":"882","name":"Samoa","callingCode":"+685","generation":"eligible"},
  {"code":"YE","alpha3":"YEM","numeric":"887","name":"Yemen","callingCode":"+967","generation":"eligible"},
  {"code":"YT","alpha3":"MYT","numeric":"175","name":"Mayotte","callingCode":"+262","generation":"eligible"},
  {"code":"ZA","alpha3":"ZAF","numeric":"710","name":"South Africa","callingCode":"+27","generation":"eligible"},
  {"code":"ZM","alpha3":"ZMB","numeric":"894","name":"Zambia","callingCode":"+260","generation":"eligible"},
  {"code":"ZW","alpha3":"ZWE","numeric":"716","name":"Zimbabwe","callingCode":"+263","generation":"eligible"},
] as const
