// Reviewed country-linked Wikidata candidate components; see docs/geographic-data.md.
export const europeGenderedNames = {
  BG: {
    female: [
      "Maria", "Elena", "Mariana", "Daniela", "Diana", "Anna",
      "Milena", "Vera", "Desislava", "Maya", "Teodora", "Mariya",
      "Petya", "Nadezhda", "Valentina", "Yordanka", "Ekaterina", "Margarita",
      "Rositsa", "Dora", "Raina", "Stefka", "Galina", "Kristina",
      "Lyudmila", "Irina", "Nina", "Svetlana", "Yelena", "Ana",
      "Gabriela", "Tsvetelina", "Albena", "Evgenia", "Anastasia", "Mara",
      "Aleksandra", "Gergana", "Ivanka", "Olga", "Penka", "Sofia",
      "Violeta", "Antoaneta", "Irena", "Lidiya", "Lora", "Mihaela",
      "Simona", "Viktoriya",
    ],
    male: [
      "Georgi", "Ivan", "Dimitar", "Stefan", "Nikolay", "Petar",
      "Hristo", "Aleksandar", "Vasil", "Todor", "Vladimir", "Boris",
      "Nikola", "Konstantin", "Emil", "Kiril", "Atanas", "Peter",
      "Angel", "Martin", "Anton", "Mikhail", "Yordan", "Ivaylo",
      "Yanko", "Valentin", "Alexander", "Pavel", "Nicholas", "Stojan",
      "Petko", "Simeon", "Asen", "Rumen", "Daniel", "Viktor",
      "Borislav", "Ivo", "Stanislav", "Veselin", "Andrey", "Lyubomir",
      "Plamen", "Radoslav", "Georgy", "Kostadin", "Krasimir", "Boyan",
      "Ilija", "Michael",
    ],
    familyFemale: [
      "Petrova", "Ivanova", "Dimitrova", "Georgieva", "Todorova", "Popova",
      "Nikolova", "Aleksandrova", "Radeva", "Borisova", "Marinova", "Vasileva",
      "Koleva", "Ilieva", "Hristova", "Petkova", "Yordanova", "Angelova",
      "Stoyanova", "Mikhaylova", "Pavlova", "Blagoeva", "Dobreva", "Peeva",
      "Vassileva", "Asenova", "Ognyanova", "Yankova", "Baeva", "Daskalova",
      "Iotova", "Khristova", "Kostova", "Krasteva", "Raeva", "Stancheva",
      "Stefanova", "Antonova", "Avramova", "Bachvarova",
    ],
    familyMale: [
      "Ivanov", "Dimitrov", "Iliev", "Petrov", "Popov", "Nikolov",
      "Stoyanov", "Avramov", "Georgiev", "Todorov", "Hristov", "Mikhaylov",
      "Tanev", "Pavlov", "Petkov", "Angelov", "Markov", "Vasilev",
      "Spasov", "Kolev", "Alexandrov", "Atanasov", "Andreyev", "Yordanov",
      "Stoilov", "Tsvetkov", "Antonov", "Lyubenov", "Borisov", "Marinov",
      "Milev", "Konstantinov", "Velchev", "Dimov", "Kostov", "Bogdanov",
      "Radev", "Rusev", "Stefanov", "Yankov",
    ],
  },
  BY: {
    female: [
      "Alena", "Taccjana", "Hanna", "Voĺha", "Anastasia", "Natallia",
      "Anna", "Lyudmila", "Sviatlana", "Galina", "Katsiaryna", "Olga",
      "Iryna", "Aliona", "Yuliya", "Irina", "Nina", "Valentina",
      "Maryna", "Vera", "Anastasiia", "Maryia", "Tamara", "Darya",
      "Valancina", "Natalia", "Svetlana", "Nadzieja", "Aliaksandra", "Alina",
      "Nadezhda", "Elena", "Aksana", "Marina", "Aleksandra", "Larisa",
      "Zinaida", "Maria", "Ina", "Lyubov", "Mariya", "Kristina",
      "Viktoriya", "Ekaterina", "Kseniya", "Alyona", "Lidia", "Oksana",
      "Tatiana", "Valeria",
    ],
    male: [
      "Aliaksandr", "Aleksandr", "Siarhiej", "Sergey", "Uladzimir", "Andrei",
      "Mikalai", "Dzmitry", "Ihar", "Aliaksiej", "Yury", "Mikhail",
      "Viktar", "Pavel", "Vladimir", "Ivan", "Yawhen", "Anatol",
      "Oleg", "Valery", "Leanid", "Aleh", "Vital", "Vladislav",
      "Vasil", "Maksim", "Anton", "Viktor", "Henadz", "Nikolay",
      "Igor", "Pyotr", "Uladzislau", "Yevgeny", "Artsyom", "Dmitry",
      "Andrey", "Anatoly", "Vyachaslaw", "Dzyanis", "Konstantin", "Ales",
      "Alexander", "Vadzim", "Kanstantsin", "Barys", "Vasily", "Eduard",
      "Aleksey", "Gennady",
    ],
    familyFemale: [
      "Haluza", "Ivanova", "Vasileuskaya", "Chernyavskaya", "Lebedeva", "Morozova",
      "Petrova", "Sokolova", "Starovoytova", "Bandarenka", "Belskaya", "Hołubiewa",
      "Isaczenka", "Ismayilova", "Kavalyova", "Kurbyka", "Lisovskaya", "Papova",
      "Popova", "Savina", "Shapetska", "Sidarenka", "Vinnikava", "Vysotskaya",
      "Zhurawskaya", "Abelskaya", "Abramava", "Agranovskaya", "Aleksandrova", "Alimbekava",
      "Alipova", "Andrejeva", "Antonawa", "Arciomienka", "Arciuszyna", "Arlowskaya",
      "Asmałouska", "Awdiejewa", "Awramyenka", "Azaranka",
    ],
    familyMale: [
      "Ivanov", "Kovalyov", "Kozlov", "Morozov", "Volkov", "Semyonov",
      "Aleksandrovich", "Golubev", "Lebedev", "Martynov", "Novikov", "Pavlov",
      "Vasilyev", "Zaytsev", "Belov", "Kalinin", "Kazlowski", "Mikhaylov",
      "Platonov", "Smirnov", "Smolski", "Vabishchevich", "Akulich", "Bandarenka",
      "Baranowski", "Belyayev", "Drozdov", "Dzemidovich", "Hramyka", "Ihnatsyenka",
      "Kavalenka", "Khatskevich", "Kraŭčanka", "Kuznetsov", "Makarov", "Medvedev",
      "Naumov", "Petrov", "Polyakov", "Popov",
    ],
  },
  CY: {
    female: [
      "Maria", "Eleni", "Elena", "Anna", "Christina", "Sophia",
      "Georgia", "Stella", "Marina", "Christiana", "Marilena", "Ioanna",
      "Marianna", "Olga", "Valentina", "Anastasia", "Androula", "Emili",
      "Katerina", "Natalia", "Alexandra", "Andri", "Athena", "Dora",
      "Efi", "Elina", "Elli", "Evanthia", "Fotini", "Irini",
      "Lia", "Niki", "Rita", "Alexia", "Andrea", "Andriana",
      "Antigoni", "Areti", "Despina", "Despoina", "Emily", "Erato",
      "Eva", "Filippa", "Giota", "Iris", "Ivana", "Karolina",
      "Keti", "Konstantina",
    ],
    male: [
      "Andreas", "Giorgos", "Georgios", "Nikos", "Marios", "Kostas",
      "Antonis", "Michalis", "Dimitris", "Kyriakos", "Panagiotis", "Giannis",
      "Konstantinos", "Stavros", "Charalampos", "Christakis", "Ioannis", "Petros",
      "Stelios", "Savvas", "Pavlos", "Christodoulos", "Panicos", "Nikolas",
      "Demetrios", "Yannakis", "Haris", "Loukas", "Sotiris", "Alexandros",
      "Christophoros", "Evangelos", "Michalakis", "Ilias", "Michael", "Takis",
      "Andros", "Angelos", "Markos", "Theodoros", "Vasilis", "Zacharias",
      "Adamos", "Alekos", "Aristos", "Doros", "Elias", "Filippos",
      "Iakovos", "Kipros",
    ],
    familyFemale: [
      "Ioannou", "Charalambous", "Konstantinou", "Christodoulou", "Chrysostomou", "Dimitriou",
      "Eleftheriou", "Georgiou", "Kyriakidou", "Stilianou", "Alexandrou", "Antoniou",
      "Athinodorou", "Avraamidou", "Constantinou", "Demosthenous", "Drakou", "Ellina",
      "Georgiadou", "Iasonos", "Knekna", "Kyprianou", "Kyriakou", "Michailidou",
      "Panagiotou", "Panayiotou", "Papaioannou", "Pissi", "Savva", "Theodorou",
      "Toumazou", "Vissi", "Achilleos", "Adamou", "Agrotou", "Aimilianídou",
      "Akkelidou", "Anastasiadou", "Anastasiou", "Angelidou",
    ],
    familyMale: [
      "Georgiou", "Michaelides", "Papadopoulos", "Ioannou", "Konstantinou", "Antoniou",
      "Christophides", "Clerides", "Nicolaides", "Panayiotou", "Savva", "Savvides",
      "Andreou", "Charalambous", "Christodoulou", "Kyprianou", "Sophokleous", "Dimitriadis",
      "Dimitriou", "Ioannidis", "Vasileiou", "Christophorou", "Constantinou", "Georgiadis",
      "Kyriakou", "Pierides", "Stilianou", "Charalambides", "Chrysostomou", "Elia",
      "Evangelou", "Konstantinidis", "Michael", "Pavlou", "Petrou", "Stavrou",
      "Anastasiou", "Aristidou", "Christodoulidis", "Christofi",
    ],
  },
  CZ: {
    female: [
      "Jana", "Eva", "Kateřina", "Hana", "Lucie", "Tereza",
      "Anna", "Petra", "Lenka", "Michaela", "Zuzana", "Alena",
      "Veronika", "Martina", "Barbora", "Markéta", "Jitka", "Věra",
      "Helena", "Ivana", "Klára", "Eliška", "Andrea", "Monika",
      "Dana", "Olga", "Pavla", "Dagmar", "Irena", "Jarmila",
      "Kristýna", "Gabriela", "Karolína", "Jiřina", "Adéla", "Jaroslava",
      "Radka", "Šárka", "Nikola", "Aneta", "Daniela", "Iva",
      "Ludmila", "Marta", "Milena", "Zdeňka", "Simona", "Blanka",
      "Renata", "Kamila",
    ],
    male: [
      "Jan", "Jiří", "Petr", "Martin", "Pavel", "Tomáš",
      "Josef", "Jaroslav", "Zdeněk", "Michal", "Karel", "Václav",
      "František", "Miroslav", "Vladimír", "Milan", "Jakub", "David",
      "Ondřej", "Lukáš", "Marek", "Ladislav", "Ivan", "Roman",
      "Daniel", "Stanislav", "Antonín", "Vojtěch", "Filip", "Radek",
      "Adam", "Aleš", "Miloš", "Jaromír", "Libor", "Rudolf",
      "Robert", "Matěj", "Oldřich", "Miloslav", "Jindřich", "Ivo",
      "Radim", "Richard", "Vlastimil", "Štěpán", "Patrik", "Lubomír",
      "Vít", "Michael",
    ],
    familyFemale: [
      "Nováková", "Novotná", "Dvořáková", "Kašparová", "Svobodová", "Veselá",
      "Pokorná", "Němcová", "Procházková", "Černá", "Fialová", "Jelínková",
      "Čechová", "Horáková", "Zemanová", "Malá", "Benešová", "Málková",
      "Růžičková", "Sedláčková", "Doležalová", "Jandová", "Marková", "Soukupová",
      "Urbanová", "Bartošová", "Králová", "Kratochvílová", "Krejčová", "Beránková",
      "Jarošová", "Kolářová", "Kučerová", "Bártová", "Bednářová", "Šimková",
      "Bláhová", "Blažková", "Fischerová", "Hlaváčková",
    ],
    familyMale: [
      "Novák", "Svoboda", "Novotný", "Dvořák", "Černý", "Kučera",
      "Hájek", "Procházka", "Němec", "Pospíšil", "Sedláček", "Horák",
      "Král", "Veselý", "Doležal", "Kolář", "Fiala", "Jelínek",
      "Čermák", "Marek", "Sýkora", "Beneš", "Růžička", "Kovář",
      "Urban", "Blažek", "Mareš", "Štěpánek", "Bartoš", "Navrátil",
      "Pokorný", "Čech", "Kraus", "Bláha", "Krejčí", "Vlček",
      "Vacek", "Kopecký", "Němeček", "Konečný",
    ],
  },
  GR: {
    female: [
      "Maria", "Eleni", "Anna", "Christina", "Sophia", "Katerina",
      "Angeliki", "Alexandra", "Elena", "Irini", "Georgia", "Ioanna",
      "Meri", "Fotini", "Stella", "Marina", "Dimitra", "Sofia",
      "Ekaterini", "Eva", "Olga", "Anastasia", "Margarita", "Elisavet",
      "Vasiliki", "Vicky", "Athena", "Marianna", "Evgenia", "Lena",
      "Alexia", "Natalia", "Despina", "Konstantina", "Lina", "Marika",
      "Maro", "Amalia", "Aspasia", "Dora", "Eleftheria", "Evangelia",
      "Niki", "Evi", "Antonia", "Nina", "Rania", "Kalliopi",
      "Tatiana", "Emilia",
    ],
    male: [
      "Giorgos", "Dimitris", "Georgios", "Nikos", "Giannis", "Konstantinos",
      "Ioannis", "Alexandros", "Vasilis", "Andreas", "Panagiotis", "Kostas",
      "Demetrios", "Vassilios", "Athanasios", "Antonis", "Antonios", "Michalis",
      "Spiros", "Theodoros", "Petros", "Ilias", "Stefanos", "Demetrio",
      "Apostolos", "Charalampos", "Michael", "Pavlos", "Anastasios", "Stavros",
      "Evangelos", "Spyridon", "Angelos", "George", "Stelios", "Leonidas",
      "Alexis", "Sotiris", "Thanos", "Tasos", "Thanasis", "Dionysios",
      "Takis", "Vangelis", "Panos", "Manolis", "Marios", "Emmanouil",
      "Epameinondas", "Lefteris",
    ],
    familyFemale: [
      "Papadopoulou", "Athanasiadou", "Papadimitriou", "Papaioannou", "Angelidou", "Asimakopoulou",
      "Sidiropoulou", "Anastasopoulou", "Angelopoulou", "Antoniadou", "Arvaniti", "Christodoulou",
      "Michailidou", "Panagiotopoulou", "Panayiotou", "Papakonstantinou", "Pappa", "Stefanou",
      "Stergiou", "Theodorou", "Anastasiadou", "Antoniou", "Charalampidou", "Diamantopoulou",
      "Fragkou", "Georgiou", "Giannatou", "Hadjioannou", "Theodoridou", "Zacharopoulou",
      "Alexandri", "Alexiou", "Alexopoulou", "Avramidou", "Emmanouilidou", "Fotiou",
      "Georgiadou",
    ],
    familyMale: [
      "Papadopoulos", "Nicolaides", "Ioannidis", "Papaioannou", "Papanikolaou", "Georgiadis",
      "Xanthopoulos", "Oikonomopoulos", "Papadakis", "Papageorgiou", "Panagiotopoulos", "Angelopoulos",
      "Athanasiadis", "Fotiadis", "Stamoulis", "Triantaphyllides", "Chatzis", "Karagiannis",
      "Mylonas", "Petridis", "Diamantopoulos", "Kanellopoulos", "Papadimitriou", "Papakonstantinou",
      "Papayiannis", "Stefanou", "Georgiou", "Konstantinidis", "Argyropoulos", "Dimitriadis",
      "Eliades", "Anastasiadis", "Antoniou", "Aravantinos", "Chatzinicolaou", "Iordanidis",
      "Kalogeropoulos", "Kyriakidis", "Oikonomou", "Zervos",
    ],
  },
  IS: {
    female: [
      "Kristín", "Margrét", "Anna", "Helga", "Guðrún", "María",
      "Hulda", "Sigríður", "Eva", "Katrín", "Edda", "Ingibjörg",
      "Ragnheiður", "Sara", "Hanna", "Sigrún", "Ásta", "Jóna",
      "Þórunn", "Elín", "Auður", "Bryndís", "Unnur", "Agnes",
      "Birna", "Halla", "Halldóra", "Helena", "Lilja", "Björk",
      "Elsa", "Erna", "Hildur", "Linda", "Rannveig", "Vigdís",
      "Andrea", "Emilía", "Marta", "Sandra", "Þóra", "Elísabet",
      "Emma", "Guðbjörg", "Jóhanna", "Ragna", "Rakel", "Selma",
      "Sólveig", "Þórdís",
    ],
    male: [
      "Jón", "Gunnar", "Guðmundur", "Sigurður", "Einar", "Ólafur",
      "Björn", "Magnús", "Árni", "Stefán", "Bjarni", "Pétur",
      "Kristján", "Jóhann", "Kristinn", "Ragnar", "Þorsteinn", "Karl",
      "Gísli", "Þór", "Páll", "Ágúst", "Birgir", "Helgi",
      "Arnar", "Haukur", "Jónas", "Halldór", "Örn", "Hannes",
      "Hilmar", "Jakob", "Jóhannes", "Kjartan", "Orri", "Viktor",
      "Þórður", "Andri", "Baldur", "Óskar", "Sigfús", "Sveinn",
      "Birkir", "Eiríkur", "Friðrik", "Ingi", "Matthías", "Ari",
      "Davíð", "Hjalti",
    ],
    familyFemale: [
      "Jónsdóttir", "Hermannsdóttir", "Pétursdóttir", "Sigurðardóttir", "Jóhannsdóttir", "Pálsdóttir",
      "Árnadóttir", "Magnúsdóttir", "Kristjánsdóttir", "Finnsdóttir", "Guðjónsdóttir", "Stefánsdóttir",
      "Arnardóttir", "Bjarnadóttir", "Haraldsdóttir", "Hauksdóttir", "Helgadóttir", "Ingólfsdóttir",
      "Jóhannesdóttir", "Rúnarsdóttir", "Björnsdóttir", "Einarsdóttir", "Garðarsdóttir", "Gísladóttir",
      "Gunnarsdóttir", "Gunnlaugsdóttir", "Harðardóttir", "Hönnudóttir", "Hrafnkelsdóttir", "Ingadóttir",
      "Jónasdóttir", "Kjartansdóttir", "Þrastardóttir", "Ágústsdóttir", "Ámundadóttir", "Ásgeirsdóttir",
      "Ásgrímsdóttir", "Atladóttir", "Baldursdóttir", "Brynjarsdóttir",
    ],
    familyMale: [
      "Jónsson", "Guðmundsson", "Ólafsson", "Einarsson", "Gunnarsson", "Benediktsson",
      "Kristjánsson", "Pálsson", "Stefánsson", "Sveinsson", "Björnsson", "Magnússon",
      "Grímsson", "Guðjónsson", "Kjartansson", "Sigurdsson", "Gudmundsson", "Karlsson",
      "Kristinsson", "Aðalsteinsson", "Haraldsson", "Jóhannsson", "Friðjónsson", "Hermannsson",
      "Jonsson", "Kristjansson", "Olafsson", "Ragnarsson", "Jóhannesson", "Masson",
      "Oskarsson", "Pétursson", "Sigurjónsson", "Þórarinsson", "Þorsteinsson", "Þorvaldsson",
      "Hallgrímsson", "Hilmarsson", "Johannesson", "Loftsson",
    ],
  },
  LT: {
    female: [
      "Irena", "Aldona", "Marija", "Dalia", "Nijolė", "Elena",
      "Birutė", "Ieva", "Janina", "Jūratė", "Rasa", "Kristina",
      "Rūta", "Ona", "Danutė", "Monika", "Regina", "Eglė",
      "Grazhina", "Agnė", "Laima", "Lina", "Daiva", "Giedrė",
      "Viktorija", "Genovaitė", "Laura", "Veronika", "Audronė", "Edita",
      "Jolanta", "Violeta", "Virginija", "Zita", "Rita", "Diana",
      "Greta", "Simona", "Danguolė", "Erika", "Karolina", "Vaida",
      "Emilija", "Justina", "Viktoriya", "Indrė", "Inga", "Asta",
      "Egle", "Gintarė",
    ],
    male: [
      "Vytautas", "Jonas", "Juozas", "Antanas", "Algirdas", "Petras",
      "Algimantas", "Tomas", "Stasys", "Kęstutis", "Vladas", "Mindaugas",
      "Andrius", "Saulius", "Povilas", "Gediminas", "Darius", "Kazys",
      "Pranas", "Rimantas", "Marius", "Paulius", "Aleksandras", "Kazimieras",
      "Gintaras", "Arūnas", "Jurgis", "Artūras", "Arvydas", "Alfonsas",
      "Audrius", "Mantas", "Martynas", "Viktoras", "Bronius", "Julius",
      "Vincas", "Donatas", "Ričardas", "Rolandas", "Karolis", "Tadas",
      "Leonas", "Mykolas", "Giedrius", "Gintautas", "Rokas", "Albinas",
      "Dainius", "Linas",
    ],
    familyFemale: [
      "Marcinkevičiūtė", "Mikalauskaitė", "Petkevičienė", "Barauskaitė", "Gricienė", "Grigaitė",
      "Jablonskytė", "Jankauskienė", "Paulauskaitė", "Petrauskaitė", "Petronytė", "Rimšaitė",
      "Rutkauskaitė", "Vaicekauskienė", "Vasiliauskaitė", "Aleksandravičiūtė", "Andriuscenkaitė", "Čiukšytė",
      "Degutytė", "Didžgalvytė", "Globytė", "Gražinytė", "Grumadienė", "Janušauskaitė",
      "Jaruševičienė", "Juodvalkė", "Jurgaitytė", "Kalėdienė", "Kaminskaitė", "Karalienė",
      "Kartanaitė", "Kaušaitė", "Kazlauskienė", "Kovaliova", "Kreivytė", "Lukšaitė",
      "Mackevičiūtė", "Marcinkevičienė", "Matulaitė", "Mickienė",
    ],
    familyMale: [
      "Jankauskas", "Kazlauskas", "Marcinkevičius", "Petrauskas", "Vasiliauskas", "Butkus",
      "Paulauskas", "Adomaitis", "Aleksandravičius", "Bagdonas", "Mackevičius", "Andriuškevičius",
      "Jurevičius", "Mikalauskas", "Sakalauskas", "Budrys", "Pocius", "Vaitkus",
      "Žukauskas", "Giedraitis", "Ivanauskas", "Mockus", "Navickas", "Norkus",
      "Savickas", "Stankevičius", "Astrauskas", "Balsys", "Bartkus", "Kairys",
      "Milašius", "Ruzgys", "Urbonas", "Balčiūnas", "Banionis", "Baranauskas",
      "Dambrauskas", "Dargis", "Gricius", "Grybauskas",
    ],
  },
  LV: {
    female: [
      "Anna", "Ieva", "Ilze", "Inese", "Linda", "Inga",
      "Laura", "Anita", "Marta", "Baiba", "Dace", "Kristīne",
      "Zane", "Agnese", "Elīna", "Liene", "Olga", "Aija",
      "Maija", "Līga", "Sandra", "Aina", "Anete", "Ilona",
      "Iveta", "Laima", "Anda", "Daina", "Elza", "Kristine",
      "Marija", "Rita", "Milda", "Gunta", "Elizabete", "Ilga",
      "Māra", "Vija", "Ausma", "Elina", "Elita", "Ināra",
      "Inta", "Paula", "Dita", "Lidija", "Lilija", "Madara",
      "Anastasija", "Ingrīda",
    ],
    male: [
      "Jānis", "Kārlis", "Andris", "Juris", "Andrejs", "Aleksandrs",
      "Mārtiņš", "Edgars", "Artūrs", "Eduards", "Roberts", "Māris",
      "Valdis", "Viktors", "Aivars", "Alfrēds", "Uldis", "Ernests",
      "Imants", "Augusts", "Kaspars", "Kristaps", "Gunārs", "Ivars",
      "Oskars", "Pauls", "Alberts", "Arvīds", "Jēkabs", "Ēriks",
      "Rihards", "Raimonds", "Antons", "Nikolajs", "Voldemārs", "Aleksejs",
      "Aigars", "Igor", "Vilis", "Vladimirs", "Bruno", "Guntis",
      "Arnolds", "Oļegs", "Rūdolfs", "Vladimir", "Aleksandr", "Ģirts",
      "Dainis", "Edmunds",
    ],
    familyFemale: [
      "Bērziņa", "Ozoliņa", "Liepiņa", "Eglīte", "Jansone", "Krūmiņa",
      "Balode", "Kļaviņa", "Zariņa", "Ozola", "Vītola", "Āboliņa",
      "Baumane", "Gaile", "Gulbe", "Kārkliņa", "Kalniņa", "Liniņa",
      "Broka", "Lāce", "Priede", "Rudzīte", "Saulīte", "Siliņa",
      "Līce", "Martinsone", "Mūrniece", "Rozentale", "Skujiņa", "Ābele",
      "Apine", "Brice", "Dreimane", "Ērgle", "Ivanova", "Jākobsone",
      "Jureviča", "Lasmane", "Liepa", "Lūse",
    ],
    familyMale: [
      "Bērziņš", "Kalniņš", "Ozoliņš", "Jansons", "Krūmiņš", "Ozols",
      "Liepiņš", "Zariņš", "Eglītis", "Ivanov", "Siliņš", "Vītols",
      "Kļaviņš", "Āboliņš", "Pētersons", "Grīnbergs", "Krastiņš", "Anderson",
      "Kārkliņš", "Vanags", "Apinis", "Gulbis", "Baumanis", "Briedis",
      "Freimanis", "Ansons", "Berg", "Blūms", "Apsītis", "Ērglis",
      "Lazdins", "Mūrnieks", "Auziņš", "Barons", "Dombrovskis", "Kroders",
      "Lācis", "Lūsis", "Putniņš", "Ulmanis",
    ],
  },
  MK: {
    female: [
      "Ana", "Elena", "Ivana", "Sara", "Vera", "Maja",
      "Simona", "Lidija", "Vesna", "Daniela", "Jana", "Magdalena",
      "Nada", "Slavica", "Tanja", "Teodora", "Angela", "Dragana",
      "Elizabeta", "Irena", "Jasmina", "Maria", "Marina", "Martina",
      "Monika", "Svetlana", "Tamara", "Aleksandra", "Andrea", "Blaga",
      "Emilia", "Gabriela", "Gordana", "Jelena", "Katerina", "Kristina",
      "Liljana", "Ljubica", "Nina", "Sonja", "Yelena", "Alexandra",
      "Andrijana", "Biljana", "Blagorodna", "Cvetanka", "Ilinka", "Iskra",
      "Katarina", "Marija",
    ],
    male: [
      "Aleksandar", "Zoran", "Nikola", "Goran", "Vladimir", "Filip",
      "Igor", "Dejan", "Petar", "Dragan", "Darko", "Ivan",
      "Dimitar", "Marian", "Vlatko", "Bojan", "Stefan", "Toni",
      "Vlado", "Kiril", "Marko", "Risto", "Blagoja", "Jovan",
      "Daniel", "Goce", "Oliver", "Andrej", "Boris", "David",
      "Ilija", "Martin", "Tomislav", "Boban", "Emil", "Georgi",
      "Jordan", "Marjan", "Milan", "Stojan", "Vasil", "Petre",
      "Slobodan", "Blagoj", "Branko", "Damjan", "Gligor", "Ljupčo",
      "Mario", "Nenad",
    ],
    familyFemale: [
      "Angelovska", "Kostovska", "Acevska", "Aleksova", "Andreevska", "Naceva",
      "Pejoska", "Ackovska", "Aleksandrova", "Anastasova", "Andrejeva", "Arnaudova",
      "Bakovska", "Borisova", "Bužarovska", "Danoska", "Eftimova", "Georgievska",
      "Gešoska", "Gočeva", "Ivanova", "Jankulovska", "Kiselyova", "Lazarova",
      "Marinova", "Markova", "Pawłowska", "Petrova", "Popovska", "Sekulovska",
      "Starova", "Taska", "Velevska", "Volkanovska", "Yakimova", "Yaneva",
      "Zafirovska", "Zaova",
    ],
    familyMale: [
      "Georgievski", "Naumoski", "Nikolov", "Ristovski", "Stojanovski", "Andonovski",
      "Dimitrov", "Hristov", "Ivanov", "Ivanovski", "Lazarov", "Popov",
      "Angelovski", "Arsovski", "Bogoev", "Mihajlovski", "Petrov", "Stefanovski",
      "Taleski", "Tsvetkovski", "Andreevski", "Angeleski", "Angelov", "Atanasovski",
      "Avramovski", "Bogdanovski", "Crvenkovski", "Dimovski", "Ilievski", "Janevski",
      "Jovanovski", "Krstevski", "Petkovski", "Stavrev", "Trajkovski", "Vasilevski",
      "Andov", "Babunski", "Đurovski", "Efremov",
    ],
  },
  PL: {
    female: [
      "Maria", "Anna", "Ewa", "Katarzyna", "Małgorzata", "Agnieszka",
      "Barbara", "Joanna", "Zofia", "Elżbieta", "Magdalena", "Krystyna",
      "Jadwiga", "Aleksandra", "Janina", "Teresa", "Marta", "Irena",
      "Monika", "Helena", "Dorota", "Danuta", "Halina", "Beata",
      "Jolanta", "Wanda", "Karolina", "Grażyna", "Hanna", "Alicja",
      "Agata", "Iwona", "Urszula", "Bożena", "Justyna", "Paulina",
      "Izabela", "Natalia", "Stanisława", "Renata", "Stefania", "Józefa",
      "Sylwia", "Julia", "Lidia", "Alina", "Dominika", "Olga",
      "Marianna", "Marzena",
    ],
    male: [
      "Jan", "Andrzej", "Stanisław", "Jerzy", "Józef", "Piotr",
      "Tadeusz", "Krzysztof", "Tomasz", "Michał", "Marek", "Wojciech",
      "Adam", "Kazimierz", "Paweł", "Zbigniew", "Władysław", "Henryk",
      "Jacek", "Marian", "Antoni", "Maciej", "Marcin", "Ryszard",
      "Stefan", "Grzegorz", "Franciszek", "Mieczysław", "Aleksander", "Zygmunt",
      "Edward", "Roman", "Witold", "Łukasz", "Zdzisław", "Karol",
      "Włodzimierz", "Jarosław", "Dariusz", "Jakub", "Robert", "Czesław",
      "Leszek", "Mariusz", "Rafał", "Mirosław", "Wiesław", "Wacław",
      "Sławomir", "Eugeniusz",
    ],
    familyFemale: [
      "Kowalska", "Dąbrowska", "Szymańska", "Kamińska", "Kozłowska", "Zielińska",
      "Wójcik", "Jankowska", "Kwiatkowska", "Piotrowska", "Nowakowska", "Nowicka",
      "Grabowska", "Sokołowska", "Michalska", "Lewandowska", "Sadowska", "Pawłowska",
      "Jaworska", "Rutkowska", "Witkowska", "Ostrowska", "Tomaszewska", "Woźniak",
      "Jabłońska", "Jasińska", "Górska", "Sawicka", "Majewska", "Domańska",
      "Zalewska", "Baranowska", "Krajewska", "Jakubowska", "Marciniak", "Szczepańska",
      "Adamska", "Lipińska", "Malinowska", "Olszewska",
    ],
    familyMale: [
      "Kowalski", "Zieliński", "Kamiński", "Dąbrowski", "Kozłowski", "Wójcik",
      "Szymański", "Piotrowski", "Grabowski", "Lewandowski", "Kowalczyk", "Kaczmarek",
      "Nowakowski", "Pawłowski", "Górski", "Majewski", "Olszewski", "Michalski",
      "Kwiatkowski", "Nowicki", "Wróblewski", "Tomaszewski", "Jabłoński", "Witkowski",
      "Mazur", "Woźniak", "Malinowski", "Jasiński", "Rutkowski", "Ostrowski",
      "Wieczorek", "Jakubowski", "Jaworski", "Sikora", "Adamczyk", "Zawadzki",
      "Klimek", "Król", "Sawicki", "Wróbel",
    ],
  },
  RU: {
    female: [
      "Olga", "Anna", "Irina", "Yelena", "Nataliya", "Ekaterina",
      "Elena", "Svetlana", "Mariya", "Marina", "Anastasia", "Valentina",
      "Galina", "Lyudmila", "Natalia", "Nina", "Yuliya", "Aleksandra",
      "Vera", "Nadezhda", "Darya", "Larisa", "Evgenia", "Tamara",
      "Margarita", "Viktoriya", "Lyubov", "Polina", "Oksana", "Alla",
      "Tatiana", "Xenia", "Maria", "Lidiya", "Sofia", "Alina",
      "Kristina", "Zoya", "Inna", "Raisa", "Nataliia", "Ludmila",
      "Antonina", "Alyona", "Veronika", "Zinaida", "Liliya", "Natalja",
      "Diana", "Elvira",
    ],
    male: [
      "Aleksandr", "Vladimir", "Sergey", "Aleksey", "Andrey", "Nikolay",
      "Ivan", "Mikhail", "Yury", "Viktor", "Dmitry", "Igor",
      "Yevgeny", "Oleg", "Anatoly", "Boris", "Valery", "Pavel",
      "Leonid", "Konstantin", "Maksim", "Vasily", "Roman", "Gennady",
      "Ilya", "Anton", "Vadim", "Georgy", "Denis", "Vladislav",
      "Alexander", "Pyotr", "Vyacheslav", "Kirill", "Valentin", "Lev",
      "Yevgeni", "Stanislav", "Artyom", "Nikita", "Eduard", "Ruslan",
      "Grigory", "Vitaly", "Fyodor", "Daniil", "Artur", "Arkady",
      "Marat", "Artem",
    ],
    familyFemale: [
      "Ivanova", "Petrova", "Smirnova", "Vasilyeva", "Fyodorova", "Mikhaylova",
      "Sokolova", "Volkova", "Popova", "Novikova", "Orlova", "Yegorova",
      "Romanova", "Alexeyeva", "Borisova", "Lebedeva", "Morozova", "Stepanova",
      "Abramova", "Sergeyeva", "Kuznetsova", "Danilova", "Solovyova", "Medvedeva",
      "Antonova", "Kudryavtseva", "Pavlova", "Yakovleva", "Baranova", "Makarova",
      "Kozlova", "Kulikova", "Maslova", "Ovchinnikova", "Sorokina", "Grigoryeva",
      "Konovalova", "Nikitina", "Aleksandrova", "Chernova",
    ],
    familyMale: [
      "Ivanov", "Kuznetsov", "Popov", "Smirnov", "Petrov", "Vasilyev",
      "Sokolov", "Alexeyev", "Volkov", "Kozlov", "Mikhaylov", "Morozov",
      "Semyonov", "Lebedev", "Novikov", "Pavlov", "Solovyov", "Fyodorov",
      "Nikolayev", "Stepanov", "Zakharov", "Makarov", "Orlov", "Yakovlev",
      "Zaytsev", "Belov", "Abramov", "Andreyev", "Borisov", "Gusev",
      "Grigoryev", "Tarasov", "Yegorov", "Romanov", "Frolov", "Sergeyev",
      "Medvedev", "Kovalyov", "Alexandrov", "Nikitin",
    ],
  },
  SK: {
    female: [
      "Zuzana", "Mária", "Jana", "Katarína", "Lucia", "Anna",
      "Eva", "Martina", "Michaela", "Veronika", "Andrea", "Monika",
      "Petra", "Barbora", "Lenka", "Ivana", "Alexandra", "Gabriela",
      "Kristína", "Daniela", "Dominika", "Marta", "Alena", "Nikola",
      "Silvia", "Simona", "Natália", "Viktória", "Hana", "Tatiana",
      "Helena", "Adriana", "Dagmar", "Elena", "Iveta", "Miroslava",
      "Erika", "Ľudmila", "Dana", "Irena", "Karin", "Nina",
      "Tamara", "Katarina", "Ľubica", "Barbara", "Ema", "Renáta",
      "Tereza", "Alica",
    ],
    male: [
      "Peter", "Jozef", "Martin", "Ján", "Michal", "Juraj",
      "Tomáš", "Milan", "Pavol", "Štefan", "Ivan", "Vladimír",
      "Miroslav", "Ladislav", "Marek", "František", "Andrej", "Marián",
      "Roman", "Lukáš", "Matej", "Jakub", "Róbert", "Dušan",
      "Karol", "Ľubomír", "Richard", "Daniel", "Igor", "Stanislav",
      "Adam", "Anton", "Tibor", "Matúš", "Ondrej", "Samuel",
      "Patrik", "Jaroslav", "Rudolf", "Filip", "Pavel", "Boris",
      "Viktor", "Július", "Alexander", "Branislav", "Emil", "Viliam",
      "Yaroslav", "Erik",
    ],
    familyFemale: [
      "Klimková", "Gašparovičová", "Horváthová", "Tóthová", "Kováčiková", "Moravčíková",
      "Orlovská", "Baranová", "Čajková", "Chovancová", "Daubnerová", "Fričová",
      "Furdová", "Gáborová", "Gašparíková", "Halušková", "Jamborová", "Kalinová",
      "Kmeťová", "Kováčová", "Kovářová", "Krišková", "Kršková", "Makarová",
      "Matejová", "Némethová", "Pavlíková", "Petríková", "Podhradská", "Remeňová",
      "Šidlová", "Slezáková", "Vajdová", "Antalová", "Babčanová", "Bahnová",
      "Bálintová", "Barteková", "Bartuszová", "Bednáriková",
    ],
    familyMale: [
      "Horváth", "Kováč", "Tóth", "Novák", "Szabó", "Nagy",
      "Sýkora", "Molnár", "Urban", "Varga", "Chovan", "Filo",
      "Kollár", "Konečný", "Kovács", "Zajac", "Baláž", "Balko",
      "Bartoš", "Gallo", "Gregor", "Hudec", "Németh", "Polák",
      "Bauer", "Chovanec", "Gábor", "Gál", "Hlinka", "Holec",
      "Horák", "Kučera", "Mráz", "Sedlák", "Sloboda", "Sopko",
      "Švec", "Valach", "Weiss", "Adamec",
    ],
  },
  UA: {
    female: [
      "Olena", "Iryna", "Olga", "Anna", "Oksana", "Tetiana",
      "Nataliia", "Valentina", "Lyudmila", "Natalia", "Halyna", "Hanna",
      "Svitlana", "Viktoriya", "Olha", "Nina", "Irina", "Mariia",
      "Galina", "Alla", "Kateryna", "Larisa", "Nataliya", "Elena",
      "Maria", "Marina", "Anastasia", "Vera", "Inna", "Tamara",
      "Yuliia", "Alina", "Liudmyla", "Nadiya", "Anastasiia", "Oleksandra",
      "Diana", "Yuliya", "Darya", "Svetlana", "Tatiana", "Nadezhda",
      "Ekaterina", "Larysa", "Valentyna", "Maryna", "Antonina", "Lidia",
      "Veronika", "Sofia",
    ],
    male: [
      "Oleksandr", "Volodymyr", "Sergey", "Viktor", "Ihor", "Vladimir",
      "Aleksandr", "Andriy", "Ivan", "Mykola", "Yurii", "Dmytro",
      "Serhii", "Roman", "Yury", "Oleg", "Anatoly", "Igor",
      "Vasyl", "Mykhailo", "Oleh", "Vitalii", "Nikolay", "Yevhen",
      "Yevgeny", "Leonid", "Oleksii", "Mikhail", "Andrey", "Vasily",
      "Aleksey", "Anatolii", "Petro", "Valery", "Bohdan", "Yaroslav",
      "Boris", "Valeriy", "Pavlo", "Valentin", "Maksim", "Artem",
      "Konstantin", "Dmitry", "Stanislav", "Alexander", "Ruslan", "Taras",
      "Anton", "Maksym",
    ],
    familyFemale: [
      "Shevchenko", "Boiko", "Kovalchuk", "Kovalenko", "Tkachenko", "Marchenko",
      "Bondarenko", "Romanova", "Savchenko", "Humeniuk", "Rudenko", "Koval",
      "Kyrychenko", "Mazur", "Ponomarenko", "Ivanova", "Petrova", "Serdiuk",
      "Borisova", "Karpenko", "Kolesnyk", "Kononenko", "Kostenko", "Kravchenko",
      "Lytvynenko", "Palamarchuk", "Pavlenko", "Shevchuk", "Sydorenko", "Tereshchenko",
      "Yablonska", "Babenko", "Biletska", "Bondar", "Dmytrenko", "Holub",
      "Honcharova", "Hres", "Kostiuk", "Kravchuk",
    ],
    familyMale: [
      "Shevchenko", "Ivanov", "Boiko", "Savchenko", "Popov", "Bondarenko",
      "Kovalenko", "Ponomarenko", "Marchenko", "Pavlov", "Petrov", "Klymenko",
      "Oliynyk", "Serdiuk", "Shevchuk", "Tkachenko", "Holovko", "Nazarenko",
      "Volkov", "Kravchenko", "Pavlenko", "Ishchenko", "Koval", "Moskalenko",
      "Kozlov", "Melnyk", "Tkachuk", "Vasilenko", "Bilyk", "Morozov",
      "Rudenko", "Smirnov", "Lutsenko", "Melnik", "Stepanov", "Zaytsev",
      "Chumak", "Sydorenko", "Tereshchenko", "Baranov",
    ],
  },
} as const

export function isEuropeGenderedCountry(code: string): code is keyof typeof europeGenderedNames {
  return Object.hasOwn(europeGenderedNames, code)
}
