// Reviewed European territory name components from the pinned birth-place report and Faroese statistics.
export const europeIslandNames = {
  AX: {
    female: [
      "Alexandra", "Linda", "Adelina", "Aili", "Alie", "Alina",
      "Amanda", "Anna", "Annette", "Anni", "Annica", "Annie",
      "Barbro", "Britt", "Camilla", "Carina", "Carol", "Caroline",
      "Constance", "Elisabeth", "Ella", "Emilia", "Erika", "Fanny",
      "Greta", "Gun", "Gyrid", "Hanna", "Helena", "Helle",
      "Henriette", "Hilda", "Ilmi", "Ingeborg", "Jenny", "Jonna",
      "Katarina", "Katrin", "Linnea", "Louise", "Lovisa", "Maria",
      "Michaela", "Mikaela", "Nanna", "Olivia", "Sally", "Sara",
      "Ulla-Lena", "Veronica",
    ],
    male: [
      "Anders", "Karl", "Henrik", "Folke", "Johan", "Erik",
      "Viktor", "August", "Emanuel", "Georg", "Gunnar", "Gustaf",
      "Lars", "Mats", "Peter", "Robert", "Wilhelm", "Alexander",
      "Anton", "Daniel", "Eliel", "Emil", "Gabriel", "Hugo",
      "Joel", "Jonas", "Julius", "Matthias", "Mikael", "Oskar",
      "Paul", "Roger", "Runar", "Stig", "Uno", "Werner",
      "Adam", "Adolf", "Åke", "Alarik", "Albert", "Aldur",
      "Algot", "Alonzo", "André", "Arthur", "Arvid", "Atos",
      "Axel", "Berndt",
    ],
    family: [
      "Eriksson", "Karlsson", "Lundberg", "Salminen", "Jansson", "Andersson",
      "Häggblom", "Johansson", "Lindberg", "Mattson", "Mattsson", "Sjölund",
      "Brotherus", "Brummer", "Gustafsson", "Holmberg", "Holmén", "Jorpes",
      "Lindqvist", "Nordgren", "Nordlund", "Pettersson", "Slotte", "Sundman",
      "Sundström", "Wallin", "Wirtanen", "Abrahamsson", "Åkerman", "Alander",
      "Alanus", "Backman", "Bengtz", "Bergman", "Bergroth", "Björklund",
      "Blomqvist", "Bomanson", "Bonds", "Britschgi", "Carpelan", "Chmielowski",
      "Cromwell-Morgan", "Danielsson", "Dührkop", "Dyggve", "Ehn", "Eklund",
      "Eliasson", "Englund", "Engman", "Erikson", "Federley", "Fellman",
      "Fliflet", "Fontell", "Forsberg", "Granskog", "Grönroos", "Gustavson",
      "Gustavsson", "Hägerstrand", "Hagman", "Hallsten", "Hansell", "Hartman",
      "Hassel", "Hausen", "Heikel", "Hellberg", "Höglund", "Högman",
      "Holmsten", "Hongell", "Hultin",
    ],
  },
  DK: {
    female: [
      "Anna", "Anne", "Karen", "Mette", "Louise", "Kirsten",
      "Elisabeth", "Julie", "Charlotte", "Maria", "Ellen", "Sophie",
      "Johanne", "Else", "Caroline", "Sofie", "Ingeborg", "Margrethe",
      "Hanne", "Birgitte", "Christine", "Inger", "Lene", "Bodil",
      "Lise", "Ida", "Amalie", "Mathilde", "Emilie", "Eva",
      "Lone", "Vibeke", "Camilla", "Christina", "Helle", "Signe",
      "Ulla", "Astrid", "Susanne", "Inge", "Pernille", "Frederikke",
      "Rikke", "Agnete", "Marianne", "Grethe", "Henriette", "Line",
      "Gerda", "Katrine",
    ],
    male: [
      "Christian", "Peter", "Hans", "Carl", "Frederik", "Niels",
      "Jens", "Jørgen", "Johan", "Erik", "Henrik", "Johannes",
      "Andreas", "Søren", "Poul", "Anders", "Knud", "Jacob",
      "Thomas", "Michael", "Ole", "Emil", "Lars", "Vilhelm",
      "Martin", "Otto", "Morten", "Rasmus", "Georg", "Aage",
      "Svend", "Mads", "Axel", "Valdemar", "Peder", "Ludvig",
      "Jesper", "Harald", "Mogens", "Per", "Julius", "Kristian",
      "John", "August", "Henning", "Theodor", "Holger", "Nicolai",
      "Jan", "Wilhelm",
    ],
    family: [
      "Hansen", "Nielsen", "Jensen", "Andersen", "Pedersen", "Christensen",
      "Larsen", "Sørensen", "Rasmussen", "Jørgensen", "Møller", "Madsen",
      "Olsen", "Thomsen", "Jacobsen", "Lund", "Knudsen", "Christiansen",
      "Poulsen", "Kristensen", "Johansen", "Schmidt", "Bang", "Mortensen",
      "Frederiksen", "Clausen", "Dahl", "Jakobsen", "Meyer", "Müller",
      "Bruun", "Lange", "Koch", "Lassen", "Mikkelsen", "Friis",
      "Simonsen", "Fischer", "Kjær", "Olesen", "Holst", "Eriksen",
      "Iversen", "Schou", "Svendsen", "Carlsen", "Jessen", "Andreasen",
      "Berg", "Henriksen", "Nissen", "Winther", "Nørgaard", "Østergaard",
      "Søndergaard", "Bech", "Lind", "Ussing", "Jespersen", "Mogensen",
      "Moltke", "Bertelsen", "Laursen", "Melchior", "Aagaard", "Fenger",
      "Fabricius", "Munk", "Skeel", "Andresen", "Bloch", "Brandt",
      "Jeppesen", "Kristiansen", "Ravn",
    ],
  },
  FO: {
    female: [
      "Ann", "Anna", "Ebba", "Elsa", "Fanny", "Jóna",
      "Julia", "Katrina", "Liv", "Margunn", "Maria", "Milja",
      "Monika", "Rebekka", "Sara", "Sigrid", "Annika", "Katrin",
      "Marjun", "Beinta", "Rannvá", "Heidi", "Elin", "Lív",
    ],
    male: [
      "Gunnar", "Jens", "John", "Marni", "Eli", "Erling",
      "Gilli", "Hans", "Heðin", "Heini", "Henning", "Hörður",
      "Jákup", "Jan", "Jóannes", "Julian", "Karl", "Kristian",
      "Magnus", "Mattias", "Olivur", "Páll", "Peter", "Pétur",
      "Regin", "René", "Rúni", "Sigurd", "Tróndur", "Trygvi",
      "Jógvan", "Høgni", "Ólavur", "Kári", "Jónas",
    ],
    family: [
      "Hansen", "Jacobsen", "Thomsen", "Danielsen", "Djurhuus", "Nielsen",
      "Abrahamsen", "Arge", "Dali", "Eriksen", "Hammershaimb", "Henningsen",
      "Hentze", "Hveding", "Jakobsen", "Joensen", "Johannesen", "Johansen",
      "Johnsson", "Kalsø", "Klakstein", "Knudsen", "Lavard", "Lindholm",
      "Magnussen", "Mortensen", "Müller", "Olsen", "Rasmussen", "Simonsen",
      "Vatnhamar", "Vatnsdal",
    ],
  },
  GG: {
    female: [
      "Mary", "Alice", "Marjorie", "Ann", "Annabelle", "Annie",
      "Beatrice", "Caroline", "Charlotte", "Chloe", "Claire", "Clare",
      "Claudia", "Crystal", "Edith", "Elena", "Elise", "Eliza",
      "Elizabeth", "Ellen", "Emma", "Fanny", "Francesca", "Harriet",
      "Heather", "Helen", "Jayne", "Jill", "Karen", "Krista",
      "Linda", "Lisa", "Mabel", "Margaret", "Maria", "Marianne",
      "Martha", "Martine", "Maud", "Maya", "Meg", "Molly",
      "Olivia", "Patricia", "Pauline", "Philipa", "Rebecca", "Rosie",
      "Sally", "Sarah",
    ],
    male: [
      "John", "Peter", "Thomas", "William", "James", "Charles",
      "Paul", "Frederick", "Henry", "Richard", "Chris", "Christopher",
      "George", "Herbert", "Lee", "Philippe", "Robert", "Andrew",
      "David", "Ernest", "Hugh", "Joshua", "Michael", "Oliver",
      "Philip", "Pierre", "Sam", "Victor", "Adrian", "Alan",
      "Alastair", "Albert", "Alex", "Alexander", "Ambrose", "Andy",
      "Arthur", "Barry", "Bill", "Billy", "Bramwell", "Brayley",
      "Cameron", "Carl", "Craig", "Cyril", "Dale", "Darren",
      "Dave", "Denys",
    ],
    family: [
      "Le Tissier", "Brock", "Chalmers", "Collings", "Le Mesurier", "Ozanne",
      "Saumarez", "Allen", "Beaumont", "Carey", "Dotrice", "Jones",
      "Le Lievre", "Le Tocq", "Lukis", "MacCulloch", "Priaulx", "Rhodes",
      "Wood", "Allan", "Ansted", "Arscott", "Austin", "Avard",
      "Banks", "Barber", "Bennett", "Benoît", "Bidmead", "Bishop",
      "Black", "Bowditch", "Brehaut", "Breton", "Caire", "Catelinet",
      "Clark", "Collas", "Collenette", "Collett", "Collins", "Colquhoun",
      "Cooney", "Cooper", "Crossan", "Davey", "Davidson", "Davies",
      "De Garis", "De Gruchy", "de La Rue", "Deverell", "Dobree", "Dobrée",
      "Doyle", "Edwards", "Ellis", "Evans", "Falla", "Ferbrache",
      "Finch", "Fink", "Fleure", "Foss", "Fox", "Frampton",
      "Fraser", "Frossard", "Garland", "Gauvain", "Gosselin", "Grant",
      "Grut", "Hamon", "Hansen",
    ],
  },
  GI: {
    female: [
      "Elizabeth", "Charlotte", "Helen", "Susan", "Alexandra", "Alison",
      "Amanda", "Amy", "Annie", "Aurelia", "Ava", "Carolina",
      "Caroline", "Catalina", "Christine", "Daniella", "Davina", "Eliza",
      "Emily", "Eva", "Geraldine", "Isobel", "Jane", "Jessica",
      "Kaiane", "Lauren", "Lenka", "Loise", "Lucy", "Margaret",
      "Marion", "Marjorie", "Marlene", "Mary", "May", "Megan",
      "Michelle", "Niamh", "Nikki", "Nina", "Olga", "Raquel",
      "Rosaleen", "Rosalind", "Samantha", "Tiffany", "Viola", "Willa",
      "Yanira", "Yvette",
    ],
    male: [
      "John", "Charles", "Joseph", "Juan", "Thomas", "Albert",
      "Edward", "George", "Nicholas", "Peter", "Anthony", "Francisco",
      "James", "Robert", "William", "Aaron", "Dylan", "Ethan",
      "Francis", "Henry", "Kyle", "Michael", "Paul", "Adam",
      "Andrew", "Antonio", "Arthur", "Daniel", "Frederick", "Gerard",
      "Gonzalo", "Jack", "Jamie", "Joe", "José", "Justin",
      "Lee", "Philip", "Abraham", "Adrian", "Aidan", "Al",
      "Alain", "Alfred", "Alfredo", "Allen", "Alonso", "Álvaro",
      "Ambrose", "Andres",
    ],
    family: [
      "Casciaro", "Edwards", "Finlayson", "Levy", "Caruana", "Chipolina",
      "Creswell", "Cruz", "Duarte", "Forbes", "Galliano", "García",
      "Hernandez", "Isola", "Macpherson", "Parody", "Pérez", "Santos",
      "Adams-Ray", "Addams", "Alcantara", "Aldorino", "Allen", "Amigo",
      "Asensio", "Avellano", "Azopardi", "Azzopardi", "Bacarisas", "Balban",
      "Baldachino", "Barbara", "Barnett", "Belchem", "Bell", "Bellairs",
      "Bellocq", "Borge", "Bosio", "Bossano", "Bossino", "Boulton",
      "Bowen", "Bowlby", "Bowles", "Bradburn", "Britto", "Browne",
      "Bruzon", "Buhagiar", "Bunbury", "Camacho", "Campbell", "Cardwell",
      "Carneiro", "Carreras", "Cartwright", "Cary", "Castle", "Chiappe",
      "Clinton", "Cook", "Coombes", "Cortes", "Costa", "Cowper",
      "Craig", "Dacres", "Del Agua", "Dignan", "Donnet", "Dudley",
      "Ellul-Hammond", "Feetham", "Felice",
    ],
  },
  IM: {
    female: [
      "Margaret", "Elizabeth", "Anna", "Jane", "Annie", "Clare",
      "Esther", "Laura", "Sophia", "Amelia", "Amy", "Angela",
      "Anne", "Araminta", "Becky", "Brianne", "Christine", "Cristen",
      "Dorothy", "Edith", "Eleanor", "Emily", "Eva", "Fanny",
      "Gwen", "Hannah", "Hazel", "Helen", "Hilary", "Isla",
      "Jennifer", "Jessica", "Josephine", "Julie", "Kate", "Kathleen",
      "Kimberley", "Letitia", "Louise", "Millie", "Mona", "Nelly",
      "Nina", "Nola", "Rosamund", "Ruth", "Samantha", "Yasmin",
      "Zoe",
    ],
    male: [
      "John", "William", "David", "Robert", "Edward", "Mark",
      "Thomas", "Charles", "James", "Hugh", "Joseph", "Peter",
      "Arthur", "Frank", "Alan", "Harry", "Richard", "Archibald",
      "Brian", "Chris", "Christopher", "Daniel", "Dave", "Derek",
      "Edmund", "Ernest", "Frederick", "George", "Juan", "Kevin",
      "Michael", "Paul", "Steve", "Stewart", "Adam", "Adrian",
      "Agnew", "Alfred", "Allan", "Andrew", "Andy", "Arnold",
      "Baldwin", "Barry", "Benjamin", "Bernard", "Bertram", "Bill",
      "Bob", "Clifford",
    ],
    family: [
      "Christian", "Moore", "Quayle", "Gill", "Kelly", "Brown",
      "Faragher", "Gibb", "Kermode", "Murray", "Quine", "Walker",
      "Adams", "Callister", "Callow", "Creer", "Crowe", "Forbes",
      "Garrett", "Gawne", "Gell", "Higgins", "Keggin", "Lowey",
      "Mansell", "McCombe", "Morrison", "Robinson", "Russell", "Swynnerton",
      "Teare", "Wilks", "Anderson", "Armstrong", "Ashton", "Atherton",
      "Bacon", "Barks", "Beecroft", "Bell", "Bellis", "Bennett",
      "Binney", "Blackley", "Bott", "Brand", "Branford", "Brennan",
      "Bridson", "Buchan", "Buckley", "Burke", "Burns", "Cain",
      "Caine", "Cameron", "Cannell", "Cavendish", "Clague", "Clarke",
      "Collister", "Cooper", "Corkill", "Corlett", "Costain", "Cowley",
      "Craine", "Cregeen", "Crellin", "Crompton", "Cubbon", "Cummins",
      "Curghey", "Dacre", "Davidson",
    ],
  },
  JE: {
    female: [
      "Elizabeth", "Ann", "Caroline", "Ellen", "Florence", "Kathleen",
      "Agnes", "Alice", "Alison", "Alma", "Amélia", "Anthea",
      "Augusta", "Babette", "Carly", "Carol", "Cecilia", "Danielle",
      "Edith", "Elinor", "Elise", "Emilie", "Emily", "Fanny",
      "Fleur", "Frances", "Helen", "Jean", "Jenny", "Joan",
      "Juanita", "Judith", "Karen", "Katharine", "Kimberley", "Kristina",
      "Lilian", "Lillie", "Lindsey", "Louisa", "Louise", "Margaret",
      "Marguerite", "Marian", "Mariana", "Mary", "Monique", "Nerina",
      "Rachel", "Rose",
    ],
    male: [
      "John", "William", "George", "Thomas", "Charles", "Jean",
      "Philip", "Philippe", "Robert", "Edward", "Henry", "James",
      "Daniel", "Francis", "Paul", "Alexander", "Jack", "Arthur",
      "Clement", "Frank", "Frederick", "Herbert", "Alfred", "Andrew",
      "Augustus", "Bob", "Cameron", "Cecil", "Dave", "Édouard",
      "Edwin", "Ferdinand", "Guy", "Hugh", "Kenneth", "Mark",
      "Matt", "Matthew", "Michael", "Oliver", "Peter", "Phil",
      "Richard", "Roger", "Steve", "Ted", "Tim", "Tom",
      "Trevor", "Alastair",
    ],
    family: [
      "Gaudin", "Le Breton", "Bailhache", "Carteret", "Cavill", "Dumaresq",
      "Renouf", "Atkinson", "Davis", "Ford", "Hill", "Jones",
      "Le Boutillier", "Le Sueur", "Lemprière", "Marett", "Oliver", "Perrot",
      "Pitman", "Savage", "Smith", "Vardon", "Walker", "Adams",
      "Adlington", "Agathangelou", "Anderson", "Ara", "Ashton", "Avard",
      "Banahan", "Banks", "Barsby", "Bartley", "Bedford", "Bedwell",
      "Bennett", "Benson", "Bettison", "Bignell", "Boot", "Boycott",
      "Boyle", "Brennan", "Buesnel", "Campbell", "Carrel", "Carrington",
      "Chads", "Chevalier", "Child Villiers", "Clare", "Clayton", "Close",
      "Cole", "Connolly", "Cook", "Coutanche", "Coxon", "d'Auvergne",
      "Dalgliesh", "Davey", "Delamain", "Dickens", "Dix", "Dixon",
      "Dorey", "Downs", "Durell", "Etienne", "Fallaize", "Falle",
      "Farley", "Farnham", "Fyers",
    ],
  },
} as const

export function isEuropeIslandCountry(code: string): code is keyof typeof europeIslandNames {
  return Object.hasOwn(europeIslandNames, code)
}
