// Reviewed Latin-script name components from the pinned Europe candidate snapshot; see docs/geographic-data.md.
export const europeReviewedNames = {
  AD: {
    female: [
      'Maria', 'Joana', 'Caterina', 'Laura', 'Anna', 'Marta',
      'Antònia', 'Margarida', 'Alba', 'Cristina', 'Laia', 'Meritxell',
      'Ariadna', 'Claudia', 'Clàudia', 'Paula', 'Aina', 'Ana',
      'Carla', 'Isabel', 'Mireia', 'Montserrat', 'Olga', 'Silvia',
      'Andrea', 'Antonia', 'Bernadeta', 'Carolina', 'Clara', 'Conxita',
      'Eva', 'Fiona', 'Francina', 'Georgia', 'Georgina', 'Jennifer',
      'Judit', 'Júlia', 'Lea', 'Mariona', 'Martina', 'Míriam',
      'Mònica', 'Roser', 'Sara', 'Sílvia', 'Teresa', 'Ada',
      'Ainhoa', 'Alexandra', 'Carlota', 'Emma',
    ],
    male: [
      'Joan', 'Jordi', 'Marc', 'Xavier', 'Josep', 'Francesc',
      'Albert', 'Antoni', 'David', 'Carles', 'Eric', 'Daniel',
      'Alex', 'Enric', 'Manuel', 'Oriol', 'Toni', 'Carlos',
      'Emili', 'Gerard', 'Guillem', 'Jesús', 'Joel', 'Oscar',
      'Sergi', 'Victor', 'Víctor', 'Alexandre', 'Andreu', 'Cristian',
      'Esteve', 'Hugo', 'Jaume', 'Javier', 'José', 'Juan',
      'Julià', 'Miquel', 'Òscar', 'Pau', 'Pere', 'Ramon',
      'Aaron', 'Adrià', 'Alain', 'Andrés', 'Armand', 'Biel',
      'Boris', 'Francesco', 'Jan', 'Martí',
    ],
    family: [
      'Martínez', 'Fernández', 'García', 'Riba', 'Sánchez', 'Areny',
      'González', 'López', 'Call', 'Pérez', 'Rossell', 'Serra',
      'Tomas', 'Albós', 'Álvarez', 'Armengol', 'Colom', 'Font',
      'Gómez', 'Grau', 'Jiménez', 'Llovera', 'Martí', 'Moreno',
      'Naudina', 'Quera', 'Rodriguez', 'Rodríguez', 'Rubio', 'Torres',
      'Barcia', 'Bastida', 'Blanco', 'Calvo', 'Cartes', 'Casal',
      'de Oliveira', 'Espot', 'Esteve', 'Godoy', 'Guirao', 'Huisman',
      'Jordana', 'Lima', 'Marfany', 'Marín', 'Márquez', 'Marsol',
      'Martinez', 'Mas', 'Montanya', 'Obiols', 'Pintat', 'Pol',
      'Pons', 'Pujol', 'Ramírez', 'Reig', 'Rodrigues', 'Romero',
      'Rossella', 'San Nicolás', 'Silva', 'Soldevila', 'Teixidó', 'Tomassa',
      'Vales', 'Vidala', 'Vieira', 'Acosta', 'Aguilar', 'Aláez',
      'Alavedra', 'Alvarez', 'Alves', 'Amigó', 'Amphoux', 'Andorrà',
      'Andres', 'Andreu', 'Anglada', 'Antor', 'Aranda', 'Arasanz',
      'Arce', 'Arias', 'Ariza', 'Ateca', 'Ayala', 'Aymamí',
      'Aymar', 'Babot', 'Badana', 'Barios', 'Barra', 'Bartolome',
      'Bartolomé', 'Benet', 'Benlloch', 'Bernadó',
    ],
  },
  AL: {
    female: [
      'Anila', 'Alma', 'Albana', 'Drita', 'Adelina', 'Sara',
      'Valbona', 'Aida', 'Besa', 'Lindita', 'Mirela', 'Vera',
      'Arta', 'Brunilda', 'Dea', 'Diana', 'Elsa', 'Klea',
      'Kristina', 'Majlinda', 'Matilda', 'Rovena', 'Rudina', 'Valentina',
      'Adela', 'Alketa', 'Anita', 'Anna', 'Anxhela', 'Aurela',
      'Aurora', 'Elisa', 'Elvira', 'Enkelejda', 'Greta', 'Luljeta',
      'Merita', 'Mimoza', 'Mira', 'Nora', 'Ornela', 'Pavlina',
      'Rita', 'Shpresa', 'Suela', 'Albina', 'Ana', 'Antoneta',
      'Blerta', 'Brikena',
    ],
    male: [
      'Ali', 'Agim', 'Fatmir', 'Alfred', 'Arben', 'Alban',
      'Albert', 'Sokol', 'Adrian', 'Edmond', 'Skënder', 'Dhimitër',
      'Altin', 'Artan', 'Ervin', 'Andrea', 'Fatos', 'Gëzim',
      'Rexhep', 'Ahmet', 'Robert', 'Anton', 'Erjon', 'Gjon',
      'Vasil', 'Arjan', 'Bujar', 'Daniel', 'Hasan', 'Ilir',
      'Julian', 'Jurgen', 'Kujtim', 'Mario', 'Mehmet', 'Mustafa',
      'Petrit', 'Qemal', 'Spiro', 'Ylli', 'Andi', 'Artur',
      'Elvis', 'Florian', 'Gjergj', 'Klodian', 'Petro', 'Sotir',
      'Agron', 'Albi',
    ],
    family: [
      'Hoxha', 'Koçi', 'Berisha', 'Bushati', 'Selmani', 'Shehu',
      'Krasniqi', 'Rama', 'Koka', 'Luarasi', 'Mehmeti', 'Sokoli',
      'Ymeri', 'Aleksi', 'Basha', 'Beqiri', 'Dervishi', 'Dule',
      'Frashëri', 'Furxhi', 'Haxhiu', 'Kadiu', 'Nimani', 'Pashaj',
      'Shala', 'Tafaj', 'Agolli', 'Arapi', 'Asllani', 'Balla',
      'Bardhi', 'Begolli', 'Biçaku', 'Bitri', 'Çaushi', 'Doda',
      'Malaj', 'Meksi', 'Morina', 'Muça', 'Sejdini', 'Spahiu',
      'Starova', 'Zogu', 'Aliaj', 'Bylykbashi', 'Çaçi', 'Çami',
      'Çoba', 'Deda', 'Domi', 'Gashi', 'Gjoni', 'Hajdari',
      'Halili', 'Jubani', 'Konomi', 'Kuçi', 'Laçi', 'Lleshi',
      'Muçaj', 'Toptani', 'Ahmedi', 'Ahmeti', 'Begeja', 'Bisha',
      'Blloshmi', 'Borova', 'Boshnjaku', 'Bulku', 'Bushi', 'Cani',
      'Çela', 'Çobani', 'Çuçi', 'Curri', 'Daja', 'Dauti',
      'Dibra', 'Erebara', 'Gjata', 'Gjoka', 'Halilaj', 'Haliti',
      'Hasanaj', 'Jaku', 'Kabashi', 'Karaj', 'Kodra', 'Kondi',
      'Kumbaro', 'Lala', 'Leka', 'Lika', 'Lluka', 'Luli',
      'Marku', 'Martini', 'Mata', 'Mema',
    ],
  },
  AT: {
    female: [
      'Maria', 'Elisabeth', 'Anna', 'Barbara', 'Eva', 'Katharina',
      'Julia', 'Johanna', 'Christine', 'Lisa', 'Susanne', 'Karin',
      'Claudia', 'Michaela', 'Brigitte', 'Andrea', 'Sabine', 'Helene',
      'Monika', 'Martina', 'Ingrid', 'Renate', 'Franziska', 'Stefanie',
      'Marianne', 'Edith', 'Daniela', 'Helga', 'Sandra', 'Gabriele',
      'Erika', 'Sonja', 'Alexandra', 'Petra', 'Melanie', 'Nina',
      'Ilse', 'Christina', 'Doris', 'Verena', 'Elfriede', 'Sophie',
      'Irene', 'Rosa', 'Sarah', 'Ulrike', 'Ursula', 'Veronika',
      'Hilde', 'Bettina',
    ],
    male: [
      'Franz', 'Josef', 'Karl', 'Hans', 'Peter', 'Rudolf',
      'Johann', 'Michael', 'Anton', 'Wolfgang', 'Thomas', 'Ernst',
      'Robert', 'Martin', 'Christian', 'Alfred', 'Andreas', 'Friedrich',
      'Otto', 'Georg', 'Gerhard', 'Paul', 'Herbert', 'Fritz',
      'Wilhelm', 'Alexander', 'Helmut', 'Hermann', 'Heinrich', 'Kurt',
      'Richard', 'Leopold', 'Erich', 'Alois', 'Stefan', 'Markus',
      'Max', 'Ludwig', 'Johannes', 'Christoph', 'Adolf', 'Heinz',
      'Ferdinand', 'Manfred', 'Werner', 'Bernhard', 'Florian', 'Erwin',
      'Gustav', 'Eduard',
    ],
    family: [
      'Müller', 'Fischer', 'Bauer', 'Wagner', 'Huber', 'Berger',
      'Mayer', 'Gruber', 'Moser', 'Schwarz', 'Schneider', 'Steiner',
      'Fuchs', 'Weber', 'Hofer', 'Wolf', 'Schmidt', 'Mayr',
      'Schmid', 'Winkler', 'Brunner', 'Leitner', 'Pichler', 'Aigner',
      'Egger', 'Baumgartner', 'Eder', 'Graf', 'Haas', 'Weiss',
      'Auer', 'Lang', 'Maier', 'Koller', 'Kraus', 'Wimmer',
      'Richter', 'Frank', 'Seidl', 'Klein', 'Koch', 'Reiter',
      'Schuster', 'Binder', 'König', 'Ebner', 'Posch', 'Adler',
      'Hofmann', 'Lechner', 'Kaiser', 'Strasser', 'Deutsch', 'Neumann',
      'Roth', 'Zimmermann', 'Hauser', 'Hoffmann', 'Holzer', 'Kaufmann',
      'Riedl', 'Böhm', 'Strobl', 'Winter', 'Haider', 'Beer',
      'Hartmann', 'Kern', 'Stadler', 'Werner', 'Angerer', 'Reisinger',
      'Hofbauer', 'Kofler', 'Pollak', 'Wieser', 'Fink', 'Lackner',
      'Maurer', 'Fritz', 'Rauch', 'Wallner', 'Braun', 'Langer',
      'Rainer', 'Resch', 'Unger', 'Baumann', 'Jelinek', 'Krenn',
      'Ortner', 'Schindler', 'Singer', 'Walter', 'Fellner', 'Hahn',
      'Lehner', 'Neuwirth', 'Stein', 'Herzog',
    ],
  },
  BA: {
    female: [
      'Alma', 'Maja', 'Jelena', 'Emina', 'Selma', 'Aida',
      'Dragana', 'Ivana', 'Amela', 'Azra', 'nerea', 'Aleksandra',
      'Amra', 'Ana', 'Jasmina', 'Marija', 'Marina', 'Melisa',
      'Tamara', 'Tanja', 'Vesna', 'Adna', 'Ajla', 'Andrea',
      'Biljana', 'Milica', 'Nejra', 'Sanja', 'Tatjana', 'Arijana',
      'Bisera', 'Ema', 'Gordana', 'Irma', 'Jadranka', 'Jovana',
      'Katarina', 'Lejla', 'Martina', 'Milena', 'Nela', 'Sandra',
      'Sara', 'Šejla', 'Svetlana', 'Adriana', 'Alisa', 'Almina',
      'Amila', 'Amina',
    ],
    male: [
      'Adnan', 'Goran', 'Marko', 'Emir', 'Ivan', 'Damir',
      'Dragan', 'Muhamed', 'Haris', 'Edin', 'Josip', 'Nikola',
      'Zoran', 'Jasmin', 'Aleksandar', 'Mladen', 'Bojan', 'Milan',
      'Sead', 'Igor', 'Kenan', 'Admir', 'Dino', 'Dejan',
      'Samir', 'Senad', 'Mehmed', 'Vladimir', 'Mustafa', 'Željko',
      'Alen', 'Darko', 'Ismet', 'Mirza', 'Nedžad', 'Saša',
      'Amar', 'Amir', 'Armin', 'Enes', 'Luka', 'Mario',
      'Nenad', 'Boris', 'Davor', 'Elvir', 'Hasan', 'Ibrahim',
      'Kemal', 'Mirsad',
    ],
    family: [
      'Hadžić', 'Marković', 'Kovačević', 'Duraković', 'Hodžić', 'Janković',
      'Jovanović', 'Karić', 'Smajić', 'Bašić', 'Begić', 'Ćosić',
      'Delić', 'Halilović', 'Ilić', 'Ćatić', 'Đurić', 'Marić',
      'Marjanović', 'Milošević', 'Nikolić', 'Omerović', 'Osmanović', 'Pavlović',
      'Petrović', 'Savić', 'Selimović', 'Aleksić', 'Babić', 'Bešlagić',
      'Cehajic', 'Čolić', 'Dizdarević', 'Filipović', 'Hadžimejlić', 'Hamzić',
      'Husić', 'Kordić', 'Milovanović', 'Muratović', 'Popović', 'Šarić',
      'Simić', 'Tomić', 'Bajić', 'Behmen', 'Bičakčić', 'Čengić',
      'Ćurić', 'Demirović', 'Dujmović', 'Hasić', 'Hrelja', 'Ibrahimović',
      'Ivanković', 'Kapetanović', 'Kovač', 'Kukić', 'Lukić', 'Matić',
      'Mehmedović', 'Mešanović', 'Mikulić', 'Miletić', 'Milićević', 'Muftić',
      'Mujanovic', 'Mujezinović', 'Mujić', 'Nikšić', 'Novaković', 'Omić',
      'Ovčina', 'Šabanović', 'Soldo', 'Stanković', 'Šunjić', 'Sušić',
      'Tadić', 'Tanović', 'Abdić', 'Agić', 'Alibegović', 'Alić',
      'Andrić', 'Avdić', 'Bajraktarević', 'Bajramovic', 'Bajramović', 'Barišić',
      'Barnjak', 'Beganović', 'Begović', 'Berić', 'Bešlić', 'Boban',
      'Boras', 'Bošković', 'Božić', 'Bravo',
    ],
  },
  BE: {
    female: [
      'Anne', 'Maria', 'Sarah', 'Ann', 'Isabelle', 'Hilde',
      'Jeanne', 'Sofie', 'Els', 'Nathalie', 'Catherine', 'Caroline',
      'Françoise', 'Sophie', 'Charlotte', 'Christine', 'Julie', 'Louise',
      'Martine', 'Madeleine', 'Anna', 'Eva', 'Laura', 'Ingrid',
      'Nicole', 'Suzanne', 'Marguerite', 'Barbara', 'Véronique', 'Veerle',
      'Tine', 'Chantal', 'Claire', 'Germaine', 'Monique', 'Alice',
      'Ellen', 'Jacqueline', 'Elisabeth', 'Elke', 'Inge', 'Yvonne',
      'An', 'Sara', 'Lieve', 'Brigitte', 'Marleen', 'Dominique',
      'Hélène', 'Annelies',
    ],
    male: [
      'Joseph', 'Paul', 'Jean', 'Louis', 'Jan', 'Charles',
      'Pierre', 'Henri', 'Albert', 'Jacques', 'François', 'Georges',
      'Marc', 'André', 'Philippe', 'Michel', 'Robert', 'Jules',
      'Marcel', 'Frans', 'Luc', 'Jozef', 'Maurice', 'René',
      'Victor', 'Roger', 'Peter', 'Patrick', 'Léon', 'Fernand',
      'Johan', 'Dirk', 'Willy', 'Karel', 'Guy', 'Bart',
      'Émile', 'Julien', 'Eugène', 'Pieter', 'Herman', 'Alain',
      'Tom', 'Bernard', 'Gustave', 'Auguste', 'Frank', 'Olivier',
      'Wim', 'Arthur',
    ],
    family: [
      'Peeters', 'Janssens', 'Maes', 'Jacobs', 'Willems', 'Claes',
      'Dubois', 'Goossens', 'Lambert', 'Martens', 'Mertens', 'Dupont',
      'De Smet', 'Stevens', 'Janssen', 'Pauwels', 'Vermeulen', 'Hermans',
      'Wouters', 'De Vos', 'Van Damme', 'Aerts', 'Martin', 'Claeys',
      'Segers', 'Devos', 'Wauters', 'Leroy', 'Michiels', 'Van de Velde',
      'De Clercq', 'Hendrickx', 'Bogaerts', 'Delvaux', 'Meyer', 'Petit',
      'Van Assche', 'Baert', 'Coppens', 'Renard', 'Bertrand', 'De Ridder',
      'Desmet', 'François', 'Michel', 'Cools', 'De Pauw', 'Goethals',
      'Verbruggen', 'Lambrecht', 'Leclercq', 'Thomas', 'Timmermans', 'Van Hecke',
      'Verstraete', 'De Meyer', 'Simons', 'Somers', 'Vermeersch', 'De Smedt',
      'Lemmens', 'Adam', 'Bernard', 'Bosmans', 'Joris', 'Thys',
      'Van Acker', 'Bauwens', 'De Cock', 'Lauwers', 'Verschueren', 'Verstraeten',
      'Carlier', 'Coppieters', 'De Bruyn', 'De Groote', 'Mortier', 'Simon',
      'Smets', 'Charlier', 'Geerts', 'Raes', 'Bogaert', 'De Wilde',
      'Dumont', 'Fontaine', 'Servais', 'Bock', 'Henry', 'Heylen',
      'Lejeune', 'Rousseau', 'Verhaegen', 'Daems', 'Franck', 'Seghers',
      'Smet', 'Wellens', 'Allard', 'De Bruyne',
    ],
  },
  CH: {
    female: [
      'Anna', 'Elisabeth', 'Maria', 'Barbara', 'Ursula', 'Nicole',
      'Ruth', 'Anne', 'Sandra', 'Christine', 'Isabelle', 'Marianne',
      'Claudia', 'Monika', 'Eva', 'Laura', 'Karin', 'Sarah',
      'Esther', 'Fabienne', 'Caroline', 'Silvia', 'Susanne', 'Brigitte',
      'Sophie', 'Verena', 'Julia', 'Martina', 'Alice', 'Andrea',
      'Franziska', 'Katharina', 'Catherine', 'Jacqueline', 'Margrit', 'Simone',
      'Daniela', 'Madeleine', 'Sabine', 'Corinne', 'Gertrud', 'Doris',
      'Heidi', 'Manuela', 'Regula', 'Sonja', 'Nathalie', 'Nina',
      'Yvonne', 'Françoise',
    ],
    male: [
      'Johann', 'Hans', 'Peter', 'Jakob', 'Paul', 'Heinrich',
      'Karl', 'Franz', 'Ernst', 'Rudolf', 'Jean', 'Johannes',
      'Daniel', 'Albert', 'Martin', 'Thomas', 'Fritz', 'Alfred',
      'Christian', 'Max', 'Josef', 'Pierre', 'Robert', 'Charles',
      'Louis', 'Andreas', 'Werner', 'Joseph', 'Otto', 'Emil',
      'Georg', 'François', 'Friedrich', 'Michael', 'Urs', 'Henri',
      'Hermann', 'André', 'René', 'Carl', 'David', 'Christoph',
      'Jacques', 'Markus', 'Samuel', 'Georges', 'Marcel', 'Ulrich',
      'Wilhelm', 'Anton',
    ],
    family: [
      'Müller', 'Meyer', 'Keller', 'Schmid', 'Weber', 'Huber',
      'Meier', 'Fischer', 'Frey', 'Moser', 'Schneider', 'Brunner',
      'Baumann', 'Zimmermann', 'Steiner', 'Widmer', 'Wyss', 'Frei',
      'Berger', 'Suter', 'Bachmann', 'Graf', 'Baumgartner', 'Ziegler',
      'Roth', 'Bucher', 'Hess', 'Studer', 'Bühler', 'Tanner',
      'Ammann', 'Gerber', 'Kunz', 'Marti', 'Martin', 'Kaufmann',
      'Egli', 'Favre', 'Hauser', 'Koch', 'Hartmann', 'Burckhardt',
      'Pfister', 'Lehmann', 'Steiger', 'Jenny', 'Lang', 'Lüthi',
      'Seiler', 'Egger', 'Hug', 'Stamm', 'Schweizer', 'Wirz',
      'Hunziker', 'Vogel', 'Fehr', 'Fuchs', 'Sutter', 'Haller',
      'Gasser', 'Michel', 'Schmidt', 'Vogt', 'Zürcher', 'Schnyder',
      'Christen', 'Herzog', 'Kaiser', 'Schwarz', 'Tobler', 'Kuhn',
      'Salis', 'Staub', 'Furrer', 'Hofer', 'Ott', 'Wehrli',
      'Hürlimann', 'Scherrer', 'Bührer', 'Koller', 'Meister', 'Rüegg',
      'Schlatter', 'Beck', 'Leu', 'Maurer', 'Wagner', 'Wolf',
      'Hirzel', 'Hofmann', 'Locher', 'Stocker', 'Zehnder', 'Haas',
      'Weiss', 'Escher', 'Flückiger', 'Walter',
    ],
  },
  DE: {
    female: [
      'Anna', 'Maria', 'Julia', 'Elisabeth', 'Katharina', 'Sabine',
      'Barbara', 'Susanne', 'Ursula', 'Claudia', 'Eva', 'Lisa',
      'Petra', 'Monika', 'Karin', 'Johanna', 'Laura', 'Christine',
      'Anne', 'Franziska', 'Ulrike', 'Sarah', 'Lena', 'Anja',
      'Renate', 'Andrea', 'Brigitte', 'Stefanie', 'Sophie', 'Katrin',
      'Birgit', 'Charlotte', 'Gisela', 'Heike', 'Sandra', 'Nina',
      'Helga', 'Christiane', 'Christina', 'Gabriele', 'Nicole', 'Katja',
      'Ruth', 'Ingrid', 'Kerstin', 'Jana', 'Martina', 'Bettina',
      'Ute', 'Annette',
    ],
    male: [
      'Hans', 'Karl', 'Johann', 'Friedrich', 'Wilhelm', 'Peter',
      'Heinrich', 'Georg', 'Michael', 'Wolfgang', 'Hermann', 'Christian',
      'Ernst', 'Otto', 'Franz', 'Thomas', 'Paul', 'Klaus',
      'Werner', 'Martin', 'Andreas', 'Johannes', 'Rudolf', 'Carl',
      'Gerhard', 'Fritz', 'Heinz', 'Ludwig', 'Jürgen', 'Max',
      'Josef', 'Kurt', 'Helmut', 'Manfred', 'Dieter', 'Christoph',
      'Alexander', 'August', 'Erich', 'Stefan', 'Joachim', 'Alfred',
      'Richard', 'Horst', 'Ulrich', 'Bernhard', 'Herbert', 'Matthias',
      'Gustav', 'Robert',
    ],
    family: [
      'Müller', 'Schmidt', 'Fischer', 'Schneider', 'Meyer', 'Weber',
      'Becker', 'Wagner', 'Hoffmann', 'Richter', 'Koch', 'Schulz',
      'Wolf', 'Bauer', 'Schröder', 'Zimmermann', 'Schwarz', 'Hartmann',
      'Klein', 'Neumann', 'Lange', 'Schäfer', 'Lehmann', 'Braun',
      'Werner', 'Mayer', 'Krause', 'Fuchs', 'Krüger', 'Hofmann',
      'Vogel', 'Wolff', 'Herrmann', 'Köhler', 'Hahn', 'Roth',
      'Schulze', 'Schmitt', 'Berger', 'Keller', 'Albrecht', 'Günther',
      'Schmid', 'Schmitz', 'Peters', 'Schubert', 'Kaiser', 'König',
      'Beck', 'Friedrich', 'Walter', 'Lang', 'Huber', 'Meier',
      'Baumann', 'Simon', 'Franke', 'Otto', 'Ludwig', 'Frank',
      'Winter', 'Jung', 'Lorenz', 'Haas', 'Maier', 'Sommer',
      'Möller', 'Winkler', 'Ziegler', 'Stein', 'Barth', 'Brandt',
      'Martin', 'Ritter', 'Weiß', 'Schreiber', 'Vogt', 'Gemmingen',
      'Arnold', 'Beyer', 'Scholz', 'Busch', 'Horn', 'Kraus',
      'Schuster', 'Pfeiffer', 'Voigt', 'Bach', 'Kramer', 'Böhm',
      'Pohl', 'Bergmann', 'Bock', 'Graf', 'Hübner', 'Fiedler',
      'Kühn', 'Engel', 'Walther', 'Kuhn',
    ],
  },
  EE: {
    female: [
      'Tiina', 'Anne', 'Katrin', 'Mari', 'Maria', 'Tiiu',
      'Reet', 'Aino', 'Anna', 'Linda', 'Anu', 'Ene',
      'Liis', 'Kadri', 'Piret', 'Mare', 'Sirje', 'Ülle',
      'Maie', 'Karin', 'Eve', 'Helle', 'Liina', 'Mai',
      'Malle', 'Olga', 'Riina', 'Salme', 'Leida', 'Eva',
      'Triin', 'Laine', 'Liisa', 'Merike', 'Marika', 'Evi',
      'Pille', 'Kai', 'Kersti', 'Maret', 'Silvia', 'Helgi',
      'Hilda', 'Maarja', 'Krista', 'Mall', 'Lea', 'Juta',
      'Ann', 'Anneli',
    ],
    male: [
      'Jaan', 'Aleksander', 'Jüri', 'Karl', 'Johannes', 'Peeter',
      'August', 'Rein', 'Toomas', 'Andres', 'Eduard', 'Ants',
      'Paul', 'Juhan', 'Heino', 'Tõnu', 'Mart', 'Mihkel',
      'Martin', 'Jaak', 'Arnold', 'Enn', 'Hans', 'Tiit',
      'Voldemar', 'Endel', 'Lembit', 'Elmar', 'Ülo', 'Vello',
      'Ilmar', 'Mati', 'Oskar', 'Priit', 'Viktor', 'Urmas',
      'Artur', 'Margus', 'Rudolf', 'Indrek', 'Kristjan', 'Tõnis',
      'Kalju', 'Vladimir', 'Alfred', 'Richard', 'Arvo', 'Uno',
      'Raivo', 'Toivo',
    ],
    family: [
      'Tamm', 'Saar', 'Sepp', 'Mägi', 'Kask', 'Oja',
      'Kukk', 'Kaasik', 'Lepik', 'Rebane', 'Raudsepp', 'Koppel',
      'Kull', 'Luik', 'Ots', 'Liiv', 'Kallas', 'Kivi',
      'Teder', 'Kuusk', 'Palm', 'Ilves', 'Pärn', 'Jõgi',
      'Kuusik', 'Lepp', 'Mölder', 'Peterson', 'Vaher', 'Laur',
      'Mets', 'Jürgenson', 'Karu', 'Põder', 'Männik', 'Arro',
      'Saks', 'Kõiv', 'Laas', 'Sarv', 'Kangro', 'Allik',
      'Lõhmus', 'Raud', 'Kütt', 'Unt', 'Hallik', 'Kangur',
      'Orav', 'Sild', 'Kolk', 'Annus', 'Johanson', 'Puusepp',
      'Sarapuu', 'Aavik', 'Roots', 'Toom', 'Adamson', 'Lill',
      'Luts', 'Mõttus', 'Raid', 'Jakobson', 'Kruus', 'Martinson',
      'Nurk', 'Õunapuu', 'Tõnisson', 'Martin', 'Ruus', 'Järv',
      'Kärner', 'Leppik', 'Parts', 'Talts', 'Anton', 'Kalda',
      'Mikk', 'Tomson', 'Väli', 'Eller', 'Kokk', 'Koort',
      'Kurvits', 'Mitt', 'Õun', 'Rand', 'Roos', 'Uibo',
      'Aru', 'Gross', 'Hansen', 'Kalm', 'Abel', 'Lember',
      'Maasik', 'Põld', 'Rätsep', 'Talvik',
    ],
  },
  ES: {
    female: [
      'María', 'Maria', 'Ana', 'Carmen', 'Marta', 'Isabel',
      'Cristina', 'Laura', 'Teresa', 'Pilar', 'Rosa', 'Anna',
      'Montserrat', 'Elena', 'Núria', 'Eva', 'Mercedes', 'Sara',
      'Paula', 'Beatriz', 'María José', 'Raquel', 'Carme', 'Alicia',
      'Irene', 'Dolores', 'Esther', 'Josefa', 'Silvia', 'Patricia',
      'Francisca', 'Marina', 'Luisa', 'Julia', 'Sandra', 'Blanca',
      'Alba', 'Susana', 'Margarita', 'Clara', 'Antonia', 'Natalia',
      'Sonia', 'Mercè', 'Juana', 'Lucía', 'María Isabel', 'Carolina',
      'Manuela', 'Victoria',
    ],
    male: [
      'José', 'Manuel', 'Juan', 'Antonio', 'Francisco', 'Josep',
      'Luis', 'Pedro', 'Joan', 'Carlos', 'Miguel', 'Fernando',
      'Rafael', 'Javier', 'Jesús', 'Ramón', 'José María', 'Enrique',
      'Ángel', 'Vicente', 'Joaquín', 'Francesc', 'Jordi', 'David',
      'Antoni', 'Eduardo', 'José Luis', 'Diego', 'Pablo', 'José Antonio',
      'Alberto', 'Daniel', 'Ignacio', 'Jaume', 'Santiago', 'Ricardo',
      'Pere', 'Salvador', 'Emilio', 'Alejandro', 'Alfonso', 'Mariano',
      'Andrés', 'Julio', 'Ramon', 'Jorge', 'Lluís', 'Miquel',
      'Xavier', 'Josep Maria',
    ],
    family: [
      'García', 'Martínez', 'Fernández', 'González', 'López', 'Rodríguez',
      'Pérez', 'Sánchez', 'Gómez', 'Álvarez', 'Martín', 'Ruiz',
      'Gil', 'Alonso', 'Díaz', 'Moreno', 'Hernández', 'Muñoz',
      'Jiménez', 'Torres', 'Romero', 'Navarro', 'Vázquez', 'Blanco',
      'Vidal', 'Serrano', 'Suárez', 'Ramos', 'Castro', 'Domínguez',
      'Ortega', 'Iglesias', 'Sanz', 'Delgado', 'Ortiz', 'Rubio',
      'Soler', 'Morales', 'Molina', 'Serra', 'Lozano', 'Núñez',
      'Ramírez', 'Puig', 'Marín', 'Otero', 'Martí', 'Peña',
      'Grau', 'Garcia', 'Méndez', 'Calvo', 'Santos', 'Vila',
      'Martin', 'Costa', 'Prieto', 'Pascual', 'Bosch', 'Rey',
      'Casas', 'Ibáñez', 'Roca', 'Arias', 'Campos', 'Pons',
      'Herrero', 'Durán', 'Mas', 'Pujol', 'Font', 'Gallego',
      'Nieto', 'Varela', 'Aguilar', 'Flores', 'Franco', 'Lorenzo',
      'Medina', 'Cano', 'Pardo', 'Martinez', 'Velasco', 'Giménez',
      'Pastor', 'Carrasco', 'Castillo', 'Guerrero', 'Díez', 'Riera',
      'Sala', 'Cruz', 'Caballero', 'Roig', 'Montero', 'Soto',
      'Aguirre', 'Cortés', 'Herrera', 'Blasco',
    ],
  },
  FI: {
    female: [
      'Maria', 'Anna', 'Johanna', 'Elina', 'Hanna', 'Leena',
      'Helena', 'Tiina', 'Liisa', 'Anne', 'Laura', 'Minna',
      'Sanna', 'Sari', 'Maija', 'Marja', 'Riitta', 'Ulla',
      'Kirsi', 'Heidi', 'Aino', 'Satu', 'Kaisa', 'Tuula',
      'Jaana', 'Eeva', 'Susanna', 'Päivi', 'Pirkko', 'Mari',
      'Katja', 'Marjatta', 'Paula', 'Kristiina', 'Anneli', 'Ritva',
      'Tarja', 'Nina', 'Pirjo', 'Anu', 'Riikka', 'Anni',
      'Merja', 'Sofia', 'Eija', 'Outi', 'Maarit', 'Katri',
      'Sirpa', 'Kirsti',
    ],
    male: [
      'Matti', 'Pekka', 'Antti', 'Mikko', 'Heikki', 'Juha',
      'Juhani', 'Timo', 'Jukka', 'Erkki', 'Kari', 'Lauri',
      'Jussi', 'Hannu', 'Mika', 'Jari', 'Olavi', 'Eero',
      'Markku', 'Seppo', 'Martti', 'Janne', 'Johannes', 'Jaakko',
      'Pentti', 'Ville', 'Jorma', 'Juho', 'Johan', 'Yrjö',
      'Olli', 'Veikko', 'Risto', 'Väinö', 'Paavo', 'Kalle',
      'Eino', 'Sami', 'Tapio', 'Petri', 'Antero', 'Marko',
      'Ari', 'Pertti', 'Harri', 'Tuomas', 'Ilmari', 'Markus',
      'Kaarlo', 'Esko',
    ],
    family: [
      'Korhonen', 'Mäkelä', 'Virtanen', 'Nieminen', 'Laine', 'Lehtonen',
      'Hämäläinen', 'Salminen', 'Koskinen', 'Mäkinen', 'Lehtinen', 'Heinonen',
      'Heikkinen', 'Mattila', 'Järvinen', 'Saarinen', 'Heikkilä', 'Jokinen',
      'Salo', 'Tuominen', 'Kinnunen', 'Aaltonen', 'Rantanen', 'Kallio',
      'Niemi', 'Turunen', 'Laitinen', 'Salonen', 'Savolainen', 'Aalto',
      'Miettinen', 'Räsänen', 'Ahonen', 'Karjalainen', 'Manninen', 'Peltonen',
      'Lahtinen', 'Seppälä', 'Anttila', 'Koivisto', 'Aho', 'Laaksonen',
      'Lehto', 'Vainio', 'Saari', 'Toivonen', 'Halonen', 'Hirvonen',
      'Leppänen', 'Laakso', 'Mikkola', 'Johansson', 'Hänninen', 'Huttunen',
      'Pesonen', 'Koskela', 'Hakala', 'Salmi', 'Mustonen', 'Partanen',
      'Ojala', 'Ahola', 'Lahti', 'Oksanen', 'Niemelä', 'Ikonen',
      'Lappalainen', 'Rinne', 'Mikkonen', 'Kettunen', 'Nyman', 'Peltola',
      'Nurmi', 'Kangas', 'Lindholm', 'Suominen', 'Väisänen', 'Mäki',
      'Rantala', 'Kauppinen', 'Pulkkinen', 'Andersson', 'Jaakkola', 'Leino',
      'Moilanen', 'Immonen', 'Jääskeläinen', 'Tikkanen', 'Heino', 'Hiltunen',
      'Rissanen', 'Kivelä', 'Kokko', 'Kukkonen', 'Rautiainen', 'Tamminen',
      'Viljanen', 'Vuorinen', 'Kokkonen', 'Leinonen',
    ],
  },
  FR: {
    female: [
      'Catherine', 'Françoise', 'Anne', 'Isabelle', 'Sophie', 'Sylvie',
      'Nathalie', 'Jeanne', 'Hélène', 'Christine', 'Louise', 'Martine',
      'Claire', 'Valérie', 'Jacqueline', 'Marguerite', 'Caroline', 'Monique',
      'Florence', 'Suzanne', 'Nicole', 'Dominique', 'Brigitte', 'Cécile',
      'Madeleine', 'Véronique', 'Julie', 'Laurence', 'Céline', 'Geneviève',
      'Anne-Marie', 'Annie', 'Chantal', 'Charlotte', 'Élisabeth', 'Michèle',
      'Virginie', 'Stéphanie', 'Alice', 'Agnès', 'Pauline', 'Camille',
      'Delphine', 'Patricia', 'Pascale', 'Corinne', 'Christiane', 'Mathilde',
      'Marion', 'Laure',
    ],
    male: [
      'Jean', 'Pierre', 'Louis', 'François', 'Charles', 'Jacques',
      'Michel', 'Henri', 'Philippe', 'Paul', 'Joseph', 'André',
      'Georges', 'Alain', 'Claude', 'Bernard', 'Antoine', 'René',
      'Nicolas', 'Maurice', 'Jean-Pierre', 'Christian', 'Robert', 'Olivier',
      'Laurent', 'Patrick', 'Daniel', 'Émile', 'Alexandre', 'Jean-Baptiste',
      'Jules', 'Gérard', 'Frédéric', 'Marcel', 'Christophe', 'Eugène',
      'Marc', 'Thierry', 'Albert', 'Dominique', 'Guillaume', 'Jean-Claude',
      'Pascal', 'Roger', 'Yves', 'Léon', 'Auguste', 'Jean-François',
      'Guy', 'Stéphane',
    ],
    family: [
      'Martin', 'Bernard', 'Durand', 'Petit', 'Dubois', 'Bertrand',
      'Moreau', 'Robert', 'Thomas', 'Michel', 'Richard', 'Fournier',
      'Simon', 'Morel', 'Laurent', 'Bonnet', 'Blanc', 'Leroy',
      'Lefebvre', 'Girard', 'Lambert', 'David', 'Dupont', 'Garnier',
      'Boyer', 'Duval', 'Rousseau', 'Fontaine', 'Vincent', 'Masson',
      'Mathieu', 'Gauthier', 'Aubert', 'Mercier', 'Faure', 'Fabre',
      'Roussel', 'Legrand', 'Vidal', 'Giraud', 'Henry', 'Chevalier',
      'Gautier', 'Guérin', 'Lefèvre', 'Dumas', 'Gaillard', 'Fleury',
      'Perrin', 'Meyer', 'Clément', 'François', 'André', 'Rey',
      'Berger', 'Lemoine', 'Meunier', 'Dumont', 'Joly', 'Nicolas',
      'Lacroix', 'Picard', 'Brun', 'Bourgeois', 'Marchand', 'Blanchard',
      'Brunet', 'Arnaud', 'Leclerc', 'Roy', 'Adam', 'Morin',
      'Boucher', 'Robin', 'Dupuy', 'Carré', 'Deschamps', 'Denis',
      'Renard', 'Barbier', 'Cohen', 'Schneider', 'Guillaume', 'Langlois',
      'Charpentier', 'Rivière', 'Rolland', 'Olivier', 'Colin', 'Germain',
      'Caron', 'Bouvier', 'Bailly', 'Philippe', 'Klein', 'Renaud',
      'Schmitt', 'Jacob', 'Leroux', 'Lucas',
    ],
  },
  GB: {
    female: [
      'Mary', 'Elizabeth', 'Margaret', 'Sarah', 'Jane', 'Helen',
      'Anne', 'Emma', 'Lucy', 'Susan', 'Catherine', 'Caroline',
      'Charlotte', 'Louise', 'Anna', 'Ann', 'Emily', 'Kate',
      'Rachel', 'Alice', 'Laura', 'Alison', 'Barbara', 'Sophie',
      'Rebecca', 'Frances', 'Hannah', 'Dorothy', 'Victoria', 'Claire',
      'Ruth', 'Patricia', 'Janet', 'Joan', 'Fiona', 'Katherine',
      'Jessica', 'Jean', 'Julia', 'Rose', 'Karen', 'Diana',
      'Clare', 'Angela', 'Jennifer', 'Lisa', 'Amy', 'Sally',
      'Alexandra', 'Christine',
    ],
    male: [
      'John', 'David', 'William', 'James', 'Peter', 'George',
      'Michael', 'Robert', 'Richard', 'Charles', 'Paul', 'Thomas',
      'Edward', 'Andrew', 'Mark', 'Henry', 'Arthur', 'Alan',
      'Ian', 'Christopher', 'Anthony', 'Simon', 'Stephen', 'Tom',
      'Jack', 'Harry', 'Martin', 'Alexander', 'Frank', 'Brian',
      'Chris', 'Philip', 'Frederick', 'Joseph', 'Francis', 'Jonathan',
      'Steve', 'Hugh', 'Nicholas', 'Colin', 'Matthew', 'Tony',
      'Patrick', 'Joe', 'Daniel', 'Alfred', 'Andy', 'Roger',
      'Mike', 'Graham',
    ],
    family: [
      'Smith', 'Jones', 'Williams', 'Brown', 'Davies', 'Taylor',
      'Wilson', 'Evans', 'Thomas', 'Walker', 'Roberts', 'Scott',
      'Johnson', 'Campbell', 'Wright', 'Robinson', 'Lewis', 'Thompson',
      'White', 'Wood', 'Clarke', 'Edwards', 'Hughes', 'Anderson',
      'Harris', 'Green', 'Hall', 'Martin', 'Jackson', 'Young',
      'Clark', 'Morgan', 'Moore', 'Watson', 'Hill', 'Murray',
      'King', 'Turner', 'Cooper', 'Stewart', 'James', 'Morris',
      'Miller', 'Bell', 'Ward', 'Baker', 'Allen', 'Bennett',
      'Mitchell', 'Russell', 'Hamilton', 'Harrison', 'Adams', 'Phillips',
      'Robertson', 'Parker', 'Richardson', 'Shaw', 'Graham', 'Davis',
      'Gray', 'Collins', 'Griffiths', 'Howard', 'Kelly', 'Marshall',
      'Simpson', 'Palmer', 'Price', 'Cox', 'Lloyd', 'Butler',
      'Foster', 'Grant', 'Bailey', 'Ross', 'Reid', 'Carter',
      'Richards', 'Cook', 'Thomson', 'Henderson', 'Gibson', 'Gordon',
      'Fraser', 'Powell', 'Mason', 'Harvey', 'Barnes', 'Wilkinson',
      'Armstrong', 'Ellis', 'Kennedy', 'Alexander', 'Fletcher', 'Rogers',
      'Chapman', 'Lee', 'Pearson', 'Webb',
    ],
  },
  HR: {
    female: [
      'Ana', 'Ivana', 'Marija', 'Maja', 'Iva', 'Petra',
      'Katarina', 'Marina', 'Kristina', 'Lucija', 'Sanja', 'Jelena',
      'Lana', 'Martina', 'Nika', 'Nina', 'Antonija', 'Matea',
      'Mia', 'Andrea', 'Barbara', 'Sandra', 'Dora', 'Nada',
      'Helena', 'Mirjana', 'Vesna', 'Lea', 'Branka', 'Irena',
      'Josipa', 'Mira', 'Tatjana', 'Vera', 'Anja', 'Dubravka',
      'Ivona', 'Karla', 'nerea', 'Tanja', 'Diana', 'Ljiljana',
      'Sara', 'Tamara', 'Tea', 'Tina', 'Zdenka', 'Anita',
      'Ema', 'Jasna',
    ],
    male: [
      'Ivan', 'Josip', 'Marko', 'Ante', 'Tomislav', 'Mario',
      'Goran', 'Igor', 'Luka', 'Petar', 'Mladen', 'Ivo',
      'Nikola', 'Boris', 'Vladimir', 'Davor', 'Filip', 'Damir',
      'Ivica', 'Branko', 'Milan', 'Marin', 'Stjepan', 'Zoran',
      'Zvonimir', 'Hrvoje', 'Robert', 'Željko', 'Antonio', 'Bruno',
      'Mirko', 'Miroslav', 'Toni', 'Zlatko', 'Darko', 'Matija',
      'Franjo', 'Marijan', 'Matej', 'Antun', 'Domagoj', 'Krešimir',
      'Mate', 'Vedran', 'Danijel', 'Dino', 'Dražen', 'Karlo',
      'Stipe', 'Aleksandar',
    ],
    family: [
      'Horvat', 'Marić', 'Popović', 'Babić', 'Tomić', 'Marković',
      'Kovačić', 'Vidović', 'Filipović', 'Pavić', 'Bošnjak', 'Jurić',
      'Petrović', 'Blažević', 'Jurković', 'Novak', 'Šimić', 'Kovač',
      'Kovačević', 'Matić', 'Tadić', 'Bašić', 'Burić', 'Jukić',
      'Lončar', 'Martinović', 'Šarić', 'Delić', 'Erceg', 'Katić',
      'Ramljak', 'Vrdoljak', 'Janković', 'Pavlović', 'Perica', 'Perković',
      'Tolić', 'Boban', 'Grgić', 'Ivančić', 'Jovanović', 'Ljubičić',
      'Mijatović', 'Mikulić', 'Nakić', 'Nikolić', 'Novosel', 'Rukavina',
      'Vlašić', 'Vujčić', 'Zovko', 'Barišić', 'Bilic', 'Brozović',
      'Bubalo', 'Buljan', 'Despot', 'Gudelj', 'Ivanišević', 'Ivanković',
      'Jović', 'Jurišić', 'Knežević', 'Lovrić', 'Lukić', 'Mamić',
      'Mandić', 'Maras', 'Martinić', 'Matković', 'Mikulic', 'Miletić',
      'Novaković', 'Valentić', 'Abramović', 'Antunović', 'Banović', 'Begović',
      'Bogdan', 'Bosanac', 'Božić', 'Brkić', 'Ćorić', 'Ćosić',
      'Damjanović', 'Dvornik', 'Filipovic', 'Gabrić', 'Galić', 'Grubišić',
      'Jerković', 'Josipović', 'Juričić', 'Kvesić', 'Lasić', 'Leko',
      'Lorković', 'Majstorovic', 'Majstorović', 'Marinković',
    ],
  },
  HU: {
    female: [
      'Mária', 'Katalin', 'Éva', 'Anna', 'Erzsébet', 'Ágnes',
      'Judit', 'Ilona', 'Margit', 'Zsuzsa', 'Zsuzsanna', 'Eszter',
      'Klára', 'Andrea', 'Ildikó', 'Krisztina', 'Zsófia', 'Gabriella',
      'Márta', 'Júlia', 'Edit', 'Dóra', 'Erika', 'Réka',
      'Irén', 'Viktória', 'Nóra', 'Anikó', 'Gizella', 'Orsolya',
      'Magda', 'Csilla', 'Borbála', 'Magdolna', 'Julianna', 'Szilvia',
      'Tímea', 'Petra', 'Veronika', 'Piroska', 'Adrienn', 'Anita',
      'Mónika', 'Barbara', 'Teréz', 'Rita', 'Enikő', 'Kinga',
      'Lilla', 'Jolán',
    ],
    male: [
      'László', 'István', 'János', 'József', 'Ferenc', 'György',
      'Sándor', 'Lajos', 'Gábor', 'Péter', 'Zoltán', 'Károly',
      'Gyula', 'András', 'Béla', 'Imre', 'Pál', 'Tamás',
      'Miklós', 'Tibor', 'Mihály', 'Antal', 'Attila', 'Jenő',
      'Géza', 'Zsolt', 'Balázs', 'Endre', 'Kálmán', 'Csaba',
      'Árpád', 'Ernő', 'Ádám', 'Dezső', 'Dániel', 'Márton',
      'Vilmos', 'Gergely', 'Róbert', 'Zsigmond', 'Ákos', 'Dávid',
      'Viktor', 'Iván', 'Andor', 'Olivér', 'Mátyás', 'Emil',
      'Ödön', 'Bence',
    ],
    family: [
      'Nagy', 'Szabó', 'Kovács', 'Tóth', 'Horváth', 'Kiss',
      'Varga', 'Molnár', 'Farkas', 'Németh', 'Balogh', 'Papp',
      'Takács', 'Fekete', 'Mészáros', 'Török', 'Esterházy', 'Székely',
      'Szilágyi', 'Balázs', 'Simon', 'Juhász', 'Fodor', 'Bíró',
      'Zichy', 'Rácz', 'Lukács', 'Sándor', 'Gál', 'László',
      'Fehér', 'Lengyel', 'Kemény', 'Király', 'Szalay', 'Magyar',
      'Halász', 'Hegedűs', 'Kelemen', 'Pap', 'Deák', 'Oláh',
      'Pintér', 'Szűcs', 'Batthyány', 'Teleki', 'Boros', 'Sipos',
      'Erdélyi', 'Katona', 'Somogyi', 'Faragó', 'Bálint', 'Fülöp',
      'Fábián', 'Gaál', 'Fischer', 'Lázár', 'Pálffy', 'Antal',
      'Vincze', 'Gáspár', 'Gulyás', 'Károlyi', 'Kertész', 'Szász',
      'Nemes', 'Orbán', 'Vajda', 'Ács', 'Bethlen', 'Orosz',
      'Bartha', 'Benedek', 'Bognár', 'Lakatos', 'Novák', 'Csáky',
      'Andrássy', 'Balla', 'Vass', 'Gábor', 'Festetics', 'Kis',
      'Almásy', 'Kováts', 'Sebestyén', 'Fazekas', 'Major', 'Pásztor',
      'Rózsa', 'Kozma', 'Szalai', 'Bánffy', 'Hajdu', 'Kardos',
      'Dénes', 'Soós', 'Ádám', 'Benkő',
    ],
  },
  IE: {
    female: [
      'Mary', 'Sarah', 'Niamh', 'Anne', 'Catherine', 'Emma',
      'Margaret', 'Elizabeth', 'Ann', 'Patricia', 'Fiona', 'Claire',
      'Kathleen', 'Aoife', 'Jane', 'Eileen', 'Ciara', 'Maria',
      'Aisling', 'Laura', 'Louise', 'Michelle', 'Áine', 'Máire',
      'Alice', 'Orla', 'Rachel', 'Sinéad', 'Anna', 'Caroline',
      'Deirdre', 'Karen', 'Katie', 'Maeve', 'Ruth', 'Susan',
      'Barbara', 'Kate', 'Lucy', 'Geraldine', 'Maureen', 'Rebecca',
      'Jennifer', 'Joan', 'Sinead', 'Elaine', 'Nora', 'Siobhán',
      'Amy', 'Hannah',
    ],
    male: [
      'John', 'Michael', 'James', 'Patrick', 'Thomas', 'David',
      'William', 'Seán', 'Paul', 'Brian', 'Peter', 'Joseph',
      'Tom', 'Kevin', 'Stephen', 'Liam', 'Mark', 'Richard',
      'Martin', 'Paddy', 'Robert', 'Sean', 'Brendan', 'Joe',
      'Pat', 'Alan', 'George', 'Conor', 'Frank', 'Mick',
      'Niall', 'Edward', 'Noel', 'Charles', 'Jack', 'Denis',
      'Jim', 'Shane', 'Tony', 'Daniel', 'Séamus', 'Anthony',
      'Francis', 'Tommy', 'Colm', 'Henry', 'Barry', 'Jimmy',
      'Donal', 'Declan',
    ],
    family: [
      'Murphy', 'Ryan', 'Kelly', 'O\'Brien', 'Byrne', 'O\'Connor',
      'Walsh', 'O\'Sullivan', 'Lynch', 'Burke', 'Kennedy', 'Brennan',
      'Doyle', 'O\'Neill', 'Murray', 'O\'Reilly', 'Connolly', 'Fitzgerald',
      'McGrath', 'Moore', 'Collins', 'Quinn', 'Brady', 'Barry',
      'O\'Connell', 'Power', 'Farrell', 'Smith', 'Flynn', 'Gallagher',
      'Clarke', 'Healy', 'Keane', 'Browne', 'Kavanagh', 'O\'Leary',
      'Carroll', 'O\'Donoghue', 'Whelan', 'Boyle', 'Nolan', 'McCormack',
      'O\'Donnell', 'Butler', 'Crowley', 'Hayes', 'Maher', 'O\'Callaghan',
      'O\'Shea', 'Foley', 'Hogan', 'Hughes', 'Martin', 'Smyth',
      'Kenny', 'McKenna', 'Moran', 'Duffy', 'McLoughlin', 'Barrett',
      'Campbell', 'Delaney', 'Cronin', 'FitzGerald', 'Joyce', 'Maguire',
      'Fitzpatrick', 'O\'Mahony', 'Doherty', 'McDonnell', 'O\'Toole', 'Cummins',
      'King', 'Lawlor', 'O\'Donovan', 'Buckley', 'Finn', 'Mitchell',
      'O\'Keeffe', 'O\'Rourke', 'Sheridan', 'White', 'Coughlan', 'Cunningham',
      'Dillon', 'Griffin', 'Higgins', 'McCann', 'Kearney', 'McMahon',
      'Sheehan', 'Allen', 'Cahill', 'Donnelly', 'Keogh', 'Phelan',
      'Reynolds', 'Carey', 'Gleeson', 'Guinness',
    ],
  },
  IT: {
    female: [
      'Maria', 'Francesca', 'Anna', 'Elena', 'Laura', 'Paola',
      'Chiara', 'Silvia', 'Giulia', 'Elisa', 'Alessandra', 'Valentina',
      'Daniela', 'Sara', 'Giovanna', 'Lucia', 'Federica', 'Cristina',
      'Barbara', 'Elisabetta', 'Stefania', 'Claudia', 'Antonella', 'Roberta',
      'Angela', 'Marina', 'Gabriella', 'Patrizia', 'Carla', 'Ilaria',
      'Eleonora', 'Simona', 'Valeria', 'Martina', 'Monica', 'Luisa',
      'Alessia', 'Margherita', 'Caterina', 'Marta', 'Rita', 'Alice',
      'Giorgia', 'Manuela', 'Beatrice', 'Giuseppina', 'Michela', 'Serena',
      'Franca', 'Donatella',
    ],
    male: [
      'Giuseppe', 'Francesco', 'Giovanni', 'Antonio', 'Mario', 'Luigi',
      'Andrea', 'Marco', 'Paolo', 'Carlo', 'Alessandro', 'Roberto',
      'Stefano', 'Alberto', 'Giorgio', 'Luca', 'Franco', 'Pietro',
      'Massimo', 'Angelo', 'Enrico', 'Michele', 'Vincenzo', 'Bruno',
      'Matteo', 'Riccardo', 'Sergio', 'Claudio', 'Fabio', 'Salvatore',
      'Guido', 'Domenico', 'Nicola', 'Federico', 'Davide', 'Maurizio',
      'Vittorio', 'Aldo', 'Daniele', 'Luciano', 'Giulio', 'Giacomo',
      'Mauro', 'Filippo', 'Renato', 'Simone', 'Piero', 'Umberto',
      'Alfredo', 'Cesare',
    ],
    family: [
      'Rossi', 'Ferrari', 'Bianchi', 'Russo', 'Ricci', 'Colombo',
      'Romano', 'Giordano', 'Costa', 'Esposito', 'Fontana', 'Gallo',
      'Martini', 'Mancini', 'Galli', 'Moretti', 'Bruno', 'Lombardi',
      'De Luca', 'Mariani', 'Marchetti', 'Martinelli', 'Rinaldi', 'Barbieri',
      'Marini', 'Longo', 'Pellegrini', 'Rizzo', 'Greco', 'Fabbri',
      'Bernardi', 'Monti', 'Gatti', 'Serra', 'Ferrara', 'Marino',
      'Cattaneo', 'Montanari', 'Morelli', 'Benedetti', 'Grassi', 'Ferri',
      'Farina', 'Caruso', 'Silvestri', 'Donati', 'Valentini', 'Alberti',
      'Amato', 'Neri', 'Vitale', 'Bernardini', 'Coppola', 'Bruni',
      'Riva', 'Antonelli', 'Bellini', 'Negri', 'Baldi', 'Baldini',
      'D\'Angelo', 'Ferretti', 'Castelli', 'Gentile', 'Parisi', 'Rizzi',
      'Costantini', 'Messina', 'Angelini', 'Gori', 'Leonardi', 'Molinari',
      'Sala', 'Giannini', 'Leone', 'Moro', 'Testa', 'Innocenti',
      'Villa', 'Giuliani', 'Carbone', 'Sartori', 'Lombardo', 'Mazza',
      'Boni', 'Castellani', 'Giorgi', 'Martino', 'Agostini', 'Guidi',
      'Leoni', 'Berti', 'Santoro', 'Stella', 'Basile', 'Brunetti',
      'Bassi', 'Bianchini', 'D\'Amico', 'Franco',
    ],
  },
  LI: {
    female: [
      'Maria', 'Elisabeth', 'Katharina', 'Doris', 'Marina', 'Barbara',
      'Brigitte', 'Claudia', 'Franziska', 'Jessica', 'Katja', 'Lara',
      'Anna', 'Antonie', 'Bettina', 'Birgit', 'Camilla', 'Diana',
      'Elena', 'Emma', 'Eva', 'Fabienne', 'Gisela', 'Helen',
      'Hermine', 'Isabel', 'Johanna', 'Josefa', 'Julia', 'Karin',
      'Manuela', 'Nina', 'Norberta', 'Petra', 'Ramona', 'Renate',
      'Sabine', 'Sophia', 'Ursula', 'Yvonne', 'Alicia', 'Alina',
      'Aloysia', 'Amelie', 'Andrea', 'Angela', 'Angelika', 'Annalena',
      'Anne', 'Assunta',
    ],
    male: [
      'Josef', 'Franz', 'Peter', 'Johann', 'Martin', 'Daniel',
      'Michael', 'Marco', 'Alois', 'Rudolf', 'Thomas', 'Wolfgang',
      'Andreas', 'Hans', 'Alexander', 'Christoph', 'Georg', 'Karl',
      'Markus', 'Stefan', 'Heinrich', 'Patrick', 'Ferdinand', 'Herbert',
      'Johannes', 'Ludwig', 'Manfred', 'Mario', 'Anton', 'David',
      'Eugen', 'Jürgen', 'Oliver', 'Paul', 'Philipp', 'Roland',
      'Adolf', 'Albert', 'Alfred', 'Benjamin', 'Egon', 'Gebhard',
      'Günther', 'Heinz', 'Hubert', 'Rainer', 'Simon', 'Wilhelm',
      'Alfons', 'Armin',
    ],
    family: [
      'Büchel', 'Beck', 'Marxer', 'Schädler', 'Frick', 'Hasler',
      'Vogt', 'Gassner', 'Ospelt', 'Kindle', 'Meier', 'Ritter',
      'von Liechtenstein', 'Rheinberger', 'Kaiser', 'Matt', 'Biedermann', 'Bühler',
      'Risch', 'Sele', 'Batliner', 'Eberle', 'Frommelt', 'Kieber',
      'Seger', 'Haas', 'Jehle', 'Kranz', 'Lampert', 'Quaderer',
      'Sprenger', 'Wohlwend', 'Wolfinger', 'Bargetze', 'Brunhart', 'Hilti',
      'Nigg', 'Wachter', 'Wille', 'Zech', 'Amann', 'Feger',
      'Hassler', 'Heeb', 'Heidegger', 'Hermann', 'Hoop', 'Kaufmann',
      'Konrad', 'Liechtenstein', 'Nägele', 'Negele', 'Walser', 'Banzer',
      'Burgmeier', 'Fischer', 'Konzett', 'Malin', 'Moser', 'Näscher',
      'Oehri', 'Schlegel', 'Walch', 'Wenzel', 'Wolf', 'Ackermann',
      'Christen', 'Deichmann', 'Donner', 'Eigenmann', 'Ender', 'Erne',
      'Fehr', 'Gantenbein', 'Gantner', 'Göppel', 'Herrmann', 'Hoch',
      'Hohenlohe', 'Klingler', 'Koller', 'Kollmann', 'Lingg', 'Lüchinger',
      'Majer', 'Novak', 'Ozcan', 'Özcan', 'Reichl', 'Rotter',
      'Schaedler', 'Schafhauser', 'Seeger', 'Steger', 'Strub', 'Telser',
      'von und zu Liechtenstein', 'Wanger', 'Weirather', 'Wilczek',
    ],
  },
  LU: {
    female: [
      'Anne', 'Martine', 'Monique', 'Nathalie', 'Isabelle', 'Lynn',
      'Claudine', 'Michèle', 'Sophie', 'Catherine', 'Danielle', 'Laura',
      'Carole', 'Julie', 'Lisa', 'Caroline', 'Elisabeth', 'Kim',
      'Maria', 'Sarah', 'Simone', 'Anna', 'Charlotte', 'Christine',
      'Claire', 'Fabienne', 'Françoise', 'Lena', 'Liz', 'Stéphanie',
      'Christiane', 'Joëlle', 'Sylvie', 'Tessy', 'Betty', 'Corinne',
      'Danièle', 'Hélène', 'Jeanne', 'Marie-Paule', 'Nicole', 'Pascale',
      'Renée', 'Sandra', 'Alexandra', 'Carine', 'Cathy', 'Colette',
      'Jessica', 'Joséphine',
    ],
    male: [
      'Jean', 'Pierre', 'Nicolas', 'Joseph', 'Jean-Pierre', 'Paul',
      'Michel', 'Charles', 'François', 'Henri', 'Marc', 'Marcel',
      'René', 'Georges', 'Robert', 'Albert', 'Jacques', 'Mathias',
      'Claude', 'Léon', 'Fernand', 'André', 'Roger', 'Emile',
      'Alphonse', 'Antoine', 'Tom', 'Victor', 'Émile', 'Louis',
      'Eugène', 'Guy', 'Camille', 'Norbert', 'Ernest', 'Guillaume',
      'Jules', 'Auguste', 'Carlo', 'Philippe', 'Romain', 'Patrick',
      'Raymond', 'Alain', 'Christian', 'Félix', 'Daniel', 'Jos',
      'Josy', 'Lucien',
    ],
    family: [
      'Hoffmann', 'Schmit', 'Wagner', 'Thill', 'Weber', 'Klein',
      'Becker', 'Welter', 'Faber', 'Kieffer', 'Schneider', 'Hansen',
      'Reuter', 'Schroeder', 'Wolff', 'Kremer', 'Krier', 'Majerus',
      'Pescatore', 'Muller', 'Diederich', 'Schmitz', 'Molitor', 'Schaack',
      'Meyer', 'Braun', 'Mersch', 'Schiltz', 'Simon', 'Weis',
      'Kayser', 'Theis', 'Bernard', 'Müller', 'Schmitt', 'Arendt',
      'Bausch', 'Goergen', 'Meyers', 'Rausch', 'Wagener', 'Decker',
      'Feller', 'Kohn', 'Reding', 'Ries', 'Steffen', 'Wolter',
      'Biver', 'de Nassau', 'Engel', 'Erpelding', 'Michels', 'Mousel',
      'Olinger', 'Servais', 'Steichen', 'Biever', 'Didier', 'Fischer',
      'Goedert', 'Jacoby', 'Kemp', 'Kirsch', 'Lentz', 'Linster',
      'Margue', 'Moes', 'Schlechter', 'Colling', 'Dondelinger', 'Felten',
      'Frisch', 'Heinen', 'Jung', 'Koch', 'Kraus', 'Lambert',
      'Metz', 'Pauly', 'Peters', 'Theisen', 'Witry', 'Bauer',
      'Bintz', 'Brasseur', 'Clement', 'Collart', 'Flammang', 'Franck',
      'Funck', 'Gillen', 'Hemmer', 'Huberty', 'Jacobs', 'Kerger',
      'Knepper', 'Kohl', 'Linden', 'Lux',
    ],
  },
  MC: {
    female: [
      'Charlotte', 'Caroline', 'Isabelle', 'Louise', 'Alexandra', 'Christine',
      'Elisabeth', 'Patricia', 'Sophie', 'Valérie', 'Anastasia', 'Angelique',
      'Anne', 'Anne-Marie', 'Barbara', 'Brigitte', 'Camille', 'Carole',
      'Catherine', 'Charlene', 'Claudia', 'Cleo', 'Coline', 'Corinne',
      'Dominique', 'Emma', 'Fabienne', 'Fiona', 'Gabriella', 'Grace',
      'Hafida', 'Hélène', 'Hippolyte', 'India', 'Irène', 'Jasmine',
      'Juliette', 'Karen', 'Laetitia', 'Laëtitia', 'Lily', 'Lisa',
      'Maguy', 'Marguerite', 'Maria', 'Marie-Charlotte', 'Marie-Noëlle', 'Marika',
      'Marine', 'Mary',
    ],
    male: [
      'Louis', 'Pierre', 'Charles', 'Jean', 'Joseph', 'Henri',
      'Claude', 'Thierry', 'Albert', 'Georges', 'Jean-Charles', 'Michel',
      'Olivier', 'Alain', 'Alexandre', 'Antoine', 'Bernard', 'Christophe',
      'François', 'Marc', 'Patrice', 'Thomas', 'Victor', 'Daniel',
      'Edmond', 'Étienne', 'Eugène', 'Gilbert', 'Gilles', 'Jacques',
      'Jean-Luc', 'Jean-Pierre', 'Laurent', 'Marcel', 'Paul', 'Philippe',
      'Rainier', 'Robert', 'Stéphane', 'André', 'Arnaud', 'Émile',
      'Éric', 'Francis', 'Franck', 'Gérard', 'Gildo', 'Guillaume',
      'Hervé', 'Hugo',
    ],
    family: [
      'Grimaldi', 'Pastor', 'Boisson', 'Casiraghi', 'Leclerc', 'Marquet',
      'Notari', 'Vatrican', 'Cellario', 'Chiappori', 'Crovetto', 'Médecin',
      'Rossi', 'Agliardi', 'Allavena', 'Bellando', 'Bernasconi', 'Biancheri',
      'Brico', 'Coletti', 'de Castro', 'Elena', 'Fissore', 'Gottlieb',
      'Jouan', 'Marsan', 'Ravera', 'Raymond', 'Rey', 'Safra',
      'Abel', 'Abril', 'Afriat', 'Albert', 'Amoratti', 'Anglès d\'Auriac',
      'Anselmi', 'Antognelli', 'Aubert', 'Auréglia', 'Aymes', 'Bacardi',
      'Badia', 'Bahadori', 'Balleret', 'Banti', 'Bardy', 'Barelli',
      'Barilaro', 'Bégué', 'Bellini', 'Beretta', 'Bergonzi', 'Berlin',
      'Bertani', 'Berti', 'Bertrand', 'Bessi', 'Billon', 'Bini',
      'Blanc', 'Boccone', 'Boeri', 'Bonafede', 'Bonelli', 'Borges',
      'Borghini', 'Bosio', 'Boutsen', 'Braggiotti', 'Brain', 'Brancato',
      'Brezzo', 'Burini', 'Calcagno', 'Campi', 'Carladès', 'Castellini',
      'Caussin', 'Cedolin', 'Cerutti', 'Chabrier', 'Chiron', 'Cima',
      'Clerissi', 'Copello', 'Cresto', 'Cucchi', 'De Laurentiis', 'de Polignac',
      'Dear', 'Del Prete', 'Delpierre', 'Detaille', 'Dorato', 'Douglas',
      'Doyle', 'Druenne', 'Ducruet', 'Efimov',
    ],
  },
  MD: {
    female: [
      'Elena', 'Valentina', 'Maria', 'Natalia', 'Tatiana', 'Anna',
      'Irina', 'Ana', 'Marina', 'Olga', 'Cristina', 'Alina',
      'Lidia', 'Ludmila', 'Victoria', 'Alexandra', 'Veronica', 'Diana',
      'Mariana', 'Nina', 'Anastasia', 'Svetlana', 'Larisa', 'Valeria',
      'Angela', 'Daniela', 'Doina', 'Eugenia', 'Galina', 'Lilia',
      'Ala', 'Alla', 'Claudia', 'Evgenia', 'Rodica', 'Silvia',
      'Zinaida', 'Adriana', 'Corina', 'Liliana', 'Mihaela', 'Stela',
      'Vera', 'Viorica', 'Alyona', 'Aurelia', 'Eleonora', 'Eva',
      'Gabriela', 'Georgeta',
    ],
    male: [
      'Ion', 'Alexandru', 'Victor', 'Nicolae', 'Gheorghe', 'Vladimir',
      'Andrey', 'Valeriu', 'Igor', 'Vasile', 'Oleg', 'Mikhail',
      'Sergey', 'Sergiu', 'Dumitru', 'Mihai', 'Petru', 'Iurie',
      'Boris', 'Ivan', 'Vitalie', 'Vadim', 'Anatolie', 'Constantin',
      'Aleksandr', 'Anatol', 'Pavel', 'Andrei', 'Denis', 'Eugen',
      'Maxim', 'Serghei', 'Tudor', 'Valentin', 'Ștefan', 'Veaceslav',
      'Yevgeny', 'Ilie', 'Cristian', 'Nikolay', 'Roman', 'Viktor',
      'Leonid', 'Georgy', 'Grigore', 'Radu', 'Vladislav', 'Adrian',
      'Iulian', 'Alexandr',
    ],
    family: [
      'Ciobanu', 'Popa', 'Rusu', 'Țurcan', 'Cebotari', 'Ivanov',
      'Munteanu', 'Ursu', 'Cojocaru', 'Cazac', 'Lupan', 'Popescu',
      'Popov', 'Balan', 'Bujor', 'Bulat', 'Istrati', 'Konstantinov',
      'Matei', 'Negru', 'Roșca', 'Ungureanu', 'Carp', 'Casian',
      'Chiriac', 'Codreanu', 'Filip', 'Gherman', 'Guțu', 'Lungu',
      'Mardare', 'Marian', 'Mocanu', 'Nemerenco', 'Osipov', 'Popovici',
      'Prodan', 'Radu', 'Timofti', 'Tkachuk', 'Toma', 'Adam',
      'Albot', 'Aldea-Teodorovici', 'Ambros', 'Anton', 'Baciu', 'Barbu',
      'Bogdan', 'Botezatu', 'Burlacu', 'Busuioc', 'Caranfil', 'Caras',
      'Cataraga', 'Chirilov', 'Ciocan', 'Ciubuc', 'Cristea', 'Cucu',
      'Dubrovin', 'Efros', 'Gheorghiu', 'Ghimpu', 'Gonța', 'Grecu',
      'Grigore', 'Grosu', 'Hanganu', 'Ivanova', 'Josan', 'Kogan',
      'Koshelev', 'Kovalchuk', 'Kuznetsov', 'Lisnic', 'Luca', 'Lucinschi',
      'Macovei', 'Madan', 'Manic', 'Mikhaylov', 'Nistor', 'Păduraru',
      'Petrenko', 'Pînzaru', 'Platon', 'Popova', 'Popović', 'Saka',
      'Șalaru', 'Semyonov', 'Shor', 'Stratan', 'Sturza', 'Tănase',
      'Tarnowski', 'Tkach', 'Topal', 'Turcan',
    ],
  },
  ME: {
    female: [
      'Jelena', 'Ana', 'Marija', 'Ivana', 'Maja', 'Milica',
      'Andrea', 'Jovana', 'Nina', 'Sara', 'Tamara', 'Marina',
      'Milena', 'Tatjana', 'Anđela', 'Bojana', 'Irena', 'Katarina',
      'Milka', 'nerea', 'Olivera', 'Sanja', 'Anastasija', 'Andrijana',
      'Biljana', 'Danica', 'Elena', 'Ivona', 'Jasna', 'Kristina',
      'Ksenija', 'Lana', 'Ljubica', 'Maida', 'Olga', 'Radmila',
      'Svetlana', 'Tanja', 'Tea', 'Tijana', 'Tina', 'Aleksandra',
      'Andjela', 'Andreja', 'Anja', 'Anna', 'Armelle', 'Borka',
      'Božica', 'Branka',
    ],
    male: [
      'Marko', 'Nikola', 'Ivan', 'Vladimir', 'Igor', 'Miloš',
      'Aleksandar', 'Miodrag', 'Zoran', 'Stefan', 'Luka', 'Goran',
      'Milan', 'Bojan', 'Dragan', 'Nemanja', 'Darko', 'Filip',
      'Andrija', 'Boris', 'Mirko', 'Petar', 'Dejan', 'Žarko',
      'Željko', 'Jovan', 'Predrag', 'Srđan', 'Dušan', 'Nebojša',
      'Nenad', 'Slobodan', 'Aleksa', 'Branko', 'Ilija', 'Stevan',
      'Mladen', 'Vladan', 'Bogdan', 'Borislav', 'Danilo', 'Lazar',
      'Milorad', 'Pavle', 'Ratko', 'Uroš', 'Boško', 'Božidar',
      'Božo', 'Branislav',
    ],
    family: [
      'Popović', 'Jovanović', 'Ivanović', 'Petrović', 'Marković', 'Radović',
      'Knežević', 'Nikolić', 'Vujović', 'Božović', 'Bulatović', 'Šćepanović',
      'Tomašević', 'Živković', 'Krivokapić', 'Mrvaljević', 'Pavićević', 'Sekulić',
      'Vukčević', 'Bakić', 'Bošković', 'Brnović', 'Đukanović', 'Filipović',
      'Karadžić', 'Maraš', 'Milošević', 'Vujačić', 'Bjelica', 'Bogavac',
      'Drobnjak', 'Kujović', 'Marović', 'Mijušković', 'Milović', 'Mitrović',
      'Pavlović', 'Radulović', 'Raičević', 'Rudović', 'Savić', 'Vučić',
      'Adžić', 'Bakic', 'Batrović', 'Blagojević', 'Bokan', 'Ćetković',
      'Ćorović', 'Dabović', 'Damjanović', 'Delibašić', 'Djokovic', 'Dragojević',
      'Đukić', 'Đurišić', 'Đurović', 'Gluščević', 'Grbović', 'Janković',
      'Jokić', 'Jovović', 'Kaluđerović', 'Klikovac', 'Kosić', 'Kostić',
      'Kovačević', 'Kralj', 'Krnić', 'Lazarević', 'Lučić', 'Mijatović',
      'Mugoša', 'Mujovic', 'Nikčević', 'Novaković', 'Peković', 'Perišić',
      'Perović', 'Petrović-Njegoš', 'Radonjic', 'Radunović', 'Rakočević', 'Šćekić',
      'Šehović', 'Simić', 'Škerović', 'Strugar', 'Tatar', 'Todorović',
      'Tomović', 'Tošković', 'Vučinić', 'Vulić', 'Zeković', 'Žižić',
      'Žugić', 'Abazi', 'Abazović', 'Adžović',
    ],
  },
  MT: {
    female: [
      'Maria', 'Rebecca', 'Nicole', 'Francesca', 'Mary', 'Michela',
      'Rachel', 'Emma', 'Alexandra', 'Charlene', 'Julia', 'Sarah',
      'Anna', 'Antoinette', 'Catherine', 'Claire', 'Abigail', 'Angela',
      'Deborah', 'Dorianne', 'Justine', 'Karen', 'Kelly', 'Laura',
      'Lisa', 'Martina', 'Miriam', 'Sharon', 'Ylenia', 'Amber',
      'Amy', 'Ann', 'Carmen', 'Claudette', 'Claudia', 'Daniela',
      'Doreen', 'Gaia', 'Hannah', 'Isabelle', 'Jade', 'Jessica',
      'Josephine', 'Josette', 'Kirsty', 'Mariah', 'Marlene', 'Samantha',
      'Stephanie', 'Theresa',
    ],
    male: [
      'Joseph', 'John', 'Charles', 'Joe', 'Paul', 'Michael',
      'Alfred', 'George', 'Anthony', 'Mario', 'Matthew', 'David',
      'Edward', 'Alex', 'Emanuel', 'Daniel', 'Anton', 'Carmelo',
      'Francis', 'Luke', 'Mark', 'Ryan', 'Tony', 'Antonio',
      'Ian', 'Peter', 'Victor', 'Albert', 'Carmel', 'Louis',
      'Adrian', 'Emmanuel', 'Frank', 'Robert', 'Vincent', 'Andrew',
      'Christian', 'Giovanni', 'Karl', 'Miguel', 'Philip', 'Raymond',
      'Silvio', 'Simon', 'William', 'Christopher', 'Edwin', 'Giuseppe',
      'Henry', 'Lawrence',
    ],
    family: [
      'Vella', 'Borg', 'Camilleri', 'Farrugia', 'Zammit', 'Galea',
      'Azzopardi', 'Micallef', 'Grech', 'Abela', 'Cassar', 'Xuereb',
      'Caruana', 'Pace', 'Attard', 'Mifsud', 'Muscat', 'Agius',
      'Calleja', 'Schembri', 'Fenech', 'Aquilina', 'Mizzi', 'Buttigieg',
      'Sammut', 'Sciberras', 'Bonello', 'Debono', 'Falzon', 'Bezzina',
      'Busuttil', 'Scicluna', 'Bonnici', 'Scerri', 'Spiteri', 'Chetcuti',
      'Portelli', 'Baldacchino', 'Gauci', 'Mallia', 'Pisani', 'Saliba',
      'Tabone', 'Cauchi', 'Cilia', 'Curmi', 'Cutajar', 'Sultana',
      'Vassallo', 'Zerafa', 'Briffa', 'Brincat', 'Cardona', 'Chircop',
      'Dimech', 'Buhagiar', 'Cachia', 'Cuschieri', 'Dalli', 'Formosa',
      'Gatt', 'Magri', 'Psaila', 'Bartolo', 'Bugeja', 'Cremona',
      'Darmanin', 'Deguara', 'Ellul', 'Holland', 'Said', 'Apap',
      'Barbara', 'Bonett', 'Coleiro', 'Cordina', 'Gerada', 'Naudi',
      'Pullicino', 'Riolo', 'Sant', 'Theuma', 'Williams', 'Xerri',
      'Zahra', 'Anastasi', 'Balzan', 'Depasquale', 'Fabri', 'Ferrante',
      'Frendo', 'Gouder', 'Jackson', 'Mamo', 'Mangion', 'Meli',
      'Mercieca', 'Mifsud Bonnici', 'Nwoko', 'Refalo',
    ],
  },
  NL: {
    female: [
      'Maria', 'Johanna', 'Anna', 'Elisabeth', 'Cornelia', 'Catharina',
      'Wilhelmina', 'Anne', 'Esther', 'Louise', 'Marijke', 'Adriana',
      'Jacoba', 'Ellen', 'Annie', 'Yvonne', 'Judith', 'Eva',
      'Karin', 'Margaretha', 'Marieke', 'Marianne', 'Laura', 'Monique',
      'Sanne', 'Saskia', 'Sophie', 'Hendrika', 'Mirjam', 'Barbara',
      'Petra', 'Carla', 'Henriëtte', 'Ingrid', 'Jacqueline', 'Anneke',
      'Charlotte', 'Els', 'Helena', 'Pauline', 'Alida', 'Caroline',
      'Henriette', 'Joke', 'Liesbeth', 'Christina', 'Femke', 'Irene',
      'Lisa', 'Maaike',
    ],
    male: [
      'Jan', 'Johannes', 'Willem', 'Hendrik', 'Pieter', 'Cornelis',
      'Johan', 'Hans', 'Peter', 'Henk', 'Jacob', 'Frans',
      'Gerrit', 'Gerard', 'Herman', 'Paul', 'Dirk', 'Jacobus',
      'Wim', 'Piet', 'Frederik', 'Kees', 'Albert', 'Louis',
      'Petrus', 'Henri', 'Adriaan', 'Karel', 'Robert', 'Rob',
      'Jaap', 'Joseph', 'Theo', 'Frank', 'John', 'Christiaan',
      'Nicolaas', 'Adrianus', 'Antonius', 'Klaas', 'Marinus', 'Gerardus',
      'Abraham', 'Maarten', 'Anton', 'Bert', 'Arie', 'Jeroen',
      'Franciscus', 'Jacques',
    ],
    family: [
      'de Jong', 'Bakker', 'Visser', 'Jansen', 'Smit', 'Janssen',
      'Meijer', 'van Dijk', 'van den Berg', 'Mulder', 'De Vries', 'de Boer',
      'Vos', 'de Vries', 'Bos', 'Smits', 'Dekker', 'van Leeuwen',
      'Brouwer', 'Jacobs', 'Peters', 'Kramer', 'de Wit', 'Maas',
      'Dijkstra', 'Hendriks', 'Cohen', 'Blom', 'de Haan', 'Schouten',
      'Sanders', 'van Vliet', 'Kok', 'Post', 'Vermeulen', 'Kuipers',
      'van der Meer', 'De Groot', 'de Haas', 'Prins', 'Koster', 'Bosch',
      'Scholten', 'Boer', 'de Groot', 'Hoekstra', 'Kuiper', 'Faber',
      'de Graaf', 'Klein', 'Postma', 'Vonk', 'Simons', 'van Wijk',
      'Bouman', 'Muller', 'Schmidt', 'van den Brink', 'de Lange', 'Smeets',
      'van den Bergh', 'Blok', 'Jonker', 'Gerritsen', 'Polak', 'Roos',
      'van Beek', 'Groot', 'Koning', 'Verbeek', 'Koopman', 'van der Laan',
      'Willems', 'Koopmans', 'Hermans', 'Groen', 'Molenaar', 'Schipper',
      'van der Heide', 'van der Wal', 'Verhoeven', 'Vink', 'Bouma', 'Smulders',
      'van Gelder', 'Evers', 'Timmermans', 'van den Broek', 'Wolf', 'Hofman',
      'Kroon', 'van der Velden', 'Dekkers', 'Huisman', 'Smith', 'Van der Linden',
      'Wiersma', 'Wolff', 'Bosman', 'Martens',
    ],
  },
  NO: {
    female: [
      'Anne', 'Ingrid', 'Anna', 'Elisabeth', 'Kristin', 'Kari',
      'Marit', 'Inger', 'Marianne', 'Hilde', 'Ellen', 'Liv',
      'Eva', 'Ida', 'Ragnhild', 'Maria', 'Siri', 'Kristine',
      'Tone', 'Hanne', 'Astrid', 'Ingeborg', 'Berit', 'Nina',
      'Cecilie', 'Julie', 'Helene', 'Silje', 'Mari', 'Hege',
      'Bente', 'Marte', 'Solveig', 'Johanne', 'Karin', 'Camilla',
      'Lise', 'Elin', 'Sigrid', 'Heidi', 'Kjersti', 'Randi',
      'Trine', 'Tove', 'Mette', 'Christine', 'Karen', 'Line',
      'Ingvild', 'Emilie',
    ],
    male: [
      'Hans', 'Ole', 'Per', 'Johan', 'Lars', 'Arne',
      'Knut', 'Christian', 'Erik', 'Jan', 'Bjørn', 'Andreas',
      'Olav', 'Anders', 'Nils', 'Harald', 'Gunnar', 'Einar',
      'Morten', 'Thomas', 'Kjell', 'Martin', 'Kristian', 'John',
      'Jon', 'Fredrik', 'Carl', 'Jens', 'Odd', 'Peter',
      'Sverre', 'Tore', 'Henrik', 'Svein', 'Terje', 'Ivar',
      'Rolf', 'Johannes', 'Geir', 'Karl', 'Tor', 'Erling',
      'Sigurd', 'Trond', 'Helge', 'Petter', 'Jørgen', 'Magnus',
      'Leif', 'Finn',
    ],
    family: [
      'Hansen', 'Andersen', 'Olsen', 'Johansen', 'Larsen', 'Pedersen',
      'Nilsen', 'Berg', 'Jensen', 'Eriksen', 'Dahl', 'Lund',
      'Johnsen', 'Kristiansen', 'Jacobsen', 'Hagen', 'Pettersen', 'Karlsen',
      'Halvorsen', 'Haugen', 'Henriksen', 'Lie', 'Johannessen', 'Nielsen',
      'Moe', 'Christensen', 'Gundersen', 'Jørgensen', 'Knudsen', 'Iversen',
      'Sørensen', 'Strand', 'Hauge', 'Andreassen', 'Lunde', 'Svendsen',
      'Christiansen', 'Berge', 'Moen', 'Aas', 'Amundsen', 'Rasmussen',
      'Steen', 'Andresen', 'Hanssen', 'Næss', 'Bakke', 'Paulsen',
      'Jenssen', 'Arnesen', 'Smith', 'Mathisen', 'Myhre', 'Strøm',
      'Jakobsen', 'Kristoffersen', 'Martinsen', 'Knutsen', 'Paus', 'Sæther',
      'Hoff', 'Bugge', 'Gulbrandsen', 'Thoresen', 'Ellingsen', 'Møller',
      'Thorsen', 'Berntsen', 'Fredriksen', 'Kristensen', 'Ruud', 'Sandvik',
      'Evensen', 'Nygaard', 'Simonsen', 'Solheim', 'Birkeland', 'Brekke',
      'Rønning', 'Sandberg', 'Danielsen', 'Vik', 'Bakken', 'Haug',
      'Lien', 'Thomassen', 'Myklebust', 'Bjerke', 'Hammer', 'Meyer',
      'Nilssen', 'Cappelen', 'Abrahamsen', 'Foss', 'Krogh', 'Vogt',
      'Bye', 'Hoel', 'Eggen', 'Haugland',
    ],
  },
  PT: {
    female: [
      'Maria', 'Ana', 'Joana', 'Isabel', 'Catarina', 'Teresa',
      'Rita', 'Mariana', 'Sofia', 'Sara', 'Helena', 'Paula',
      'Margarida', 'Cristina', 'Marta', 'Inês', 'Raquel', 'Carla',
      'Beatriz', 'Susana', 'Carolina', 'Cláudia', 'Manuela', 'Sandra',
      'Filipa', 'Patrícia', 'Luísa', 'Diana', 'Fernanda', 'Alexandra',
      'Leonor', 'Mafalda', 'Rosa', 'Andreia', 'Daniela', 'Madalena',
      'Alice', 'Gabriela', 'Liliana', 'Vera', 'Anabela', 'Mónica',
      'Fátima', 'Laura', 'Vanessa', 'Adelaide', 'Clara', 'María José',
      'Patricia', 'Elsa',
    ],
    male: [
      'José', 'João', 'António', 'Manuel', 'Pedro', 'Carlos',
      'Francisco', 'Luís', 'Fernando', 'Joaquim', 'Miguel', 'Jorge',
      'Rui', 'Paulo', 'Nuno', 'Ricardo', 'Mário', 'Tiago',
      'André', 'Diogo', 'Eduardo', 'Alberto', 'Bruno', 'Henrique',
      'Augusto', 'Filipe', 'Artur', 'Álvaro', 'Alexandre', 'Alfredo',
      'Hugo', 'Luis', 'Gonçalo', 'Vítor', 'Vasco', 'Antonio',
      'Sérgio', 'Daniel', 'Afonso', 'David', 'Jaime', 'Júlio',
      'Rodrigo', 'Guilherme', 'Bernardo', 'Duarte', 'Fábio', 'Tomás',
      'Domingos', 'Marco',
    ],
    family: [
      'Silva', 'Pereira', 'Costa', 'Ferreira', 'Santos', 'Alves',
      'Martins', 'Rodrigues', 'Fernandes', 'Oliveira', 'Pinto', 'Gomes',
      'Lopes', 'Ribeiro', 'Almeida', 'Sousa', 'Gonçalves', 'Carvalho',
      'Teixeira', 'Monteiro', 'Dias', 'Marques', 'Soares', 'Mendes',
      'Correia', 'Machado', 'Vieira', 'Lima', 'Cardoso', 'Neves',
      'Reis', 'Castro', 'Nunes', 'Rocha', 'Tavares', 'Ramos',
      'Cunha', 'Freitas', 'Coelho', 'Cruz', 'Duarte', 'Fonseca',
      'Moreira', 'Azevedo', 'Barbosa', 'Pires', 'Borges', 'Matos',
      'Magalhães', 'Pinheiro', 'Rosa', 'Morais', 'Antunes', 'Baptista',
      'Melo', 'Cabral', 'Amaral', 'Simões', 'Campos', 'Figueiredo',
      'Vasconcelos', 'Araújo', 'Abreu', 'Andrade', 'Pacheco', 'Faria',
      'Moura', 'Barros', 'Leite', 'Miranda', 'Mota', 'Guimarães',
      'Maia', 'Neto', 'Henriques', 'Torres', 'Aguiar', 'Guedes',
      'de Sousa', 'Nogueira', 'Sá', 'Lourenço', 'Macedo', 'Afonso',
      'Conceição', 'Leitão', 'Brito', 'Carneiro', 'da Costa', 'Saraiva',
      'Valente', 'Amorim', 'Bastos', 'Branco', 'Freire', 'Gouveia',
      'Jorge', 'Rebelo', 'da Silva', 'Guerra',
    ],
  },
  RO: {
    female: [
      'Maria', 'Elena', 'Cristina', 'Ana', 'Alexandra', 'Ioana',
      'Mihaela', 'Daniela', 'Gabriela', 'Diana', 'Andreea', 'Alina',
      'Carmen', 'Mariana', 'Simona', 'Laura', 'Adriana', 'Irina',
      'Monica', 'Anca', 'Rodica', 'Oana', 'Raluca', 'Doina',
      'Liliana', 'Corina', 'Ileana', 'Katalin', 'Claudia', 'Eugenia',
      'Roxana', 'Bianca', 'Cornelia', 'Georgeta', 'Mária', 'Silvia',
      'Camelia', 'Iulia', 'Lucia', 'Mădălina', 'Anna', 'Teodora',
      'Adina', 'Éva', 'Nicoleta', 'Viorica', 'Dana', 'Luminița',
      'Olga', 'Emilia',
    ],
    male: [
      'Ion', 'Gheorghe', 'Ioan', 'Constantin', 'Alexandru', 'Nicolae',
      'Vasile', 'Mihai', 'Adrian', 'Dumitru', 'Andrei', 'Florin',
      'George', 'Ștefan', 'Mircea', 'Daniel', 'Dan', 'Cristian',
      'Marius', 'Marian', 'Radu', 'Bogdan', 'Gabriel', 'László',
      'István', 'Victor', 'Aurel', 'Petru', 'János', 'Petre',
      'Ionuț', 'Sorin', 'Eugen', 'Lucian', 'Paul', 'Valentin',
      'Emil', 'Liviu', 'Cătălin', 'Viorel', 'Ionel', 'Ilie',
      'Cornel', 'Mikhail', 'József', 'Zoltán', 'Ovidiu', 'Iulian',
      'Sándor', 'Teodor',
    ],
    family: [
      'Popescu', 'Popa', 'Ionescu', 'Pop', 'Dumitrescu', 'Nagy',
      'Constantinescu', 'Munteanu', 'Radu', 'Kovács', 'Moldovan', 'Stoica',
      'Rădulescu', 'Georgescu', 'Szabó', 'Constantin', 'Matei', 'Gheorghe',
      'Oprea', 'Marinescu', 'Petrescu', 'Marin', 'Șerban', 'Barbu',
      'Dumitru', 'Rusu', 'Cristea', 'Gheorghiu', 'Mureșan', 'Toma',
      'Roman', 'Ciobanu', 'Dinu', 'Ilie', 'Lazăr', 'Popovici',
      'Vasile', 'Niculescu', 'Sandu', 'Nistor', 'Iordache', 'Teodorescu',
      'Andrei', 'Preda', 'Stănescu', 'Ungureanu', 'Stanciu', 'Ștefănescu',
      'Tudor', 'Olteanu', 'Vlad', 'Suciu', 'Tănase', 'Zaharia',
      'Anghel', 'Iacob', 'Lungu', 'Bălan', 'Florea', 'Iliescu',
      'Albu', 'Bucur', 'Iancu', 'Coman', 'Kiss', 'Mihai',
      'Pavel', 'Dobre', 'Moraru', 'Voicu', 'Cojocaru', 'Dragomir',
      'Enache', 'Ion', 'Simion', 'Badea', 'Crăciun', 'Ioniță',
      'Petre', 'Grigore', 'Rotaru', 'Bogdan', 'David', 'Filip',
      'Varga', 'Anton', 'Ivan', 'Marcu', 'Nicolae', 'Stancu',
      'Luca', 'Mihăilescu', 'Vasilescu', 'Florescu', 'Muntean', 'Rus',
      'Chiriac', 'Dima', 'Manea', 'Botez',
    ],
  },
  RS: {
    female: [
      'Jelena', 'Ana', 'Ivana', 'Marija', 'Milica', 'Jovana',
      'Maja', 'Aleksandra', 'Katarina', 'Tamara', 'Sanja', 'Bojana',
      'Gordana', 'Marina', 'Milena', 'Mirjana', 'Vesna', 'Biljana',
      'Nina', 'Tijana', 'Dragana', 'Kristina', 'Ljiljana', 'Sonja',
      'Tatjana', 'Teodora', 'Olga', 'Sara', 'Svetlana', 'Tanja',
      'Branka', 'Anja', 'Mina', 'Olivera', 'Radmila', 'Ljubica',
      'Nada', 'Vera', 'Danica', 'Jasmina', 'Ksenija', 'Mira',
      'Suzana', 'Zorica', 'Iva', 'Jana', 'Marijana', 'Andrea',
      'Irena', 'Jasna',
    ],
    male: [
      'Aleksandar', 'Marko', 'Milan', 'Nikola', 'Miloš', 'Zoran',
      'Vladimir', 'Ivan', 'Dragan', 'Dušan', 'Nemanja', 'Stefan',
      'Dejan', 'Goran', 'Đorđe', 'Nenad', 'Petar', 'Slobodan',
      'Saša', 'Bojan', 'Jovan', 'Igor', 'Predrag', 'Miroslav',
      'Filip', 'Srđan', 'Branko', 'Luka', 'Miodrag', 'Nebojša',
      'Darko', 'Branislav', 'Uroš', 'Stevan', 'Milorad', 'Lazar',
      'Mladen', 'Aleksa', 'Boris', 'Mirko', 'Danilo', 'Bogdan',
      'Božidar', 'Vladan', 'Željko', 'Ognjen', 'Ilija', 'Pavle',
      'Veljko', 'Andrija',
    ],
    family: [
      'Jovanović', 'Marković', 'Popović', 'Petrović', 'Janković', 'Nikolić',
      'Ilić', 'Đorđević', 'Živković', 'Pavlović', 'Milošević', 'Stojanović',
      'Stanković', 'Kovačević', 'Savić', 'Mitrović', 'Stefanović', 'Kostić',
      'Todorović', 'Obradović', 'Stevanović', 'Marić', 'Simić', 'Bogdanović',
      'Maksimović', 'Aleksić', 'Jovanovic', 'Knežević', 'Lukić', 'Milovanović',
      'Filipović', 'Stanojević', 'Ivanović', 'Matić', 'Ristić', 'Stojković',
      'Cvetković', 'Radovanović', 'Dimitrijević', 'Đurić', 'Jakovljević', 'Marjanović',
      'Milenković', 'Babić', 'Jeremić', 'Krstić', 'Marinković', 'Mladenović',
      'Novaković', 'Radosavljević', 'Jelić', 'Lazić', 'Milosavljević', 'Pešić',
      'Tadić', 'Tomić', 'Anđelković', 'Bošković', 'Đukić', 'Jović',
      'Mihajlović', 'Milićević', 'Milojević', 'Mitić', 'Radulović', 'Vučković',
      'Živanović', 'Avramović', 'Ćirić', 'Mandić', 'Mihailović', 'Miladinović',
      'Urošević', 'Djokovic', 'Jakšić', 'Luković', 'Miljković', 'Perović',
      'Simović', 'Antić', 'Bjelica', 'Ćirković', 'Ćurčić', 'Jevtić',
      'Kovač', 'Lončar', 'Nedeljković', 'Nenadić', 'Panić', 'Perić',
      'Perišić', 'Petkovic', 'Radivojević', 'Smiljanić', 'Terzić', 'Trifunović',
      'Vasić', 'Veljković', 'Andrić', 'Bajić',
    ],
  },
  SE: {
    female: [
      'Anna', 'Maria', 'Margareta', 'Eva', 'Karin', 'Christina',
      'Elisabeth', 'Sofia', 'Kerstin', 'Johanna', 'Helena', 'Kristina',
      'Birgitta', 'Lena', 'Ingrid', 'Elisabet', 'Sara', 'Emma',
      'Charlotta', 'Hanna', 'Cecilia', 'Elsa', 'Elin', 'Ulla',
      'Gunilla', 'Catharina', 'Ulrika', 'Malin', 'Ida', 'Lisa',
      'Louise', 'Åsa', 'Ebba', 'Katarina', 'Jenny', 'Annika',
      'Marianne', 'Lovisa', 'Ingeborg', 'Hedvig', 'Linda', 'Augusta',
      'Charlotte', 'Ellen', 'Julia', 'Barbro', 'Agneta', 'Carolina',
      'Frida', 'Märta',
    ],
    male: [
      'Johan', 'Carl', 'Erik', 'Anders', 'Gustaf', 'Lars',
      'Nils', 'Per', 'Fredrik', 'Karl', 'Sven', 'Olof',
      'Axel', 'Hans', 'Peter', 'Gunnar', 'Magnus', 'Bengt',
      'Jonas', 'Henrik', 'Daniel', 'Jan', 'Lennart', 'John',
      'Martin', 'Wilhelm', 'Gösta', 'August', 'Bertil', 'Andreas',
      'Göran', 'Åke', 'Björn', 'Bo', 'David', 'Johannes',
      'Mats', 'Ulf', 'Mikael', 'Georg', 'Oscar', 'Eric',
      'Otto', 'Gustav', 'Thomas', 'Christian', 'Adolf', 'Robert',
      'Stefan', 'Ernst',
    ],
    family: [
      'Andersson', 'Johansson', 'Nilsson', 'Larsson', 'Olsson', 'Eriksson',
      'Karlsson', 'Persson', 'Svensson', 'Pettersson', 'Carlsson', 'Gustafsson',
      'Jonsson', 'Hansson', 'Lindberg', 'Jansson', 'Bergström', 'Bengtsson',
      'Lindström', 'Lindgren', 'Lundberg', 'Berg', 'Bergman', 'Jönsson',
      'Ekman', 'Lundgren', 'Magnusson', 'Sandberg', 'Sjöberg', 'Berglund',
      'Holmberg', 'Petersson', 'Forsberg', 'Nordström', 'Lindqvist', 'Ericsson',
      'Engström', 'Söderberg', 'Wallin', 'Nyström', 'Danielsson', 'Lundström',
      'Falk', 'Samuelsson', 'Sjögren', 'Olofsson', 'Sandström', 'Lind',
      'Lundin', 'Möller', 'Björkman', 'Eklund', 'Gustavsson', 'Håkansson',
      'Sundberg', 'Dahl', 'Nyberg', 'Åberg', 'Ribbing', 'Jacobsson',
      'Lundqvist', 'Anderson', 'Sparre', 'Nordin', 'Berggren', 'Johnsson',
      'Ericson', 'Löfgren', 'Mattsson', 'Ohlsson', 'Johnson', 'Sundström',
      'Fredriksson', 'Wikström', 'Dahlberg', 'Hamilton', 'Palm', 'Wachtmeister',
      'Öberg', 'Ekström', 'Hellström', 'Björk', 'Björklund', 'Holmgren',
      'Norberg', 'Ström', 'Roos', 'Axelsson', 'de Geer', 'Hallberg',
      'Lindahl', 'Göransson', 'Hedberg', 'Hedlund', 'Arvidsson', 'Strömberg',
      'Söderström', 'Lund', 'Rosén', 'Blom',
    ],
  },
  SI: {
    female: [
      'Mojca', 'Maja', 'Alenka', 'Ana', 'Marija', 'Barbara',
      'Andreja', 'Mateja', 'Irena', 'Katja', 'Tanja', 'Tina',
      'Nina', 'Petra', 'Vesna', 'Katarina', 'Urška', 'Tatjana',
      'Anja', 'Eva', 'Špela', 'Darja', 'Simona', 'Sonja',
      'Martina', 'Jana', 'Polona', 'Tjaša', 'Metka', 'Helena',
      'Marjeta', 'Janja', 'Jasna', 'Nika', 'Lidija', 'Saša',
      'Nada', 'Vida', 'Breda', 'Zdenka', 'Sara', 'Milena',
      'Aleksandra', 'Sabina', 'Kristina', 'Ksenija', 'Karmen', 'Monika',
      'Jožica', 'Lucija',
    ],
    male: [
      'Andrej', 'Janez', 'Marko', 'Jože', 'Peter', 'Franc',
      'Tomaž', 'Matjaž', 'Igor', 'Matej', 'Aleš', 'Marjan',
      'Bojan', 'Miha', 'Ivan', 'Gregor', 'Anton', 'Boris',
      'Boštjan', 'Dušan', 'Rok', 'Milan', 'Jure', 'Mitja',
      'Borut', 'Luka', 'Robert', 'Uroš', 'Branko', 'Primož',
      'Jernej', 'Blaž', 'Martin', 'Dejan', 'Klemen', 'Iztok',
      'Miran', 'Drago', 'Simon', 'Vladimir', 'Aleksander', 'Jurij',
      'Žiga', 'Janko', 'David', 'Darko', 'Alojz', 'Matija',
      'Jan', 'Samo',
    ],
    family: [
      'Novak', 'Horvat', 'Zupančič', 'Kovačič', 'Kovač', 'Zupan',
      'Kos', 'Turk', 'Vidmar', 'Krajnc', 'Božič', 'Golob',
      'Potočnik', 'Rozman', 'Kralj', 'Bizjak', 'Hočevar', 'Mlakar',
      'Oblak', 'Kavčič', 'Košir', 'Dolenc', 'Kotnik', 'Korošec',
      'Žagar', 'Hribar', 'Petrič', 'Zajc', 'Klemenčič', 'Lah',
      'Černe', 'Knez', 'Kolar', 'Logar', 'Kastelic', 'Pogačnik',
      'Tomšič', 'Koren', 'Furlan', 'Petek', 'Babič', 'Kranjc',
      'Pavlin', 'Vodopivec', 'Jerman', 'Zorko', 'Mihelič', 'Uršič',
      'Demšar', 'Eržen', 'Kobal', 'Medved', 'Bogataj', 'Cerar',
      'Erjavec', 'Lavrič', 'Janežič', 'Jenko', 'Dolinar', 'Kuhar',
      'Sever', 'Pavlič', 'Zupanc', 'Grošelj', 'Marolt', 'Pirnat',
      'Bergant', 'Jereb', 'Kramberger', 'Pirc', 'Rupnik', 'Vidic',
      'Čeh', 'Rus', 'Kramar', 'Likar', 'Močnik', 'Pahor',
      'Gregorič', 'Perko', 'Ravnik', 'Bregar', 'Gobec', 'Pečnik',
      'Snoj', 'Tavčar', 'Tomažič', 'Žnidaršič', 'Breznik', 'Hafner',
      'Kopač', 'Mrak', 'Simončič', 'Zidar', 'Ambrožič', 'Kolenc',
      'Leban', 'Modic', 'Stare', 'Debeljak',
    ],
  },
  SM: {
    female: [
      'Maria', 'Anna', 'Daniela', 'Francesca', 'Simona', 'Alessandra',
      'Antonella', 'Federica', 'Lorella', 'Marina', 'Sara', 'Valentina',
      'Alice', 'Anita', 'Anna Maria', 'Arianna', 'Assunta', 'Barbara',
      'Camilla', 'Chiara', 'Clara', 'Clelia', 'Denise', 'Domenica',
      'Edda', 'Eleanor', 'Elena', 'Eleonora', 'Emanuela', 'Fausta',
      'Fernanda', 'Giorgia', 'Giulia', 'Giuseppina', 'Gloriana', 'Grazia',
      'Graziella', 'Kamilla', 'Kristina', 'Laura', 'Lea', 'Lidia',
      'Loretta', 'Lucia', 'Ludmila', 'Luisa', 'Maria Teresa', 'Mariella',
      'Martina', 'Milena',
    ],
    male: [
      'Francesco', 'Giovanni', 'Marino', 'Antonio', 'Andrea', 'Giuseppe',
      'Giacomo', 'Matteo', 'Pietro', 'Federico', 'Pier', 'Marco',
      'Paolo', 'Simone', 'Filippo', 'Alessandro', 'Nicola', 'Vincenzo',
      'Michele', 'Luigi', 'Domenico', 'Giambattista', 'Girolamo', 'Luca',
      'Roberto', 'Carlo', 'Gian', 'Alberto', 'Giuliano', 'Lodovico',
      'Tommaso', 'Bartolo', 'Bartolomeo', 'Fabio', 'Mattia', 'Maurizio',
      'Stefano', 'Claudio', 'Enrico', 'Massimo', 'Davide', 'Luciano',
      'Alex', 'Benedetto', 'Cristofaro', 'Gino', 'Giorgio', 'Manuel',
      'Melchiorre', 'Christian',
    ],
    family: [
      'Belluzzi', 'Di Antonio', 'Di Giovanni', 'Gozi', 'Giannini', 'Bonelli',
      'Martelli', 'Ceccoli', 'Giangi', 'Di Marino', 'Mularoni', 'Gasperoni',
      'Lonfernini', 'Calcigni', 'Francini', 'Righi', 'Berti', 'Casali',
      'Onofri', 'Corbelli', 'di Francesco', 'Lunardini', 'Rossi', 'Valentini',
      'Valli', 'Bollini', 'Capicchioni', 'Casadei', 'di Andrea', 'Maiani',
      'Marcucci', 'Reffi', 'Terenzi', 'Tosini', 'Ugolini', 'Zanotti',
      'Benedettini', 'di Bianco', 'Di Cecco', 'di Paolo', 'Filippi', 'Franciosi',
      'Gabrielli', 'Giacomini', 'Malpeli', 'Mazza', 'Michelotti', 'Morri',
      'Muccioli', 'Nanni', 'Zafferani', 'Berardi', 'Bonetti', 'Cardelli',
      'Cecchetti', 'Chiaruzzi', 'di Bartolo', 'di Vita', 'Loli', 'Rossini',
      'Tini', 'Venturini', 'Zonzini', 'Angeli', 'Beni', 'Bugli',
      'Busignani', 'Carattoni', 'Ciavatta', 'Cionini', 'Di Girolamo', 'di Giuliano',
      'di Menghino', 'di Simone', 'Fabbri', 'Giardi', 'Leonardelli', 'Manenti',
      'Nicolini', 'Pelliccioni', 'Piva', 'Selva', 'Simoncini', 'Tura',
      'Zavoli', 'Arzilli', 'Bacciocchi', 'Begni', 'Bianchi', 'Ciacci',
      'Della Balda', 'di Cristofaro', 'di Fosco', 'Ercolani', 'Galassi', 'Gatti',
      'Guerra', 'Maccioni', 'Marani', 'Masi',
    ],
  },
} as const

export function isEuropeReviewedCountry(code: string): code is keyof typeof europeReviewedNames {
  return Object.hasOwn(europeReviewedNames, code)
}
