// Reviewed country-linked Wikidata candidate components; see docs/geographic-data.md.
export const northAmericaReviewedNames = {
  AG: {
    female: [
      "Samantha", "Kai", "Afia", "Alincia", "Alisha", "Allison",
      "Althea", "Alyssa", "Amanda", "Amelia", "Amy", "Ann Marie",
      "Athina", "Barbara", "Bertha", "Breanna", "Charmaine", "Christal",
      "Claudette", "Colette", "Dalia", "Dine", "Dorothy",
      "Dulcie", "Elizabeth", "Ellie", "Gwendolyn", "Heather", "Heidi",
      "Hilda", "Jackie", "Jacqui", "Jamila", "Janice", "Joanne",
      "Joella", "Karen", "Karin", "Keisha",
    ],
    male: [
      "Alex", "Anthony", "George", "James", "John", "Kareem",
      "Michael", "Sydney", "Antonio", "Curtis", "Dale", "Dave",
      "Devon", "Gavin", "Kelly", "Kevin", "Larry", "Lennox",
      "Lester", "Neil", "Paul", "Quentin", "Ralston", "Robert",
      "Rowan", "Roy", "Shannon", "Troy", "Vere", "Winston",
      "Aaron", "Adolphus", "Adonis", "Aiden", "Alexis", "Alfred",
      "Allen", "Alston", "Alvin", "Amir",
    ],
    family: [
      "Joseph", "Thomas", "Simon", "Williams", "Browne", "Francis",
      "James", "Spencer", "Benjamin", "Bird", "Christian", "Edwards",
      "Harris", "Hughes", "Jacobs", "Lewis", "Peters", "Richards",
      "Richardson", "Walsh", "Burton", "Charles", "Henry", "Prince",
      "Anthony", "Braithwaite", "Camacho", "Carr", "Clarke", "Davis",
      "Falcone", "Frederick", "Gomes", "Grant", "Gregory", "Hillhouse",
      "Jackson", "Jarvis", "Lindsay", "Lloyd", "Murray", "Nicholas",
      "Phillip", "Roberts", "Robinson",
    ],
  },
  BB: {
    female: [
      "Andrea", "Danielle", "Amanda", "Karen", "Natalie", "Alison",
      "Amber", "Daphne", "Esther", "Hannah", "Jalisa", "Melissa",
      "Mia", "Monique", "Patricia", "Tia", "Toni", "Acacia",
      "Akela", "Alana", "Alberta", "Aleisha", "Alesha", "Alexis",
      "Amor", "Ann", "Anya", "Ashlee", "Ayanna", "Barbara",
      "Bernadine", "Bertha", "Billie", "Britnee", "Caitlin", "Carlie",
      "Carol", "Caroline", "Chalise", "Charice",
    ],
    male: [
      "John", "Charles", "George", "James", "Michael", "David",
      "Shaquille", "Andrew", "Harold", "Henry", "Nicholas", "Richard",
      "Ryan", "Anthony", "Christopher", "Joseph", "Mark", "Orlando",
      "Roy", "Tony", "Wayne", "William", "Albert", "Alvin",
      "Barry", "Clifford", "Colin", "Edward", "Elvis", "Frank",
      "Gregory", "Hugh", "Jason", "Jonathan", "Joshua", "Keith",
      "Kemar", "Kevin", "Lionel", "Mario",
    ],
    family: [
      "Williams", "Clarke", "Holder", "Griffith", "Browne", "Forde",
      "Haynes", "Jones", "Marshall", "Smith", "Blackman", "King",
      "Edwards", "Hinds", "Phillips", "Thomas", "Jordan", "Moore",
      "Thompson", "Alleyne", "Austin", "Best", "Boyce", "Cox",
      "Gibson", "Nurse", "Payne", "Small", "Adams", "Barrow",
      "Bishop", "Carrington", "Carter", "Goodman", "Goodridge", "Hall",
      "Harris", "Ifill", "Johnson", "Kelly", "Layne", "Lewis",
      "Louis", "Lynch", "Padmore",
    ],
  },
  BM: {
    female: [
      "Emma", "Nicole", "Phyllis", "Rebecca", "Alisha", "Alison",
      "Aliyyah", "Amara", "Angela", "Arantxa", "Ashley", "Bessie",
      "Caitlyn", "Cecilia", "Charlene", "Chevonne", "Christina", "Debbie",
      "Eleanor", "Eliza", "Erica", "Eva", "Fiona", "Flora",
      "Heather", "Isabelle", "Jeanne", "Jessica", "Juliana", "Kathy",
      "Kiera", "Kim", "Leigh", "Linda", "Lucy", "Madison",
      "Maryellen", "Melanie", "Michele", "Michelle",
    ],
    male: [
      "David", "Peter", "John", "James", "Charles", "George",
      "Michael", "Nicholas", "Richard", "Robert", "Allan", "Arthur",
      "Bill", "Donald", "Henry", "Roger", "Anthony", "Arnold",
      "Chris", "Clarence", "Dennis", "Edmund", "Graham", "Harold",
      "Keith", "Ronald", "Stanley", "Stephen", "Steven", "Thomas",
      "Warren", "Adam", "Alan", "Albert", "Alex", "Alexander",
      "Barry", "Brian", "Brownlow", "Bruce",
    ],
    family: [
      "Smith", "Tucker", "Dill", "Jones", "Robinson", "Douglas",
      "Butterfield", "Cooper", "Gibbons", "Gray", "Minors", "Brown",
      "Cox", "Gilbert", "Hall", "Harvey", "Hill", "Hodgson",
      "Jackson", "James", "Manders", "Richardson", "Saunders", "Stubbs",
      "Talbot", "Thompson", "White", "Williams", "Wilson", "Ahad",
      "Aitken", "Albouy", "Alger", "Alizadeh", "Altamura", "Andrews",
      "Archer", "Babb", "Bailey", "Bardgett", "Barnard", "Barry",
      "Barton", "Basden", "Bean",
    ],
  },
  BS: {
    female: [
      "Latoya", "Patricia", "Anthonique", "Christine", "Helen", "Janice",
      "Linda", "Lori", "Tiffany", "Alana", "Albertha", "Alexandria",
      "Alexus", "Allyson", "Althea", "Amanda", "Anastacia", "Angelique",
      "Anina", "Ann", "Anna", "Arianna", "Ashley", "Barbara",
      "Bertha", "Bianca", "Brea", "Britany", "Carmel", "Catherine",
      "Celeste", "Chandra", "Chantel", "Cheryl", "Cintia", "Cynthia",
      "Danae", "Danica", "Daphne", "Daria",
    ],
    male: [
      "Michael", "Christopher", "Ryan", "Kevin", "Ian", "John",
      "Joshua", "Lynden", "Mark", "Robert", "David", "Dwight",
      "Godfrey", "James", "Jonathan", "Philip", "Rashad", "Trevor",
      "Aaron", "Adrian", "Albert", "Allan", "Alonzo", "Andre",
      "Andrew", "Anthony", "Arthur", "Blake", "Calvin", "Cory",
      "Craig", "Daniel", "Davonte", "Derrick", "Dwayne", "Dylan",
      "Elvis", "Eric", "Garvin", "George",
    ],
    family: [
      "Smith", "Johnson", "Knowles", "Rolle", "Thompson", "Ferguson",
      "Williams", "Davis", "Miller", "Brown", "Hanna", "Sands",
      "Bain", "Cooper", "Cox", "Jones", "Moss", "Pratt",
      "Butler", "Cartwright", "Greene", "Kelly", "Parker", "Rose",
      "Russell", "Wilson", "Clarke", "Evans", "Forbes", "Gibson",
      "Hall", "Ingraham", "Joseph", "Kemp", "Lewis", "Lockhart",
      "Mackey", "Munnings", "Pinder", "Taylor", "Wells", "Adderley",
      "Bethel", "Burrows", "Carey",
    ],
  },
  BZ: {
    female: [
      "Rebecca", "Althea", "Elizabeth", "Jane", "Patricia", "Abbie",
      "Adele", "Agnes", "Aishah", "Alice", "Alicia", "Alisha",
      "Ana", "Andrea", "Angela", "Ann", "Ann-Marie", "Anthea",
      "Arianne", "Audrey", "Beatrice", "Beverly", "Brenda", "Camille",
      "Carla", "Carle", "Carolyn", "Carrie", "Cathleen", "Charmaine",
      "Christine", "Cristina", "Deborah", "Debra", "Denise", "Destinee",
      "Dian", "Diane", "Dolores", "Dominique",
    ],
    male: [
      "Charles", "Anthony", "John", "Michael", "David", "Henry",
      "Joseph", "George", "Paul", "Alexander", "Carlos", "Daniel",
      "Mark", "Oscar", "Robert", "Russell", "William", "Francis",
      "Frank", "Ian", "Jose", "Kenneth", "Leon", "Mario",
      "Peter", "Phillip", "Arthur", "Edward", "Ignacio", "James",
      "Kevin", "Manuel", "Marlon", "Pablo", "Sam", "Samuel",
      "Santiago", "Wilfred", "Albert", "Alex",
    ],
    family: [
      "Smith", "Castillo", "Williams", "Usher", "Barrow", "Flowers",
      "Jones", "Leslie", "Marin", "Martinez", "Young", "Cayetano",
      "Hyde", "Palacio", "Thurton", "Vernon", "Wright", "Campos",
      "Davis", "Dawson", "Fonseca", "Garcia", "Gibson", "Gill",
      "Gray", "Lewis", "Longsworth", "López", "Lovell", "Mena",
      "Mendez", "Musa", "Reneau", "Roches", "Salazar", "Sutherland",
      "Sylvestre", "Thompson", "Acosta", "Anderson", "Andrews", "Arana",
      "Arceo", "Ayuso", "Bowen",
    ],
  },
  CA: {
    female: [
      "Louise", "Catherine", "Mary", "Anne", "Elizabeth", "Sarah",
      "Julie", "Isabelle", "Margaret", "Nicole", "Susan", "Jennifer",
      "Diane", "Caroline", "Christine", "Sylvie", "Karen", "Nancy",
      "Suzanne", "Barbara", "Hélène", "Michelle", "Ann", "Danielle",
      "Sophie", "Linda", "Geneviève", "Annie", "Claire", "Jessica",
      "Lisa", "Jane", "Monique", "Nathalie", "Patricia", "Laura",
      "Heather", "Anna", "Chantal", "Emily",
    ],
    male: [
      "John", "William", "Robert", "James", "David", "George",
      "Joseph", "Charles", "Paul", "Michael", "Pierre", "Richard",
      "Thomas", "Peter", "Daniel", "Michel", "Jean", "Louis",
      "Henry", "Alexander", "Mike", "Edward", "André", "Arthur",
      "Andrew", "François", "Jacques", "Mark", "Frank", "Claude",
      "Bill", "Donald", "Jim", "Brian", "Patrick", "Bob",
      "Marc", "Gordon", "Jack", "Albert",
    ],
    family: [
      "Smith", "Tremblay", "Brown", "Gagnon", "Roy", "Campbell",
      "Wilson", "Martin", "Taylor", "Johnson", "Côté", "Jones",
      "Anderson", "Bouchard", "Young", "Stewart", "Thompson", "Gauthier",
      "MacDonald", "Miller", "Pelletier", "Williams", "Ross", "Fraser",
      "White", "Macdonald", "Morin", "Scott", "Bélanger", "Fortin",
      "Reid", "Bergeron", "Leblanc", "Cameron", "Robinson", "Mitchell",
      "Murray", "Clark", "Caron", "Johnston", "Boucher", "Moore",
      "McDonald", "Robertson", "Landry",
    ],
  },
  CR: {
    female: [
      "María", "Natalia", "Ana", "Carolina", "Maria", "Laura",
      "Adriana", "Catalina", "Daniela", "Emilia", "Karina", "Paula",
      "Alejandra", "Elena", "Marta", "Mónica", "Paola", "Patricia",
      "Priscilla", "Sofía", "Victoria", "Virginia", "Adela", "Elizabeth",
      "Eugenia", "Karen", "Karla", "Mariana", "Mariela", "Montserrat",
      "Sara", "Wendy", "Amalia", "Amanda", "Andrea", "Brenda",
      "Diana", "Fabiana", "Fabiola", "Gabriela",
    ],
    male: [
      "José", "Carlos", "Juan", "Luis", "Manuel", "Jorge",
      "Daniel", "Fernando", "Francisco", "Alejandro", "Rafael", "Mario",
      "Miguel", "Diego", "Guillermo", "Rodrigo", "Marco", "Ricardo",
      "Enrique", "Gerardo", "Álvaro", "Antonio", "David", "Pablo",
      "Rodolfo", "Andrés", "Edgar", "Pedro", "Roberto", "Víctor",
      "Esteban", "Ronald", "William", "Alberto", "Hernán", "Joaquín",
      "Mauricio", "Sergio", "José María", "Alexander",
    ],
    family: [
      "González", "Mora", "Fernández", "Rodríguez", "Jiménez", "Alfaro",
      "Rojas", "Aguilar", "Quesada", "Brenes", "Sánchez", "Vega",
      "Alvarado", "Castro", "Blanco", "Chaves", "Fonseca", "Hernández",
      "Herrera", "Ramírez", "Salazar", "Villalobos", "Gómez", "López",
      "Morales", "Pérez", "Salas", "Esquivel", "Flores", "Quirós",
      "Trejos", "Araya", "Calvo", "Cruz", "Núñez", "Valverde",
      "Arias", "Campos", "Chacón", "Murillo", "Ruiz", "Álvarez",
      "Díaz", "Guzmán", "Martínez",
    ],
  },
  CU: {
    female: [
      "María", "Ana", "Rosa", "Mercedes", "Isabel", "Laura",
      "Marta", "Maria", "Miriam", "Carmen", "Claudia", "Margarita",
      "Mirta", "Olga", "Beatriz", "Lisandra", "Luisa", "Teresa",
      "Inés", "Juana", "Lourdes", "Nancy", "Adriana", "Alina",
      "Amelia", "Aurora", "Caridad", "Cecilia", "Elena", "Hilda",
      "Josefina", "Martha", "Mayra", "Alicia", "Cristina", "Emilia",
      "Esther", "Ileana", "Niurka", "Odalys",
    ],
    male: [
      "José", "Luis", "Carlos", "Jorge", "Juan", "Manuel",
      "Pedro", "Roberto", "Antonio", "Alberto", "Enrique", "Miguel",
      "Francisco", "máximo merilio", "Raúl", "Mario", "Julio", "Ramón",
      "Rafael", "Ernesto", "Jesús", "Ángel", "Orlando", "Guillermo",
      "Eduardo", "Alejandro", "Alfredo", "Fernando", "Emilio", "Lázaro",
      "Pablo", "Ricardo", "Félix", "Rolando", "Sergio", "René",
      "Héctor", "Joaquín", "José Antonio", "Andrés",
    ],
    family: [
      "González", "Martínez", "Rodríguez", "Pérez", "Fernández", "García",
      "Díaz", "López", "Hernández", "Álvarez", "Valdés", "Herrera",
      "Gómez", "Sánchez", "Suárez", "Ramos", "Torres", "Castro",
      "Ruiz", "Castillo", "Cruz", "Morales", "Acosta", "Romero",
      "Núñez", "Alonso", "Guerra", "Jiménez", "Reyes", "Martinez",
      "Alfonso", "Espinosa", "Delgado", "Rojas", "Estrada", "Ramírez",
      "Rodriguez", "Abreu", "Blanco", "Cabrera", "Mesa", "Peña",
      "Diaz", "Menéndez", "Mora",
    ],
  },
  DM: {
    female: [
      "Francine", "Alix", "Anette", "Britney", "Carissa", "Catherine",
      "Chelsea", "Cleopatra", "Cynthia", "Dawn", "Denise", "Dominique",
      "Doreen", "Doris", "Elenora", "Éléonore", "Elizabeth", "Émeline",
      "Eugenia", "Evelina", "Gertrude", "Gloria", "Gretta", "Irmine",
      "Jasmine", "Jean", "Kirsten", "Kylee", "Luan", "Mabel",
      "Marcia", "Marisol", "Melissa", "Merissa", "Michele", "Neva",
      "Nicole", "Ophelia", "Patricia", "Pauline",
    ],
    male: [
      "David", "Edward", "Joseph", "Brian", "Cecil", "Christopher",
      "Clifford", "Crispin", "Frederick", "Ian", "Kenneth", "Kurt",
      "Lester", "Michael", "Paul", "Ronnie", "Shane", "Vernon",
      "Adam", "Alvin", "Alwin", "Ambrose", "Anthony", "Augustus",
      "Bentley", "Billy", "Brion", "Cassius", "Chad", "Charles",
      "Chris", "Clarence", "Claudius", "Daniel", "Darius", "Delbert",
      "Derek", "Dillon", "Dionisio", "Don",
    ],
    family: [
      "Joseph", "Bertrand", "Douglas", "George", "James", "Baron",
      "Charles", "Francis", "Lawrence", "Phillip", "Williams", "Benjamin",
      "Harris", "Henderson", "Henry", "John", "Lockhart", "Marshall",
      "Philip", "Roberts", "Royer", "Shillingford", "Allfrey", "Antoine",
      "Archibald", "Baptiste", "Bazil", "Bernard", "Blanchard", "Bowers",
      "Brand", "Bryan", "Bully", "Burton", "Byam", "Caroit",
      "Casimir", "Christian", "Connor", "Cooke", "Dangler", "Defoe",
      "Dumas", "Durand", "Durañona",
    ],
  },
  DO: {
    female: [
      "Ana", "Carmen", "María", "Rosa", "Juana", "Maria",
      "Margarita", "Raquel", "Sonia", "Claudia", "Josefina", "Karla",
      "Natalia", "Teresa", "Gabriela", "Laura", "Mercedes", "Adela",
      "Alexandra", "Amelia", "Angela", "Arianna", "Ashley", "Belkis",
      "Camila", "Carolina", "Elizabeth", "Emely", "Gina", "Hilda",
      "Isabel", "Jenny", "Jessica", "Johanna", "Kimberly", "Leidy",
      "María Altagracia", "Milagros", "Minerva", "Nancy",
    ],
    male: [
      "José", "Juan", "Luis", "Rafael", "Carlos", "Francisco",
      "Antonio", "Pedro", "Ramón", "Miguel", "Manuel", "Oliver",
      "Héctor", "Julio", "Félix", "Fernando", "Alberto", "Ángel",
      "César", "Domingo", "Alejandro", "Andrés", "Gabriel", "Jorge",
      "Roberto", "Tony", "Víctor", "Alfredo", "Henry", "Jesús",
      "Manny", "Nelson", "Arturo", "Frank", "Franklin", "Freddy",
      "Joel", "Jose", "Junior", "Mario",
    ],
    family: [
      "Martínez", "García", "Rodríguez", "Pérez", "Ramírez", "Peña",
      "Castillo", "Núñez", "Santana", "Cruz", "Rosario", "González",
      "Guzmán", "Gómez", "Reyes", "Jiménez", "Guerrero", "Valdez",
      "Díaz", "Santos", "Sánchez", "Polanco", "Castro", "Hernández",
      "Marte", "Rodriguez", "Arias", "Brito", "Fernández", "Mercedes",
      "Abreu", "López", "Peralta", "Soriano", "Acosta", "Almonte",
      "Bautista", "Cabrera", "Paulino", "Suero", "de la Rosa", "Espinal",
      "Garcia", "Mateo", "Báez",
    ],
  },
  GD: {
    female: [
      "Hilda", "Joan", "Lucy", "Aaliyah", "Abigail", "Afy",
      "Agnes", "Allison", "Amanda", "Andrea", "Angelia", "Ann",
      "Arlene", "Brenda", "Briana", "Britney", "Camille", "Cassie",
      "Cayla", "Cécile", "Clarice", "Colleen", "Cynthia", "Diamond",
      "Elfriede", "Erin", "Eva", "Gabriela", "Gaia", "Genevieve",
      "Geraldine", "Gertrude", "Gillian", "Gloria", "Glynis", "Hailey",
      "Halle", "Jacqueline", "Janelle", "Jean",
    ],
    male: [
      "Andre", "Anthony", "George", "Josh", "Kevin", "Ricky",
      "Alister", "Anderson", "Arthur", "Bernard", "David", "Eric",
      "John", "Lindon", "Nigel", "Paul", "Shane", "Trevor",
      "Alleyne", "Allister", "Andray", "Andy", "Ben", "Benjamin",
      "Bethuel", "Cameron", "Canute", "Carlyle", "Chris", "Clifton",
      "Clint", "Clive", "Corey", "Craig", "Daniel", "Daniel Charles",
      "Darius", "Darren", "Delon", "Delron",
    ],
    family: [
      "Williams", "Charles", "Lewis", "Felix", "Mitchell", "Fletcher",
      "George", "James", "Joseph", "Peters", "Redhead", "Roberts",
      "Sylvester", "Thomas", "Baptiste", "Bishop", "Hughes", "Rennie",
      "Bain", "Chase", "Collins", "Edwards", "Francis", "Gibbs",
      "Hazzard", "Hood", "John", "Johnson", "Jones", "Julien",
      "Kord", "Paul", "Phillip", "Robertson", "Smith", "Abel",
      "Addo", "Adewunmi", "Agee", "Alexander", "Alexis", "Antoine",
      "Antrobus", "Ashby", "Augustine",
    ],
  },
  GT: {
    female: [
      "María", "Ana", "Andrea", "Gabriela", "Isabel", "Maria",
      "Daniela", "Alejandra", "Claudia", "Marta", "Sandra", "Silvia",
      "Thelma", "Adriana", "Carmen", "Cynthia", "Diana", "Elisa",
      "Gloria", "Karen", "Mayra", "Paula", "Valeria", "Alicia",
      "Astrid", "Aura", "Carolina", "Emily", "Evelyn", "Isabella",
      "Jennifer", "Jessica", "Juana", "Lucía", "Marcela", "Margarita",
      "Mariana", "Mónica", "Rosa", "Sara",
    ],
    male: [
      "José", "Carlos", "Luis", "Mario", "Juan", "Jorge",
      "Manuel", "Roberto", "Francisco", "Julio", "Antonio", "Ricardo",
      "Rafael", "Edgar", "Enrique", "Alejandro", "Eduardo", "Héctor",
      "Óscar", "Pedro", "Álvaro", "Gustavo", "Hugo", "Marco",
      "Sergio", "Alfonso", "Fernando", "Oscar", "César", "Erick",
      "Kevin", "Miguel", "Pablo", "René", "Rodolfo", "Rodrigo",
      "Daniel", "Rolando", "Víctor", "Alberto",
    ],
    family: [
      "López", "Martínez", "Morales", "González", "Méndez", "Pérez",
      "Rodríguez", "Estrada", "García", "Aguilar", "Castillo", "Escobar",
      "Cabrera", "Cruz", "Flores", "Castañeda", "Fernández", "Gómez",
      "Hernández", "Monterroso", "Ramírez", "Torres", "Archila", "Castellanos",
      "Herrera", "Rodas", "Samayoa", "Sandoval", "Barrios", "Blanco",
      "Díaz", "Marroquín", "Reyes", "Ruiz", "Árbenz", "Arévalo",
      "Barrera", "García Granados", "Godoy", "Gonzalez", "Lopez", "Martinez",
      "Mejía", "Miranda", "Monzón",
    ],
  },
  HN: {
    female: [
      "María", "Ana", "Maria", "Margarita", "Brenda", "Carmen",
      "Elvia", "Gabriela", "Isabella", "Karla", "Mercedes", "Raquel",
      "Sandra", "Victoria", "Wendy", "Andrea", "Berta", "Bertha",
      "Bessy", "Blanca", "Carolina", "Cesia", "Claudia", "Elizabeth",
      "Eva", "Fernanda", "Gladys", "Graciela", "Helen", "Linda",
      "Lorena", "Lourdes", "Marta", "Martha", "Melissa", "Perla",
      "Vilma", "Virginia", "Vivian", "Adela",
    ],
    male: [
      "José", "Carlos", "Luis", "Jorge", "Mario", "Francisco",
      "David", "Miguel", "Óscar", "Roberto", "Juan", "Eduardo",
      "Héctor", "Henry", "Ramón", "Kevin", "Ricardo", "Antonio",
      "César", "Enrique", "Marco", "Manuel", "Rafael", "Víctor",
      "Ángel", "Edwin", "Erick", "Javier", "Arturo", "Brayan",
      "Daniel", "Juan Carlos", "Marlon", "Marvin", "Mauricio", "Milton",
      "Oscar", "Rigoberto", "Rodolfo", "Alexander",
    ],
    family: [
      "Martínez", "Flores", "López", "García", "Castillo", "Pineda",
      "Ramírez", "Castro", "Reyes", "Gómez", "Medina", "Mejía",
      "Ramos", "Alvarado", "Cruz", "Moncada", "Padilla", "Rodríguez",
      "Suazo", "Aguilar", "Cárcamo", "Martinez", "Castellanos", "Díaz",
      "Figueroa", "Hernández", "Molina", "Palacios", "Álvarez", "González",
      "Güity", "Mendoza", "Morales", "Pavón", "Torres", "Williams",
      "Acosta", "Ávila", "Caballero", "Canales", "Diaz", "Guerrero",
      "Núñez", "Oliva", "Paz",
    ],
  },
  HT: {
    female: [
      "Michèle", "Rose", "Maryse", "Sophia", "Vanessa", "Elsie",
      "Jenny", "Micheline", "Nadine", "Nancy", "Angeline", "Barbara",
      "Camille", "Cynthia", "Danielle", "Darlene", "Darline", "Edith",
      "Elisabeth", "Esther", "Evelyn", "Florence", "Gina", "Ginette",
      "Jacquelin", "Jacqueline", "Jessica", "Martine", "Melissa", "Mireille",
      "Nathalie", "Nicole", "Pascale", "Rachelle", "Yanick", "Yolette",
      "Adeline", "Alice", "Anne", "Antoinette",
    ],
    male: [
      "Jean", "Joseph", "Pierre", "Jacques", "Frantz", "Fritz",
      "Emmanuel", "Georges", "Louis", "François", "Michel", "Jean-Claude",
      "Charles", "Yves", "Guy", "André", "Gérard", "Paul",
      "Antoine", "Ernst", "Jean-Baptiste", "Max", "Serge", "Andre",
      "Raymond", "Daniel", "Maurice", "Patrick", "Roger", "Dominique",
      "Gabriel", "Gary", "Philippe", "René", "Claude", "Robert",
      "Yvon", "Gerard", "James", "Samuel",
    ],
    family: [
      "Joseph", "Pierre", "Louis", "Jean", "Michel", "Charles",
      "Etienne", "Augustin", "Guillaume", "Paul", "François", "Jacques",
      "Vincent", "Constant", "Nicolas", "Pascal", "Toussaint", "Auguste",
      "Benjamin", "Cadet", "Gabriel", "Henry", "Jean-Baptiste", "Liautaud",
      "Saint Fleur", "Alexandre", "Ambroise", "Antoine", "Casseus", "Desir",
      "Duvalier", "Gauthier", "Jeudy", "Lafontant", "Laraque", "Latortue",
      "Louissaint", "Marcelin", "Moïse", "Saint-Fleur", "Simon", "Abraham",
      "Baptiste", "Casimir", "Chery",
    ],
  },
  JM: {
    female: [
      "Christine", "Nicole", "Patricia", "Christina", "Andrea", "Ann",
      "Barbara", "Carol", "Elaine", "Jean", "Marcia", "Margaret",
      "Mary", "Nadine", "Natasha", "Samantha", "Sharon", "Simone",
      "Yvonne", "Angela", "Audrey", "Beverley", "Beverly", "Camille",
      "Cynthia", "Dawn", "Dorothy", "Jacqueline", "Jennifer", "Kimberly",
      "Lorna", "Louise", "Maria", "Marlene", "Olivia", "Sheila",
      "Alyssa", "Amy", "Carmen", "Catherine",
    ],
    male: [
      "Michael", "Anthony", "Richard", "George", "Winston", "David",
      "John", "Robert", "Andrew", "Christopher", "Lloyd", "Peter",
      "Paul", "Andre", "Dennis", "Jermaine", "Keith", "Omar",
      "Roy", "Kenneth", "Patrick", "Ricardo", "Charles", "Errol",
      "Jason", "Joseph", "Trevor", "Arthur", "Wayne", "Eric",
      "Ian", "Jah", "Ryan", "Tony", "Albert", "Daniel",
      "Delroy", "Herbert", "Horace", "Shaquille",
    ],
    family: [
      "Williams", "Brown", "Smith", "Campbell", "Reid", "Thomas",
      "Anderson", "Johnson", "Thompson", "Gordon", "Clarke", "Robinson",
      "Stewart", "Bailey", "Taylor", "Edwards", "Richards", "Jackson",
      "Jones", "Lewis", "Powell", "Barrett", "Blake", "Davis",
      "James", "Miller", "Palmer", "Scott", "Walker", "Bennett",
      "Grant", "Morgan", "Wilson", "Foster", "Hall", "Henry",
      "Phillips", "Spencer", "Watson", "Barnes", "Dixon", "King",
      "Marley", "Allen", "McDonald",
    ],
  },
  KN: {
    female: [
      "Josephine", "Mary", "Wendy", "Akilah", "Althea", "Anne",
      "Ariel", "Caroline", "Chelsey", "Constance", "Diane", "Elise",
      "Eliza", "Elsa", "Hazel", "Iyanla", "Janice", "Janine",
      "Jasmine", "Jessica", "Joyelle", "Kathryn", "Kaylee", "Lenore",
      "Lorna", "Marcella", "Natasha", "Sarah", "Sherry", "Shirley",
    ],
    male: [
      "Ian", "James", "Michael", "Shaquille", "Dennis", "Jason",
      "Joel", "Kareem", "Keith", "Paul", "William", "Aaron",
      "Adam", "Adolphus", "Ahmed", "Alain", "Alexis", "Alister",
      "Ammar", "Andre", "Anthony", "Antoine", "Arif", "Armen",
      "Atiba", "Austin", "Bertram", "Brijesh", "Calvert", "Caryl",
      "Charles", "Clement", "Clifford", "Clyde", "Codville", "Constantine",
      "Cuthbert", "Cyril", "Dale", "Denzil",
    ],
    family: [
      "Williams", "Harris", "Francis", "Clarke", "Browne", "Byron",
      "Douglas", "Mills", "Powell", "Rogers", "Simmonds", "Adams",
      "Bennett", "Charles", "Duncan", "Flemming", "Freeman", "Gumbs",
      "Huggins", "Kelly", "Lawrence", "Morton", "Phipps", "Queeley",
      "Saunders", "Skerritt", "Amory", "Bailey", "Barzey", "Bass",
    ],
  },
  LC: {
    female: [
      "Michelle", "Patricia", "Alvina", "Angelina", "Beth", "Cassandra",
      "Cheryll", "Danielle", "Emma", "Eugena", "Fiona", "Gale",
      "Hilary", "Ilana", "Jane", "Jeanelle", "Jeannine", "Joy-Ann",
      "Julien", "Kenna", "Kiva", "Laura", "Len", "Leonne",
      "Llewellyn", "Louise", "Makeba", "Mara", "Megan", "Melanie",
      "Morella", "Natasha", "Nicole", "Nina", "Pamela", "Pearlette",
      "Petronilla", "Philipa", "Racquel", "Rosemary",
    ],
    male: [
      "John", "George", "Allen", "Cecil", "David", "Francis",
      "Guy", "Ignatius", "Joachim", "Kevin", "Michael", "Philip",
      "Richard", "Ron", "Stephen", "Troy", "Alain", "Albert",
      "Alfred", "Allan", "Alton", "Alva", "Andre", "Andreas",
      "Andrew", "Anthony", "Antonio", "Arthur", "Barry", "Bayan",
      "Bernard", "Boswell", "Bradford", "Bradley", "Carlos", "Chris",
      "Christian", "Claudius", "Clement", "Cliff",
    ],
    family: [
      "James", "John", "Joseph", "Compton", "Edward", "Lewis",
      "Charles", "George", "Henry", "Simon", "Alcide", "Alfred",
      "Auguste", "Elva", "Frederick", "Hippolyte", "King", "Lionel",
      "Louisy", "Paul", "Peterkin", "Pierre", "Prospere", "Reynolds",
      "Shepherd", "Walcott", "Williams", "Wilson", "Abbott", "Albert",
      "Aman", "Anthony", "Augustin", "Baptiste", "Beaubrun", "Bernard",
      "Biscette", "Boucher", "Bousquet", "Brown", "Butcher", "Calderon",
      "Carasco", "Cenac", "Charlery",
    ],
  },
  MX: {
    female: [
      "María", "Ana", "Patricia", "Laura", "Martha", "Alejandra",
      "Gabriela", "Claudia", "Guadalupe", "Adriana", "Margarita", "Carmen",
      "Rosa", "Daniela", "Mariana", "Gloria", "Maria", "Silvia",
      "Diana", "Beatriz", "Karla", "Mónica", "Alicia", "Susana",
      "Andrea", "Cecilia", "Norma", "Luz", "Teresa", "Elena",
      "Paola", "Fernanda", "Alma", "Blanca", "Irma", "Yolanda",
      "Cristina", "Elizabeth", "Isabel", "Sandra",
    ],
    male: [
      "José", "Carlos", "Luis", "Francisco", "Juan", "Manuel",
      "Jorge", "Antonio", "Jesús", "Miguel", "Alejandro", "Fernando",
      "Rafael", "Enrique", "Eduardo", "Roberto", "Pedro", "Ricardo",
      "Mario", "Alberto", "Guillermo", "Sergio", "Arturo", "máximo merilio",
      "Raúl", "Daniel", "Javier", "Héctor", "Alfonso", "Ignacio",
      "Salvador", "Alfredo", "Pablo", "David", "Jaime", "Gerardo",
      "Diego", "Gustavo", "Ángel", "Ramón",
    ],
    family: [
      "González", "García", "Hernández", "Martínez", "López", "Sánchez",
      "Pérez", "Rodríguez", "Fernández", "Flores", "Gómez", "Ramírez",
      "Díaz", "Aguilar", "Mendoza", "Ruiz", "Torres", "Álvarez",
      "Romero", "Castro", "Castillo", "Morales", "Jiménez", "Herrera",
      "Salazar", "Reyes", "Guzmán", "Ramos", "Martinez", "Moreno",
      "Cruz", "Guerrero", "Ortega", "Ortiz", "Muñoz", "Vázquez",
      "Medina", "Aguirre", "Estrada", "Rodriguez", "Garza", "Carrillo",
      "Chávez", "Navarro", "Rojas",
    ],
  },
  NI: {
    female: [
      "Maria", "María", "Ana", "Gloria", "Olga", "Blanca",
      "Rosa", "Sara", "Adriana", "Indiana", "Reyna", "Victoria",
      "Alicia", "Allison", "Cecilia", "Cristiana", "Cristina", "Daniela",
      "Dayana", "Daysi", "Diana", "Elizabeth", "Geraldine", "Iris",
      "Irma", "Josefa", "Judith", "Leisha", "Lillian", "Lucía",
      "Margarita", "Mariana", "Marianela", "Martha", "Mercedes", "Rosario",
      "Scarleth", "Sharon", "Silvia", "Teresa",
    ],
    male: [
      "Carlos", "José", "Francisco", "Manuel", "Eduardo", "Juan",
      "Luis", "Pedro", "Fernando", "Joaquín", "Miguel", "David",
      "Oliver", "Alejandro", "Salvador", "Julio", "Ricardo", "Alberto",
      "Alfonso", "Antonio", "Enrique", "Guillermo", "Jaime", "Jorge",
      "José María", "Mariano", "Pablo", "Rigoberto", "Rolando", "César",
      "Erick", "Gabriel", "Gustavo", "Marcos", "René", "Tomás",
      "Adolfo", "Alfredo", "Anastasio", "Arturo",
    ],
    family: [
      "López", "Martínez", "Rodríguez", "Chamorro", "Ramírez", "González",
      "Ortega", "Arce", "Argüello", "Cruz", "Estrada", "Palacios",
      "Pérez", "Rivas", "Rosales", "Cardenal", "Castillo", "Guevara",
      "Hernández", "Hodgson", "Mayorga", "Mejía", "Rojas", "Romero",
      "Sacasa", "Torres", "Belli", "Calero", "Campbell", "Cortés",
      "Cuadra", "Delgado", "Fernández", "García", "Gordillo", "Guerrero",
      "Mairena", "Mena", "Méndez", "Mendieta", "Mendoza", "Molina",
      "Morales", "Núñez", "Rocha",
    ],
  },
  PA: {
    female: [
      "Ana", "María", "Carmen", "Isabel", "Karla", "Marta",
      "Nicole", "Carolina", "Giselle", "Gladys", "Gloria", "Patricia",
      "Rosa", "Sandra", "Silvia", "Alicia", "Amelia", "Ashley",
      "del Carmen", "Diana", "Emilia", "Emily", "Erika", "Gabriela",
      "Karen", "Katherine", "Lineth", "Lucy", "Natalia", "Olga",
      "Rosario", "Sofia", "Virginia", "Wendy", "Alejandra", "Alexandra",
      "Amalia", "Angela", "Aura", "Carlota",
    ],
    male: [
      "José", "Luis", "Carlos", "Ricardo", "Roberto", "Manuel",
      "Enrique", "Jorge", "Antonio", "Alberto", "Eduardo", "Juan",
      "Ernesto", "Rafael", "Fernando", "Julio", "Francisco", "Gabriel",
      "Javier", "Omar", "Alfredo", "Jaime", "Arturo", "Eric",
      "Pedro", "Víctor", "Alejandro", "Guillermo", "Mario", "Miguel",
      "Ramón", "Rolando", "Rubén", "Alfonso", "Daniel", "Humberto",
      "Rodolfo", "Alex", "Ángel", "César",
    ],
    family: [
      "González", "Rodríguez", "Herrera", "Castillo", "Brown", "Quintero",
      "Rodriguez", "Sánchez", "Alvarado", "Díaz", "Gómez", "Hernández",
      "Jaén", "Jiménez", "Aguilar", "Martínez", "Mosquera", "Vásquez",
      "Arias", "Arosemena", "Cedeño", "López", "Moreno", "Salazar",
      "Aparicio", "Caballero", "Dominguez", "Gonzalez", "Medina", "Méndez",
      "Mendoza", "Montenegro", "Morales", "Muñoz", "Peralta", "Pérez",
      "Tejada", "Torres", "Acosta", "Anderson", "Córdoba", "Delgado",
      "Diaz", "Fábrega", "Fernández",
    ],
  },
  SV: {
    female: [
      "Ana", "María", "Gabriela", "Claudia", "Andrea", "Beatriz",
      "Carmen", "Julia", "Karen", "Mercedes", "Rosa", "Antonia",
      "Guadalupe", "Irma", "Luisa", "Maria", "Michelle", "Patricia",
      "Sara", "Valeria", "Vanessa", "Verónica", "Victoria", "Adriana",
      "Alejandra", "Camila", "Cecilia", "Celina", "Daniela", "Fátima",
      "Gertrudis", "Iris", "Josefa", "Karina", "Lilian", "Nicole",
      "Rebeca", "Roxana", "Silvia", "Adelaida",
    ],
    male: [
      "José", "Carlos", "Francisco", "Juan", "Rafael", "Jorge",
      "Roberto", "Luis", "Miguel", "Antonio", "Ricardo", "Mario",
      "Mauricio", "Manuel", "Salvador", "Ernesto", "Julio", "Óscar",
      "Eduardo", "José María", "William", "Pedro", "Héctor", "Alejandro",
      "Arturo", "Diego", "Guillermo", "Tomás", "Alfredo", "David",
      "Joaquín", "Jose", "Raúl", "Nelson", "René", "Alberto",
      "Andrés", "Edwin", "Fernando", "Jaime",
    ],
    family: [
      "Martínez", "González", "Castro", "García", "Rivas", "Rodríguez",
      "Guirola", "Aguilar", "Molina", "Romero", "Castillo", "Hernández",
      "Cruz", "López", "Ramos", "Torres", "Gómez", "Salazar",
      "Alfaro", "Bukele", "Flores", "Hernandez", "Menéndez", "Miranda",
      "Osorio", "Pineda", "Rodriguez", "Alvarado", "Bonilla", "Cáceres",
      "Escobar", "Garcia", "Guevara", "Huezo", "Kessels", "Lopez",
      "Mejía", "Mena", "Morán", "Orellana", "Pérez", "Tobar",
      "Amaya", "Ayala", "Campos",
    ],
  },
  TT: {
    female: [
      "Ayanna", "Jennifer", "Aaliyah", "Ann", "Danielle", "Marion",
      "Alicia", "Althea", "Angela", "Candice", "Gillian", "Hazel",
      "Lisa", "Maureen", "Patrice", "Patricia", "Paula", "Rhea",
      "Simone", "Abigail", "Adele", "Alexis", "Ayana", "Barbara",
      "Beverly", "Brianna", "Catherine", "Christine", "Cynthia", "Denyse",
      "Donna", "Giselle", "Janelle", "Janice", "Joan", "June",
      "Karen", "Linda", "Louise", "Margaret",
    ],
    male: [
      "Michael", "Shaquille", "John", "Anthony", "George", "David",
      "Robert", "Kenneth", "Christopher", "Clyde", "Ian", "Lennox",
      "Patrick", "Winston", "Justin", "Kevin", "Leslie", "Stephen",
      "Andre", "Andrew", "Kareem", "Marvin", "Raymond", "Roger",
      "Samuel", "Tony", "Aaron", "Adrian", "Alvin", "Ancil",
      "Arnold", "Arthur", "Brandon", "Brian", "Carlton", "Dwayne",
      "Edwin", "Errol", "Gary", "Gerald",
    ],
    family: [
      "Williams", "Alexander", "Charles", "James", "John", "Lewis",
      "Joseph", "King", "Thomas", "Mitchell", "Moore", "Roberts",
      "Brown", "Clarke", "Edwards", "Jones", "Baptiste", "Browne",
      "Holder", "Johnson", "Smith", "Walcott", "Baksh", "Bernard",
      "Jack", "Paul", "Stewart", "Adams", "Andrews", "Armstrong",
      "Beckles", "Campbell", "Carter", "Chen", "Cox", "Cumberbatch",
      "Cummings", "Forbes", "George", "Gordon", "Grant", "Griffith",
      "Henry", "Marshall", "Mills",
    ],
  },
  US: {
    female: [
      "Mary", "Elizabeth", "Margaret", "Susan", "Sarah", "Ann",
      "Barbara", "Helen", "Jane", "Anne", "Jennifer", "Nancy",
      "Anna", "Ruth", "Alice", "Laura", "Lisa", "Linda",
      "Patricia", "Emily", "Louise", "Karen", "Frances", "Dorothy",
      "Amy", "Carol", "Ellen", "Jessica", "Katherine", "Martha",
      "Jean", "Julia", "Catherine", "Rebecca", "Rachel", "Joan",
      "Maria", "Michelle", "Julie", "Grace",
    ],
    male: [
      "John", "William", "James", "Robert", "Charles", "David",
      "George", "Michael", "Thomas", "Joseph", "Richard", "Henry",
      "Edward", "Paul", "Frank", "Mark", "Daniel", "Mike",
      "Peter", "Samuel", "Bill", "Joe", "Jim", "Andrew",
      "Arthur", "Tom", "Jack", "Bob", "Stephen", "Chris",
      "Harry", "Steve", "Scott", "Albert", "Brian", "Francis",
      "Donald", "Anthony", "Frederick", "Eric",
    ],
    family: [
      "Smith", "Johnson", "Brown", "Williams", "Jones", "Davis",
      "Miller", "Anderson", "Wilson", "Taylor", "Moore", "White",
      "Jackson", "Thompson", "Harris", "Allen", "Clark", "Young",
      "Lewis", "Thomas", "Robinson", "Martin", "Adams", "Baker",
      "Scott", "Walker", "Hall", "Wright", "Lee", "King",
      "Green", "Hill", "Mitchell", "Campbell", "Nelson", "Roberts",
      "Evans", "Murphy", "Carter", "Parker", "Bell", "Collins",
      "Phillips", "Wood", "Turner",
    ],
  },
  VC: {
    female: [
      "Andrea", "Angelika", "Annette", "Annis", "Bianca", "Clea",
      "Deborah", "Dilys", "Gertrude", "Inga", "Jacqueline", "Judith",
      "Juliana", "Kristiane", "Lorna", "Marcia", "Monica", "Mya",
      "Natalie", "Natasha", "Peggy", "Phyllis", "Ronnia", "Rosalind",
      "Shantal", "Sophia", "Susan", "Tamara",
    ],
    male: [
      "Brendon", "Cornelius", "David", "Dexter", "Jamal", "James",
      "Joel", "Joseph", "Julian", "Kendall", "Shawn", "Wesley",
      "Winston", "Abraham", "Adonal", "Adrian", "Ajani", "Albert",
      "Alex", "Alston", "Andre", "André", "Andrew", "Andy",
      "Antonio", "Arnhim", "Benford", "Bertram", "Brandon", "Brenton",
      "Burton", "Camillo", "Cammie", "Carlisle", "Carlos", "Caswain",
      "Chad", "Charles", "Clair", "Courtney",
    ],
    family: [
      "Browne", "King", "Samuel", "Williams", "Adams", "John",
      "Joseph", "Richards", "Young", "Alexander", "Baptiste", "Baynes",
      "Bobb", "Creese", "Edwards", "Gonsalves", "Jackson", "James",
      "Lewis", "Matthews", "Miller", "Millington", "Morgan", "Peters",
      "Prince", "Richardson", "Smart", "Stewart", "Weekes", "Allen",
      "Anderson", "Andrews", "Balcombe", "Ballantyne", "Barbour", "Barker",
      "Barnes", "Blake", "Bowman", "Bramble", "Burke", "Cadogan",
      "Caesar", "Campbell", "Carr",
    ],
  },
} as const

export function isNorthAmericaReviewedCountry(code: string): code is keyof typeof northAmericaReviewedNames {
  return Object.hasOwn(northAmericaReviewedNames, code)
}
