// Reviewed country-linked Wikidata candidate components; see docs/geographic-data.md.
export const northAmericaTerritoryNames = {
  AW: {
    female: [
      "Laura", "Alina", "Alysha", "Anouk", "Bernadina", "Carmen",
      "Chloë", "Christina", "Claudette", "Cornelia", "Daniella", "Danielle",
      "Diana", "Emily", "Evelina", "Frances", "Giselle", "Glenda",
      "Hannah", "Jane", "Jennifer", "Juliette", "June", "Karol",
      "Lia", "Liliana", "Lily", "Liza", "Lydia", "Marisol",
      "Maureen", "Monica", "Nathalie", "Nicole", "Nydia", "Olga",
      "Rita", "Stefanie", "Susan", "Thaisa",
    ],
    male: [
      "Juan", "Hendrik", "Jan", "William", "David", "Gregorio",
      "Henny", "Henry", "Javier", "Jeffrey", "Jorge", "Maurice",
      "Miguel", "Rafael", "Rudy", "Shawn", "Adi", "Adriaan",
      "Albert", "Alejandro", "Alfonso", "Alfred", "Alonso", "Andrew",
      "Antoine", "Antwone", "Bart", "Basilio", "Ben", "Bill",
      "Bobby", "Bruce", "Calvin", "Carl", "Chadwick", "Ciro",
      "Curt", "Daniel", "Danny", "Darwin",
    ],
    family: [
      "Croes", "Ecury", "Eman", "Arends", "Tromp", "Henriquez",
      "Irausquin", "Kelly", "King", "Kock", "Oduber", "Rahman",
      "Anderson", "Aparicio", "Baten", "Beaujon", "Benton", "Bergen",
      "Bishop", "Bogaerts", "Bolton", "Bridgewater", "Brunings", "Buckley",
      "Bunyan", "Burgos", "Clark", "Collins", "Comvalius", "Cook",
      "de Jong", "de Palm", "Erasmus", "Escalona", "Farrell", "Farro",
      "Ferguson", "Fortin", "Gibson", "Grant", "Hodgson", "Holleran",
      "Irie", "Janssen", "Jüssi",
    ],
  },
  CW: {
    female: [
      "Lucille", "Maria", "Eline", "Jennifer", "Vanessa", "Adèle",
      "Ailsa", "Aletta", "Ange", "Angela", "Annie", "Barbara",
      "Beatrice", "Bernadette", "Birgit", "Carissa", "Carmita", "Charetti",
      "Chaunice", "Chimène", "Christiana", "Christina", "Claire", "Constance",
      "Cynthia", "Daisy", "Dayanara", "Diana", "Digna", "Dinah",
      "Dorothea", "Dyanne", "Emily", "Enith", "Eugènie", "Eunice",
      "Evalina", "Fina", "Gabriela", "Helen",
    ],
    male: [
      "Herman", "Jan", "José", "Pedro", "David", "Frank",
      "Jaime", "Luis", "Paul", "Wilhelm", "Willem", "Alberto",
      "Andruw", "Angelo", "Anton", "Benjamin", "Boy", "Danny",
      "Edgar", "Edsel", "Etienne", "Eugene", "Frederik", "George",
      "Gerard", "Geronimo", "Gilbert", "Glenn", "Hensley", "Herbert",
      "Ivan", "Johannes", "John", "Jonathan", "Juan", "Kenneth",
      "Kevin", "Manuel", "Philip", "Pierre",
    ],
    family: [
      "Martina", "Römer", "de Lima", "Jansen", "Martha", "Martis",
      "Rafaela", "Schoop", "Simon", "Zimmerman", "Anastatia", "Behr",
      "Bito", "Bonevacia", "Boskaljon", "Cicilia", "Cijntje", "De Sola",
      "de Veer", "Douglas", "Fecunda", "Francisco", "Gregorius", "Henriquez",
      "Hermans", "Hooi", "Jones", "Palm", "Peters", "Profar",
      "Richards", "Smit", "Statius Muller", "Winklaar", "Agard", "Albert",
      "Allen", "Apostel", "Arias", "Axwijk", "Badaracco", "Bade",
      "Belfor", "Benschop", "Berkvens",
    ],
  },
  GL: {
    female: [
      "Martha", "Naja", "Ane", "Anna", "Sara", "Sofie",
      "Agnethe", "Dorthe", "Elisabeth", "Hanne", "Julie", "Lise",
      "Lone", "Mariane", "Niviaq", "Paneeraq", "Pipaluk", "Randi",
      "Sofia", "Aaja", "Adler", "Agathe", "Aka", "Anja",
      "Anne-Lise", "Astri", "Augusta", "Aviaaja", "Bertha", "Caroline",
      "Cecilie", "Doris", "Elisa", "Ella", "Ellen", "Else",
      "Elvira", "Emilie", "Germaine", "Gitte",
    ],
    male: [
      "Peter", "Hans", "Jens", "Frederik", "Karl", "Lars",
      "Jakob", "Johan", "Kristian", "Ole", "Jørgen", "Niels",
      "Christian", "Johannes", "Knud", "Simon", "Abel", "Albrecht",
      "Anders", "Carl", "Jonas", "Otto", "Rasmus", "Henrik",
      "Samuel", "Tobias", "Aage", "Andreas", "Anthon", "David",
      "Elias", "Emil", "Gustav", "Hendrik", "Isak", "Jonathan",
      "Josef", "Kristoffer", "Ludvig", "Mathæus",
    ],
    family: [
      "Olsen", "Lynge", "Rosing", "Nielsen", "Berthelsen", "Hansen",
      "Chemnitz", "Egede", "Høegh", "Jensen", "Kleist", "Fleischer",
      "Møller", "Heilmann", "Motzfeldt", "Frederiksen", "Larsen", "Lund",
      "Abelsen", "Andersen", "Geisler", "Johansen", "Mathæussen", "Pedersen",
      "Steenholdt", "Thomsen", "Broberg", "Danielsen", "Kreutzmann", "Kruse",
      "Mørch", "Poulsen", "Rasmussen", "Sørensen", "Andreassen", "Balle",
      "Brandt", "Brønlund", "Davidsen", "Friis-Salling", "Godtfredsen", "Hammeken",
      "Hardenberg", "Henningsen", "Hertling",
    ],
  },
  GP: {
    female: [
      "Hélène", "Laura", "Michèle", "Aline", "Andrée", "Anita",
      "Charlotte", "Christine", "Deborah", "Dominique", "Élisabeth", "Fabienne",
      "Flora", "George", "Gerty", "Jacqueline", "Johanna", "Josette",
      "Louisa", "Lucie", "Marguerite", "Marie-France", "Marie-Louise", "Marlène",
      "Véronique", "Adrienne", "Albertine", "Alexis", "Ama", "Amandha",
      "Amandine", "Annick", "Aude", "Bénédicte", "Brigitte", "Camille",
      "Carole", "Caroline", "Caryne", "Cécilia",
    ],
    male: [
      "Joseph", "Henri", "Jacques", "Pierre", "Georges", "Philippe",
      "Jean", "Charles", "Daniel", "Eugène", "François", "Guy",
      "Jules", "Louis", "Maurice", "Alexandre", "Émile", "Olivier",
      "Paul", "Roger", "Alain", "Arthur", "Christian", "Claude",
      "David", "Dominique", "Édouard", "Ernest", "Félix", "Gabriel",
      "Ludovic", "Michel", "Thomas", "Yannick", "Alexis", "Armand",
      "Auguste", "Cédric", "Élie", "Gaston",
    ],
    family: [
      "Coco", "Lara", "Léger", "Tirolien", "Fanfant", "Gène",
      "Girard", "Théophile", "Archimede", "Bamy", "Baptiste", "Beaugendre",
      "Belocian", "Benjamin", "Benoît", "Biabiany", "Casimir", "Christophe",
      "Cyprien", "Dahomay", "Dain", "David", "de Perier", "de Salvert",
      "de Sonis", "Delos", "Gargar", "Gendrey", "Gentille", "Geoffroy",
      "Germain", "Hauterville", "Houllier", "Isaac", "Jalton", "Kanor",
      "Lacascade", "Lambourde", "Landre", "Légitimus", "Martial", "Martin",
      "Mathurin", "Michel", "Morandais",
    ],
  },
  MQ: {
    female: [
      "Nathalie", "Christiane", "Jeanne", "Stéphanie", "Suzanne", "Catherine",
      "Clémence", "Gabrielle", "Josette", "Karine", "Ketty", "Laure",
      "Liliane", "Nicole", "Paule", "Sabine", "Valérie", "Agnès",
      "Aimée", "Alexandra", "Alexe", "Alicia", "Amélie", "Anaïs",
      "Angela", "Anne-Emmanuelle", "Aubertine", "Audrey", "Aurelie", "Aurélie",
      "Betty", "Caprice", "Cécile", "Clara", "Clarissa", "Claude",
      "Cora", "Coralie", "Danièle",
    ],
    male: [
      "Jean", "Louis", "Pierre", "François", "Joseph", "André",
      "Victor", "Emmanuel", "Georges", "Charles", "Émile", "Maurice",
      "Patrick", "Thierry", "Auguste", "Henri", "Jacques", "Jules",
      "Marc", "Michel", "Raphaël", "René", "Alfred", "Camille",
      "Ernest", "Guy", "Jean-Claude", "Jean-Michel", "Jean-Philippe", "Raymond",
      "Robert", "Christophe", "Daniel", "David", "Edmond", "Fabrice",
      "Gilles", "Jean-Baptiste", "Mickaël", "Nicolas",
    ],
    family: [
      "Clément", "Sainte-Rose", "Césaire", "de La Pagerie", "Gibson", "Lise",
      "Marbot", "Monnerot", "Petit", "Abaul", "Aliker", "Augustine",
      "Beauharnais", "Biron", "Bocaly", "Charles", "Daquin", "de Grandmaison",
      "Déau", "Désiré", "du Buc", "Duquesnay", "Duval", "Fabre",
      "Gabriel", "Gratiant", "Knight", "Léro", "Lessort", "Louis",
      "Maran", "Martial", "Ménil", "Monthieux", "Nadeau", "Nardal",
      "Octavia", "Palcy", "Parsemain", "Renard", "Roy", "Tardon",
      "William", "Abati", "Acquevillo",
    ],
  },
  PR: {
    female: [
      "Carmen", "María", "Ana", "Maria", "Isabel", "Laura",
      "Mercedes", "Olga", "Margarita", "Miriam", "Vanessa", "Marta",
      "Michelle", "Paola", "Wanda", "Adriana", "Alba", "Alexandra",
      "Antonia", "Beatriz", "Carla", "Edna", "Elena", "Gabriela",
      "Gloria", "Iris", "Ivonne", "Jennifer", "Lourdes", "Mayra",
      "Melissa", "Pilar", "Rosa", "Sylvia", "Valeria", "Yolanda",
      "Ada", "Brenda", "Cristina", "Diana",
    ],
    male: [
      "José", "Luis", "Carlos", "Juan", "Rafael", "Antonio",
      "Francisco", "Pedro", "Ángel", "Miguel", "Ramón", "Jorge",
      "Héctor", "Manuel", "Roberto", "Orlando", "Alberto", "Javier",
      "Enrique", "Fernando", "Julio", "David", "Alex", "Jaime",
      "Angel", "Edwin", "Víctor", "Daniel", "Félix", "Andrés",
      "Jesús", "Jose", "máximo merilio", "Raúl", "Emilio", "Iván",
      "John", "William", "Eddie", "Gabriel",
    ],
    family: [
      "González", "Santiago", "Rodríguez", "Torres", "Cruz", "Pérez",
      "López", "Ramos", "Figueroa", "Díaz", "Martínez", "Hernández",
      "Ortiz", "Soto", "García", "Morales", "Rodriguez", "Arroyo",
      "Jiménez", "Maldonado", "Vázquez", "Colón", "Delgado", "Fernández",
      "Ramírez", "Sánchez", "Santos", "Álvarez", "Meléndez", "Rosario",
      "Serrano", "Miranda", "Nieves", "Quiñones", "Ruiz", "Méndez",
      "Molina", "Reyes", "Vega", "Castro", "Gómez", "Irizarry",
      "Lopez", "Medina", "Muñoz",
    ],
  },
  VI: {
    female: [
      "Anne", "Barbara", "Cora", "Edith", "Margaret", "Tricia",
      "Adrianne", "Albertine", "Alexa", "Alisa", "Aliyah", "Allison",
      "Amalie", "Aniska", "Annie", "Ashton", "Bertha", "Bethany",
      "Denise", "Dora", "Ella", "Erina", "Gertrude", "Gigi",
      "Grace", "Hannah", "Janelle", "Jasmin", "Jasmine", "Jean",
      "Karrine", "Laverne", "Lee", "Lilibet", "Lisa", "Louise",
      "Louize", "Marcella", "Megan", "Mekia",
    ],
    male: [
      "John", "Charles", "Peter", "David", "Henry", "Carl",
      "William", "Aage", "Adam", "Albert", "Alex", "Alexander",
      "Alphonso", "Anton", "Carlton", "Clayton", "Edward", "Emanuel",
      "Erik", "Francis", "George", "Glen", "Gustav", "Jacob",
      "Jens", "Joe", "Mike", "Rashawn", "Roy", "Samuel",
      "Stephen", "Sylvester", "Theodore", "Thomas", "Victor", "Abdul",
      "Abraham", "Ademola", "Adolf", "Adolph",
    ],
    family: [
      "Hodge", "Jackson", "Smith", "Williams", "Blyden", "Evans",
      "James", "Richards", "Adams", "Behn", "Bell", "Benjamin",
      "Blash", "Browne", "Caesar", "Campbell", "Charles", "Christian",
      "Cotton", "Duncan", "Edwin", "Francis", "George", "Hansen",
      "Jones", "Milligan", "Reed", "Sainte-Claire Deville", "Thomas", "Thompson",
      "Todman", "Turnbull", "Abernathy", "Abraham", "Ali", "Andrews",
      "Aska", "Averil", "Badin", "Bang", "Baptiste", "Barnes",
      "Barrows", "Bartsch", "Bentzon",
    ],
  },
} as const

export function isNorthAmericaTerritoryCountry(code: string): code is keyof typeof northAmericaTerritoryNames {
  return Object.hasOwn(northAmericaTerritoryNames, code)
}
