// Reviewed Wikidata name components; see docs/geographic-data.md.
export const oceaniaTerritoryNames = {
  AS: {
    female: [
      "Rose", "Amata", "Ashley", "Diana", "Edwina", "Emily",
      "Jasmine", "Leslie", "Lisa", "Louisa", "Luava'a", "Mary",
      "Naomi", "Patricia", "Roselyn", "Solinuu", "Tilali", "Tina",
    ],
    male: [
      "Daniel", "Al", "Alex", "Junior", "Mike", "Pita",
      "Sam", "Shalom", "Alexander", "Alfred", "Andrew", "Aniekpeno",
      "Anthony", "Anton", "Ata", "Austin", "Ben", "Bob",
      "Charlie", "Chris", "Darrell", "Dave", "David", "Demetrius",
      "Don", "Ed", "Edgar", "Edward", "Eni", "Fofō",
      "Frank", "Gabe", "Gabriel", "Gary", "George", "Henry",
      "Isaac", "Ismael", "Jack", "Jerome", "Joe", "Joey",
      "John", "Jonathan", "Jordan", "Kennedy", "Leonard", "Lisi",
      "Lolo", "Mao",
    ],
    family: [
      "Anoa'i", "Gabbard", "Heleta", "Kaleopa", "Lui", "Noga",
      "Sewell", "Sinapati", "Sunia", "Thompson", "Victor", "Achica",
      "Afu", "Alatasi", "Anderson", "Beauchamp", "Bell", "Collins",
      "Ekuale", "Enesi", "Faaloua", "Falaniko", "Faleao", "Faleomavaega",
      "Fanene", "Faoa-Danielson", "Fatu", "Faumuina", "Feagiai", "Fonoti",
      "Hall", "Halliday", "Hannemann", "Harrington", "Ioane", "Iosefa",
      "Iupati", "Leota", "Liamatua", "Liu", "Luani", "Luvu",
      "Maiava", "Maivia", "Malepeai", "Malu", "Mariko", "Mauga",
      "Mavaega", "Misipeka", "Mitchell", "Mo", "Moe", "Mulipola",
      "Nua", "Onesemo", "Ott", "Palelei", "Palepoi", "Pati",
    ],
  },
  GU: {
    female: [
      "Lourdes", "Joanne", "Regine", "Alicia", "Aline", "Allyson",
      "Alyssa", "Ann", "Antoinette", "Carmen", "Christina", "Cora",
      "Cynthia", "Elizabeth", "Eloise", "Emma", "Esther", "Hayley",
      "Judith", "Kimberley", "Lee", "Lenore", "Lou", "Margaret",
      "Maria", "Mia", "Moira", "Pia", "Pilar", "Rosa",
      "Sara", "Shayna", "Sian", "Susan", "Tessa",
    ],
    male: [
      "Edward", "Michael", "Benjamin", "Frank", "John", "Anthony",
      "Brian", "Daniel", "Derek", "Eddie", "James", "Joe",
      "Jon", "Joseph", "Kyle", "Manuel", "Paul", "Ricardo",
      "Richard", "Scott", "Tommy", "Tony", "Alfred", "Allan",
      "Angel", "Antonio", "Benjamin Joseph", "Bill", "Bleu", "Borja",
      "Bruce", "Carl", "Carlos", "Charles", "Christopher", "Craig",
      "Cruz", "Curtis", "Danny", "Dominic", "Donald", "Donovan",
      "Douglas", "Drake", "Dylan", "Earnest", "Elias", "Felix",
      "Felixberto", "Fernando",
    ],
    family: [
      "Camacho", "Perez", "Calvo", "Flores", "Santos", "Cruz",
      "Aguero", "Alves", "Anderson", "Andrew", "Baker", "Barrett",
      "Baza", "Bean", "Blas", "Bordallo", "Brocka", "Carney",
      "Chargualaf", "Chiu", "Conrey", "Cook", "Cowley", "Cunliffe",
      "Curry", "Duarte", "Duenas", "Dunn", "Evans", "Fegurgur",
      "Francisco", "Franquez", "Gadia", "Garcia", "Guerrero", "Gumataotao",
      "Hocog", "Horton", "Howard", "Huerto", "Husslein", "Ilustre",
      "Inman", "Johnson", "Kia'aina", "Kileen", "Lane", "Leon",
      "Limtiaco", "López", "Lujan", "Manglona", "Mariano", "Martinez",
      "McDonald", "Mendiola", "Merfalen", "Modzelewski", "Morrison", "Moylan",
    ],
  },
  NC: {
    female: [
      "Françoise", "Isabelle", "Nathalie", "Sonia", "Suzanne", "Valentine",
      "Angélique", "Annabel", "Ashley", "Bianca", "Caroline", "Catherine",
      "Céline", "Christelle", "Clotilde", "Corine", "Cynthia", "Diane",
      "Élodie", "Évelyne", "Flavy", "Ghislaine", "Hélène", "Jeanne",
      "Jenna", "Johanna", "Lara", "Laure", "Léontine", "Lucienne",
      "Madeleine", "Magali", "Manon", "Marguerite", "Mariane", "Marianne",
      "Marie-France", "Marie-Pierre", "Marie-Thérèse", "Marilyse", "Nadia", "Nina",
      "Raymonde", "Rose", "Simone", "Stella", "Susanna", "Sylvie",
      "Titaua", "Valérie",
    ],
    male: [
      "Georges", "Pierre", "Jacques", "Robert", "Louis", "André",
      "Charles", "Frédéric", "Henri", "Jean", "Michel", "Philippe",
      "Christian", "Nicolas", "Patrick", "Didier", "Emile", "Jean-Louis",
      "Jean-Pierre", "Laurent", "Léon", "Marc", "Paul", "Roger",
      "Thierry", "Thomas", "Yves", "Alain", "Antoine", "Arnaud",
      "Bernard", "Bertrand", "Cédric", "Christopher", "Dick", "Dimitri",
      "Edmond", "Édouard", "Emmanuel", "Éric", "François", "Gilbert",
      "Jean-Charles", "Jean-Claude", "Joris", "Joseph", "Julien", "Marcel",
      "Marius", "Maurice",
    ],
    family: [
      "Lafleur", "Mapou", "Taofifénua", "Wakanumuné", "Caillard", "Gorendiawé",
      "Hmaé", "Hnepeune", "Ixoée", "Kayara", "Leenhardt", "Machoro",
      "Michelino", "Tjibaou", "Wajoka", "Aïfa", "Andriambololona", "Apikaoua",
      "Arlie", "Babin", "Bako", "Barbançon", "Battistella", "Beer",
      "Bénébig", "Berger", "Bladinières", "Blaise", "Bologna", "Bourgade",
      "Boutin", "Brial", "Briault", "Brignone", "Brinon", "Brizard",
      "Bui Duyet", "Calleja", "Cané", "Carco", "Case", "Cassier",
      "Céléné", "Cévaër", "Cherrier", "Cibone", "Clarque", "Colardeau",
      "Corbin", "Corigliano", "Cortot", "d'Anglebermes", "Dahite", "David",
      "Devaux", "Devillers", "Djaïwé", "Djamali", "Djiet", "Dokunengo",
    ],
  },
  PF: {
    female: [
      "Anne", "Louise", "Aelan", "Aline", "Amanda", "Anaise",
      "Anne-Caroline", "Armelle", "Célestine", "Chantal", "Cheyenne", "Denise",
      "Diane", "Edna", "Elisabeth", "Ella", "Esther", "Flora",
      "Ida", "Jocelyne", "Karina", "Lana", "Linda", "Lucy",
      "Lytta", "Madeleine", "Maima", "Maina", "Mareva", "Maréva",
      "Mary", "Miriama", "Nathalie", "Nicole", "Noémie", "Pascale",
      "Rita", "Rosa", "Sandra", "Sylvie",
    ],
    male: [
      "Jean", "Michel", "Georges", "John", "Eddy", "Émile",
      "Lucien", "Pascal", "Patrick", "Paul", "Samuel", "Teva",
      "William", "Angelo", "Axel", "Benjamin", "Billy", "Charles",
      "Daniel", "Gabriel", "Gaston", "George", "Gérald", "Henri",
      "Hubert", "Jacques", "Jonathan", "Joseph", "Marcel", "Moana",
      "Pierre", "Stéphane", "Steve", "Vincent", "Xavier", "Alain",
      "Albéric", "Albert", "Alex", "Alexandre", "Alfred", "Aliocha",
      "Allen", "Alvin", "Andy", "Anthony", "Antony", "Barthélémy",
      "Bimbo", "Boris",
    ],
    family: [
      "Coppenrath", "Tehau", "Bennett", "Salmon", "Bambridge", "Drollet",
      "Grand", "Kautai", "Kimitete", "Paama", "Riveta", "Rousseau",
      "Samin", "Vaast", "Vernaudon", "Williams", "Adams", "Ahnne",
      "Allard", "Amau", "Appriou", "Archer", "Aroita", "Atani",
      "Bandera", "Barioz", "Basset", "Bessette", "Besson", "Bonno",
      "Bono", "Bouissou", "Bourebare", "Bourgoin", "Brando", "Bremond",
      "Brémond", "Brotherson", "Buillard", "Carcasses", "Carlson", "Caroine",
      "Céran-Jérusalémy", "Chailloux", "Chang", "Chaves", "Chevalier", "Chong",
      "Christian", "Corday", "Cousin", "d'Estienne", "d'Orves", "Dauphin",
      "Davani", "Debaere", "Degage", "Delfour", "Devatine", "Doom",
    ],
  },
} as const

export function isOceaniaTerritoryCountry(code: string): code is keyof typeof oceaniaTerritoryNames {
  return Object.hasOwn(oceaniaTerritoryNames, code)
}
