// Reviewed Wikidata name components; see docs/geographic-data.md.
export const oceaniaReviewedNames = {
  AU: {
    female: [
      "Mary", "Margaret", "Elizabeth", "Anne", "Sarah", "Helen",
      "Jane", "Kate", "Susan", "Ann", "Emma", "Louise",
      "Catherine", "Emily", "Jessica", "Lisa", "Anna", "Barbara",
      "Patricia", "Rebecca", "Michelle", "Jennifer", "Alice", "Sally",
      "Karen", "Jean", "Christine", "Wendy", "Amanda", "Joan",
      "Amy", "Ruth", "Rachel", "Nicole", "Alison", "Caroline",
      "Dorothy", "Julie", "Robyn", "Jenny", "Frances", "Melissa",
      "Sue", "Natalie", "Janet", "Lucy", "Stephanie", "Laura",
      "Grace", "Kathleen", "Fiona", "Judith", "Sophie", "Linda",
      "Angela", "Claire", "Julia", "May", "Samantha", "Deborah",
    ],
    male: [
      "John", "William", "James", "David", "Peter", "Robert",
      "George", "Michael", "Charles", "Thomas", "Andrew", "Paul",
      "Richard", "Jack", "Henry", "Mark", "Arthur", "Edward",
      "Frank", "Ian", "Bill", "Joseph", "Alan", "Tom",
      "Chris", "Matthew", "Alexander", "Daniel", "Harry", "Anthony",
      "Francis", "Stephen", "Ben", "Frederick", "Brian", "Tony",
      "Jim", "Bruce", "Bob", "Alfred", "Albert", "Steve",
      "Keith", "Scott", "Tim", "Kevin", "Adam", "Patrick",
      "Gordon", "Luke", "Matt", "Donald", "Harold", "Colin",
      "Ernest", "Eric", "Christopher", "Greg", "Craig", "Ken",
    ],
    family: [
      "Smith", "Brown", "Jones", "Williams", "Wilson", "Anderson",
      "Taylor", "Martin", "White", "Johnson", "Young", "Campbell",
      "Walker", "Scott", "Thomas", "Green", "Hill", "Kelly",
      "Thompson", "Evans", "Moore", "Hall", "Miller", "Ryan",
      "Watson", "Wright", "Roberts", "Robinson", "Clarke", "Edwards",
      "King", "Harris", "McDonald", "Davies", "Lewis", "Stewart",
      "Mitchell", "Bennett", "Murphy", "Jackson", "Hughes", "Clark",
      "Wood", "Davis", "James", "Cooper", "Allen", "Robertson",
      "Murray", "Adams", "Bell", "Baker", "Kennedy", "Turner",
      "Cox", "Morgan", "Cook", "O'Brien", "Richardson", "Phillips",
    ],
  },
  CK: {
    female: [
      "Elizabeth", "Agnes", "Audrey", "Caren", "Ella", "Erin",
      "Irene", "Jacqueline", "Kate", "Maeva", "Maki", "Marina",
      "Marjorie", "Niki", "Pamela", "Piri", "Ramona", "Rose",
      "Selina", "Tasha",
    ],
    male: [
      "Mark", "Teina", "Tony", "Bernard", "Bryden", "Campbell",
      "Chris", "Daniel", "Henry", "Jake", "James", "Jim",
      "John", "Joseph", "Malcolm", "Michael", "Patrick", "Paul",
      "Richard", "Sam",
    ],
    family: [
      "Brown", "Harmon", "Nicholas", "Wichman", "Williams", "Armstrong",
      "Ash", "Beer", "Best", "Browne", "Carr", "Dean",
      "Evans", "Hetherington", "Ingram", "Marsters", "Maru", "Pera",
      "Pereira", "Pittman", "Rangi", "Rattle", "Richardson", "Rongo",
      "Shepherd",
    ],
  },
  FJ: {
    female: [
      "Ana", "Adi", "Agnes", "Ateca", "Danielle", "Lia",
      "Luisa", "Miriama", "Nalini", "Rachel", "Salote", "Sera",
      "Adele", "Aliana", "Alissa", "Aliza", "Amelia", "Andra",
      "Angela", "Annette", "Apolonia", "Asena", "Bernadette", "Caroline",
      "Charlene", "Cheyenne", "Dale", "Delores", "Doreen", "Dorrie",
      "Elena", "Elina", "Ella", "Erika", "Estelle", "Faith",
      "Felicitas", "Finau", "Gabriella", "Georgia", "Geraldine", "Helen",
      "Hilda", "Irene", "Jiko", "Joana", "Joyce", "Karyn",
      "Kasanita", "Kayla",
    ],
    male: [
      "Jone", "Tevita", "James", "Kitione", "Semi", "Timoci",
      "William", "David", "Epeli", "George", "Henry", "John",
      "Josaia", "Josefa", "Josua", "Peter", "Apisai", "Daniel",
      "Inoke", "Joshua", "Leone", "Malakai", "Marika", "Ratu",
      "Samuela", "Sireli", "Thomas", "Vijay", "Albert", "Alipate",
      "Emosi", "Isireli", "Jerry", "Joe", "Joseph", "Mahendra",
      "Ozeasz", "Paul", "Penaia", "Peni", "Pio", "Roy",
      "Samu", "Taniela", "Tomasi", "Aisea", "Alvin", "Anand",
      "Anthony", "Antonio",
    ],
    family: [
      "Koroi", "Singh", "Cakobau", "Fong", "Kumar", "Soqeta",
      "Tuwai", "Vugakoto", "Waqabaca", "Bole", "Dyer", "Ganilau",
      "Hughes", "Kamikamica", "Laqeretabua", "Masi", "Nalaga", "Ratu",
      "Tuqiri", "Vesikula", "Whiteside", "Ali", "Anthony", "Armstrong",
      "Baleinadogo", "Bukalidi", "Chand", "Costello", "Dean", "Delai",
      "Domolailai", "Finau", "Fox", "Hussein", "Kautoga", "Kenny",
      "Khan", "Lal", "Leweniqila", "Lomani", "Lotawa", "Molia",
      "Momoedonu", "Nainima", "Nakarawa", "Namoce", "Nasiga", "Nawai",
      "Ó hAilpín", "Patel", "Qoro", "Ratuvou", "Rova", "Ruivadra",
      "Salawa", "Shaw", "Smith", "Tamani", "Tamanisau", "Tani",
    ],
  },
  FM: {
    female: [
      "Elina", "Adelyn", "Ann", "Anna", "Carmen", "Christina",
      "Debra", "Emma", "Iris", "Jane", "Jennifer", "Margie",
      "Maria", "Maurina", "Regina", "Rose", "Teressa", "Tracy",
    ],
    male: [
      "John", "Jack", "Robert", "Amando", "Anderson", "Andon",
      "Aren", "Bailey", "Claude", "Daniel", "Dave", "David",
      "Dean", "Dionisio", "Elias", "Emanuel", "Erhart", "Esmond",
      "Fabian", "Gerson", "Gideon", "Hiroshi", "Isaac", "Jacob",
      "James", "Jessie", "Jimmy", "Joseph", "Josh", "Joshua",
      "Kody", "Lawrence", "Leo", "Lyndon", "Manuel", "Marcel",
      "Marcelo", "Masao", "Mike", "Moses",
    ],
    family: [
      "Howard", "Jackson", "Nakayama", "Palik", "Samuel", "Weilbacher",
      "Adams", "Amor", "Andrew", "Benjamin", "Christian", "Clarence",
      "Doone", "Erra", "Erwin", "Fritz", "George", "Graham",
      "Henry", "Ismael", "Jonas", "Joseph", "Ladore", "Lawrence",
      "Martin", "Minginfel", "Moses", "Narruhn", "Nelson", "Nena",
    ],
  },
  NR: {
    female: [
      "Angelita", "Charmaine", "Chitra", "Christine", "Greta", "Isabella",
      "Joanne", "Lois", "Margaret", "Marlene", "Maximina", "Michaela",
      "Millicent", "Nancy", "Olympia", "Reanna", "Ruby", "Sheba",
      "Sheeva", "Suzanne",
    ],
    male: [
      "Joseph", "David", "Ludwig", "Timothy", "Aaron", "Alfred",
      "Alopua", "Asterio", "Ategan", "Baron", "Bernard", "Cherico",
      "Clinton", "Dadvan", "Dantes", "Derog", "Detonga", "Dominic",
      "Edwin", "Elson", "Ezekiel", "Fabian", "Frederick", "Fredrick",
      "Gerard", "Godfrey", "Hammer", "Itte", "Jay", "Jeremiah",
      "Jesse", "Jonah", "Kennan", "Kenos", "Kieren", "Kinza",
      "Lad", "Lagumot", "Landon", "Leo", "Lionel", "Lowe",
      "Marcus", "Martin", "Mathew",
    ],
    family: [
      "Harris", "Detenamo", "Detudamo", "Kun", "Thoma", "Deireragea",
      "Dowiyogo", "Jeremiah", "Adeang", "Akua", "Aroi", "Baguga",
      "Batsiua", "Clodumar", "Hiram", "Keke", "Moses", "Scotty",
      "Solomon", "Stephen", "Tsitsi", "Appi", "Benjamin", "Bernicke",
      "Bingham", "Bop", "Brechtefeld", "Cain", "Cook", "Dabwido",
      "Deiye", "DeRoburt", "Dick", "Dowabobo", "Fritz", "Gadabu",
      "Gadoengin", "Garabwan", "Genzel", "Gioura", "Gobure", "Hartman",
      "Hartmann", "Hendrie", "Jackman", "Jones", "Kam", "Mau",
      "Oppenheimer", "Peo",
    ],
  },
  NZ: {
    female: [
      "Mary", "Margaret", "Elizabeth", "Anne", "Jane", "Helen",
      "Ann", "Sarah", "Frances", "Catherine", "Louise", "Jean",
      "Susan", "Joan", "Anna", "Patricia", "Ruth", "Emma",
      "Kate", "Rachel", "Rebecca", "Alison", "Barbara", "Judith",
      "Janet", "Christine", "Dorothy", "Alice", "Jennifer", "Karen",
      "Emily", "Maria", "Michelle", "Joy", "Rose", "Lisa",
      "Heather", "Nicola", "Edith", "Fiona", "May", "Claire",
      "Grace", "Amy", "Angela", "Kathleen", "Linda", "Sue",
      "Ellen", "Julia", "Annie", "Jenny", "Joyce", "Lucy",
      "Victoria", "Caroline", "Hannah", "Laura", "Rosemary", "Charlotte",
    ],
    male: [
      "John", "William", "James", "David", "George", "Robert",
      "Peter", "Charles", "Thomas", "Michael", "Richard", "Henry",
      "Edward", "Arthur", "Paul", "Andrew", "Ian", "Mark",
      "Alexander", "Joseph", "Frederick", "Alan", "Bruce", "Francis",
      "Brian", "Frank", "Anthony", "Alfred", "Jack", "Donald",
      "Gordon", "Graham", "Patrick", "Bill", "Chris", "Daniel",
      "Matthew", "Stephen", "Douglas", "Christopher", "Ross", "Simon",
      "Keith", "Murray", "Albert", "Kevin", "Ernest", "Colin",
      "Philip", "Kenneth", "Harry", "Hugh", "Mike", "Tom",
      "Ronald", "Craig", "Martin", "Tony", "Ben", "Neil",
    ],
    family: [
      "Smith", "Wilson", "Williams", "Brown", "Taylor", "Jones",
      "Anderson", "Scott", "Campbell", "Clark", "White", "Wright",
      "Walker", "Harris", "Robinson", "Stewart", "Thompson", "King",
      "Young", "Bell", "Robertson", "Baker", "Watson", "Hall",
      "Johnson", "Marshall", "Martin", "Turner", "Hill", "Jackson",
      "Thomas", "Bennett", "Cooper", "Miller", "Mitchell", "Moore",
      "Wood", "Reid", "Cameron", "McKenzie", "Edwards", "Ross",
      "Allen", "Roberts", "Clarke", "Davis", "Murray", "Thomson",
      "Kelly", "Carter", "Hunter", "Mason", "Ward", "Collins",
      "Graham", "Adams", "Evans", "Morgan", "Parker", "Simpson",
    ],
  },
  PG: {
    female: [
      "Betty", "Alice", "Elizabeth", "Margaret", "Samantha", "Grace",
      "Helen", "Julie", "Lucy", "Lynette", "Rita", "Rose",
      "Violet", "Barbara", "Florence", "Jane", "Josephine", "Judith",
      "Linda", "Mary", "Miriam", "Monica", "Olivia", "Philomena",
      "Sarah", "Veronica", "Abigail", "Adrine", "Amanda", "Amelia",
      "Ana", "Ann", "Anne", "Annie", "Belinda", "Bellinda",
      "Bertha", "Beverly", "Bianca", "Blanche", "Bosa", "Brenda",
      "Carol", "Carolyn", "Catherine", "Cecilia", "Cecille", "Cynthia",
      "Deborah", "Diane",
    ],
    male: [
      "John", "Peter", "Michael", "Francis", "William", "David",
      "Joseph", "Robert", "Steven", "Allan", "George", "James",
      "Andrew", "Joe", "Justin", "Richard", "Samuel", "Thomas",
      "Alex", "Bernard", "Chris", "Daniel", "Henry", "Jimmy",
      "Patrick", "Paul", "Simon", "Albert", "Anton", "Bob",
      "Charles", "Charlie", "Jack", "Jason", "Johnson", "Kevin",
      "Luke", "Philip", "Raymond", "Ryan", "Timothy", "Vincent",
      "Willie", "Adrian", "Arnold", "Ben", "Benjamin", "Edwin",
      "Ephraim", "Ezekiel",
    ],
    family: [
      "Somare", "Morris", "Muri", "Albert", "Bray", "John",
      "Joseph", "Simon", "Abal", "Abel", "Aia", "Amos",
      "Anisi", "Bina", "Davani", "Genia", "Getsi", "Kala",
      "Kama", "Kila", "Lepani", "Opa", "Pora", "Simogun",
      "Wright", "Zurenuoc", "Ain", "Akon", "Alois", "Ame",
      "Amet", "Andreas", "Angula", "Aua", "Bai", "Baki",
      "Bal", "Bandi", "Bani", "Barter", "Basa", "Basil",
      "Bendo", "Benjamin", "Bird", "Boas", "Bogari", "Boie",
      "Boito", "Bona", "Bradley", "Brokam", "Browne", "Cappo",
      "Chen", "Coates", "Conrad", "Cooper", "Costigan", "Crawley",
    ],
  },
  PW: {
    female: [
      "Valerie", "Akiko", "Amber", "Athena", "Debbie", "Ernestine",
      "Evelyn", "Faustina", "Gabriela", "Gloria", "Grace", "Ilana",
      "Jenna", "Jennifer", "Keesha", "Kierra", "Kristen", "Leilani",
      "Maria", "Marina", "Ngerak", "Nicole", "Peoria", "Romana",
      "Ruby", "Sandra", "Sydney", "Vicky", "Victoria", "Yuri",
    ],
    male: [
      "John", "Francis", "Ignacio", "Peter", "Surangel", "Thomas",
      "Adalbert", "Adams", "Adrian", "Alan", "Alexander", "Alfonso",
      "Anlloyd", "Arthur", "Bright", "Caleb", "Charles", "Christian",
      "Christopher", "David", "Denzel", "Elgin", "Elias", "Emais",
      "Eyos", "Florian", "Franco", "Gibson", "Gregorio", "Harry",
      "Haruo", "Hersey", "Hokkons", "Isidoro", "Jackson", "James",
      "Jared", "Jerry", "Jesse", "Johnny", "Johnson", "Joshua",
      "Kangichi", "Kerai", "Kuniwo", "Lazarus", "Lebuu", "Mengirarou",
      "Mlib", "Ngiratkel",
    ],
    family: [
      "Gibbons", "Reklai", "Anastacio", "Remengesau", "Sugiyama", "Whipps",
      "Gabriel", "Hosei", "Keane", "Koshiba", "Oiterong", "Otto",
      "Rudimch", "Salii", "Seid", "Tmetuchl", "Toribiong", "Adachi",
      "Adolf", "Alexander", "Anson", "Asanuma", "Baules", "Beck",
      "Chilton", "Chin", "Chinn", "Demk", "Dengokl", "Eledui",
      "Elwais", "Emery", "Etpison", "Florencio", "Francisco", "Fritz",
      "Hayes", "Hilbert", "Kanai", "Littler", "Marino", "Mariur",
      "Marugg", "Merep", "Misech", "Nakamura", "Ngiraingas", "Ngirakelsong",
      "Orrukem", "Patris",
    ],
  },
  SB: {
    female: [
      "Catherine", "Rose", "Cynthia", "Doreen", "Elizabeth", "Emma",
      "Ethel", "Lilly", "Margaret", "Mary", "Pauline", "Victoria",
      "Alice", "Cathy", "Christina", "Daphne", "Dorothy", "Edith",
      "Everlyn", "Freda", "Gwendolyn", "Hellen", "Hilda", "Irene",
      "Jenny", "Joan", "Jovita", "Joy", "Julian", "Lilian",
      "Liza", "Matilda", "Monique", "Norah", "Phoebe",
    ],
    male: [
      "David", "George", "Peter", "Jacob", "James", "Francis",
      "Fred", "Jack", "John", "Joseph", "Matthew", "Alex",
      "Allan", "Andrew", "Augustine", "Benjamin", "Clement", "Daniel",
      "Joe", "Leslie", "Manasseh", "Nelson", "Paul", "Philip",
      "Samson", "Selwyn", "Steve", "Tony", "Abraham", "Adrian",
      "Alden", "Alfred", "Ali", "Alick", "Aloysio", "Alvin",
      "Barrett", "Bartholomew", "Basil", "Bernard", "Bodo", "Celestine",
      "Charles", "Charlie", "Chris", "Christopher", "Danny", "Derek",
      "Derrick", "Desmond",
    ],
    family: [
      "Hale", "Kaua", "Meke", "Soaki", "Wickham", "Aba",
      "Abba", "Baegeni", "Boardman", "Brown", "Cheka", "Daka",
      "Egeta", "George", "Grantham", "Higa", "Hoka", "Hou",
      "Iro", "Kabui", "Kalia", "Kapu", "Kini", "Kofana",
      "Kofela", "Koti", "Kruger", "Laeta", "Le'ai", "Lepping",
      "Magi", "Mango", "Mara", "Matiota", "Mekawir", "Molea",
      "Naka", "Oliver", "Ora", "Orobulu", "Pacha", "Pegi",
      "Pemberton", "Philip", "Plant", "Pollard", "Sade", "Salato",
      "Suri", "Taro",
    ],
  },
  TL: {
    female: [
      "Maria", "Ana", "Isabel", "Domingas", "Filomena", "Guilhermina",
      "Odete", "Regina", "Angela", "Ângela", "Cristina", "Josefa",
      "Laura", "Lúcia", "Madalena", "Maria do Céu", "Norberta", "Rosa",
      "Teresa", "Adalgisa", "Adelaide", "Águeda", "Aicha", "Albina",
      "Ana Isabel", "Angélica", "Angelina", "Angelita", "Anita", "Armanda",
      "Armandina", "Aurora", "Bella", "Bernardina", "Berta", "Brigida",
      "Brígida", "Carmelita", "Chloé", "Cipriana", "Dolores", "Élia",
      "Elisa", "Elisabeth", "Emilia", "Esmeralda", "Fatima", "Felícia",
      "Fernanda", "Florentina",
    ],
    male: [
      "José", "Francisco", "António", "João", "Manuel", "Luís",
      "Carlos", "Abel", "Fernando", "Paulo", "Joaquim", "Jorge",
      "Domingos", "Jacinto", "Mário", "Pedro", "Vicente", "César",
      "Miguel", "Abílio", "Afonso", "Alberto", "Augusto", "Eduardo",
      "Faustino", "Jaime", "Júlio", "Mateus", "Ricardo", "Adriano",
      "Alexandre", "Alfredo", "Armindo", "Bernardo", "Duarte", "Estanislau",
      "Gabriel", "Guido", "Jacob", "Leandro", "Marcos", "Mariano",
      "Salvador", "Tomás", "Alarico", "Albino", "Alexandrino", "Antonio",
      "Cipriano", "Cirilo",
    ],
    family: [
      "Alves", "Martins", "Soares", "Guterres", "Pereira", "Araújo",
      "Fernandes", "Freitas", "Belo", "Santos", "da Costa", "Ximenes",
      "Amaral", "Nunes", "Pires", "Ribeiro", "Costa", "da Silva",
      "Gomes", "Gusmão", "Monteiro", "Sarmento", "Silva", "Borges",
      "Branco", "Carvalho", "Conceição", "Cruz", "de Araújo", "Lemos",
      "Maia", "Neves", "Oliveira", "Pinto", "Tilman", "Barreto",
      "Cardoso", "Carmo", "Carrascalão", "Dias", "Ferreira", "Gama",
      "Lobato", "Lopes", "Madeira", "Mota", "Quintão", "Ramos",
      "Reis", "Rodrigues", "Saldanha", "Trindade", "Varela", "Verdial",
      "Abel", "Abrantes", "Aleixo", "Almeida", "Armindo", "Assis",
    ],
  },
  VU: {
    female: [
      "Agnes", "Andrea", "Chloe", "Elise", "Elizabeth", "Florence",
      "Gloria", "Grace", "Heather", "Henriette", "Hilda", "Isabelle",
      "Janice", "Maria", "Mary", "Merilyn", "Nadia", "Olivette",
      "Priscila", "Selina",
    ],
    male: [
      "John", "Andrew", "Jean", "George", "James", "Joe",
      "Robert", "Simon", "Willie", "Alfred", "Alphonse", "Arnold",
      "Daniel", "François", "Jacques", "Jimmy", "Joseph", "Michel",
      "Paul", "Rodney", "Roger", "Samson", "Timothy", "Tom",
      "Tony", "Abraham", "Alexander", "Alexis", "Ali", "Alick",
      "Ancel", "Antoine", "Anton", "August", "Azariah", "Baldwin",
      "Baptiste", "Barak", "Bill", "Bob", "Brian", "Bruce",
      "Bruno", "Callum", "Charlot", "Christophe", "Claude", "David",
      "Derek", "Dick",
    ],
    family: [
      "Coulon", "Fred", "Kalsrap", "Kaltack", "Lini", "Moses",
      "Regenvanu", "Soromon", "Abil", "Alick", "Aru", "Bani",
      "Bayer", "Bice", "Blake", "Bong", "Bonke", "Boulet",
      "Brown", "Carcasses", "Chabod", "Chen", "Chichirua", "Cooper",
      "Crowby", "David", "Fowler", "Frater", "Garae", "George",
      "Hilton", "Iamak", "Iawak", "Iwai", "Jeffrey", "Joe",
      "Kalo", "Kaloros", "Kalotang", "Kaltak", "Kaltonga", "Kilman",
      "King", "Leingkone", "Ligo", "Lonsdale", "Loughman", "Lynch",
      "Maleb", "Malsarani",
    ],
  },
  WS: {
    female: [
      "Harmony", "Maria", "Mary", "Sienna", "Tyla", "Aemalemaloitia",
      "Ana Maria", "Anne", "Bianca", "Brianna", "Caprice", "Carolyn",
      "Charlize", "Cherish", "Elisapeta", "Emma", "Frankie", "Giselle",
      "Hana", "Helen", "Heseti", "Hildegard", "Jadyn", "Jalyn",
      "Jana", "Jordan", "Kaiya", "Kalani", "Lailani", "Lani",
      "Leilani", "Lina", "Maggie", "Malia", "Mara", "Margaret",
      "Marley", "Maureen", "Mavis", "Monica", "Monique", "Naomi",
      "Nellie", "Olive", "Olivia", "Paea", "Pearl", "Phyllis",
      "Regina", "Riley",
    ],
    male: [
      "Henry", "Mike", "Paul", "Richard", "Albert", "Andrew",
      "Chris", "David", "George", "John", "Micah", "Michael",
      "Oliva", "Peter", "Ryan", "Arthur", "Brandon", "Brian",
      "Duncan", "Elijah", "Faafetai", "Frank", "Jeremy", "Jerry",
      "Joseph", "Justin", "Manu", "Max", "Patrick", "Sanele",
      "Viliamu", "William", "Aaron", "Ace", "Akelei", "Alaifatu",
      "Aleni", "Alesana", "Alexander", "Ali", "Ata", "Bailey",
      "Bob", "Brett", "Bright", "Carl", "Carlos", "Christian",
      "Clarke", "Damien",
    ],
    family: [
      "Tuilagi", "Brown", "Manumaleuga", "Keil", "Tuimavave", "Ah",
      "Aiono", "Joseph", "Seumanutafa", "Smith", "Tumua", "Bell",
      "Cahill", "Craig", "Crichton", "Fatialofa", "Gordon", "Gray",
      "Harder", "Hettig", "Hoeflich", "Kaleopa", "Ki", "Lima",
      "Malosi", "Matthes", "Nelson", "Sa", "Sapolu", "Scanlan",
      "Schuster", "Setefano", "Stowers", "Su'a", "Taufua", "Taulealo",
      "Toeava", "Tuitama", "Tyrell", "Young", "Adams", "Afa",
      "Afualo", "Afuie", "Aia", "Aitupe", "Akazawa", "Ameperosa",
      "Amosa", "Andrews", "Asiata", "Ataga", "Bartley", "Brunt",
      "Bruun", "Bureta", "Cairns", "Clarke", "Collins", "Cooper",
    ],
  },
} as const

export function isOceaniaReviewedCountry(code: string): code is keyof typeof oceaniaReviewedNames {
  return Object.hasOwn(oceaniaReviewedNames, code)
}
