export const geographicSources = {
  'iso-3166': {
    title: 'iso-3166 4.4.0',
    url: 'https://github.com/wooorm/iso-3166',
    license: 'MIT',
    edition: '2026-09-24',
  },
  'libphonenumber-js': {
    title: 'libphonenumber-js 1.13.14',
    url: 'https://github.com/catamphetamine/libphonenumber-js',
    license: 'MIT',
    edition: '2026-09-24',
  },
  geonames: {
    title: 'GeoNames cities1000.zip',
    url: 'https://download.geonames.org/export/dump/cities1000.zip',
    license: 'CC BY 4.0',
    edition: '2026-09-24',
    sha256: '56fb681d6daf41f0fad2e8ee3431082399f3b321daea102fcf25c02bfa8bb370',
  },
  'geonames-admin1': {
    title: 'GeoNames admin1CodesASCII.txt',
    url: 'https://download.geonames.org/export/dump/admin1CodesASCII.txt',
    license: 'CC BY 4.0',
    edition: '2026-09-24',
    sha256: '1da92a6323a5fec3176f3f743bf4cf4040fd56a876da55e46fbca23c863aa60a',
  },
  'geonames-country-info': {
    title: 'GeoNames countryInfo.txt language tags',
    url: 'https://download.geonames.org/export/dump/countryInfo.txt',
    license: 'CC BY 4.0',
    edition: '2026-09-24',
    sha256: '93bafc525813f22e4711ff9ed6d626343094ce48c26388dc7c49189b3d7d5512',
  },
  faker: {
    title: '@faker-js/faker 10.6.0 person locale data',
    url: 'https://github.com/faker-js/faker',
    license: 'MIT',
    edition: '10.6.0',
  },
  'wikidata-names': {
    title: 'Wikidata aggregate name-component candidates by citizenship',
    url: 'https://query.wikidata.org/',
    license: 'CC0-1.0',
    edition: '2026-09-24',
    sha256: 'da3dec79e6ec5a0f412b9d94f9360712fa74cff856cca7be56440f9d0afff503',
  },
  'wikidata-africa-name-batch': {
    title: 'Wikidata Africa aggregate name-component candidates',
    url: 'https://query.wikidata.org/',
    license: 'CC0-1.0',
    edition: '2026-09-24',
    sha256: '5ee1d1ce7fcd7550d336034d027550ca679b95190983c26b460266c58c4891be',
  },
  'wikidata-africa-qlever-candidates': {
    title: 'Wikidata Africa name candidates via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-24',
    sha256: 'db878f5a1f9b4b1ca9165cc3a2b9b4938e9090866410973dd5ea7a524afa89d6',
  },
  'wikidata-africa-birthplace-candidates': {
    title: 'Wikidata Africa name candidates by birth place via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-24',
    sha256: 'a42dceddd27373a2ce32353ccb26582992e6b5718f91aa48a8b3b826fd26fc58',
  },
  'wikidata-europe-qlever-candidates': {
    title: 'Wikidata Europe name candidates via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-24',
    sha256: '170863c630bde60968af7b6d125083144bd735aeec08b9b66ef002186a018e5a',
  },
  'wikidata-europe-gendered-families': {
    title: 'Wikidata Europe family-name candidates grouped by gender via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-24',
    sha256: '28641da72c5b85e1c9a5ae1d2b3170f6862fed88596cd8be9b88cf3af44ca62c',
  },
  'wikidata-europe-birthplace-candidates': {
    title: 'Wikidata Europe territory name candidates by birth place via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: '5c6e4e2d92bc17520f23959f4a47ca0e24eb039996fb2eaca3cee797a84cd9b2',
  },
  'wikidata-asia-qlever-candidates': {
    title: 'Wikidata Asia name candidates via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: 'd6e92036ef467d5e5ba43c767a9a15e5914857c489c882b3f06b932644868ca8',
  },
  'wikidata-north-america-qlever-candidates': {
    title: 'Wikidata North America and Caribbean name candidates via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: 'ff94dd0962bec588d768d6ccafc42bfaeff3cd92a7c34e223c80335d7c82271a',
  },
  'wikidata-north-america-birthplace-candidates': {
    title: 'Wikidata North American territory name candidates by birth place via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: '3204de1275952be70033181a5b2073f4bfe3dd9dca15df97294823ff62c9d35a',
  },
  'wikidata-oceania-qlever-candidates': {
    title: 'Wikidata Oceania name candidates via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: '3fa9a18df28904f3fadc5cccf02d5b6e90c8ed9335741793dcada3cdd5fa2f91',
  },
  'wikidata-oceania-birthplace-candidates': {
    title: 'Wikidata Oceanian territory name candidates by birth place via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: '1d53617a2bf92d3af624e70dd978a43aeef91131a8ec81bd7ded656d4b5be37e',
  },
  'wikidata-south-america-qlever-candidates': {
    title: 'Wikidata South America name candidates via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: 'eed673c6594b61d1c9bd4df671600d11b714afeafe2085dc81323ea2b25ed152',
  },
  'wikidata-south-america-birthplace-candidates': {
    title: 'Wikidata South American territory name candidates by birth place via QLever',
    url: 'https://qlever.dev/api/wikidata',
    license: 'CC0-1.0',
    edition: '2026-09-25',
    sha256: '7c25edcc56b820f7c20880897ae94ddb6724b2cebf8ef6380a515efc35f00a2e',
  },
  'faroe-name-statistics': {
    title: 'Statistics Faroe Islands 2024 resident given names',
    url: 'https://hagstova.fo/fo/tidindi/jakup-og-maria-vanligastu-novnini-i-foroyum',
    license: 'Published aggregate name facts',
    edition: '2025-09-09',
  },
  'st-helena-election-names': {
    title: 'St Helena Government 2025 general-election candidate name components',
    url: 'https://www.sainthelena.gov.sh/official-list-of-candidates-for-the-2025-general-election/',
    license: 'Public candidate name-component facts',
    edition: '2025',
  },
  'st-helena-election-names-2021': {
    title: 'St Helena Government 2021 general-election candidate name components',
    url: 'https://www.sainthelena.gov.sh/official-list-of-candidates-for-the-2021-general-election/',
    license: 'Public candidate name-component facts',
    edition: '2021',
  },
  'sahrawi-womens-union-names': {
    title: 'Sahrawi Women Union preparatory committee name components in Arabic',
    url: 'https://spsrasd.info/ar/2026/01/26/13930.html',
    license: 'Public committee name-component facts',
    edition: '2026-01-26',
  },
  'insee-reunion-given-names': {
    title: 'Insee departmental given names, Réunion 974, births 2000–2025',
    url: 'https://www.insee.fr/fr/statistiques/8595130',
    license: 'Licence Ouverte / Open Licence',
    edition: '2025',
    sha256: '0d69c7083016e3e4e72457d6aa43a452cbae97d09b821f0736d74c32e76cf55c',
  },
  'insee-mayotte-given-names': {
    title: 'Insee departmental given names, Mayotte 976, births 2012–2025',
    url: 'https://www.insee.fr/fr/statistiques/8595130',
    license: 'Licence Ouverte / Open Licence',
    edition: '2025',
    sha256: '0d69c7083016e3e4e72457d6aa43a452cbae97d09b821f0736d74c32e76cf55c',
  },
  'mayotte-election-names': {
    title: 'Mayotte 2021 elected departmental councillor name components',
    url: 'https://www.archives-resultats-elections.interieur.gouv.fr/resultats/departementales-2021/976/CD976.php',
    license: 'Public officeholder name-component facts',
    edition: '2021',
  },
  'insee-reunion-family-names': {
    title: 'Insee departmental family names, Réunion 9D, births 1891–2000',
    url: 'https://www.insee.fr/fr/statistiques/3536630',
    license: 'Licence Ouverte / Open Licence',
    edition: '2018-05-22',
    sha256: 'd46698e90bb90783f3ff99dea779a51bc8186ce375bb340fac6bb84988b87b43',
  },
  'georgia-name-statistics': {
    title: 'Georgian Public Service Development Agency name counts reported by Rustavi2',
    url: 'https://rustavi2.ge/ka/news/289258',
    license: 'Public name-frequency facts',
    edition: '2024-08-14',
  },
  'burmese-name-frequencies': {
    title: 'Burmese Names common male and female name counts',
    url: 'https://burmesenames.wordpress.com/category/stats/',
    license: 'Public common-name frequency facts (small sample)',
    edition: '2014-06-07',
  },
  'uk-myanmar-names': {
    title: 'HM Passport Office Myanmar naming guidance',
    url: 'https://www.gov.uk/government/publications/myanmar-burma-knowledge-base-profile/myanmar-burma-knowledge-base-profile',
    license: 'Public naming guidance',
    edition: '2025-07-18',
  },
  'uk-indonesia-names': {
    title: 'HM Passport Office Indonesia naming guidance',
    url: 'https://www.gov.uk/government/publications/indonesia-knowledge-base-profile/indonesia-knowledge-base-profile',
    license: 'Public naming guidance',
    edition: '2026-07-01',
  },
  'andorra-civil-names': {
    title: 'Andorra civil registry 2013 common newborn names',
    url: 'https://www.govern.ad/ca/w/el-registre-civil-publica-la-memoria-de-funcionament-2013-1',
    license: 'Public name-frequency facts (small sample)',
    edition: '2013',
  },
  'bhutan-naming-study': {
    title: 'Karma Phuntsho, Naming Culture: Part 2 of 3',
    url: 'https://texts.mandala.library.virginia.edu/shanti_texts/node_embed/39441',
    license: 'Public naming convention and short name facts',
    edition: '2017',
  },
  'peace-corps-chichewa-names': {
    title: 'Learning Chichewa, Book 1: given-name examples',
    url: 'https://eric.ed.gov/?id=ED206157',
    license: 'Public given-name facts (small sample)',
    edition: '1980',
  },
  'ifla-malawi-names': {
    title: 'IFLA Names of Persons: Malawi clan-name examples',
    url: 'https://www.ifla.org/g/cataloguing/names-of-persons/',
    license: 'Public clan-name facts (small sample)',
    edition: '1996',
  },
  'tesfa-ethiopian-names': {
    title: 'Tesfa Alliance Ethiopian male and female given-name examples',
    url: 'https://tesfaalliance.org/names.php',
    license: 'Public given-name facts (small sample)',
    edition: '2026-09-24',
  },
  'uk-ethiopia-names': {
    title: 'HM Passport Office Ethiopia naming guidance',
    url: 'https://www.gov.uk/government/publications/ethiopia-knowledge-base-profile/ethiopia-knowledge-base-profile',
    license: 'Public naming guidance',
    edition: '2026-06-30',
  },
  'congo-senate-names': {
    title: 'Senate of the Republic of the Congo public member roster',
    url: 'https://www.senat.cg/groupe-parlementaire-pct-et-allies.php',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'ghana-parliament-names': {
    title: 'Parliament of Ghana public member names',
    url: 'https://www.parliament.gh/members',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'senegal-presidency-names': {
    title: 'Presidency of Senegal public appointment names',
    url: 'https://www.presidence.sn/fr/actualites/conseil-2/',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'stats-sa-birth-names': {
    title: 'Statistics South Africa Recorded Live Births 2024, Table 12',
    url: 'https://www.statssa.gov.za/publications/P0305/P03052024.pdf',
    license: 'Public aggregate name-frequency facts (small sample)',
    edition: '2024',
  },
  'rwanda-vital-names': {
    title: 'National Institute of Statistics of Rwanda Vital Statistics Report 2024, Annex 1',
    url: 'https://www.statistics.gov.rw/sites/default/files/documents/2025-04/Rwanda%20Vital%20Statistics%20Report%202024_N.pdf',
    license: 'Public aggregate name-frequency facts (small sample)',
    edition: '2024',
  },
  'rwanda-parliament-names': {
    title: 'Parliament of Rwanda public deputy profiles',
    url: 'https://www.parliament.gov.rw/chamber-of-deputies-2/member-profile/deputies-profiles',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'uganda-parliament-names': {
    title: 'Parliament of Uganda public member roster',
    url: 'https://mpsdb.parliament.go.ug/',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'kenya-parliament-names': {
    title: 'Parliament of Kenya 13th National Assembly members by party, July 2025',
    url: 'https://parliament.go.ke/sites/default/files/2025-07/List%20of%20Members%20by%20Parties%2013th%20Parliament%20as%20at%2002072025.pdf',
    license: 'Public name-component facts (small sample)',
    edition: '2025-07-02',
  },
  'namibia-parliament-names': {
    title: 'Namibian Parliament 8th National Assembly public member roster',
    url: 'https://www.parliament.na/8th-national-assembly-2025-2030/',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'tanzania-parliament-names': {
    title: 'Parliament of Tanzania public member profiles with stated sex',
    url: 'https://polis.parliament.go.tz/members',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'zambia-parliament-names': {
    title: 'National Assembly of Zambia public members list',
    url: 'https://www.parliament.gov.zm/members-of-parliament',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'zimbabwe-parliament-names': {
    title: 'Parliament of Zimbabwe public ministers and officials names',
    url: 'https://www.parlzim.gov.zw/ministers/',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'botswana-parliament-names': {
    title: 'Parliament of Botswana public members roster',
    url: 'https://parliament.gov.bw/members.php',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'lesotho-parliament-names': {
    title: 'National Assembly of Lesotho public members roster',
    url: 'https://nationalassembly.parliament.ls/members/',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'seychelles-parliament-names': {
    title: 'National Assembly of Seychelles 8th Assembly and Women’s Parliamentary Caucus',
    url: 'https://www.nationalassembly.sc/members-8th-assembly',
    license: 'Public name-component facts (small sample)',
    edition: '2026-09-24',
  },
  'libaddressinput-data': {
    title: 'Google Address Data Service country metadata',
    url: 'https://github.com/google/libaddressinput/wiki/AddressValidationMetadata',
    license: 'CC BY 4.0',
    edition: '2026-09-24',
    sha256: '5022ba62bdbaa1e5b10593ba9cbc02022e4f9ec7a8bef0ec937aaac357bac49c',
  },
  'geonames-postal': {
    title: 'GeoNames postal allCountries.zip',
    url: 'https://download.geonames.org/export/zip/allCountries.zip',
    license: 'CC BY 4.0',
    edition: '2026-09-24',
    sha256: '40cc0fcac59639c4fe6c666363bd9e314c006a1a883c8a63c2b78b1ce430c2ba',
  },
  'upu-pitcairn': {
    title: 'UPU Pitcairn postcode and address format',
    url: 'https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/pcnEn.pdf',
    license: 'Public postal format guidance (range fact)',
    edition: '2026-09-24',
  },
  'upu-falkland': {
    title: 'UPU Falkland Islands single postcode and address format',
    url: 'https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/flkEn.pdf',
    license: 'Public postal format guidance (single-code fact)',
    edition: '2026-09-25',
  },
  'persona-policy': {
    title: 'Persona V1 editorial selection policy',
    url: 'https://github.com/Osiris-Balonga/persona/blob/dev/docs/geographic-data.md',
    license: 'Project-owned selection rule',
    edition: 'v1',
  },
  nanpa: {
    title: 'NANPA 555 line numbers',
    url: 'https://nanpa.com/numbering/555-line-numbers',
    license: 'Public numbering guidance (range fact)',
    edition: '2026-09-24',
  },
  ofcom: {
    title: 'Ofcom numbers for drama',
    url: 'https://www.ofcom.org.uk/phones-and-broadband/phone-numbers/numbers-for-drama',
    license: 'Public numbering guidance (range fact)',
    edition: '2026-09-24',
  },
  'acma-fictional-numbers': {
    title: 'ACMA phone numbers for creative works',
    url: 'https://www.acma.gov.au/phone-numbers-use-tv-shows-films-and-creative-works',
    license: 'Public numbering guidance (range fact)',
    edition: '2026-09-25',
  },
  'crtc-fictional-numbers': {
    title: 'CRTC decision 2017-203 on Canadian 555 numbers',
    url: 'https://crtc.gc.ca/eng/archive/2017/2017-203.htm',
    license: 'Public numbering guidance (range fact)',
    edition: '2017-06-20',
  },
  'cnac-area-codes': {
    title: 'Canadian Numbering Administrator exchange area listing',
    url: 'https://cnac.ca/reference_data/canadian_exchange_area_listing.htm',
    license: 'Public numbering guidance (area-code fact)',
    edition: '2026-09-25',
  },
  'nanpa-area-codes': {
    title: 'NANPA United States area-code maps',
    url: 'https://www.nanpa.com/resources/area-code-maps',
    license: 'Public numbering guidance (area-code fact)',
    edition: '2026-09-25',
  },
  'nanpa-territory-areas': {
    title: 'NANPA country and territory NPA map',
    url: 'https://www.nanpa.com/resources/area-code-map/territories',
    license: 'Public numbering guidance (area-code fact)',
    edition: '2026-09-25',
  },
  'arcep-fictional-numbers': {
    title: 'ARCEP national numbering plan, audiovisual numbers',
    url: 'https://en.arcep.fr/uploads/tx_gsavis/25-2215.pdf',
    license: 'Public numbering decision (range fact)',
    edition: '2026-01-01',
  },
  'bnetza-drama-numbers': {
    title: 'Bundesnetzagentur drama numbers, notice 148/2021',
    url: 'https://www.bundesnetzagentur.de/DE/Fachthemen/Telekommunikation/Nummerierung/_DL/mittlg148_2021.pdf?__blob=publicationFile&v=1',
    license: 'Public numbering guidance (range fact)',
    edition: '2021-04-14',
  },
  'comreg-drama-numbers': {
    title: 'ComReg numbering conditions, drama mobile range',
    url: 'https://www.comreg.ie/media/2024/04/ComReg-15136R4.pdf',
    license: 'Public numbering guidance (range fact)',
    edition: '2024-04',
  },
  'pts-fictional-numbers': {
    title: 'PTS phone numbers for books and films',
    url: 'https://pts.se/internet-och-telefoni/telefonnummer-och-adressering/telefonnummer-till-bocker-och-filmer/',
    license: 'Public numbering guidance (range fact)',
    edition: '2024-05-14',
  },
} as const

export type GeographicSource = keyof typeof geographicSources
