// Reviewed Wikidata name components; see docs/geographic-data.md.
export const southAmericaReviewedNames = {
  AR: {
    female: [
      "María", "Ana", "Laura", "Cecilia", "Susana", "Silvia",
      "Alicia", "Gabriela", "Graciela", "Beatriz", "Maria", "Patricia",
      "Florencia", "Mariana", "Carolina", "Cristina", "Liliana", "Paula",
      "Andrea", "Marta", "Mónica", "Adriana", "Claudia", "Victoria",
      "Inés", "Alejandra", "Natalia", "Marcela", "Elena", "Mercedes",
      "Agustina", "Julia", "Sofía", "Julieta", "Sandra", "Virginia",
      "Nora", "Daniela", "Carmen", "Verónica", "Juana", "Rosa",
      "Valeria", "Elsa", "Lucía", "Diana", "Norma", "Isabel",
      "Luciana", "Marina",
    ],
    male: [
      "Carlos", "Juan", "José", "Jorge", "Luis", "Pablo",
      "Alberto", "Eduardo", "Roberto", "Alejandro", "Daniel", "Francisco",
      "Fernando", "Nicolás", "Ricardo", "Pedro", "Diego", "Guillermo",
      "Enrique", "Manuel", "Mario", "Marcelo", "Federico", "Antonio",
      "Martín", "Héctor", "Gustavo", "Miguel", "Julio", "Oscar",
      "máximo merilio", "Raúl", "Santiago", "anal", "Lucas", "Alfredo",
      "Juan Carlos", "Gabriel", "Mariano", "Sergio", "Horacio", "Agustín",
      "Hugo", "Sebastián", "Javier", "Rodolfo", "Ángel", "Andrés",
      "Tomás", "Emilio",
    ],
    family: [
      "González", "Martínez", "Fernández", "López", "García", "Rodríguez",
      "Gómez", "Díaz", "Pérez", "Álvarez", "Romero", "Sánchez",
      "Molina", "Aguirre", "Torres", "Castro", "Acosta", "Rossi",
      "Suárez", "Ruiz", "Moreno", "Giménez", "Herrera", "Ramírez",
      "Méndez", "Ramos", "Blanco", "Quiroga", "Ferrari", "Medina",
      "Muñoz", "Alonso", "Navarro", "Figueroa", "Núñez", "Vidal",
      "Gil", "Morales", "Pereyra", "Rojas", "Flores", "Silva",
      "Domínguez", "Ledesma", "Peralta", "Vega", "Acuña", "Godoy",
      "Ortiz", "Costa", "Franco", "Varela", "Castillo", "Iglesias",
      "Mendoza", "Ojeda", "Ortega", "Rodriguez", "Vázquez", "Aguilar",
      "Delgado", "Otero", "Paz", "Soto", "Arias", "Ayala",
      "Ferreyra", "Martinez", "Cabrera", "Gallo", "Romano", "Villanueva",
      "Martín", "Palacios", "Colombo",
    ],
  },
  BO: {
    female: [
      "María", "Ana", "Paola", "Claudia", "Ximena", "Carmen",
      "Gabriela", "Julia", "Carla", "Mariana", "Mónica", "Alejandra",
      "Beatriz", "Cecilia", "Gladys", "Sandra", "Adriana", "Carolina",
      "Daniela", "Isabel", "Marcela", "Maria", "Rosario", "Sonia",
      "Teresa", "Verónica", "Virginia", "Blanca", "Camila", "Elizabeth",
      "Erika", "Esther", "Fernanda", "Karen", "Martha", "Natalia",
      "Rosa", "Susana", "Vivian", "Amparo", "Angélica", "Cristina",
      "Elsa", "Graciela", "Hilda", "Iris", "Jessica", "Julieta",
      "Kimberly", "Lidia",
    ],
    male: [
      "José", "Carlos", "Luis", "Juan", "Jorge", "Mario",
      "Jaime", "Juan Carlos", "Manuel", "Eduardo", "Pedro", "Roberto",
      "Fernando", "Daniel", "Hugo", "Miguel", "Diego", "Alberto",
      "Óscar", "Gustavo", "Víctor", "Marcelo", "Pablo", "René",
      "Ricardo", "Alejandro", "David", "Javier", "Julio", "Oscar",
      "Edgar", "Ronald", "Antonio", "Mauricio", "máximo merilio", "Raúl",
      "César", "Francisco", "Sergio", "Alfredo", "Enrique", "Gonzalo",
      "Guillermo", "Rodrigo", "Andrés", "Leonardo", "Marco", "Félix",
      "Freddy", "Jesús",
    ],
    family: [
      "Rojas", "Fernández", "Suárez", "Sánchez", "Morales", "Paz",
      "Camacho", "López", "Peña", "Arce", "Ballivián", "Flores",
      "García", "Mamani", "Mendoza", "Quispe", "Ramos", "Saavedra",
      "Vaca", "Álvarez", "Pérez", "Quiroga", "Méndez", "Rodríguez",
      "Cárdenas", "Choque", "Galindo", "Navarro", "Rivero", "Salazar",
      "Áñez", "Borda", "Cajías", "Castro", "Chávez", "Cruz",
      "Herrera", "Maldonado", "Medina", "Melgar", "Miranda", "Paniagua",
      "Pinto", "Reyes", "Ríos", "Romero", "Velasco", "Zapata",
      "Aguilar", "Alfaro", "Antezana", "Bejarano", "Castillo", "Durán",
      "Guzmán", "Jiménez", "Justiniano", "Lopez", "Loza", "Mercado",
      "Montes", "Pinedo", "Prado", "Rocha", "Sandoval", "Torres",
      "Veizaga", "Acosta", "Aguirre", "Alandia", "Alanoca", "Angulo",
      "Arze", "Cabrera", "Campero",
    ],
  },
  BR: {
    female: [
      "Maria", "Ana", "Fernanda", "Adriana", "Juliana", "Mariana",
      "Renata", "Vera", "Beatriz", "Cristina", "Patrícia", "Aline",
      "Daniela", "Regina", "Helena", "Gabriela", "Carolina", "Bruna",
      "Carla", "Paula", "Sandra", "Luciana", "Camila", "Laura",
      "Vanessa", "Cláudia", "Denise", "Marina", "Claudia", "Cristiane",
      "Márcia", "Anna", "Marcia", "Larissa", "Amanda", "Bianca",
      "Lúcia", "Raquel", "Luiza", "Alice", "Rita", "Tatiana",
      "Alessandra", "Luana", "Roberta", "Flávia", "Viviane", "Julia",
      "Letícia", "Sonia",
    ],
    male: [
      "José", "João", "Carlos", "Antônio", "Paulo", "Francisco",
      "Luiz", "Antonio", "Pedro", "Marcelo", "Marcos", "Eduardo",
      "Fernando", "Ricardo", "Roberto", "Jose", "Alexandre", "Rodrigo",
      "Jorge", "Bruno", "Rafael", "Joaquim", "André", "Luís",
      "Manuel", "Lucas", "Sérgio", "Daniel", "Felipe", "Henrique",
      "Guilherme", "Mário", "Renato", "Gabriel", "Gustavo", "Leonardo",
      "Fábio", "Thiago", "Augusto", "Leandro", "Geraldo", "Luis",
      "Márcio", "Marco", "Edson", "Luciano", "Raimundo", "Alberto",
      "Sebastião", "Diego",
    ],
    family: [
      "Silva", "Alves", "da Silva", "Santos", "Pereira", "Oliveira",
      "Lima", "Ferreira", "Costa", "Martins", "Rodrigues", "Ribeiro",
      "de Oliveira", "Gomes", "Gonçalves", "Barbosa", "Rocha", "Machado",
      "Soares", "Dias", "Fernandes", "Souza", "Araújo", "de Souza",
      "Almeida", "Lopes", "Nunes", "Cardoso", "Andrade", "Carvalho",
      "Guimarães", "Campos", "Ramos", "Vieira", "Borges", "Neto",
      "Pinheiro", "Nascimento", "Leite", "Monteiro", "Pinto", "Teixeira",
      "Filho", "Nogueira", "Santana", "Reis", "Moreira", "Miranda",
      "Castro", "Braga", "Cunha", "Barros", "Marques", "Moura",
      "Maia", "Da Silva", "de Almeida", "Pires", "Freitas", "Rosa",
      "Azevedo", "Fonseca", "Magalhães", "Brito", "Mendes", "Cruz",
      "Barreto", "de Carvalho", "Duarte", "Melo", "Menezes", "Amaral",
      "Aguiar", "Coelho", "Batista",
    ],
  },
  CL: {
    female: [
      "María", "Carmen", "Carolina", "Francisca", "Catalina", "Claudia",
      "Alejandra", "Javiera", "Daniela", "Ana", "Patricia", "Paula",
      "Andrea", "Camila", "Cecilia", "Valentina", "Marcela", "Fernanda",
      "Marta", "Constanza", "Gabriela", "Paulina", "Gloria", "Ximena",
      "Teresa", "Antonia", "Isabel", "Macarena", "María José", "Laura",
      "Mónica", "Rosa", "Verónica", "Natalia", "Pamela", "Bárbara",
      "Alicia", "Elena", "Elisa", "Carla", "Magdalena", "Adriana",
      "Loreto", "Paola", "Josefina", "Maria", "Raquel", "Sara",
      "Silvia", "Victoria",
    ],
    male: [
      "Carlos", "José", "Luis", "Juan", "Jorge", "Francisco",
      "Manuel", "Eduardo", "Pedro", "Fernando", "Sergio", "Pablo",
      "Alejandro", "Rodrigo", "Guillermo", "Enrique", "Ricardo", "Mario",
      "Felipe", "Jaime", "Roberto", "Andrés", "Diego", "Patricio",
      "Claudio", "Miguel", "Alberto", "Julio", "Antonio", "Ignacio",
      "Gonzalo", "Hernán", "Arturo", "Daniel", "Ramón", "Sebastián",
      "Nicolás", "máximo merilio", "Raúl", "Cristián", "Marcelo", "Héctor",
      "Rafael", "Alfredo", "Mauricio", "Gustavo", "Hugo", "Javier",
      "Víctor", "Vicente",
    ],
    family: [
      "González", "Muñoz", "Silva", "Rojas", "Pérez", "Fernández",
      "Díaz", "Martínez", "Rodríguez", "García", "López", "Soto",
      "Contreras", "Reyes", "Valenzuela", "Castillo", "Vergara", "Flores",
      "Castro", "Bravo", "Carrasco", "Figueroa", "Herrera", "Guzmán",
      "Morales", "Miranda", "Ramírez", "Araya", "Parra", "Saavedra",
      "Tapia", "Vial", "Errázuriz", "Gómez", "Moreno", "Torres",
      "Pinto", "Vidal", "Molina", "Álvarez", "Núñez", "Valdés",
      "Campos", "Hernández", "Jara", "Salinas", "Correa", "Godoy",
      "Cortés", "Larraín", "Pizarro", "Urrutia", "Donoso", "Espinoza",
      "Romero", "Alarcón", "Toro", "Palma", "Acuña", "Cruz",
      "Escobar", "Jiménez", "Lobos", "Montt", "Peña", "Rivas",
      "Sepúlveda", "Yáñez", "Arriagada", "Concha", "Lagos", "Olivares",
      "Poblete", "Salazar", "Aguilera",
    ],
  },
  CO: {
    female: [
      "María", "Ana", "Laura", "Carolina", "Natalia", "Andrea",
      "Diana", "Maria", "Patricia", "Adriana", "Sandra", "Gloria",
      "Claudia", "Lina", "Luz", "Margarita", "Martha", "Catalina",
      "Paola", "Marcela", "Daniela", "Paula", "Camila", "Cristina",
      "Alejandra", "Mariana", "Isabel", "Juliana", "Valentina", "Sara",
      "Beatriz", "Cecilia", "Liliana", "Tatiana", "Luisa", "Rosa",
      "Gabriela", "Mercedes", "Clara", "Lorena", "Mónica", "Helena",
      "Jessica", "Sofía", "Teresa", "Ángela", "Angie", "Blanca",
      "Carmen", "Inés",
    ],
    male: [
      "Carlos", "Luis", "Juan", "José", "Jorge", "Andrés",
      "Fernando", "Diego", "Manuel", "Daniel", "Jaime", "Alberto",
      "Rafael", "Eduardo", "Álvaro", "David", "Alejandro", "Antonio",
      "Francisco", "Pedro", "Miguel", "Camilo", "Ricardo", "Javier",
      "Mauricio", "Gustavo", "John", "Santiago", "Julio", "Guillermo",
      "Mario", "Enrique", "Óscar", "Felipe", "Julián", "Alfonso",
      "Juan Carlos", "Jhon", "Jesús", "Cristian", "Gabriel", "Germán",
      "Héctor", "Roberto", "César", "Víctor", "Sergio", "Hernán",
      "Hernando", "Oscar",
    ],
    family: [
      "Martínez", "Gómez", "González", "López", "García", "Rodríguez",
      "Valencia", "Mosquera", "Pérez", "Moreno", "Restrepo", "Ramírez",
      "Torres", "Castro", "Uribe", "Sánchez", "Salazar", "Rojas",
      "Arango", "Herrera", "Díaz", "Hernández", "Jaramillo", "Muñoz",
      "Álvarez", "Escobar", "Medina", "Osorio", "Arias", "Zapata",
      "Castillo", "Palacios", "Acosta", "Morales", "Quintero", "Ospina",
      "Cardona", "Giraldo", "Mejía", "Montoya", "Murillo", "Romero",
      "Ruiz", "Duque", "Jiménez", "Rivas", "Caicedo", "Botero",
      "Reyes", "Vélez", "Cruz", "Fernández", "Guerrero", "Mendoza",
      "Silva", "Angulo", "Camacho", "Hurtado", "Londoño", "Parra",
      "Camargo", "Peña", "Ramos", "Trujillo", "Cano", "Lozano",
      "Mora", "Rodriguez", "Delgado", "Ortiz", "Acevedo", "Rueda",
      "Soto", "Suárez", "Correa",
    ],
  },
  EC: {
    female: [
      "María", "Ana", "Rosa", "Andrea", "Diana", "Carmen",
      "Maria", "Gabriela", "Mónica", "Paola", "Patricia", "Isabel",
      "Alexandra", "Elizabeth", "Verónica", "Ximena", "Carolina", "Cristina",
      "Daniela", "Fernanda", "Elena", "Karla", "Laura", "Lorena",
      "Marcela", "Mariana", "Sandra", "Susana", "Lucía", "Mercedes",
      "Paulina", "Sonia", "Viviana", "Adriana", "Blanca", "Cecilia",
      "Juana", "Katherine", "Liliana", "Martha", "Mayra", "Alejandra",
      "Ángela", "Catalina", "Erika", "Inés", "Manuela", "Marcia",
      "Margarita", "Piedad",
    ],
    male: [
      "Luis", "Carlos", "José", "Jorge", "Juan", "Diego",
      "Francisco", "Fernando", "Eduardo", "Andrés", "Pedro", "Manuel",
      "Antonio", "César", "Jaime", "David", "Pablo", "Rafael",
      "Julio", "Miguel", "Enrique", "Alfredo", "Roberto", "Xavier",
      "Alberto", "Gustavo", "Javier", "Marco", "Ángel", "Daniel",
      "Hugo", "máximo merilio", "Raúl", "Jonathan", "Santiago", "Vicente",
      "Patricio", "Alejandro", "Christian", "Galo", "Segundo", "Gonzalo",
      "Oswaldo", "Víctor", "Héctor", "Jefferson", "Ricardo", "Wilson",
      "Alfonso", "Cristian",
    ],
    family: [
      "Zambrano", "Rodríguez", "González", "Valencia", "Castillo", "Caicedo",
      "Torres", "García", "Hurtado", "Andrade", "López", "Delgado",
      "Mina", "Moreno", "Martínez", "Mendoza", "Ortiz", "Sánchez",
      "Romero", "Angulo", "Muñoz", "Pérez", "Borja", "Guerrero",
      "Quiñónez", "Castro", "Palacios", "Paredes", "Arroyo", "Calderón",
      "Gómez", "Herrera", "Mora", "Maldonado", "Nazareno", "Ponce",
      "Rojas", "Valverde", "Aguirre", "Cabezas", "Chiriboga", "Espinoza",
      "Estrada", "Flores", "León", "Medina", "Moncayo", "Naranjo",
      "Velasco", "Álvarez", "Bonilla", "Escobar", "Guerra", "Guevara",
      "Jaramillo", "Larrea", "Molina", "Preciado", "Suárez", "Cordero",
      "Corozo", "Crespo", "Jiménez", "Lara", "Morales", "Mosquera",
      "Ordóñez", "Peña", "Quintero", "Ramírez", "Serrano", "Vallejo",
      "Vásquez", "Acosta", "Aguilar",
    ],
  },
  GY: {
    female: [
      "Anaya", "Annalisa", "Annette", "Brenda", "Catherine", "Dawn",
      "Hannah", "Jennifer", "June", "Karen", "Melissa", "Philomena",
      "Samantha", "Alice", "Alisha", "Alison", "Aliyah", "Alyssa",
      "Ambika", "Andrea", "Angel", "Ann", "Arya", "Asha",
      "Ashley", "Aubrey", "Barbara", "Bernadette", "Bria", "Briana",
      "Brianna", "Brianne", "Britany", "Candace", "Carol", "Carolyn",
      "Caron", "Cassie", "Chelsea", "Cheryl", "Christa", "Christine",
      "Claire", "Claudette", "Coretta", "Cyndie", "Daniela", "Deborah",
      "Demelza", "Denise",
    ],
    male: [
      "Andrew", "Anthony", "Colin", "Mark", "Aubrey", "Frank",
      "James", "Michael", "Robert", "Arthur", "Carl", "Charles",
      "Christopher", "David", "Edward", "George", "Jason", "John",
      "Keith", "Leon", "Neville", "Randolph", "Richard", "Samuel",
      "Shawn", "Travis", "Winston", "Alfred", "Andre", "Basil",
      "Clayton", "Clive", "Clyde", "Cyril", "Donald", "Edmond",
      "Gordon", "Howard", "Hugh", "Ian", "İmran", "Jermaine",
      "Kevin", "Lennox", "Lloyd", "Neil", "Nigel", "Paul",
      "Ralph", "Ricardo",
    ],
    family: [
      "Adams", "Williams", "Harris", "James", "Abrams", "Hooper",
      "Jeffrey", "Moore", "Roberts", "Thomas", "Burnett", "Campbell",
      "Charles", "Fraser", "George", "Glasgow", "Johnson", "Rogers",
      "Singh", "Thompson", "Baird", "Browne", "Cameron", "Cort",
      "Griffith", "Hunter", "Jones", "Joseph", "Lewis", "Persaud",
      "Phillips", "Ramdhani", "Rose", "Smith", "Anderson", "Archer",
      "Benjamin", "Blackman", "Bowen", "Braithwaite", "Butts", "Carter",
      "Crandon", "David", "de Souza", "Dover", "Duncan", "Edwards",
      "Fernandes", "Gaskin", "Gilkes", "Gill", "Granger", "Grant",
      "Greene", "Hastings", "Ifill", "Jacobs", "Jagan", "John",
      "Jordan", "King", "Kissoon", "Lloyd", "Locke", "Matthews",
      "McDonald", "McKenzie", "McPherson", "McWatt", "Mitchell", "Murray",
      "Newton", "Nurse", "Peters",
    ],
  },
  PE: {
    female: [
      "María", "Rosa", "Patricia", "Ana", "Carmen", "Elizabeth",
      "Isabel", "Cecilia", "Luz", "Milagros", "Andrea", "Claudia",
      "Mercedes", "Teresa", "Elena", "Alejandra", "Gabriela", "Carolina",
      "Cristina", "Lucía", "Rocío", "Diana", "Paola", "Beatriz",
      "Karina", "Julia", "Rosario", "Esther", "Sofía", "Luisa",
      "Mónica", "Sandra", "Silvia", "Victoria", "Gloria", "Valeria",
      "Angélica", "Gladys", "Alexandra", "Margarita", "Roxana", "Daniela",
      "Fiorella", "Liliana", "Edith", "Susana", "Fernanda", "Jessica",
      "Lourdes", "Martha",
    ],
    male: [
      "José", "Luis", "Carlos", "Juan", "Manuel", "Jorge",
      "Alberto", "Enrique", "Antonio", "César", "Miguel", "Eduardo",
      "Fernando", "Pedro", "Víctor", "Francisco", "Augusto", "Javier",
      "Alejandro", "Ricardo", "Guillermo", "Julio", "Daniel", "Alfredo",
      "Jesús", "Martín", "Raúl", "Roberto", "David", "Ernesto",
      "Rafael", "Andrés", "Ángel", "Hugo", "Mario", "Arturo",
      "Diego", "Pablo", "Alfonso", "Gustavo", "Jaime", "Felipe",
      "Alonso", "Gonzalo", "Humberto", "Mariano", "Óscar", "Santiago",
      "Héctor", "Marco",
    ],
    family: [
      "García", "Rodríguez", "Flores", "Sánchez", "Fernández", "López",
      "Castillo", "Chávez", "Díaz", "Vásquez", "Castro", "Rojas",
      "Espinoza", "León", "Quispe", "Ramírez", "Torres", "Pérez",
      "Gonzales", "Romero", "Delgado", "Morales", "Mendoza", "Salazar",
      "Martínez", "González", "Ramos", "Ruiz", "Paredes", "Aguilar",
      "Álvarez", "Cáceres", "Herrera", "Gómez", "Huamán", "Jiménez",
      "Bustamante", "Soto", "Alvarado", "Guevara", "Medina", "Pacheco",
      "Vega", "Luna", "Silva", "Reyes", "Cárdenas", "Hurtado",
      "Calderón", "Cornejo", "Villanueva", "Ortiz", "Aguirre", "Campos",
      "Cruz", "Guzmán", "Muñoz", "Figueroa", "Hernández", "Salas",
      "Velásquez", "Cabrera", "Palomino", "Gamarra", "Benavides", "Bravo",
      "Moreno", "Núñez", "Zegarra", "Arce", "Carrasco", "Castañeda",
      "Ponce", "Córdova", "Guerrero",
    ],
  },
  PY: {
    female: [
      "María", "Maria", "Ana", "Gabriela", "Gloria", "Margarita",
      "Alicia", "Carmen", "Diana", "Jessica", "Liz", "Mabel",
      "Natalia", "Ramona", "Rosa", "Andrea", "Claudia", "Cristina",
      "Juana", "Julia", "Karen", "Marta", "Olga", "Sandra",
      "Teresa", "Alma", "Camila", "Cecilia", "Cynthia", "Fabiola",
      "Gladys", "Guadalupe", "Isabel", "Larissa", "Laura", "Lourdes",
      "Mercedes", "Paola", "Patricia", "Raquel", "Rocio", "Sara",
      "Silvia", "Sofia", "Sofía", "Susana", "Verónica", "Adela",
      "Alice", "Analia",
    ],
    male: [
      "Carlos", "Juan", "José", "Luis", "Jorge", "Francisco",
      "Antonio", "Diego", "Pedro", "Gustavo", "Manuel", "Ramón",
      "Pablo", "César", "Fernando", "Julio", "Miguel", "Roberto",
      "Daniel", "Enrique", "Hugo", "Marcos", "Ángel", "Arnaldo",
      "Oscar", "Óscar", "Ricardo", "Mario", "Rodrigo", "Rubén",
      "Víctor", "Alejandro", "Alfredo", "David", "Félix", "Héctor",
      "Javier", "máximo merilio", "Raúl", "Derlis", "Edgar", "Ignacio",
      "Juan Carlos", "Adolfo", "Julio César", "Marcelo", "Richard", "Alberto",
      "Celso", "Cristian",
    ],
    family: [
      "González", "Martínez", "López", "Benítez", "Fernández", "Franco",
      "Caballero", "Romero", "Ferreira", "Giménez", "Ortiz", "Escobar",
      "Rojas", "Acosta", "Ayala", "Bogado", "Gómez", "Peralta",
      "Ramírez", "Díaz", "Rodríguez", "Duarte", "Martinez", "Torres",
      "Barrios", "Centurión", "Godoy", "Miranda", "Paredes", "Pérez",
      "Acuña", "Báez", "Cáceres", "Mendoza", "Riveros", "Aquino",
      "Bareiro", "Cabrera", "Coronel", "García", "Medina", "Mora",
      "Ruiz", "Sánchez", "Yegros", "Aguilar", "Arce", "Cardozo",
      "Domínguez", "Florentín", "Gamarra", "Jara", "Morel", "Olmedo",
      "Santacruz", "Aguilera", "Aranda", "Barreto", "Benitez", "Bobadilla",
      "Brizuela", "Caceres", "Chamorro", "Colmán", "Delgado", "Espínola",
      "Garay", "Gimenez", "Lezcano", "Montiel", "Núñez", "Pereira",
      "Riquelme", "Rivarola", "Rodas",
    ],
  },
  SR: {
    female: [
      "Jennifer", "Lilian", "Naomi", "Patricia", "Ruth", "Carla",
      "Diana", "Gloria", "Joan", "Maria", "Nisha", "Xaviera",
      "Astrid", "Audrey", "Christine", "Conchita", "Helen", "Ilse",
      "Ingrid", "Loes", "Marlène", "Melissa", "Monique", "Yvonne",
      "Agnes", "Alice", "Ann", "Annemarie", "Annie", "Carolyn",
      "Chayenne", "Cheryl", "Cornelly", "Cynthia", "Danielle", "Dorothy",
      "Elfriede", "Ellen", "Evita", "Gerda", "Henna", "Irene",
      "Jacqueline", "Jenny", "Joanna", "Johanna", "Joyce", "Karin",
      "Liesbeth", "Lucretia",
    ],
    male: [
      "John", "Eddy", "Henk", "André", "Humphrey", "Kenneth",
      "Albert", "Glenn", "Johan", "Ronald", "Stanley", "Harold",
      "Iwan", "Jules", "Roy", "George", "Hugo", "Leo",
      "René", "Armand", "Frank", "Paul", "Robby", "Siegfried",
      "Wilfred", "Alexander", "Cornelis", "Edgar", "Edmund", "Eugène",
      "Harry", "Herman", "Julius", "Louis", "Patrick", "Rudi",
      "Shaquille", "Theo", "Walther", "August", "Dennis", "Eduard",
      "Eric", "Hendrik", "Henry", "Johannes", "Jozef", "Lesley",
      "Lucien", "Marcel",
    ],
    family: [
      "Pinas", "Bouterse", "Breeveld", "Esajas", "Mook", "Sabajo",
      "Sardjoe", "Sjauw", "Ahmadali", "Cairo", "Comvalius", "Ferrier",
      "Jones", "Lichtveld", "Muringen", "Simons", "van Dijk", "Verwey",
      "Aloema", "Amatstam", "Artist", "Boldewijn", "Brunings", "Chin",
      "de la Fuente", "Demon", "Faerber", "Fernandes", "Haynes", "Helstone",
      "Illes", "Ishaak", "Jadnanansing", "Jameson", "Jessurun", "Kamperveen",
      "Leerdam", "Lewis", "Malone", "Mijnals", "Miranda", "Misiedjan",
      "Mungra", "Pollack", "Radhakishun", "Ramcharan", "Sedoc", "Snijders",
      "Telting", "Toney", "van Vliet", "Waal", "Wong Loi Sing", "Abdoelrahman",
      "Abrahams", "Agerkop", "Ajodhia", "Alberga", "Alexander", "Alfaisie",
      "Amafo", "Asin", "Asinga", "Axwijk", "Bakas", "Biervliet",
      "Bonjaski", "Brand Flu", "Brandon", "Bueno", "Burleson", "Chen",
      "Cheng A June", "Clemens", "Dawson",
    ],
  },
  UY: {
    female: [
      "María", "Ana", "Laura", "Graciela", "Alicia", "Susana",
      "Raquel", "Carmen", "Silvia", "Mariana", "Gabriela", "Beatriz",
      "Cecilia", "Cristina", "Elena", "Lucía", "Patricia", "Carolina",
      "Mónica", "Adriana", "Margarita", "Martha", "Teresa", "Inés",
      "Blanca", "Marta", "Mercedes", "Rosa", "Olga", "Andrea",
      "Isabel", "Virginia", "Gloria", "Sara", "Elsa", "Gladys",
      "Rosario", "Celia", "Claudia", "Florencia", "Sofía", "Mary",
      "Nelly", "Victoria", "Alba", "Delia", "Julia", "Nora",
      "Alejandra", "Camila",
    ],
    male: [
      "Carlos", "José", "Juan", "Luis", "Jorge", "Eduardo",
      "Julio", "Daniel", "Alberto", "Pablo", "Enrique", "Héctor",
      "Pedro", "Diego", "Fernando", "Francisco", "Mario", "Roberto",
      "Miguel", "Alejandro", "Ricardo", "máximo merilio", "Raúl", "Alfredo",
      "Gustavo", "Federico", "Martín", "Hugo", "Manuel", "Santiago",
      "Antonio", "Juan Carlos", "Nicolás", "Guillermo", "Álvaro", "Andrés",
      "Gabriel", "Gonzalo", "Marcelo", "Sergio", "Sebastián", "Nelson",
      "Rafael", "Rodrigo", "Ignacio", "Ernesto", "Víctor", "Javier",
      "Washington", "Agustín",
    ],
    family: [
      "Martínez", "González", "Rodríguez", "Pérez", "Fernández", "Silva",
      "García", "López", "Gómez", "Castro", "Díaz", "Pereira",
      "Álvarez", "Medina", "Alonso", "Cabrera", "Méndez", "Acosta",
      "Núñez", "Suárez", "Ramos", "Viera", "Olivera", "Pereyra",
      "Machado", "Vidal", "Blanco", "Barrios", "Costa", "Romero",
      "Aguirre", "Cardozo", "Delgado", "Guerra", "Ramírez", "Duarte",
      "Ferreira", "Pintos", "Torres", "Herrera", "Varela", "Aguiar",
      "Gil", "Muñoz", "Reyes", "Santos", "Da Silva", "Flores",
      "Miranda", "Morales", "Moreira", "Rivero", "Silveira", "Arocena",
      "Barboza", "Cardoso", "Castellanos", "Castillo", "Hernández", "Lima",
      "Peralta", "Rodriguez", "Araújo", "Márquez", "Montero", "Ribeiro",
      "Rossi", "Barreto", "Bianchi", "Curbelo", "Figueroa", "Prieto",
      "Puig", "Risso", "Sanguinetti",
    ],
  },
  VE: {
    female: [
      "María", "Ana", "Carolina", "Carmen", "Gabriela", "Patricia",
      "Maria", "Adriana", "Daniela", "Elizabeth", "Mariana", "Vanessa",
      "Alejandra", "Andrea", "Gladys", "Mercedes", "Andreína", "Elena",
      "Luisa", "Claudia", "Laura", "Paola", "Valentina", "Alexandra",
      "Bárbara", "Isabel", "Olga", "Teresa", "Beatriz", "Diana",
      "Elisa", "Gloria", "Mary", "Michelle", "Milagros", "Cecilia",
      "Cristina", "Fabiola", "Karina", "Rosa", "Sandra", "Victoria",
      "Virginia", "Alicia", "Blanca", "Carla", "Dayana", "Génesis",
      "Jessica", "Luz",
    ],
    male: [
      "José", "Luis", "Carlos", "Rafael", "Jesús", "Juan",
      "Antonio", "Pedro", "Francisco", "Manuel", "Alejandro", "Enrique",
      "Jorge", "Miguel", "Eduardo", "Ricardo", "Daniel", "Ramón",
      "Alberto", "Fernando", "Andrés", "César", "Gustavo", "David",
      "Alfredo", "Guillermo", "Ángel", "Gabriel", "Julio", "Diego",
      "Juan Carlos", "Alexander", "Héctor", "Víctor", "Roberto", "Vicente",
      "Oliver", "Freddy", "Oscar", "Ernesto", "Javier", "máximo merilio",
      "Raúl", "Edgar", "Henry", "Oswaldo", "Tomás", "Félix",
      "Jose", "Nelson",
    ],
    family: [
      "González", "Pérez", "Rodríguez", "Martínez", "Díaz", "López",
      "García", "Castillo", "Romero", "Fernández", "Hernández", "Torres",
      "Medina", "Sánchez", "Álvarez", "Blanco", "Herrera", "Rivas",
      "Ramírez", "Rojas", "Gómez", "Mendoza", "Moreno", "Salazar",
      "Márquez", "Silva", "Delgado", "Ruiz", "Suárez", "Castro",
      "Jiménez", "Machado", "Palacios", "Ramos", "Flores", "Parra",
      "Reyes", "Marcano", "Contreras", "Peña", "Méndez", "Ortega",
      "Zambrano", "Acosta", "Barrios", "Diaz", "Guevara", "León",
      "Mata", "Pinto", "Quintero", "Guerra", "Guzmán", "Andrade",
      "Mora", "Rodriguez", "Tovar", "Alvarado", "Morales", "Navarro",
      "Camacho", "Escobar", "Muñoz", "Ochoa", "Rosales", "Barreto",
      "Bravo", "Campos", "Gil", "Maldonado", "Martinez", "Rivero",
      "Vásquez", "Abreu", "Aguilar",
    ],
  },
} as const

export function isSouthAmericaReviewedCountry(code: string): code is keyof typeof southAmericaReviewedNames {
  return Object.hasOwn(southAmericaReviewedNames, code)
}
